### ISSUE TITLE
Doesn't work in IE9 as advertised

### ISSUE THREAD

**Issue by stoikerty** [Popmotion/popmotion#101]
Hey Matt,

nice job with this project, looks very promising! The narrow focus makes it useable for React which is exactly what I was looking for (a physics engine that I can incorporate into `state`) :)

Now onto business... I hate to be the guy pointing this out. You advertise popmotion as being compatible with IE9. Your main site [popmotion.io](http://popmotion.io) throws this error:
```
SCRIPT438: Object doesn't support property or method 'now' 
site.js, line 1257 character 2
```

I haven't looked into it in depth, it feels like this might have to do with how `performance.now` is implemented.

**Comment by InventingWithMonster** [comment]
Thanks for pointing this out, that shouldn't be happening. 

Let us know how you get on with React. I'd like to provide a more specific implementation for it.

**Comment by InventingWithMonster** [comment]
3.3.3

**Comment by stoikerty** [comment]
that was quick! :+1: 

As a sidenote, maybe [the repo for `popmotion.io`](https://github.com/InventingWithMonster/popmotion-frontend) could live in popmotion's github-profile when you feel that it's ready?

**Comment by InventingWithMonster** [comment]
Yeah, it's going to, though like you say "when it's ready" - it uses an old
version of Popmotion with old syntax, not strictly something I want people
to learn from just yet.

**Comment by InventingWithMonster** [comment]
@stoikerty https://github.com/Popmotion/popmotion-frontend
