### ISSUE TITLE
How to handle scrolling and ui.track for a div

### ISSUE THREAD

**Issue by dpkpnm** [Popmotion/popmotion#104]
Just wondering on how to implement vertical page scrolling and horizontal swipe for a page using popmotion

**Comment by InventingWithMonster** [comment]
With scrolling are you referring to a a smooth page scroll? Like when you click an anchor link? In which case you can just `Tween` any value to your desired page offset and set `document.documentElement.scrollTop` to that value in an `onUpdate` callback. I'll probably make this the subject of my next guide.

Horizontal swipe would be simpler - you just `Track` the `x` property of any div and it'll move horizontally with the user input.

**Comment by dpkpnm** [comment]
By scrolling I was referring to window scroll when the content is more than the height of the window (innerHeight). Since touchdown is bound to track you loose the regular scroll functionality, I was looking for a way to only bind x and leave y scroll to be handled by the browser.

**Comment by InventingWithMonster** [comment]
Ah yeah I see, we fire e.preventDefault for various reasons so I guess y is
being blocked even if you only listen to X.

In that case have you tried making a custom onUpdate method that passes y
through to document.body.scrollTop?
