### ISSUE TITLE
Update demos on codepen to serve popmotion.js over https

### ISSUE THREAD

**Issue by bramus** [Popmotion/popmotion#107]
Eg. the demo at http://codepen.io/popmotion/pen/WvYdEB can not be embedded on a website that is served over HTTPS as the contained http://popmotion.io/assets/js/popmotion.global.min.3.1.2.js is served over HTTP. A (modern) webbrowser will give a Mixed Content Warning and block loading of said asset.

I am currently encountering this issue [on my own blog](https://www.bram.us/2015/10/20/popmotion/): the demo won't load entirely.

**Comment by InventingWithMonster** [comment]
Thanks for letting me know about this - I've updated the specific pen you've embedded. I'm usually serving the file from // to take whichever protocol is in use, but for some reason this pen wasn't. I'll check the others.

**Comment by bramus** [comment]
Hi Matt,

Thanks for the quick update. Unfortunately it's still not working.

I think you'll have to force `https://` instead of using protocol relative URLs _(which [have been doomed as an anti-pattern](http://www.paulirish.com/2010/the-protocol-relative-url/))_.

Regards,
Bramus.

**Comment by InventingWithMonster** [comment]
@bramus Well all I can say is I'm glad you showed me this link before I went and updated 70+ codepens! Thanks, Pen in OP should be working now.

**Comment by bramus** [comment]
Works fine indeed now; thanks!
