### ISSUE TITLE
Need a basic Meteor package

### ISSUE THREAD

**Issue by bmordan** [Popmotion/popmotion#110]
Wrap the library for use in Meteor.
So folk can use popmotion with meteor using `meteor add london:popmotion`

**Comment by InventingWithMonster** [comment]
@bmordan Looking into it, expect a resolution over the next couple days. Thanks!

**Comment by tinchox5** [comment]
Thanks!

2015-11-02 5:57 GMT-04:00 Bernard Mordan <notifications@github.com>:

**Comment by InventingWithMonster** [comment]
@tinchox5 @bmordan 

I've published to https://atmospherejs.com/popmotion/popmotion

Let me know if this works for you guys, this is my first Meteor package.

**Comment by tinchox5** [comment]
Hi Matt, I think there is a problem. I installed the package and I tried to
run popmotion with Meteor  using "onRendered" or "events", like this:

Template. templatename.onRendered(function() {
        var ballActor = new ui.Actor({element: '.ball'});
var move = new ui.Tween({
    duration: 1200,
    ease: 'backOut',
    values: {
        x:500
    }
});

ballActor.start(move);
});
--or--

Template.templatename.events({
        'click .ball': function(event, templateInstance){
var ballActor = new ui.Actor({element: '.ball'});
var move = new ui.Tween({
   duration: 1200,
   ease: 'backOut',
   values: {
       x:500
   }
});

ballActor.start(move);
        }

});

The error is the same:

Exception from Tracker afterFlush function:
debug.js:41 TypeError: tick is not a function
    at Object.frame (loop.js:54)
    at Object.start (timer.js:6)
    at Object.activate (manager.js:159)
    at Object.activate (Process.js:117)
    at Object.start (Process.js:85)
    at Actor.activate (Actor.js:330)
    at Actor.start (Actor.js:163)
    at null.<anonymous>
(test.js?d691a90c5dd1ee35bc02f23d6cfcf0ff80576efa:24)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:437)


When I uninstalled the package and used directly the popmotion js file, it
was working fine.

I hope that give you a clue to solve the problem,
Martin

2015-11-02 13:14 GMT-04:00 Matt Perry <notifications@github.com>:

**Comment by InventingWithMonster** [comment]
@tinchox5 Thanks for this report, I might have an idea. Could you console.log(window) in your app and let me know what it returns?

**Comment by tinchox5** [comment]
I send and image with the console log (Iam using meteor in secure mode
maybe another info is missing) :


2015-11-03 12:40 GMT-04:00 Matt Perry <notifications@github.com>:

**Comment by InventingWithMonster** [comment]
@tinchox5 Thanks for you help with this - could you try the latest version and let me know if that works? I've updated our Meteor tests too so this shouldn't happen again.

**Comment by tinchox5** [comment]
Yeah it's working perfect!

2015-11-03 15:00 GMT-04:00 Matt Perry <notifications@github.com>:
