### ISSUE TITLE
About setting initial values

### ISSUE THREAD

**Issue by tinchox5** [Popmotion/popmotion#123]
Hi Matt, I have this fork based on your pen "circle movement..." ( http://codepen.io/tinchox5/pen/KVKZXq)
I wanted to set initial position of "box" actor, so I thought that setting initial properties were enough to do that. But this didn't work for me, so I had to create a "fake tween": 

var circularMovement0 = new ui.Tween({
    duration: 0
});

Doing that it worked,but I think this isn't the correct way.

**Comment by InventingWithMonster** [comment]
Yeah I should look into a more natural way of doing this, but the way you can do it now is by changing `ball.set()` to `ball.set().sync()`
