### ISSUE TITLE
Question: Reverse tween animation on click

### ISSUE THREAD

**Issue by tinchox5** [Popmotion/popmotion#124]
Matt, Is there a way to rewind or reverse a tween animation based on mouse event? 

In this pen http://codepen.io/tinchox5/pen/KVKZX when I click on the ball the Tween animation start, but I dont know how to rewind to initial position when I click it again. Have you got any suggestion?

**Comment by InventingWithMonster** [comment]
Yeah the .start function returns Controls, and Tweens have special TweenControls which include a few more methods, including .reverse() - so you'd

var controls = actor.start(tween)

// onclick
controls.reverse()

**Comment by InventingWithMonster** [comment]
Just to elaborate, the reason we return `Controls` is because you can start multiple different actions on an Actor at the same time. So you could run Simulate on `x` and a Tween on `y`, and this way you retain control over both.

**Comment by tinchox5** [comment]
Thank you Matt! It isn't var controls = actor.*controls*(tween)?
I think I need a sort of toggle control because with the same "mousedown"
event  the actor firstly moves to point B and when I click again I need to
return it to Point A.
Maybe it work if I put a callback in the tween using onComplete


2015-12-05 13:26 GMT-04:00 Matt Perry <notifications@github.com>:

**Comment by InventingWithMonster** [comment]
I think there is a `toggle`, you could try `.toggle().reverse()`? I'll take a deeper look at this tomorrow though. You could also use `.then()` for the callback approach.

**Comment by InventingWithMonster** [comment]
And `controls` returns Controls without playing, `start` returns Controls and plays.

**Comment by tinchox5** [comment]
OK Matt, I tried your suggestions but didnt work for me. I believe that
.toggle is for iterator only​.

2015-12-05 14:58 GMT-04:00 Matt Perry <notifications@github.com>:

**Comment by InventingWithMonster** [comment]
@tinchox5 I've been looking into this and I've just realised that the technical reason this is happening is the Tween is finishing, so when it's restarted all `origin` points are reset. So it reverses the `origin` point and the `to` value that you've configured, but now they're exactly the same.

So my advice for now is to defined one Tween like this:

```
var myTween = new ui.Tween({
    // other props
    values: {
        x: 500
    }
});
``` 

and then instead of using `reverse`, extend that tween like:

```
var myOppositeTween = myTween.extend({
    values: {
        x: 0
    }
});
```

In the mean time I'll look for a solution that doesn't break stuff!

**Comment by InventingWithMonster** [comment]
@tinchox5 Think I found a solution that doesn't break stuff!

With `4.2.4`:

```
var tweenControls = actor.start(tween);

// later
tweenControls.toggle().reverse();
// or .start().reverse()
```

**Comment by tinchox5** [comment]
Thank you I'll try!  Can you upload this version into //
popmotion.io/assets/js/ ? because I'm using codepen.


2015-12-06 6:57 GMT-04:00 Matt Perry <notifications@github.com>:

**Comment by InventingWithMonster** [comment]
Ah yeah sorry forgot about that - just uploaded it now

**Comment by tinchox5** [comment]
Matt its working now! Thank you!

Demo working here: http://codepen.io/tinchox5/pen/eJYLMM

2015-12-06 9:35 GMT-04:00 Matt Perry <notifications@github.com>:

**Comment by tinchox5** [comment]
Sorry Matt, .toggle.reverse(), works for an Actor, but not for Iterator.

**Comment by tinchox5** [comment]
http://codepen.io/tinchox5/pen/obgYqb

**Comment by InventingWithMonster** [comment]
Yeah for iterators need to do something like this:

iterator.each(function (actor) {
    actor.toggle().reverse();
})

**Comment by tinchox5** [comment]
console: TypeError: ball.toggle(...).reverse is not a function (in the
above pen)


2015-12-07 15:04 GMT-04:00 Matt Perry <notifications@github.com>:

**Comment by InventingWithMonster** [comment]
Ah yeah. This is an annoying one! I'll figure out a way to make this easier but you could do

```
var ballControls = balls.eachIntoNew(function (ball) {
    return ball.controls(yourTween)
});

ballControls.stagger()...
```

`eachIntoNew` creates a new Iterator based on the return value of the callback, and you can stagger over that instead.

Also in your callback you're passing `ball` as an argument when `ball` is already defined as an Iterator which will cause problems.

**Comment by tinchox5** [comment]
Thank for the reply, I'm just testing so I can wait. Is there a possibility
to use the same commands for Actor in the future? I mean integrate them

**Comment by InventingWithMonster** [comment]
It actually used to work like this, but I started running into all sorts of problems with functions where something was returned, or say when you access `values` - it works for one but not multiple Actors. That;s why I like having Iterator separate, its quite explicitly different. Also an Iterator can be used to `stagger` over any array instead of just one of Actors.

The thing I like the least about the current approach is that `ui.select` returns an Actor or an Iterator depending on the number of results, which isn't great when they work so differently.

**Comment by tinchox5** [comment]
Yeah I understand what you mean. I said that because running things with
one actor is it very simple, but you re right there are diferents things

**Comment by tinchox5** [comment]
And yes, using select for one or multiple elements makes you think that a
priori you can use actor methods for an iterator. Sorry I really want to
give you a technical aproach but sadly I'm a diplomat not a programmer and
I didnt have the knowledge. Maybe using pure js to make iterations and
managing arrays and then using actor methods for each elements. Sorry if
I'm saying nonsense.
