### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by tinchox5** [Popmotion/popmotion#125]
Matt, in this working pen http://codepen.io/tinchox5/pen/eJYLMM I defined an Actor (new ui.Actor),then I set some properties (.set), and finally I put .sync(), like this:

var box = new ui.Actor({
    element: '.box'
});
box.set({
    values: {
        originX: 0,
        originY: 0,
        distance: 180,
        angle: 240,
        opacity: 1,
        x: {
            transform: fromAngleAndDistance
        },
        y: {
            transform: fromAngleAndDistance
        }
    }
}).sync();

I wanted to simplify some lines of code, so I did it this:
var box = new ui.Actor({
    element: '.box',
    values: {
        originX: 0,
        originY: 0,
        distance: 180,
        angle: 240,
        opacity: 1,
        x: {
            transform: fromAngleAndDistance
        },
        y: {
            transform: fromAngleAndDistance
        }
    }
}).sync();

The code isn't working anymore and Console shows : "Uncaught RangeError: Maximum call stack size exceeded"

Here is the new pen http://codepen.io/tinchox5/pen/eJYqaj

**Comment by InventingWithMonster** [comment]
What browser are you testing this in? As I can't replicate this. However you no longer have to call `sync` yourself - I added it at the end of the Actor constructor after your feedback the other day.

**Comment by InventingWithMonster** [comment]
Ah sorry you only don't have to call `sync` after the contructor - I didn't think about the `set` use case and will look into that too.

**Comment by tinchox5** [comment]
I´m using chrome. Now its working!! Thanks

**Comment by InventingWithMonster** [comment]
Glad to hear it : ) - If you see it again though please let me know - I'm certain there's a runaway infinite loop under specific conditions and its getting harder to replicate as the framework matures.
