### ISSUE TITLE
[enhancement] Add new types in svg role

### ISSUE THREAD

**Issue by tinchox5** [Popmotion/popmotion#126]
Matt, It would be nice to add new types to svg roles such as "fill-opacity" and "stroke-opacity". Is it possible?

**Comment by InventingWithMonster** [comment]
I've just updated the type map to include opacity, fill-opacity and stroke-opacity for version 4.2.5 - is this what you meant?

**Comment by tinchox5** [comment]
Perfect!

2015-12-07 12:49 GMT-04:00 Matt Perry <notifications@github.com>:

**Comment by tinchox5** [comment]
Hi Matt, strokeOpacity and fillOpacity didnt work when I tested them.
http://codepen.io/tinchox5/pen/YwPREE

line 61

var fadeIn = new ui.Tween({
  duration: 280,
  ease: 'backOut',
  values: {
    strokeOpacity: 0
  }
});


2015-12-07 17:25 GMT-04:00 Matt Perry <notifications@github.com>:
