### ISSUE TITLE
 strange behavior with opacity 0

### ISSUE THREAD

**Issue by tinchox5** [Popmotion/popmotion#127]
Matt, I have this pen http://codepen.io/tinchox5/pen/YwPREE

I defined some tweens, one is called fadeIn and another fadeOut. FadeIn (opacity:1) works perfect, but fadeOut (opacity:0) isn't working when I use toggle().reverse() . I mean the opacity style doesnt change when I monitoring via browser inspector tool (chrome).

You can see the problem touching the circle situated at the top left main circle.

Is it a kind of bug or my fault?

**Comment by InventingWithMonster** [comment]
I'll have to take a closer look when I'm back at a computer but my first guess is the first time the fadeIn animation fires it isn't going from '0' - you can force this by setting 'to' and 'current' explicitly on 'opacity' bit generally I just have one for fadeIn and one for fadeOut and call them both with 'start'

**Comment by tinchox5** [comment]
You are right!
var fadeOut = new ui.Tween({
  duration: 280,
  values: {
    opacity: {current:1, to:0}  // works
  }
});

var fadeOut = new ui.Tween({
  duration: 280,
  values: {
    opacity: 0  // doesnt works
  }
});

Thanks

**Comment by tinchox5** [comment]
in addition, a want to change the border color, so I set borderColor both in Actor and Tween:
this is the error on console : TypeError: t.getPlayable is not a function (vs 4.2.4)

note: (also I tried use current and to, but not works). you can view this if uncomment line 58

**Comment by InventingWithMonster** [comment]
I think this line is the problem:

ctrlcircle.toggle().reverse().then(ctrlcontact.toggle().reverse());

should be

    ctrlcircle.toggle().reverse().then(function () {
ctrlcontact.toggle().reverse()
                                                   });

**Comment by tinchox5** [comment]
Sorry Matt, when I do that, this is the error: Uncaught RangeError: Maximum call stack size exceeded

**Comment by InventingWithMonster** [comment]
Ah I've found the source of this bug, I'll try to fix it today.

Thanks

**Comment by InventingWithMonster** [comment]
@tinchox5 Should be fixed with `4.2.6`

**Comment by tinchox5** [comment]
Yeah thank you Matt! Also for add fillOpacity and strokeOpacity to svg role.

**Comment by InventingWithMonster** [comment]
@tinchox5 I saw another message somewhere but can't find it now about fillOpacity and strokeOpacity still not working but can't find it now. Try `4.2.7` - I misunderstood what was required. They were getting set as `strokeOpacity` when the format is `stoke-opacity`, now all properties will be reformatted to this.

Thanks for letting me know, it's been a real help ironing out bugs.

**Comment by MightyRevenge** [comment]
Animating the opacity doesn't work in the latest release.
