### ISSUE TITLE
[Question] How to apply Sequence when you have defined Controls

### ISSUE THREAD

**Issue by tinchox5** [Popmotion/popmotion#128]
Hi Matt, I´m a bit stuck traying to implement Sequence in order to optimice my animation. The main problem is that I need to set Controls because of mouse events. I mean, when I click on Search Circle, the animation starts,then when I click again I have to reverse animation based on the previuos controls.
PEN. http://codepen.io/tinchox5/pen/YwPREE

The straight forward is : 
(Line 142 )
//interaction
$('.search').one('mousedown', function(e) {
      var ctrlpag = paginator.start(fadeOutPag);
      var ctrlsearch = search.start(circularMovement);
      var ctrlc2 = circle2.start(circular2);
      var ctrlcircle = circle.start(fadeIn);
      var ctrlcontact = contact.start(fadeOut);
      var ctrlsb = searchBox.start(enlarge);
   
  $('.search').on('mousedown', function(e) {
    ctrlpag.toggle().reverse();
    ctrlsearch.toggle().reverse();
    ctrlc2.toggle().reverse();
    ctrlcircle.toggle().reverse();
    ctrlcontact.toggle().reverse();
    ctrlsb.toggle().reverse();

  });
});

The problem is that all animations starts at same time, so many lags occurs on mobile. Also, I can´t set "delays" into tween because I need to reverse them later.

For this reason, I tried to implement Sequence in this way: 

//interaction
$('.search').one('mousedown', function(e) {
  var sequence = new ui.Sequence();
  sequence
    .do(function(){
     var ctrlpag = paginator.start(fadeOutPag);
    }).then(function(){
    var ctrlsearch = search.start(circularMovement);
    }).then(function(){
     var ctrlc2 = circle2.start(circular2);
    }).then(function(){
     var ctrlcircle = circle.start(fadeIn);
    }).then(function(){
     var ctrlcontact = contact.start(fadeOut);
    }).then(function(){
    var ctrlsb = searchBox.start(enlarge);
    });
 
  $('.search').on('mousedown', function(e) {
   <--omitted code-->
  });
});

But console shows that --->  "TypeError: e.split is not a function"

Maybe I´m not clear but have you got any suggestion to implement Sequence when Controls are also defined?

**Comment by InventingWithMonster** [comment]
At this point I'd suggest ditching the controls approach. Controls are best used when you're using, say two different animations on the same Actor. 

Instead, you can make two sequences. You could keep the toggle.reverse stuff and fire them in sequenced callbacks, or instead of using reverse you'd make seperate Tweens/Simulate for in and out and sequence those instead

**Comment by tinchox5** [comment]
Thank you but I dont figure how to implement what you suggest Matt. I tried
another aproach based on pure js.

http://codepen.io/tinchox5/pen/QybxZa

$('.search').one('mousedown', function(e) {
  var ctrlpag, ctrlsearch, ctrlc2, ctrlcircle, ctrlcontact, ctrlsb;
  setTimeout(ctrlpag = paginator.start(fadeOutPag), 0);
  setTimeout(ctrlsearch = search.start(circularMovement), 200);
  setTimeout(ctrlc2 = circle2.start(circular2), 500);
  setTimeout(ctrlcircle = circle.start(fadeIn), 700);
  setTimeout(ctrlcontact = contact.start(fadeOut), 900);
  setTimeout(ctrlsb = searchBox.start(enlarge), 1100);

  $('.search').on('mousedown', function(e) {
    setTimeout(ctrlpag.toggle().reverse(), 0);
    setTimeout(ctrlsearch.toggle().reverse(), 200);
    setTimeout(ctrlc2.toggle().reverse(), 500);
    setTimeout(ctrlcircle.toggle().reverse(), 700);
    setTimeout(ctrlcontact.toggle().reverse(), 900);
    setTimeout(ctrlsb.toggle().reverse(), 1100);
  });
});

2015-12-10 13:04 GMT-04:00 Matt Perry <notifications@github.com>:
