### ISSUE TITLE
[Question] Warnings console using FF

### ISSUE THREAD

**Issue by tinchox5** [Popmotion/popmotion#131]
Hi Matt, I´m doing a kind of circle UI using popmotion http://codepen.io/tinchox5/pen/KVdjNe. When I use FF its console shows me a couple of warnings: 

1) mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

2) too much recursion

Thats not happen with Chrome.

Thank you! 
Martin

**Comment by InventingWithMonster** [comment]
Ah well the first error is a result of the Babel transpilation. I'll take a look at the second, that should be fixed now.

**Comment by InventingWithMonster** [comment]
Hey Martin I've just been having a play in Firefox but can't get the recursion bug to show - what steps are you taking to get that error?

**Comment by tinchox5** [comment]
Yes you are right, "too much recursion" error doesnt appears anymore.
Surely was something related with my code that I tried to optimize during
the weekend. My fault.
Thank you

2015-12-21 6:54 GMT-04:00 Matt Perry <notifications@github.com>:

**Comment by tinchox5** [comment]
Hi @InventingWithMonster ! A lot of time has passed! I have learnt much about coding and I want to contact you to present my new project! Best regards, Martin!
