### ISSUE TITLE
Acceleration property not handled correctly when defined as a function

### ISSUE THREAD

**Issue by silawrenc** [Popmotion/popmotion#133]
Hi Matt,

I've created a codepen [here](http://codepen.io/anon/pen/adBbyq?editors=001) which shows the issue. If you try and define the `acceleration` property of a value (e.g. `x`) of a `ui.Simulate` as a function, it is ignored.

it looks like the issue starts from here...
https://github.com/Popmotion/popmotion/blob/master/src/actions/simulate/simulations.js#L19
...and then `calc.speedPerFrame` is using a `utils.isNum` check, with default of zero.

I'll try and put up a PR for this in a bit.

Simon

**Comment by InventingWithMonster** [comment]
Hey Simon

Numerical properties should be able to be set as functions, but these are meant to be resolved on `start`.

The best way to achieve what you're attempting is probably the `onFrame` method, like this:

```javascript
onFrame: function () {
    actor.values.yourValue.acceleration = 100;
}
```

Thanks for the PR, what I'll do is make a new branch with the missing dependencies and add `acceleration` to the list of properties that should be resolved as a function.

**Comment by silawrenc** [comment]
Sounds good to me - I'll close the PR.
