### ISSUE TITLE
Help - blurry results

### ISSUE THREAD

**Issue by tinchox5** [Popmotion/popmotion#137]
Hi Matt, I'm here again.  I'm doing a sort of prezi user interface. I made the initial draft with css transformations here [zui.meteor.com](http://zui.meteor.com) and works "fine". Then, I rewrote it in order to add popmotion. The main problem is the results are blur when I touch the circles. Have you got any idea to solve this? The popmotion version is here:  [zuipop.meteor.com](http://zuipop.meteor.com)

(In chrome and mobile chrome is blur; not in FFox)

Thank you!

**Comment by InventingWithMonster** [comment]
Hey man

That's because for performance reasons we enforce `translateZ()` - this forces the transformed element to be rendered on the GPU. 

This means that essentially the GPU receives an image of the element, so when you scale it up it can look blurry. I'd like at some point to have an override for this, but for now I'd recommend rendering the element big in the first place and then scaling it down for its rest state.

**Comment by tinchox5** [comment]
Thank you Matt! I thinking that for cases like this project maybe
TransalteZ could be deactivated using z: "none" into values of Tween. What
do you think about that?

2016-01-20 6:52 GMT-04:00 Matt Perry <notifications@github.com>:

**Comment by InventingWithMonster** [comment]
Yeah, well ideally it'd be an option like `hardwareAcceleration: none` as the `translateZ` thing is just a hack for that. I'm working on a bit of an api rewrite at the moment to simplify things so I'll take a look at it as part of that

**Comment by tinchox5** [comment]
Following your idea it would be nice to have the option to deactivated some
of this hacks, but mantain others such as requestAnimationFrame depending
of your necesities.

**Comment by tinchox5** [comment]
What if you keep this hacks and when animation finishes translateZ is
eliminated?

2016-01-20 13:19 GMT-04:00 Juan Martín Muda <martinmuda@gmail.com>:

**Comment by tinchox5** [comment]
Matt, I have this code working to eliminate translateZ() when animations
finishes.

var actor = new ui.Actor({
 ...
})

var zuilander = new ui.Tween({
  duration:750,
  values:{
    ...
    },
    onComplete: function(){
      var transformArray = canvas.element.style.transform.split(' ') //get
transform values from actor
      var check = transformArray.pop() // delete last element
      if(check=='translateZ(0px)'){
        ui.css(canvas.element,'transform', transformArray.join(' ')) //set
new transform style
      }
    }
})

2016-01-21 19:11 GMT-04:00 Juan Martín Muda <martinmuda@gmail.com>:
