### ISSUE TITLE
Memory consumption / Garbage collection

### ISSUE THREAD

**Issue by vkammerer** [Popmotion/popmotion#139]
Hello,

It seems that popmotion can be very demanding in terms of memory, even for very basic animations. This unfortunately causes the Garbage collector to trigger very often, and can result (even on my macbook pro) to jank, AKA long frames...

For example, when profiling the second example shown in the docs ( http://codepen.io/popmotion/pen/BNGwrK ), we can clearly a sawtooth pattern in the timeline tab: 

![capture d ecran 2016-01-28 a 20 57 23](https://cloud.githubusercontent.com/assets/1177483/12665015/64a6f022-c602-11e5-92f8-0f5f3e18ed8a.png)

Would there be places in the codebase where new object creations could be replaced with existing objects assignments? If yes, this could improve dramatically the performance of the library.

**Comment by InventingWithMonster** [comment]
Thanks for pointing this out, I'm rewriting large parts of it at the moment
so I'll be sure to investigate. I don't think we make many object objects
but every frame there's a lot .forEach(function () {})-esque things
happening and as every functions an object I assume these are getting
created every frame. I'll unroll these as a priority.

**Comment by InventingWithMonster** [comment]
@vkammerer Hey man just to give you an update, I've managed to reduce memory consumption by over half for `5.0`, so when it's released in a couple of weeks you should see some significant improvements.

**Comment by Charuru** [comment]
Could we get a hotfix or something in the interim? It's a pretty major issue that makes the lib almost unusable.

**Comment by InventingWithMonster** [comment]
@Charuru Unlikely to have a hotfix for this, `5.0` is a rewrite so it's been rewritten from the ground up to help reduce memory consumption. 

Out of interest what are you running this on? I've been testing on a 2015 Macbook Pro, 2012 Air and iPhone 5S and I haven't experienced dropped frames (although I can clearly see memory usage spiking)

**Comment by Charuru** [comment]
I was evaluating it vs greensock and seeing this memory pattern makes it a non-starter for my team. We didn't get as far as implementing it, our usecase is pretty memory heavy already. I didn't personally notice any dropped frames on my 2013 imac.

**Comment by InventingWithMonster** [comment]
It's worth comparing directly to Greensock, as it has a similar memory pattern (although the `4.x.x` branch is undoubtedly more memory intensive. I think it's difficult avoid the sawtooth pattern altogether but I am trying to make it as flat as possible.

As for release, between thorough testing and documentation it won't be this month - hopefully mid-March.

**Comment by bryzaguy** [comment]
@InventingWithMonster: If you need any help I'd be interested in getting involved.  Maybe create some github issues to look over.

**Comment by InventingWithMonster** [comment]
Forgot to mention, 5.0 is now released and memory consumption should be reduced!

**Comment by vkammerer** [comment]
Great! thank you @InventingWithMonster !
