### ISSUE TITLE
rotation - how to force popmotion to use rotate3d

### ISSUE THREAD

**Issue by sqal** [Popmotion/popmotion#142]
Is there any way i can force popmotion to use rotate3d property insead of just rotate? I can't find anything about it in the docs. Thanks for the help and good work on the library, very cool ;)

**Comment by InventingWithMonster** [comment]
Cool man glad you're enjoying it!

There isn't, but you can set `rotateX`, `rotateY` and `rotateZ` separately.

If that doesn't work for you, could you show me an example of what you're trying to achieve and I'll look into the best way we can make it happen?

Thanks

**Comment by sqal** [comment]
Ok i think we can close it issue. I thought about rotate3d because uses hardware acceleration, but apparently adding translateZ(0) can trigger it as well :). Sorry for my lack of knowledge.

**Comment by InventingWithMonster** [comment]
No worries - also, translateZ should be added by default of not otherwise
defined, for precisely this reason
