### ISSUE TITLE
To & From working correctly?

### ISSUE THREAD

**Issue by mspoulsen** [Popmotion/popmotion#143]
Hi,

Thanks for a great library!

I am having a small problem using 'to' and 'from' combined. I would like to tween values from 50 to 100. I have tried all sorts of stuff but it always starts from zero. Here is my latest attempt:

```javascript
var Actor = popmotion.Actor;
            var Tween = popmotion.Tween;

            var tweenOptions = {

                values: {
                    x : {
                        to : 100,
                        from : 50
                    }
                }

            };

            var myActor = new Actor({
                onUpdate: function (output) {
                    console.log(output)
                },
                onComplete: function () {
                    console.log('complete')
                }
            });

            var tween = new Tween(tweenOptions);

            myActor.start(tween);
```

Please tell me what I am doing wrong. Thanks in advance! :)

**Comment by InventingWithMonster** [comment]
Hey man - from is a 5.0 property - try using current with 4.0 to start from there. Let me know how you get on.

**Comment by mspoulsen** [comment]
Excellent, current works like a charm :)

I am unable to update popmotion from 4.3.4 to 5.0. I have tried npm uninstall and npm update but I keep getting 4.3.4. Any ideas? When I check on npm it says latest version 5.0.3.

I am using npm 3.7.3.

**Comment by InventingWithMonster** [comment]
Yeah that's odd - sometimes I find npm update popmotion works, or deleting Popmotion from npm_modules and package.json and then run npm install popmotion again

**Comment by InventingWithMonster** [comment]
Just a warning this will break all your code as all the concepts have changed including Actor - if read through the get started tutorial before proceeding

**Comment by mspoulsen** [comment]
Ok, thanks. I will figure it out somehow. Thanks for the heads-up. I plan to use popmotion extensively in my project so better to break it now than later :)
