### ISSUE TITLE
Question: Documentation for 4.3.x

### ISSUE THREAD

**Issue by ACOSW** [Popmotion/popmotion#144]
Hi.
Where i can find documentation for old 4.3.x API ?

**Comment by InventingWithMonster** [comment]
Hi Egor

I've actually broken the docs, ironically because I moved away from a CMS
so we could version control the docs going forward avoiding situations like
this. I'll have a look at fixing them tomorrow - the url is
http://popmotion.io/4.0 though the links are broken currently

**Comment by InventingWithMonster** [comment]
Hi Egor

The docs are up again at the above URL - sorry they don't look the
prettiest but all the links work now.

Thanks
Matt

**Comment by ACOSW** [comment]
Hi Matt
Thank you! :)
