### ISSUE TITLE
Inertia Action plugin not working

### ISSUE THREAD

**Issue by andrewn** [Popmotion/popmotion#145]
Hi,

I'm trying to use the [Inertia Action plugin](https://popmotion.io/plugins/actions/inertia/) to experiment with momentum-based scrolling but I can't seem to get it to work.

[I've made an example](http://codepen.io/andrewnicolaou/pen/reKjMm?editors=1010) based on the code in the docs. Clicking "animate" moves the element but doesn't seem to apply the inertia at the end.

[I've tried another example tracking mouse/touch motion](http://codepen.io/andrewnicolaou/pen/wGXoyR?editors=0010) but releasing the element after dragging causes the animation to stop suddenly.

I thought [the following line](https://github.com/Popmotion/popmotion/blob/master/packages/popmotion-action-inertia/src/inertia.js#L18) might be causing the problem - `value.mass` isn't defined anywhere so I changed it to `value.amp` on a local copy of the plugin. This causes some sort of inertia but it's still not right, the div jumps back up when the timeout fires.

I'd love to raise a PR to help fix this but I'm not sure where to start. Some guidance would be much appreciated!

Thanks.

**Comment by InventingWithMonster** [comment]
Hi Andrew

If I don't get a chance to look tonight I'll take a look tomorrow morning -
your example should work perfectly.

**Comment by InventingWithMonster** [comment]
The missing `mass` value is definitely a culprit, though the jumping is odd too, I've not seen this before. Honestly you turn your back on code for two seconds... I'll let you know when I've got a fix for this.

**Comment by andrewn** [comment]
Thanks, let me know if I can help somehow.
