### ISSUE TITLE
VirtualDom

### ISSUE THREAD

**Issue by tinchox5** [Popmotion/popmotion#147]
Hi Matt, I have a question.... I'm trying to use some kind of library with virtual dom (ex: mithril, react), in order to make animations more fluent on mobile devices, but Is it a good idea or is it no necessary at all ?

**Comment by InventingWithMonster** [comment]
It isn't necessary at all. It will actually slow things down (maybe not perceptibly), as the virtual DOM libraries will have to do the diff, and then the rendering as normal.

I do have a React component nearly ready to go, if you go down that road, which bypasses React's diffing engine.

Your best bet with performance is sticking to animating just a few things simultaneously, and only animating properties highlighted on [CSS Triggers](https://csstriggers.com) that stay on the compositor thread, like `transform` properties and `opacity`.

**Comment by tinchox5** [comment]
Thank you! I'll follow your advices and also implement flip method.
