### ISSUE TITLE
Update demo to popmotion 5

### ISSUE THREAD

**Issue by Charuru** [Popmotion/popmotion#148]
Could this demo be updated to the latest version of popmotion please: https://codepen.io/popmotion/pen/ojrmmd

**Comment by InventingWithMonster** [comment]
Yeah I've been meaning to do this actually, thanks for bringing it up. I'm away on holiday at the moment so I won't get the chance for maybe a few days. 

Just off the top of my head the way to replace the `watch` function is to use the `transform` property instead. You can get the `flow` of the box (which is more or less the successor to actor) by using `motion.detectFlow(document.querySelector('.box')).set({
    values: {
        rotateX: { transform: yourfunction }
    }
})`

But I'll do a full example soon.

**Comment by Charuru** [comment]
Hey would still like this.

**Comment by InventingWithMonster** [comment]
Coincidentally I began working on it a couple hours ago. It required a bug fix so please update to 5.0.8. Here's the pen:

https://codepen.io/popmotion/pen/xVeWmm
