### ISSUE TITLE
Disable auto addition of translateZ?

### ISSUE THREAD

**Issue by jamieowen** [Popmotion/popmotion#150]
Hey man,

Awesome work on the library man.. Good stuff!

Just using this on a mobile project and noticed the addition of translateZ to force into 3d compositing / hardware acceleration mode.

Thats cool for most things but is there anyway to disable it may be on a per tween basis?
On iOS, Safari / Chrome likes to use lower quality anti-aliasing when translateZ is set which makes text appear a bit poo!

I noticed there is some addition of the flag here, but couldn't see further if this was settable! : 
https://github.com/Popmotion/popmotion/blob/e33c62164fdf92d39aed91214410b51ba05fbdd7/src/adapter/css/build.js#L7

What do you think?

Cheers,

Jamie

**Comment by InventingWithMonster** [comment]
Thanks man glad you're enjoying it!

I left the flag in because I do want to implement this feature in the near future, but it currently isn't. I'll try and take a look over the next few days.

Matt

**Comment by jamieowen** [comment]
Cool man no worries..
I've just commented it out for now..

One other question actually.. ( if you don't mind ) -- Is seek() support meant to be available on Timelines?

Cheers,
Jamie

**Comment by InventingWithMonster** [comment]
It is, though it might be quite buggy due to the way the [timeline's](https://github.com/Popmotion/popmotion/blob/master/src/inc/timeline.js) setTweens function works. Right now it's a fairly stupid loop for speed but I'm quickly seeing need to make it a little more intelligent to allow fast or arbitrary scrubbing.

**Comment by lazarljubenovic** [comment]
Has this been addressed? Can we turn off the automatic addition of `translateZ`?

**Comment by InventingWithMonster** [comment]
@lazarljubenovic in Pose, no. In Popmotion/Stylefire you can set enableHardwareAcceleration to false
