### ISSUE TITLE
Physics not automatically stopping

### ISSUE THREAD

**Issue by InventingWithMonster** [Popmotion/popmotion#152]

**Comment by huyaxiong** [comment]
`
var xx = motion.physics({
    onComplete:()=>{},
    onStop:()=>{},
}).on('xxx');
xx.start();
`

i meet the same situation,once i called start(),onComplete or onStop never triggered.

**Comment by huyaxiong** [comment]
no one response?

**Comment by InventingWithMonster** [comment]
Hey there, sorry for the delay. I'll take a look at this over the weekend!
