### ISSUE TITLE
CSS Properties name docs? 2d Transform in IE9?

### ISSUE THREAD

**Issue by sinutwentyone** [Popmotion/popmotion#155]
Hello, amazing plugin sir :).

I cant find documentation of animatable properties that i can use in popmotion. Do 2d transform animation not working in ie9? trying { x: { from: 100, to: 0} }. and it did'nt work. Or it's just did'nt support ie9 transform animation?

thanks.

**Comment by InventingWithMonster** [comment]
Hi there, thanks for the kind words!

Every numerical/colour value should be animatable. Some like `padding` need to be broken down to `paddingRight` etc. Still, I do want to create a list of supported values to make things like `x` clearer (which is usually `translateX` obviously)

As for IE9 we are meant to support transforms - could you make sure you're on the latest version (5.0.10) and try again? I fixed some bugs around browser prefixes yesterday so this might be related.

Thanks
Matt
