### ISSUE TITLE
From To Properties issue

### ISSUE THREAD

**Issue by dmcrt** [Popmotion/popmotion#156]
Hello, 

I am having some issue with the from/to property value, it always start from the 'to' value, here is the snippet : 

`const tween = motion.tween({`
`      values: {`
`        y: {`
`          from: -100,`
`          to: 0`
`        },`
`        opacity: 1`
`      },`
`      duration: 1000`
`    });`

`tween.on(_elements[0]);`
`tween.start();`

I saw that this problem have been posted before, with a version error (updating popmotion from 4.xx to 5.xx), but i have popmotion 5.0.8 installed in my node_modules.

`"popmotion": "^5.0.8"``

EDIT : 

Maybe it could help, it works correctly only if the element property is set in popmotion.tween options.

Thanks a lot for the help,

Regards

Thomas D.

**Comment by InventingWithMonster** [comment]
Thanks for this, I'll take a look as soon as possible

**Comment by InventingWithMonster** [comment]
Fixed in 5.0.12
