### ISSUE TITLE
Opacity cannot be set to decimal value

### ISSUE THREAD

**Issue by null-null-null** [Popmotion/popmotion#159]
I'm new to popmotion, so this might be user error. Still, here's what I'm finding: when I set the `to` or `from` for opacity to a decimal value, it is rounded down to 0. There's a codepen [here](http://codepen.io/nullnullnull/pen/VjeGVP) to illustrate.

Whether user error or a bug, I'm excited to see what popmotion has to offer. I'm considering alternatives now that velocity has entered a limbo state, and popmotion seems to have a better architecture. I really like how it exposes adapters, transformers, and value types.

**Comment by InventingWithMonster** [comment]
Hey man. Thanks for reporting, this is definitely a bug. I'll look into it.

**Comment by InventingWithMonster** [comment]
You might already know this but to make `yoyo` run indefinitely you can set it to `Infinity`

**Comment by InventingWithMonster** [comment]
@null-null-null The problem is specific to `5.0.0` - I've updated the sandbox to `5.0.11` and if you do the same to your CodePen it will work

**Comment by null-null-null** [comment]
Thanks for the quick turnaround! This resolves the issue.
