### ISSUE TITLE
Unit types are not respected

### ISSUE THREAD

**Issue by null-null-null** [Popmotion/popmotion#162]
If I provide a unit type other than `px`, it will simply be converted into `px`. For instance, I could try something like this:

``` js
const myTween = motion.tween({
    values: {
        x: '200%'
    }
});

myTween.on(document.getElementById('ball')).start();
```

And it would result in this:

`<div id="ball" style="transform: translateX(200px) translateZ(0px);"></div>`

[Here](http://codepen.io/nullnullnull/pen/wWzoJp?editors=0010) is a codepen demonstrating the issue.

I'm still new to the popmotion codebase, but spent a bit of time trying to debug the issue. I wasn't able to find the the root cause, but it looks like there are possibly two issues. The first is with [this line](https://github.com/Popmotion/popmotion/blob/master/src/value-types/unit.js#L12), which I believe would only run if the unit was `NaN`.

The second thing I found was that when running this:

``` js
const myTween = motion.tween({
    values: {
        x: '200%'
    }
});
```

The actual unparsed `200%` gets passed into [parse](https://github.com/Popmotion/popmotion/blob/master/src/value-types/unit.js#L9). However, when running this:

```
myTween.on(document.getElementById('ball')).start();
```

The `unparsed` comes in as `200`, which is why it uses the default `px` unit. Hope that helps!

**Comment by InventingWithMonster** [comment]
I'm just looking into this now - I think a problem is Popmotion already "knows" this type of value is in pixels, when of course there's a few different types it could potentially be. I'm thinking a potential approach could be to define permitted value types along with just one default type.

**Comment by null-null-null** [comment]
Let me know if there's anything I can do to help! My main observation was that Popmotion was "forgetting" the type [here](https://github.com/Popmotion/popmotion/blob/master/src/actions/Flow.js#L42). I'm curious how it remembers the value, though. Perhaps we could store the type in a similar manner?
