### ISSUE TITLE
What is the isTweening GSAP equivalent in Popmotion?

### ISSUE THREAD

**Issue by PierBover** [Popmotion/popmotion#168]

**Comment by InventingWithMonster** [comment]
Sorry I'm not in the position to double check this but I think every action has an isActive property that you can query

**Comment by PierBover** [comment]
You [are right](https://github.com/Popmotion/popmotion/search?utf8=%E2%9C%93&q=isActive) although it's a bit weird this isn't documented (or I couldn't find any reference in the docs).

**Comment by InventingWithMonster** [comment]
It's sometimes hard to know what you should expose publicly based on your
own use - I personally never use isActive as a consumer, I only use it
within the framework, so it's easy to start believing no one uses it. I'll
make sure to make it a public part of future apis.
