### ISSUE TITLE
React.js examples

### ISSUE THREAD

**Issue by gaou-piou** [Popmotion/popmotion#172]
Would it be possible to add examples with React.js?

**Comment by InventingWithMonster** [comment]
Sure, I'll get some up soonish. I use Popmotion exclusively with React at https://drivetribe.com/ -  there's no difference than using it normally. You get the DOM using component's ref attributes and lifecycle methods like those provided with https://facebook.github.io/react/docs/animation.html

**Comment by mars** [comment]
Can you drop a few hints for how to use the React components in [packages/popmotion-react-dom](https://github.com/Popmotion/popmotion/tree/master/packages/popmotion-react-dom/src)? That would be amazing. I'm lost trying to understand what the props are and what a `flow` is.

**Comment by InventingWithMonster** [comment]
@mars Hey Mars sorry I need to get round to unpublishing or updating our packages since 6.0 - they're all designed to work with 5 which has a more confusing api.

I generally make packages like this as and when I need them at work. Since using React more myself I haven't encountered the need for a Component abstraction - I generally use Popmotion as documented with dom `ref`s, in `componentDidMount` and React's own `react-transition-group` plugin.

Do you have an approach you currently take for animations?

**Comment by mars** [comment]
@InventingWithMonster I've got basic React integration going ([example](http://codepen.io/marsi/pen/RKYvYv?editors=0010)) but not yet figured out how to use Popmotion with transition groups. If popmotion-react-dom components are not a useful abstraction then I'll focus on building with Popmotion + React directly. My goal is to make an image slideshow that can be swiped left/right (with gesture tracking) to navigate between images.

**Comment by mars** [comment]
Ah, I see that popmotion-react-dom depends on Popmotion 5, not the current 6.

Are the [guides in the documentation site](https://popmotion.io/guides/basics/get-started/) still meaningful?

Thanks so much for following-up. You saved me a bunch of needless wheel-spinning. And thanks for Popmotion… I'm really excited to figure out gesture tracking with physics 😆

**Comment by InventingWithMonster** [comment]
@mars Helpfully, those docs are almost 100% useless. Sorry for any time wasted, I've been too slammed at work to update the site - however all the current docs are up [in the repo](https://github.com/Popmotion/popmotion/tree/master/docs).

Luckily the API is simplified now so it should be simpler to get up and running. I'm using Popmotion in production to make galleries [like this](https://drivetribe.com/gallery/f_QxyzgURfmHwSNMezLvHA/PBlBg1MST8aAx07Jtppc0Q/MG6-hsHbRbOXHDVIYQPM6A) and sliders [like this](https://drivetribe.com/tribes)

We don't have much in the way of guides yet but luckily the one we do have is [https://github.com/Popmotion/popmotion/blob/master/docs/guides/topics/functional-value-pipelines.md](this) which is an example of a slider which will hit a lot of the bases you're after.

**Comment by InventingWithMonster** [comment]
@mars @gaou-piou Here's a fork of Mars' CodePen updated to 6.0 http://codepen.io/popmotion/pen/YNJNxo?editors=0010

Just a note, now `flow` is in the left-to-right functional compositor, not the confusing and semi-hidden concept we had in <=5.0

**Comment by mars** [comment]
Thank you @InventingWithMonster 🙏 This new Codepen example & the repo docs link for functional-value-pipeline will help tremendously. It will be a couple days before I can pick back up on this project again. I'll follow-up once I make progress.

**Comment by InventingWithMonster** [comment]
We've got full React support now with https://popmotion.io/api/react
