### ISSUE TITLE
SVG Path example won't run on Firefox

### ISSUE THREAD

**Issue by Mike-NetCode** [Popmotion/popmotion#174]
I am trying to open https://codepen.io/popmotion/pen/MKNzRR sample in latest firefox (51) and it simply doesn't show up yet the console is clean. The same issued I observed on FF 48.

I tried to use older versions of codepen (3.x and 4.x) with their respective samples of the same animation (tick in a circle) and I got NS_ERROR_FAILURE in the console log, but I dont get any error in 5.x

Can you confirm?

**Comment by InventingWithMonster** [comment]
Hey Mike - I'll upgrade this example to 6.0 and fix the path issue in Firefox

**Comment by Mike-NetCode** [comment]
Oh, I must have been tired as I thought that 5.0 is the latest :)

**Comment by InventingWithMonster** [comment]
@Mike-NetCode Hey Mike. I've updated the pen to 6.0 and works in Firefox now.

The problem was animating `path` tags within `defs`. They don't technically have a bounding box in Firefox hence the error. To fix, I moved to normal paths.

**Comment by Mike-NetCode** [comment]
Thanks I will check it out in a few hours
