### ISSUE TITLE
Erron on Firefox when trying to animate a svg path

### ISSUE THREAD

**Issue by kaisermann** [Popmotion/popmotion#175]
I'm trying to animate a svg path that I use as a loading mask. 

The following code works on Safari and Chrome (didn't test it on IE or Edge yet) but fails on Firefox.
```js
const svgRenderer = svg(svgPathNode)
  tween({
    from: 0,
    to: 1,
    duration: 800,
    ease: easing.backOut,
    onUpdate: v => svgRenderer.set('scale', v),
  })
  .start()
```

The point of failing is the line which the `svg/index.js` calls the `getBBox`. However, in firefox, the `<path>` has no method `getBBox`and so popmotion crashes.

For the time being, my current workaround is to pass the complete svg node to the renderer and then overwriting `svgRenderer.props.element` with the `<path>` element.

Is this the expected behaviour? I mean, should I pass only `<svg>` elements to the `svgRenderer`? If so, how would I scale my `<path>` that's inside of it?

Thanks and awesome lib ;)

Edit:

I've already tried to use `svgPath(path)` but it did not animate the scale property :(

**Comment by InventingWithMonster** [comment]
@kaisermann Hey there! Do you have a codepen example I could take a look at?

For instance here: http://codepen.io/popmotion/pen/MKNzRR we've got an `path` element being animated by both the `svg` and `svgPath` renderers, and that works fine in Firefox, so it'd be helpful to a broken example so I can have a tinker

**Comment by kaisermann** [comment]
There you go: http://codepen.io/kaisermann/pen/jygOEw :)

**Comment by InventingWithMonster** [comment]
Brilliant thanks - I suspect this is down to Firefox handling certain elements funny. For instance a element within a `defs` block has no `getBBox` method either, I reckon it'll be the same for `mask`. I'll see if there's a way around this.
