### ISSUE TITLE
Input tracking example

### ISSUE THREAD

**Issue by gaou-piou** [Popmotion/popmotion#177]
Can we have the old example with the ball & input tracking & physics using this version of popmotion?

**Comment by InventingWithMonster** [comment]
Sure, are you referring to this http://codepen.io/popmotion/pen/pyeKoB?

**Comment by gaou-piou** [comment]
Yes, this one. :)

**Comment by InventingWithMonster** [comment]
I've updated that CodePen to 6.0!

**Comment by gaou-piou** [comment]
getVelocity().

Beautiful.
Thank you
