### ISSUE TITLE
Add support for prefers-reduced-motion

### ISSUE THREAD

**Issue by InventingWithMonster** [Popmotion/popmotion#180]
http://devdocs.io/dom/window/matchmedia

**Comment by Martin-Pitt** [comment]
What do you mean by this? I'm really confused.

Prefers Reduced Motion is what it says on the tin, not remove it, but reduce it, or more generally alternative animations, e.g. replacing a big heavy movement with a fade effect.

With how popmotion is just a values pipeline, it doesn't to do the rendering itself it seems, the user chooses to put the use values as they fit right now, e.g. into a transform (for a full motion animation) or into opacity of an element (for an alternative fade option).

Would be cool to see an example in docs with it though, just to help promote it and bring awareness.
But I'm not sure how support could fit in beyond what matchmedia does already?

**Comment by InventingWithMonster** [comment]
True, I think you're right on this one. 

I was thinking each action could automatically jump to its "to" fair but that's not purr responsibility. Would make a good
Blog post though
