### ISSUE TITLE
Can we have tween methods into actions?

### ISSUE THREAD

**Issue by gaou-piou** [Popmotion/popmotion#185]
It would be great if we could use tween methods, like flip or reverse into actions

```
composite({
  scale: tween({ from: 1, to: 0.6 }),
  opacity: tween({ from: 1, to: 0 }),
}, {
  duration: 300,
  onUpdate: (props) => {
    testRenderer.set(props)
  },
}).flip().start()
```

**Comment by InventingWithMonster** [comment]
Sorry for the delay, seem to have alerts turned off. The with this approach is a lot of actions can't necessarily be flipped or reverse - these are tween specific controls. I'll have a think how I can make it easier to work with composite actions.
