### ISSUE TITLE
One animation mapping to multiple properties

### ISSUE THREAD

**Issue by jacobp100** [Popmotion/popmotion#187]
Say I have something like google maps where the user can pan and zoom around a map. This is done in a canvas, so the renderer simply sets transforms on the canvas context, and then triggers a draw.

I define three `value`s to represent the viewport: `screenX`, `screenY`, and `screenZoom`. These values can be animated, for example, to zoom out to show area. They can also have the `set` method called when the user pans.

For the former, it's as simple as `parallel([tween({...}).output(screenX), ...])`. For the other part, I'm actually using [d3-zoom](https://github.com/d3/d3-zoom/), but I can handle user interaction with `screenX.stop().set(newX)`.

So now I have an object that is moving on the screen, and I want to track it.

```js
const objectX = value(0, v => renderer.set('object-x', v))
const demoAnimation = tween({ from: 0, to: endX, duration })
  .output(objectX)
  .start()
```

However, whilst this is happening, I want the screen to pan along with it, based on the zoom. This could look something like,

```js
const initialX = screenX.get()
const initialZoom = screenZoom.get()
demoAnimation
  .alsoOutputTo(x.andTransformIt(value => value * initialZoom + initialX))
```

However, if the user starts panning the screen, the screen animation should stop, but the object animation should not.

I tried various approaches using composite and other actions. Some of them have issues where one the screen and the object would be a frame apart from each other. None of them cancelled screen animation when I called `screenX.stop()`

---

To get this working, I've made the following class,

```js
class PassThrough extends Action {
  constructor({ value, transform }) {
    super()
    this.toUpdate = value
    this.transform = transform
  }

  set(v) {
    if (this._isActive) {
      this.toUpdate = this.transform(v)
      onFrameUpdate(this.scheduledUpdate)
    }
    return this.toUpdate
  }

  update() {
    return this.toUpdate
  }
}

const passThrough = (value, transform = x => x) => new PassThrough({ value, transform })
```

And hooked it up with the following,

```js
const animateObject = passThrough(0).output(objectX)
const animateScreen = passThrough(initialX, v => v * initialZoom + initialX))

const demoAnimation = tween({ from: 0, to: endX, duration })
  .output(t => {
    animateObject.set(t)
    animateScreen.set(t)
  })
  .start()
```

---

I was wondering if either I've missed something obvious, or if this use case has been considered.

I think this issue would in part be solved by being able to fork animations, so that the object animation can continue but the screen animation is stopped. And also the ability to have each animation output to multiple `value`s (because I only showed moving in x here, but in reality, it's x *and* y, but both are based off the same parameter).

**Comment by InventingWithMonster** [comment]
Hey Jacob

Is it not possible to do (and this is stipped down)

```javascript
const screenX = value(0, () => {});
const objectX = value(0, () => {});

let isPanning = false;

const demoAnimation = tween({
  onUpdate: (v) => {
    objectX.set(v);
    if (!isPanning) screenX.set(v)
  }
}).start();
```

Or maybe something like

```javascript
const { pipe, conditional } = transform;

let isPanning = false;

const objectX = value(0, pipe(
  conditional(
    () => isPanning,
    (v) => screenRenderer.set('x', v)
  ),
  (v) => objectRenderer.set('x', v)
));

tween(props).output(objectX).start();
```

**Comment by jacobp100** [comment]
I think the additional `isPanning` state will add a lot of complexity to my app. I want to play around with the idea of forking animations, and an animation can either be forked (possibly multiple times), or have an output. I'll play around with this and let you know how it goes!

**Comment by InventingWithMonster** [comment]
Cool man keep me updated!

**Comment by jacobp100** [comment]
I was able to do this with `trackOffset`!

```js
const tAnimation = physics({ ... }).start()
parallel([
  trackOffset(tAnimation).output(objectX),
  trackOffset(tAnimation, { transform: value => value * initialZoom + initialX }).output(screenX)
]).start()
```
