### ISSUE TITLE
Frame error on timeline loop

### ISSUE THREAD

**Issue by gaou-piou** [Popmotion/popmotion#188]
When i use timeline into loop, there is a frame error on repeat.

Example with code:  http://acantha.mooo.com/popmotion/

p.s.  On the occasion, very useful the timeline

**Comment by InventingWithMonster** [comment]
Hey man, your example isn't loading for me, but are you saying that

```
timeline(tweens, { loop: true }).start()
```

Is throwing an error after the first play?

**Comment by gaou-piou** [comment]
the code is the following
```
const elRenderer = css(this.$el)
		const
			anim = {
				up: tween({
					to: -100,
					duration: 300,
					ease: easing.easeOut,
				}),
				down: tween({
					from: -100,
					to: 0,
					duration: 300,
					ease: easing.easeIn,
				}),
			}
		timeline([
			anim.up.output((v) => elRenderer.set('y', v)),
			anim.down.output((v) => elRenderer.set('y', v)),
		], {
			loop: Infinity,
		}).start()
```

After first repeat, the anim has a frame render from position y: -100

**Comment by InventingWithMonster** [comment]
Ah I see. Could you do me a favour and try this:

```
const setY = (v) => elRenderer.set('y', v);

// define your animations as you already do

timeline([
  anim.up.output(setY),
  anim.down.output(setY),
], {
  loop: Infinity,
}).start()
```

**Comment by gaou-piou** [comment]
Yea, it works in that way

**Comment by InventingWithMonster** [comment]
Cool man. I'll clarify this in the documentation - basically to make sure we're firing the correct setters and allow seeking, we categorise timeline segments by their `onUpdate`. By providing two functions that do the same but are actually different, we're making sure to firing both which results in the effect you saw.

**Comment by gaou-piou** [comment]
Ok, i understand
