### ISSUE TITLE
react-transition-group v2.0

### ISSUE THREAD

**Issue by MrArnoldPalmer** [Popmotion/popmotion#190]
Hey,

Wondering if its on the roadmap to support react-transition-group v2.0? Its possible that its already supported and the examples are just out of date?

Either way I could possibly make a PR to help?

Thanks.

**Comment by InventingWithMonster** [comment]
Hey man

Yeah this only occurred to me the other day when looking through the
transition-group docs. We're still using 1 at work so I didn't realise it
was such a difference. If you've got the time by all means, it'd be great
to support 2!

**Comment by MrArnoldPalmer** [comment]
Cool. I'll check it out and see if I can lend a hand.

**Comment by InventingWithMonster** [comment]
Closing as Popmotion x React is deprecated in favour of React Pose and the `PoseGroup` component.
