### ISSUE TITLE
issues after `componentWillLeave`

### ISSUE THREAD

**Issue by chrisdrackett** [Popmotion/popmotion#191]
I'm trying to follow the react example in the doc and added `componentWillLeave` along with `componentWillEnter`

Everything works great, however after the component leaves I get the following in the console:

```Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the MotionValue component.```

**Comment by InventingWithMonster** [comment]
@chrisdrackett Thanks for letting me know, I'll take a look

**Comment by InventingWithMonster** [comment]
Closing as Popmotion x React is deprecated in favour of React Pose
