### ISSUE TITLE
popmotion-draggable is popmotion-spinnable after babel

### ISSUE THREAD

**Issue by dylancarlone** [Popmotion/popmotion#193]
For some reason, the post-install babel on popmotion-draggable leaves you with the source of popmotion-spinnable in node_modules/popmotion-draggable/lib/index.js. I don't see any reference to spinnable outside of its package directory. I am quite confused.

**Comment by InventingWithMonster** [comment]
Haha well this is a new one. I'll take a look when I get to work, thanks
for pointing it out.

**Comment by dylancarlone** [comment]
Thanks! I was worried it was something stupid I was doing with my build, but I even installed it in a fresh directory with the same problem.

**Comment by InventingWithMonster** [comment]
@dylancarlone Fixed in `1.0.2`
