### ISSUE TITLE
currentFrameTime Rename Breaking SemVer

### ISSUE THREAD

**Issue by jacobp100** [Popmotion/popmotion#197]
It looks like `currentFrameTimestamp` was renamed to `currentFrameTime` in what was published a non-breaking update. Also worth noting the documentation has not been updated for the new name.

**Comment by InventingWithMonster** [comment]
Ah my mistake, thanks for pointing this out. `currentFrameTimestamp` is still correct, this isn't due to change until `8.0.0`. I'll publish a fix now.

**Comment by InventingWithMonster** [comment]
Actually, to be more accurate, all these render loop functions are deprecated and will be available through `framesync` after `8.0.0`, so you can get on the upgrade path with 

```
import { currentFrameTime } from 'framesync';
```
