### ISSUE TITLE
support named colors

### ISSUE THREAD

**Issue by mking-clari** [Popmotion/popmotion#199]
I'm using popmotion in the next version of [react-ios-switch](https://github.com/clari/react-ios-switch), and I think it's great. However, I noticed popmotion does not support named colors.  

I can think of a couple of alternatives.
1. [small change] Use [color-name](https://github.com/colorjs/color-name)
1. [large change] Delegate color functions to an external library such as [color](https://github.com/Qix-/color) or [d3-color](https://github.com/d3/d3-color) 

My preference is the second option because it moves maintenance of color functions out of popmotion (which I consider to be an animation library) to a color-specific library.

**Comment by InventingWithMonster** [comment]
Hey man

We don't support named colours just because it's pretty cheap to support hex/rgba/hsla and named colours are so limited. But I feel like animating colours is common enough that we should offer support in some capacity (like colortween)

**Comment by aleclarson** [comment]
At the very least, I think `black` and `white` should be supported. :)

**Comment by InventingWithMonster** [comment]
I understand the sentiment but in a way those are also the least valuable to be supported. All other colours are the subject of some ambiguity so it theoretically helps to have a shorthand like blue, but everyone knows #fff and #000
