### ISSUE TITLE
Cancel / reset animation on mouseout/mouseleave

### ISSUE THREAD

**Issue by aderaaij** [Popmotion/popmotion#200]
Heya! I absolutely love Popmotion, but I have a small problem which I was hoping you could help me with: I'm not sure how to cancel an animation on a hover toggle. I'm using Popmotion in a React setup and I've got one complex item which animates itself + multiple items inside it on hover. It works fine until you hover over it real quickly. The animation reverses but in the end the last element to animate always reverts to its previous state due to the `mouseenter` animation not being completed. 
As example I made a quick pen; https://codepen.io/aderaaij/pen/OxLmvm

I understand that this might be more of a general JS question than a question about Popmotion, so by all means send me to SO if you don't have time for this

**Comment by InventingWithMonster** [comment]
Hey man!

I haven't had a chance to give it a play but by glancing at code my first guess would be that actions from the previous mouse event aren't being stopped.

For performance reasons I'd recommend doing your query selection onMount and then setting up value actions for each value you want to change. Then you can provide the values to onUpdate. This will ensure any other actions bound to them are stopped before the new actions are started. Alternatively you could manually keep track of animations you start and stop them yourself

**Comment by aderaaij** [comment]
Hey there, thank you for your reply! That is exactly what seems to happen indeed. I think this points me in the right direction. I've got some things to try out. 

Building the query selection and actions onComponentDidMount seems like the way to do it, I'll see if I can figure that out with my current setup as well.

Thanks again, also for the awesome library!
