### ISSUE TITLE
Should trackOffset stop when the animation stops?

### ISSUE THREAD

**Issue by jacobp100** [Popmotion/popmotion#201]
I feel like if I do,

```js
const base = spring({ ... })
trackOffset(base).output(x)
trackOffset(base).output(y)
```

`x` and `y` should stop receiving updates when `base` stops.

I looked into how this might be implemented, but it seems like you'll need `onStartListeners` and `onStopListeners` to have this work when one animation is passed to `trackOffset` multiple times.

**Comment by jacobp100** [comment]
I'm using this in the meantime.

```js
import { Action, transform } from "popmotion"

class TrackOffset extends Action {
  onStart() {
    const { action } = this.props
    const previousOnStop = action._onStop
    action._onStop = () => {
      this.stop()
      if (previousOnStop) previousOnStop()
    }
    this.applyOffset = transform.applyOffset(action.get(), this.current)
  }

  update() {
    const { action } = this.props
    return this.applyOffset(action.get())
  }
}

export default (action, props) => new TrackOffset({ action, ...props })
```

**Comment by InventingWithMonster** [comment]
Yeah it's a bit mad with the track offset stuff, I made a mistake putting that in to be honest. I recommend making composing an output function for spring that uses the applyoffset transformer instead

**Comment by jacobp100** [comment]
I have some functions that take an animation as a parameter use track offset to sync with it. It would be bad to mutate the animation by overriding the transform. For this, trackOffset is (almost) perfect! Did you have something else in mind for this use case?

**Comment by jacobp100** [comment]
Would you accept a PR that fixes this?

**Comment by InventingWithMonster** [comment]
Yeah I'm working on a slightly alternative API that embraces immutability and reactive patterns. So you could do:

const base = spring()
base
  .pipe(offset(x.get())) //returns new animation
  .start(x)
// repeat for y

So you'd not be mutating the animation. And instead of managing three actions you'd just have two.

Interested on your thoughts.

**Comment by jacobp100** [comment]
That could work! Could the `pipe` or `offset` take a transform function?

**Comment by InventingWithMonster** [comment]
Yeah in this case `offset` would be a transformer. 

The idea is every action would return a `pipe`, `bind` and `start` method.

`pipe` would return a new version of the action where every new value first gets passed through the functions given to it.

`bind` would take an update function and return a bound version of the action with just a `start` function.

`start` would take an update function and start an instance of the action. It would return an api, specific to the action type (for instance `tween().start()` would have a `seek` method but all actions would return at least `get`, `getVelocity` and `stop`)
