### ISSUE TITLE
Popmotion React Docs Page Crashes

### ISSUE THREAD

**Issue by KraigWalker** [Popmotion/popmotion#202]
![screenshot_091317_033010_pm](https://user-images.githubusercontent.com/1294877/30383043-a3d34d1c-9898-11e7-9dfa-59566ba33a3a.jpg)

**Comment by InventingWithMonster** [comment]
Thanks I'll take a look asap

**Comment by KraigWalker** [comment]
to me it looks like one of the examples is crashing, causing the catchall error screen to come up. I've been disabling javascript in devtools to get round the issue for now.

**Comment by InventingWithMonster** [comment]
Sorry for the delay in fixing this, I've just published a fix
