### ISSUE TITLE
Parallel action sometimes never completes in certain scenarios

### ISSUE THREAD

**Issue by danielkalen** [Popmotion/popmotion#204]
I cannot provide an example scenario when this issue arises, but the parallel action's [isActionComplete](https://github.com/Popmotion/popmotion/blob/b4c3a6d296ba58bd99a95ad116f4223ecf47360f/src/actions/parallel.js#L51) seems to never return `true` in scenarios where [added actions' `onStop` methods executes more than once](https://github.com/Popmotion/popmotion/blob/b4c3a6d296ba58bd99a95ad116f4223ecf47360f/src/actions/parallel.js#L28), causing `this.numActiveActions` to equal to a value below 0, hence `isActionComplete` never returns `true` because it checks for 0 equality.

The quick fix would be to modify `isActionComplete` to test if `this.numActiveActions <= 0` but the source of the bug is obviously `action.onStop` firing twice.

**Comment by InventingWithMonster** [comment]
Fixed in `8.1.24`
