### ISSUE TITLE
Keyframes on beta

### ISSUE THREAD

**Issue by gaou-piou** [Popmotion/popmotion#208]
Congrats for your new approach.
Here i create a codepen with a bug on keyframes

https://codepen.io/gaougalos/pen/GOmrrx?editors=0011

**Comment by InventingWithMonster** [comment]
Hey man, thanks for the test case! I'll look into this now

**Comment by InventingWithMonster** [comment]
Hey man so I moved this into my test suite and it worked fine. I did uncover a bug where the first outputted value was undefined so I’ll take a look at that tomorrow. But I actually suspect this file isn’t the latest version of Popmotion, which you can get from the repo directly or from https://unpkg.com/popmotion@8.0.11/dist/popmotion.global.min.js

**Comment by InventingWithMonster** [comment]
@gaou-piou Fixed https://unpkg.com/popmotion@8.0.19/dist/popmotion.global.min.js
