### ISSUE TITLE
Styler not setting CSS values in latest Beta

### ISSUE THREAD

**Issue by aderaaij** [Popmotion/popmotion#210]
How's it going? I was just experimenting a bit, and when I grabbed the latest beta file from your github (after putting it through gitraw) it seems that values do not get set anymore with the `styler`. See here for an example: https://codepen.io/aderaaij/pen/10ecfc65a1d9f987cba53586bdab3e65/

The element does get a style tag (and also `.get` seems to work and gets the updated value) but `.set` doesn't apply any css values. 
When I use the file that is in your last demos on codepen, everything works fine.

On a side note, I'm loving where you're going with popmotion. It would be great if you had some more visual examples though, basic stuff like toggling a position, color, with different physics. I have to admit that I don't always get along too well with your docs 😅

**Comment by InventingWithMonster** [comment]
Hey man, there was a fixed bug in Stylefire that I didn't upgrade Popmotion with. Doh! https://unpkg.com/popmotion@8.0.28/dist/popmotion.global.min.js - this url is better as well for pens as I've noticed the `rawgithub` urls tend to cache old versions.

Glad you're enjoying the new direction. There is a site revamp coming too, that's actually what I'm working on now. It should be more example-heavy, the homepage looks like this:

![image](https://user-images.githubusercontent.com/7850794/33114998-3e4ef018-cf57-11e7-892d-583c4f00be62.png)

**Comment by aderaaij** [comment]
Thanks, I'll use the unpkg  link.

It's amazing, the amount of possibilities you've created in such a small package. Looking forward to the new site 🔥🔥🔥
