### ISSUE TITLE
Example viewport units

### ISSUE THREAD

**Issue by exdeniz** [Popmotion/popmotion#211]
Please show an example of working with viewport units(100vw, 100vh).

**Comment by Martin-Pitt** [comment]
The window object has all you need to do the same in JS for viewport units:

1vw = `window.innerWidth * 0.01`

1vh = `window.innerHeight * 0.01`

Is that what you meant?

**Comment by InventingWithMonster** [comment]
When you output, you can just do

```
tween({
  from: 0,
  to: 100,
  onUpdate: (v) => myRenderer.set('x', v + 'vh')
}).start()
```
