### ISSUE TITLE
How we can trigger 'complete' on an action at the end of each loop?

### ISSUE THREAD

**Issue by gaou-piou** [Popmotion/popmotion#213]
Here is an example on codepen
https://codepen.io/gaougalos/pen/GOmrrx?editors=0011

**Comment by InventingWithMonster** [comment]
You can't, currently. You'd have to restart the tween on `complete` rather than using `loop`.

It has made me think we could add a new `event` function where actions could emit custom events, and you'd subscribe like

`tween({ loop: Infinity }).start({
  event: (type, value) => {
    if (type === 'loop) // do stuff
  }
})`

What do you think?

**Comment by gaou-piou** [comment]
It sounds very good and is increases the abilities of the library, i think.

And since we started the suggestions, how would you feel if we could have generics easings on keyframes?
Something like this 

```
keyframes({
	values: [
		{ scaleX: 1.4, scaleY: 0.6, y: 0 },
		{ scaleX: 1, scaleY: 1, y: 0 },
		{ scaleX: 1, scaleY: 1, y: -200 },
		{ scaleX: 1, scaleY: 1, y: 0 },
		{ scaleX: 1.4, scaleY: 0.6, y: 0 },
	],
	duration: 1000,
	times: [0, 0.15, 0.5, 0.85, 1],
	ease: [easing.circInOut],
	loop: Infinity,
})
```
and it was applied to the whole movement and not to each one separately

**Comment by InventingWithMonster** [comment]
You can do that with `ease: easing.circInOut`. I'll make sure it's in the
docs

**Comment by gaou-piou** [comment]
Here is the result with `ease: easing.circInOut` 
https://codepen.io/gaougalos/pen/GOmrrx
It applies the easing to each keyframe separately.
I mean to apply the easing to the full action.

**Comment by InventingWithMonster** [comment]
Oh I see! Yeah fair point. I’ll have a think, it might be a ‘easePlayback’
property

**Comment by InventingWithMonster** [comment]
@gaou-piou from 8.0.34 `ease` will control the easing of the master tween, `easings` will apply to the individual transitions
