### ISSUE TITLE
Popmotion Beta suggestions

### ISSUE THREAD

**Issue by gaou-piou** [Popmotion/popmotion#214]
Hello again.
Can we have delay as prop or as method to actions too?
for example

`tween().delay(300).play(v => {  })`
or
```
tween({
  from: [0, 5, 20],
  to: [100, 200, 300],
  ease: easing.linear,
  delay: 300,
})
```

**Comment by InventingWithMonster** [comment]
Hey man, I'm trying to keep functions that composite actions in this way to external compositor functions. It keeps the library more modular and composable.

For instance I just released a `schedule` compositor, this way you could conceivably do this:
```
schedule(
  chain(delay(200), everyFrame()),
  pointer()
)
```

Which would output the latest pointer position every frame after a 200ms delay
