### ISSUE TITLE
chain reset or restart animation.

### ISSUE THREAD

**Issue by exdeniz** [Popmotion/popmotion#217]
How to reset animation and restart on event in chain? Timeline is not suitable for physics.

**Comment by InventingWithMonster** [comment]
Hey man. I’d need some
Code to understand what you’re doing but physics is integrated which means
you can’t replay or reverse it unless you output its values to a buffer and
then use everyFrame to iterate over that buffer

**Comment by exdeniz** [comment]
I want simple restart animation. Like GSAP timeline.restart()

**Comment by InventingWithMonster** [comment]
Ah ok for that you'd just start the animation again.

**Comment by exdeniz** [comment]
start again don't reset transition on element. For example, i use animation on change slide, GSAP:
```
onSlideChangeStart: {
   timeline.restart().stop()
   // revert initial position element and stop animation
}
onSlideChangeEnd: {
    timeline.play()
    // on slide change, start animation.
}
```
For live demo - https://www.glav-beer.ru/

**Comment by InventingWithMonster** [comment]
With Popmotion you wouldn't approach it in that way. You'd do it like this:

7: 
```javascript
onSlideChangeStart: {
    animation = physics({
      onUpdate: update
    }).start();
}
onSlideChangeEnd: {
   animation.stop();
}
```

8: 
```javascript
onSlideChangeStart: {
    animation = physics().start(update);
}
onSlideChangeEnd: {
   animation.stop();
}
```

Especially if you're trying to use physics, half the point of that animation is to take an existing `velocity` and provide it to a new animation:

8:
```javascript
const sliderX = value(0, updateSliderPosition);

function onSlideChangeStart() {
  physics({
    velocity: sliderX.getVelocity(),
    from: sliderX.get(),
    springStrength: 500,
    to: target
  }).start(sliderX)
}
```

**Comment by exdeniz** [comment]
Tnx, i can try on next project.

**Comment by jzyds** [comment]
`
controls.seek(0)
controls.stop()
`
