### ISSUE TITLE
Broken tutorial

### ISSUE THREAD

**Issue by lazarljubenovic** [Popmotion/popmotion#218]
The tutorial on https://popmotion.io/learn/velocity-and-physics/ is broken. In both latest Chrome and Firefox the demos are not running properly. As I "pick up" the ball with my mouse, I can't shake it off, not matter how many times I do mouseup.

**Comment by InventingWithMonster** [comment]
Thanks for the heads up! I'm days away from releasing Popmotion 8 and a new site to go with it. I'll make sure that these examples are all working properly.

**Comment by lazarljubenovic** [comment]
Oh. Hopefully things won't change _too_ much in 8. I'm stalking this lib for months now and only today got to play around with :sweat_smile:
