### ISSUE TITLE
Consider aligning the API with the Observable proposal

### ISSUE THREAD

**Issue by appsforartists** [Popmotion/popmotion#223]
It looks like you have some very similar structures to [the observable proposal](https://github.com/tc39/proposal-observable/), but with different names.  For instance:

`action.start(callback)` vs `observable.subscribe(observer)`

or 

`subscription.unsubscribe` vs `subscription.stop()`

Have you considered aligning these names with the Observable proposal, so they're more easily interoperable with other functional-reactive libraries?

**Comment by appsforartists** [comment]
Note: if you're attached to `start` and `stop` as simpler concepts than `subscribe` and `unsubscribe`, it seems like it would be pretty simple to add the Observable API to `action`, as a sugar over the existing API.

e.g.

```typescript
  subscribe(observer) {
    const callback = observer.next || observer;
    return this.start(callback);
  }
```

**Comment by InventingWithMonster** [comment]
Yeah it’s been considered, but:

1) I didn’t want to stray too far from the existing API
2) I don’t think subscribe is a good name for what is actually happening. We do have a subscribe/unsubscribe on the multicast reaction. It makes sense in that situation. But I didn’t want to get into explaining the whole hot and cold observable thing to an audience that might just be using a reactive frame incidentally

That said I can see a near future where a wrapper lib or method is offered. Like ’observableFromAction’

**Comment by QuentinRoy** [comment]
If I may add my grain of salt, I do agree that the observable paradigm does have many subtleties and edge cases that might be hard to grasp for beginners.
However, I have been digging into its API for half an hour now and I still do not have a clear sense of how to do some simple things---e.g switching from an animations to another (i.e. a basic `map`). As an advanced programmer, I do feel a bit frustrated to have to learn an entirely new API (that does not necessarily makes much more sense that the near-standard one).
