### ISSUE TITLE
Tell what actual color blending you use

### ISSUE THREAD

**Issue by flying-sheep** [Popmotion/popmotion#228]
On the demo page it says

> Popmotion uses advanced color blending that avoids muddy brightness loss.

So… which one is it? HSL? HuSL? L\*a\*b? Please add this info to the demo page.

**Comment by InventingWithMonster** [comment]
Yeah fair, I'll look into doing this. For your own information, we're using the method outlined in this video https://www.youtube.com/watch?v=LKnqECcg6Gw

**Comment by flying-sheep** [comment]
OK, so you’re using the “linear RGB” space! maybe even linking the vid.

sadly not even chroma.js can do it yet (gka/chroma.js#154).

[Here’s a pen](https://codepen.io/flying-sheep/pen/wPmKmB) visualizing the different color spaces.

**Comment by InventingWithMonster** [comment]
Ah nice one thanks 👍
