### ISSUE TITLE
TS errors on import

### ISSUE THREAD

**Issue by InventingWithMonster** [Popmotion/popmotion#229]
See https://www.reddit.com/message/messages/a9y415

**Comment by ralexand56** [comment]
Getting this error when installing in typescript project. error TS2411: Property 'stop' of type '(() => void) | undefined' is not assignable to string index type 'Function'.

**Comment by InventingWithMonster** [comment]
Thanks man I’ll take a look

**Comment by PhilipDavis** [comment]
I'm getting the same (using TypeScript v2.5.3)

```
...\node_modules\popmotion\action\types.d.ts
(4,5): error TS2411: Property 'stop' of type '(() => void) | undefined' is not assignable to string index type 'Function'.
```

**Comment by PhilipDavis** [comment]
FWIW, it compiles if I take out the `?`.  Also works if I change the following line from `Function` to `Function | undefined`

**Comment by ralexand56** [comment]
Hmmm, I ended up taking out the whole line since I don't use stop. Thanks for the info.

**Comment by DoNormal** [comment]
I'm getting TS warnings/errors on import too. I don't have a reddit account so I don't know if they're the same as yours. (I can open a separate issue if you prefer.)

Multiple of this type of warning:

```
WARNING in ./~/framesync/lib/create-render-step.js
Cannot find source file '../src/create-render-step.ts': Error: Can't resolve '../src/create-render-step.ts' in '/home/x/www/dev/x/robert/public/node_modules/framesync/lib'
 @ ./~/framesync/lib/index.js 4:27-58
 @ ./~/popmotion/transformers.js
 @ ./~/popmotion-pose/lib/factories/values.js
 @ ./~/popmotion-pose/lib/index.js
```

And 1 error:

```
ERROR in [at-loader] node_modules/popmotion-pose/lib/factories/poses.d.ts:1:37
    TS2307: Cannot find module 'types'.
```

I'm only importing `pose` and I'm building with TypeScript 2.8.1 / webpack 2.2.1.
```
import pose from 'popmotion-pose';
```

If you need more debugging info, just let me know.

**Comment by InventingWithMonster** [comment]
Hmm that’s a weird one. As framesync is a dependency I should be getting the same error in Pose. I’ll take a look into that, I assume I have to republish framesync with the source files included (if they’re not already)

**Comment by DoNormal** [comment]
> Hmm that’s a weird one. As framesync is a dependency I should be getting the same error in Pose. I’ll take a look into that, I assume I have to republish framesync with the source files included (if they’re not already)

If I compile without webpack it works fine 🤔 I'll try and isolate the issue.

**Comment by DoNormal** [comment]
I've isolated the problem here: https://github.com/DoNormal/popmotion-prose-ts-errore. The warnings result from the `source-map-loader`, while the error seems to originate from the `awesome-typescript-loader`.

Could [this line](https://github.com/Popmotion/popmotion/blob/master/packages/popmotion-pose/src/factories/poses.ts#L3) be the problem?

```
import { PoserProps, Pose, PoseMap, Draggable } from 'types';
```

`'types'` is located in the directory above. [dimensions.ts](https://github.com/Popmotion/popmotion/blob/master/packages/popmotion-pose/src/factories/dimensions.ts) imports the types differently:

```
import { BoundingBox, Dimensions } from '../types';
```

**Comment by InventingWithMonster** [comment]
This was fixed in a previous release, thanks for the repo btw
