### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by FinesseRus** [Popmotion/popmotion#230]
What browsers does Popmotion support? Can't find this information in the documentation. Is all the stuff shown on the main page of [popmotion.io](popmotion.io) supported in IE9?`

**Comment by InventingWithMonster** [comment]
Hi there, I'll look into getting this info on the homepage. I'd be surprised if it didn't work in IE9 but officially we only support IE11+

**Comment by FinesseRus** [comment]
@InventingWithMonster 
> but officially we only support IE11+

Sounds not nice

Anyway thank you for the response

**Comment by InventingWithMonster** [comment]
Just going off browser stats. IE10 is used by a fraction of a percent of
users and due to Microsoft dropping support it should be considered a
security risk. I wouldn’t be doing anyone a favour by supporting it.

**Comment by FinesseRus** [comment]
@InventingWithMonster We have 0.73% of IE9 and IE10 users on our site. I think this is much enough.

![2017-12-17 12 17 45](https://user-images.githubusercontent.com/9006227/34075993-547e927c-e324-11e7-9f97-8c72a679c719.png)

I don't ask Popmotion to support this browsers, I just ask what browsers does Popmotion support.
