### ISSUE TITLE
use with angular.io 2/4/5

### ISSUE THREAD

**Issue by andy-dev** [Popmotion/popmotion#233]
Hello,

Could this work in production with angular 2? Do you have an easy example of best practices on how this would be done?

**Comment by cloudIC** [comment]
Of course, you can use in any framework. the popmotion is not binding to any library. you can see example in the doc.

**Comment by InventingWithMonster** [comment]
As cloudC says, it’s not bound to any framework so how you implement is up to you.

I don’t know Angular 2 but I use React a lot. The official React plugin simply uses a component wrapper to pass numbers to other components for greater versitility. Whereas personally I use the ref escape hatch to work with DOM nodes themselves for better performance.

I assume similar approaches are available in Angular.

**Comment by andy-dev** [comment]
Thanks, this is helpful, I'll give it a try!
