### ISSUE TITLE
Popmotion x React TransitionGroup Example

### ISSUE THREAD

**Issue by zachgibson** [Popmotion/popmotion#234]
Tried to run the example below, but there’s a TypeError that `px` is not a function. Also tried animating  without using `px` but still no luck, so I’m obviously missing something. I’m new to Popmotion and React Transition Group—any help would be greatly appreciated!

```JSX
import React from "react";
import TransitionGroup from "react-transition-group/TransitionGroup";
import { MotionValue } from "popmotion-react";
import { tween, transform } from "popmotion";
const { px } = transform;

const stateChangeHandlers = {
  componentWillAppear: ({ value, complete }) =>
    tween({
      from: value.get(),
      to: 100,
      onUpdate: value,
      onComplete: () => {
        console.log("Transition completed.");
      }
    }).start({
      update: value,
      complete
    })
};

export default () => (
  <TransitionGroup>
    <MotionValue key="unique-id" onStateChange={stateChangeHandlers}>
      {({ v }) => <div style={{ width: px(v) }} />}
    </MotionValue>
  </TransitionGroup>
);
```

**Comment by InventingWithMonster** [comment]
Hey man

Thanks for pointing this out - I'll amend the docs when I get the chance.

I removed `px` in Popmotion 8. You can replicate its functionality:

`const px = v => v + 'px'`

Reason being `width` in React doesn't automatically assign a default value type, so you have to provide it a string.

Alternatively `<div style={{ width: v + 'px' }} />`

Hope this helps!

**Comment by InventingWithMonster** [comment]
Actually looking at it, I've missed removing `onUpdate` and `onComplete` too! It should actually read:

```javascript

const stateChangeHandlers = {
  componentWillAppear: ({ value, complete }) =>
    tween({
      from: value.get(),
      to: 100
    }).start({
      update: value,
      complete: () => console.log("Transition completed.")
    })
};
```

**Comment by zachgibson** [comment]
Yeah that definitely helps. Is this code snippet all that’s needed to work? I assumed so, but my numerical value doesn’t change, it stays at 0. I feel like I’m just missing something simple.

**Comment by hanpei** [comment]
```

const px = (v) => `${v}px`;

const stateChangeHandlers = {
  componentWillAppear: ({ value, complete }) =>
    tween({
      from: value.get(),
      to: 100,
    }).start({
      update: (v) => console.log(v),
      complete: () => console.log('complete!'),
    }),
};

export default () => (
  <TransitionGroup>
    <MotionValue key="unique-id" onStateChange={stateChangeHandlers}>
      {({ v, complete }) => <div style={{ width: px(v), height: px(v) }} />}
    </MotionValue>
  </TransitionGroup>
);
```

is this code right?  nothing happened.

**Comment by hanpei** [comment]
``` javascript
const px = (v) => `${v}px`

const stateChangeHandlers = {
  componentWillAppear: ({ value, complete }) =>
    tween({
      from: value.get(),
      to: 100,
    }).start({
      update: value,
      complete: () => {
        console.log('complete!');
        complete();
      },
    }),
};

export default () => (
  <TransitionGroup>
    <MotionValue key="unique-id" onStateChange={stateChangeHandlers}>
      {({ v }) => <div style={{ width: px(v), height: px(v), backgroundColor: 'red' }} />}
    </MotionValue>
  </TransitionGroup>
);
```

what's problem about this code ? nothing happened.

**Comment by kevronosx** [comment]
Yeah, I am not seeing this work at all....

`import React from 'react';

import { TransitionGroup } from 'react-transition-group';
import { tween } from 'popmotion';
import { MotionValue } from 'popmotion-react';

import './App.css';

const px = (v) => `${v}px`;

const stateChangeHandlers = {
  componentWillAppear: ({ value, complete }) =>
    tween({
      from: value.get(),
      to: 100,
    }).start({
      update: value,
      complete: () => {
        console.log('complete!');
        complete();
      },
    }),
};

export default () => (
  <TransitionGroup>
    <MotionValue key="unique-id" onStateChange={stateChangeHandlers}>
      {({ v }) => <div style={{ width: px(v), height: px(v), backgroundColor: 'red' }} />}
    </MotionValue>
  </TransitionGroup>
);
`

**Comment by InventingWithMonster** [comment]
Just an update - not ignoring this just been slammed between
Work and moving house atm

**Comment by ralexand56** [comment]
Also are there any type definitions for popmotion-react?

**Comment by Dremora** [comment]
@kevronosx looks like popmotion-react depends on [react-transition-group v1](https://github.com/Popmotion/popmotion/blob/c1a6db7528dbfc7868166b72ef4a27055bf868e6/packages/popmotion-react/package.json#L57).

**Comment by MrArnoldPalmer** [comment]
Just came across this. There is a separate issue regarding react-transition-group 2.0 support. I have been slowly (very slowly) trying to figure this out as I have time. Hopefully can get it resolved soon.

https://github.com/Popmotion/popmotion/issues/190

**Comment by dbismut** [comment]
Do you still need help on this? I'm not sure this helps but I was trying Popmotion this week-end and wanted to replicate the new App Store card behavior on click.

You can see it right [here](http://sid-appstore.surge.sh/). The code is a bit messy (I'm far from pro), it uses router5, redux which are a bit superfluous but it does use react-transition-group v2.

react-transition-group v2 no longer creates special lifecycle hooks such as `componentWillAppear()` on `<TransitionGroup>` children. Now `<TransitionGroup/>` needs to have `<Transition>` component as children.

**Comment by InventingWithMonster** [comment]
I've deprecated Popmotion React in favour of React Pose and the `PoseGroup` component so won't have the chance to take a look at this.
