### ISSUE TITLE
React-PopMotion TransitionGroup - componentWillLeave never fired

### ISSUE THREAD

**Issue by kalutheo** [Popmotion/popmotion#239]
Hi there, 

I'm trying to build a menu with a staggering animation when the menu appears (mounted) and disappears (unmounted).

I'm using React-PopMotion with TransitionGroup.
`componentWillAppear` is triggered and works as expected
but `componentWillLeave` is never called.

Here is my code running : 

https://stackblitz.com/edit/react-popmotion
( Click on the Blue Header with Mobile Breakpoint to Toggle Menu Opening)

Can you spot the mistake ?

The expected behavior is an animation when the menu is closed

**Comment by InventingWithMonster** [comment]
If I'm reading this right, `isShown` basically removes the entire `TransitionGroup` component when `false`?

`react-transition-group` only fires `willLeave`events if the child component is leaving. If the entire `TransitionGroup` component is removed, this event won't be fired. So you need to leave the `TransitionGroup` component rendered **at least** until all the children have animated out.

This is a big pain point using `TransitionGroup`.

**Comment by kalutheo** [comment]
I moved the `isShown` test on  the `MotionValue` component. So now the `TransitionGroup` is always rendered but know i got no animation anymore. the `componentWillAppear` hook is no more called :-( ...

**Comment by InventingWithMonster** [comment]
Ah yeah well now you’d be using componentWillEnter, I sometime use both

**Comment by kalutheo** [comment]
Hey @InventingWithMonster ! `componentWillEnter` did the trick. Works like a charm 
https://react-popmotion.stackblitz.io/

Thanks !
