### ISSUE TITLE
A Link In The Documentation Link Is Broken

### ISSUE THREAD

**Issue by ankitkumarojha** [Popmotion/popmotion#249]
The link under API > ACTION https://popmotion.io/api/reactions in the documentation is redirecting to "page not found".
<img width="1676" alt="screen shot 2018-01-18 at 10 53 53 am" src="https://user-images.githubusercontent.com/11675208/35082147-3fa541ce-fc3e-11e7-9284-db87669ee71c.png">

**Comment by InventingWithMonster** [comment]
Thanks man, I haven't published yet but I have updated the docs to remove this reference (as the whole section needed removing anyway)
