### ISSUE TITLE
the Codepen demo in `/api/keyframes` is broken

### ISSUE THREAD

**Issue by fate-lovely** [Popmotion/popmotion#251]
link is [here](https://popmotion.io/api/keyframes/), the demo can't work, should change `keyframes({ease: [...]})` to `keyframes({easings: easing.easeInOut})`.

**Comment by HelTi** [comment]
@fate-lovely 
it's not ease!
easing
`
keyframes({
  values: [0, 100, 200],
  duration: 1000,
  times: [0, 0.2, 1],
  easings: [easing.linear, easing.cubicBezier(.17,.67,.83,.67)]
}).start((v) => console.log(v));
`

**Comment by InventingWithMonster** [comment]
Thanks! This has been fixed now
