### ISSUE TITLE
finished argument in complete callback

### ISSUE THREAD

**Issue by souporserious** [Popmotion/popmotion#257]
How do you feel about passing back a `finished` argument in the complete callback of `action`? I was thinking something similar to what Animated does [here](https://facebook.github.io/react-native/docs/animated.html#working-with-animations).

I'm rebuilding an old library powered by Animated that I'm converting to Popmotion and ran into the need for a finished argument as seen [here](https://github.com/souporserious/animated-ui/blob/master/src/Fluid.jsx#L99). This works well since I only update the `isAnimating` state when the animation has really finished. Right now with Popmotion it can get triggered multiple times if the animation is interrupted. I may be doing something wrong though so please let me know if there is a similar alternative 😇.

**Comment by InventingWithMonster** [comment]
Unless I’m misreading you shouldn’t need it. Sorry for formatting I’m on my phone but you can just set the state on complete:

spring().start({
  update: v => v,
  complete: () => this.setState({ isAnimating: false })
})

**Comment by souporserious** [comment]
Sorry, I might not have explained that well, that's what I'm doing right now :). However, if the animation is interrupted by running the `spring` multiple times, from something like a button being toggled, then it causes the `complete` callback to fire multiple times. If there was a `finished` argument, I could determine if the animation was just interrupted or truly finished and call my `setState` update only once.

**Comment by InventingWithMonster** [comment]
Ah I see. It should be the case that if you cal
Stop on the existing animation, that it’s complete will never fire. Is that not the case?

**Comment by souporserious** [comment]
Ah I see! That's where I was misunderstanding things 💩I just read about all of the returned subscription methods 🤦‍♂️ . This works great! Sorry for the confusion on my end. Thank you 🙏
