### ISSUE TITLE
Performance improvement:

### ISSUE THREAD

**Issue by trusktr** [Popmotion/popmotion#258]
https://github.com/Popmotion/popmotion/blob/f3358c7e962289143ecbd740c5f902b1b31a8a0f/packages/popmotion/src/animations/tween/index.ts#L39

Creating functions inside of every tween is heavy, it duplicates the some function, one per instance.

If you save the functions on a prototype, then the same function is only created once, and shared with all instances. This can increase performance.

**Comment by trusktr** [comment]
Memory usage becomes O(1) instead of O(n) for these routines, and initialization is improved.

**Comment by InventingWithMonster** [comment]
Popmotion is quite careful to not, for instance, create a new function every frame. But for the purposes of normal use this shouldn’t be an issue (no premature optimisations)

Also using a class-based approach isn’t always a magic bullet. this- lookups are slower than using in-scope variables. Also if we sometimes have to do stuff like this:

someFunction().then(nextFunction)

With a class/prototypical approach we’ll have to bind nextFunction to this either using bind, creating it as a new function on class creation or wrapping it in an arrow function, all of which make new functions. Of course overall I imagine there’s be fewer instances of this but I doubt we’d avoid it altogether
