### ISSUE TITLE
How to hook into another animation loop?

### ISSUE THREAD

**Issue by trusktr** [Popmotion/popmotion#259]
Seems like `tween()` doesn't return an object with an `update` function, and doesn't have a way to manually tick the tween. Did I miss it?

**Comment by trusktr** [comment]
Seems like using `seek` is the way to do it, but it requires knowing where to seek to.

An `update` method that would require no arguments would be simple to use.

For example, with Tween.js, I can do this:

```js
import { Tween } from 'tween.js'

let done = false

const tween = new Tween(objectToAnimate)
  .to({x: 100}, /*duration*/300)
  .onComplete(() => done = true)
  .start()

// manually update the tween in your own animation loop
function loop(time) {
  tween.update(time)
  if (!done) requestAnimationFrame(loop)
}
```

It's important to make this easy in a library like Popmotion so that is can be easily integrated into existing applications that have their own render loops.

**Comment by InventingWithMonster** [comment]
I’ve got no objections to this functionality I’ve just only had the need to scrub via progress. If you look at the tween.js file it should be pretty easy to add a ‘seekTime’ method via PR
