### ISSUE TITLE
Release popmotion-spinnable 2.0.1 in NPM, current release 2.0.0 is broken

### ISSUE THREAD

**Issue by mikaelnousiainen** [Popmotion/popmotion#263]
Current release 2.0.0 of popmotion-spinnable cannot be used, because of a missing import (see #250).

Please release the current code as 2.0.1 in NPM.

**Comment by InventingWithMonster** [comment]
Thanks for the reminder man I’ll try and get to this ASAP

**Comment by gpmcadam** [comment]
Still broken a month later - any plans to bump this and release 2.0.0?

**Comment by mikaelnousiainen** [comment]
@InventingWithMonster ping once more :)

**Comment by InventingWithMonster** [comment]
Fixed in 2.0.1
