### ISSUE TITLE
Updating React component state when component props are updated

### ISSUE THREAD

**Issue by thisiskylierose** [Popmotion/popmotion#268]
At the moment, with the current implementation of popmotion-react, it doesn't seem possible to dynamically update the 'v' props values and trigger a reposition of the child element passed into MotionValue class. This seems because the position values are tied to the popmotion/reactions/value 'subscribe' method. 

This is an issue for animations that depend on dynamic changes to values that are triggered by viewport width or orientation changes. This issue also exists in Storybook implementations - especially so with addon-knobs that take user inputs. 

At present, I am part of a team that is looking to use popmotion-react on a large media site build. And we are considering whether the library is suitable for our needs, or not. 

What can be done to fix this issue? And are there any workarounds we can use in the meantime?

**Comment by InventingWithMonster** [comment]
It's pre-release but I'm going to deprecate this in favour of Pose, which you can see the WIP docs for here https://github.com/Popmotion/popmotion/tree/master/packages/popmotion-pose/docs/learn/basics

As for your request I just published an (untested!) update that should accomplish what you're after https://github.com/Popmotion/popmotion/blob/master/packages/popmotion-react/src/index.js#L75

**Comment by thisiskylierose** [comment]
Ok - thank you for the quick response. Is there an anticipated release date for pose?

**Comment by thisiskylierose** [comment]
Also, that update doesn't pass in a updated value object to the onStateChange methods. Unless I am interpreting the documentation incorrectly, the initial props seem to be static at that point.
