### ISSUE TITLE
argument to flip should be optional in typescript

### ISSUE THREAD

**Issue by pickle-ts** [Popmotion/popmotion#270]
So change this:
`flip: (op: Function) => Promise<any>;`

To this:
`flip: (op?: Function) => Promise<any>;`

Since in some cases you've already performed the measure. This change is already consistent with the implementation:

```
 flip: op => {
      if (op) {
        api.measure();
        op();
      }
      return set('flip');
    },
```

**Comment by InventingWithMonster** [comment]
Fixed in 1.0.19
