### ISSUE TITLE
[Pose] API page links are broken

### ISSUE THREAD

**Issue by jesstelford** [Popmotion/popmotion#272]
This page: https://popmotion.io/pose/api/

**Actual Behaviour:**

Points to the following links:
- Poser: `https://popmotion.io/pose/api/api/dom-pose/`
- Props: `https://popmotion.io/pose/api/api/props/`
- React
  - Posed Component: `https://popmotion.io/api/posed/`
  - PoseGroup: `https://popmotion.io/api/posegroup/`
- Transition Utils: `https://popmotion.io/pose/api/api/transition-compositors/`

**Expected Behaviour:**

Should point to:
- Poser: `https://popmotion.io/pose/api/dom-pose/`
- Props: `https://popmotion.io/pose/api/props/`
- React
  - Posed Component: `https://popmotion.io/pose/api/posed/`
  - PoseGroup: `https://popmotion.io/pose/api/posegroup/`
- Transition Utils: `https://popmotion.io/pose/api/transition-compositors/`

**Comment by InventingWithMonster** [comment]
Fix going out for this now, thanks man
