### ISSUE TITLE
website link is broken

### ISSUE THREAD

**Issue by cbbfcd** [Popmotion/popmotion#273]
hi, website link is broken...............

**Comment by estaub** [comment]
I've no idea what link @cbbfcd is referring to... I wanted to report what may be a different one.

On https://popmotion.io/pose/learn/get-started/, in the second **Setup** section, the [Install]() link is broken, should go to https://popmotion.io/pose/learn/install/ .

**Comment by cbbfcd** [comment]
it works!  thanks!!

**Comment by InventingWithMonster** [comment]
@estaub Thanks man - publishing a fix now
