### ISSUE TITLE
react-pose - posed onChange overrides input onChange

### ISSUE THREAD

**Issue by JoaoCnh** [Popmotion/popmotion#280]
I wanted an animated input but I lose complete control over the onChange event when using posed.

Is there any way around this? I'm using Formik to handle the change on the input.

**Comment by InventingWithMonster** [comment]
Hey man have you got a code example of this? I’m not familiar with formik

**Comment by JoaoCnh** [comment]
If I use:

`<input id="email" ... onChange={handleChange} />`

it works fine. But if I use a posed input

`<PosedInput id="email" pose="foobar" onChange={handleChange} />`

it doesn't. 

**handleChange** is a simple method that updates the value based on the input's id. More on formik [here](https://github.com/jaredpalmer/formik)

**Comment by InventingWithMonster** [comment]
Ah I see. This is a tricky one. I totally fucked up by naming it `onChange`.

What I'll do is:

1) Deprecate `onChange`
2) Introduce `onValueChange`
3) Check if `onChange` is a function or an object. If it's an object I'll use it, if it's a function we'll pass it on to the React Element.

I'll try and introduce this fix at some point today, thanks for raising this issue!

**Comment by JoaoCnh** [comment]
No problem. Love the lib. Works amazingly well

**Comment by InventingWithMonster** [comment]
Thanks man!

PR here: https://github.com/Popmotion/popmotion/pull/282

Probably won't get a chance to publish until tonight

**Comment by JoaoCnh** [comment]
No problem. Thanks for responding so fast

**Comment by eric-personal** [comment]
I've been trying to get the onValueChange work on a div. I just want to be able to get the value that is been updated every frame event. 

```
const Box = posed.div({
  visible: {
    opacity: 1,
    transition: props =>
      tween({ ...props, duration: 1400, ease: easing.easeInOut })
  },
  hidden: {
    opacity: 0
  },
  initialPose: 'hidden'
});

onBoxValueChanged(value) {
  console.log('BOX CHANGE = ', value);
}
<Box pose={this.state.isVisible ? 'visible' : 'hidden'} id="box" onClick={this.onToggle} onPoseComplete={this.onBoxComplete} onValueChange={this.onBoxValueChanged} />
```

**Comment by InventingWithMonster** [comment]
@JoaoCnh Just going through my PRs, as you probably know this has been fixed and published now.

From today there's a warning message if people try to use `onChange`.

@eric-personal It's per value ie `onValueChange={{ x: this.onBoxXChanged }}`
