### ISSUE TITLE
React playground not working

### ISSUE THREAD

**Issue by nodatall** [Popmotion/popmotion#284]
Hello friends,

The React playground [linked](https://codepen.io/popmotion/pen/mxmrPZ?editors=0010) from the docs is not working. 

I've also tried to get a basic transition working using the docs but couldn't get any animations to work. Here is the [pen](https://codesandbox.io/s/oxv1zlkn1z).

Thanks!

**Comment by InventingWithMonster** [comment]
Hey man. The playground is just a pen with Pose and Popmotion included for you to fork and mess around with. 

Your example is defining a new posed component every render so it can’t maintain pose state. Try moving that code outside of render where your styles are defined.
