### ISSUE TITLE
What's the suggested way to use PoseGroup with a render-prop child?

### ISSUE THREAD

**Issue by FezVrasta** [Popmotion/popmotion#287]
Hi, I'm trying to animate a tooltip using react-pose, but I'm having some trobules with your API.

This is my tooltip code:

```jsx
<Manager>
  <Reference>{({ ref }) =>
    <button type="button" ref={ref}>
      Reference Box
    </button>
  }</Reference>
  {this.state.isOpen &&
    <Popper placement="right">{({ ref, style }) =>
      <div ref={ref} style={style}>
        Tooltip Box
      </div>
    }</Popper>
  }
</Manager>
```

Now, to add `PoseGroup` I should change it to be:

```jsx
const Animated = posed.div();

<Manager>
  <Reference>{({ ref }) =>
    <button type="button" ref={ref}>
      Reference Box
    </button>
  }</Reference>
  <PoseGroup>
    {this.state.isOpen &&
      <Popper placement="right">{({ ref, style }) =>
        <Animated ref={el => ref(findDOMNode(el))} style={style}>
          Tooltip Box
        </Animated>
      }</Popper>
    }
  </PoseGroup>
</Manager>
```

But this is not going to work because there is `Popper` between `PoseGroup` and `Animated`.

If there was a way to get the style of the animation from the `Animated` component and a way to pass it down to my `div` that would work:

```jsx
<PoseGroup>
  {this.state.isOpen &&
    <Animated>
      {animationStyle =>
        <Popper style={{ ...animationStyle }} />
      }
    </Animated>
  }
</PoseGroup>
```

An alternative would be:

```jsx
<Popper>{({ ref, style }) =>
  <PoseGroup>
    {this.state.isOPen &&
      <Animated key="popper" style={style} ref={el => ref(ReactDOM.findDOMNode(el))}>
        Tooltip box
      </Animated>
    }
  </PoseGroup>
</Popper>
```

But `Animated` is a stateless component and it doesn't provide a way to retrieve the `ref`...

What's the solution?

**Comment by FezVrasta** [comment]
Nevermind, I figured out I can use `innerRef` to get the `ref` of a `react-pose` element.

You may want to use the new `React.forwardRef` method to make the API cleaner maybe.

Now I have to figure out how to blend my own `transform` property with the one generated by Popmotion...

**Comment by Ghirigoro** [comment]
@FezVrasta Did you ever figure out a way to blend the transform generated by Popper with the Popmotion one? I'm working around it by applying the Popper data via props in the `applyAtStart` function. That seems pretty hacky so I'd love to see if you have a cleaner solution.
