### ISSUE TITLE
Manual flip with react-pose?

### ISSUE THREAD

**Issue by tume** [Popmotion/popmotion#288]
Not sure if I understood documentation correctly but seems that in react version you can't call measure/flip manually?

I was trying to animate component with changing width from one pose to another but in react-pose I would need to know the exact width when creating a posed component. Is it better just to try with non-react version or am I reading the docs somehow wrong?

**Comment by InventingWithMonster** [comment]
I'm looking into options to alleviate this problem in Pose but for now if you have your pose set to "flip" and then change `width` via `style` tag, that should work
