### ISSUE TITLE
Add staggering to PoseGroup

### ISSUE THREAD

**Issue by gleborgne** [Popmotion/popmotion#290]
It would be great to set a staggering delay when using PoseGroup with animateOnMount

**Comment by InventingWithMonster** [comment]
There could probably be a more formal way of doing it but you can already achieve this. With the caveat that you'd need to distinguish between mount and subsequent new items, you could do this:

```javascript
const Item = posed.li({
  enter: {
    x: 0,
    delay: ({ i }) => i * staggerDuration
  }
})

export default ({items}) => (
  <PoseGroup animateOnMount>
    {items.map((item, i) => <Item i={i} />)}
  </PoseGroup>
)
```

**Comment by InventingWithMonster** [comment]
(requires 1.2.0 or later)
