### ISSUE TITLE
Callback when Pose animation is finished?

### ISSUE THREAD

**Issue by Cryrivers** [Popmotion/popmotion#291]
Hi, I've been trying `react-pose`. This is a really great animation library! I would like to ask if there is any callback when a Pose animation is finished. Like `onRest` callback in `react-motion`.

Thank you!

**Comment by InventingWithMonster** [comment]
I’ll take a look. Pose animations return promises so this should be simple enough

**Comment by InventingWithMonster** [comment]
So simple it already exists: use the `onPoseComplete` prop. I'll add it to the docs
