### ISSUE TITLE
Pose: FLIP origin being overridden

### ISSUE THREAD

**Issue by InventingWithMonster** [Popmotion/popmotion#295]
In Pose, if an element is being FLIPped we explicitly set a transform origin, overriding anything that may have been set in the CSS. Instead we should:

1) Enable reading of originX and originY as separate properties in Stylefire
2) Only force set the transform origin if the FLIP requires 0 or 100%. If it's 50%, just leave the origin as the user's defined it.

**Comment by eballeste** [comment]
wondering if this is the same reason I can't apply transforms, always seems to reset to `none`
