### ISSUE TITLE
PoseGroup w/ staggerChildren

### ISSUE THREAD

**Issue by kamranayub** [Popmotion/popmotion#299]
Okay, I'm like 90% to what I want! With the new `posed(MyComponent)` API I can get my list items to animate on mount/exit.

But now I'd like to take advantage of the stagger feature but I can't see how it works with PoseGroup. Is there a way to use stagger/delay with a PoseGroup's children?

**Comment by InventingWithMonster** [comment]
What you could do is set (sorry on phone)

Enter: { delay:({}) =>  }

In the object provided to delay there is anything you set on the posed component
For example 

<Posed i={0} />

So if you had a way of figuring out what order you want things to stagger in your function would be

({i}) =>i * staggerDuration

Let me know if this helps

**Comment by kamranayub** [comment]
Oh! I'll try that! I do pass the order in to list items.

**Comment by scottdevito** [comment]
@srhise Second that. I'm having the same issue. They all animate at once.

**Comment by InventingWithMonster** [comment]
@scottdevito I'd need to take a look at a code example if you need more help. I'm closing this now as the `staggerChildren` won't have any effect in @srhise's example as theres only a single child. In that case you want `delayChildren`.
