### ISSUE TITLE
Props being passed down to DOM element

### ISSUE THREAD

**Issue by juhaelee** [Popmotion/popmotion#304]
It appears that invalid props are being passed to the DOM when creating React components used posed. For example:

> Warning: React does not recognize the `dragBounds` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dragbounds` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by sonaye** [comment]
Yes this is an annoying issue, makes debugging difficult. Here is a workaround I've been using:

```javascript
// when you have
<Foo bar="baz" />
// created with
const PosedFoo = posed.div({ /* .. */ });
const Foo = styled(PosedFoo)`/* .. */`;
// it will scream a warning at you (React does not recognize the `bar` prop ..)

// to block the `bar` prop completely
const Foo = styled(({ bar, ...props }) => <PosedFoo {...props} />)`/* .. */`;
// however this may end up breaking your styles or animations

// solution: use a data attribute as a prop `pose-something`
<Foo pose-bar="baz" /> // gotcha: value must be a string
// instead of `props => props.bar` use props => props['pose-bar']
// keep in mind it will still show `pose-bar` in the dom
```

**Comment by InventingWithMonster** [comment]
For my (or anyone who fancies writing a PR's) future reference

https://github.com/styled-components/styled-components/blob/master/src/utils/validAttr.js

**Comment by Leeds-eBooks** [comment]
This also happens in `react-native-pose`:

```js
const Posed = posed.View({
  loading: {
    x: ({orientation}) =>
      getCenterPosition(
        orientation === 'portrait' ? screenWidth : screenHeight
      )
  },
  loaded: {x: 0},
})

<Posed
  orientation={props.orientation}
  pose={props.loaded ? 'loaded' : 'loading'}
  style={styles.posed} />
```

The output becomes:

```js
<View
  collapsable={undefined}
  orientation="portrait"
  style={
    Object {
      ...
    }
  }
/>
```

Currently, passing the prop `orientation` down to the actual `View` doesn't cause any problems, but that's purely a happy accident, as someone could easily use a prop name that does have an effect on the underlying `View`.

**Comment by InventingWithMonster** [comment]
Exactly yeah - this is the double edged sword. I'm treading lightly here.

There is a `posed(Component)` API but it's not quite as simple to use. The one design goal of Pose is simplicity.

I think `transitionProps` or something like it may be a solution. I'll be looking into the way Styled Components handles it, which I know isn't bulletproof but it seems to do fairly good job.

**Comment by Leeds-eBooks** [comment]
Yeah, in writing my comment edit I realised that `posed(Component)` was a solution, and actually I've just implemented it and it works great. I think it's a good solution and as I say it might be worth putting it in the docs. I basically did:

```js
// Can't use a stateless functional component because
// createAnimatedComponent() won't accept one
class ControlledView extends Component {
  render() {
    return <View style={this.props.style}>{this.props.children}</View>
  }
}

const Posed = posed(ControlledView)({
  loading: {
    x: ({orientation}) =>
      getCenterPosition(
        orientation === 'portrait' ? screenWidth : screenHeight
      )
  },
  loaded: {x: 0},
})
```

**Comment by chadams** [comment]
how would this look using styled-components?
