### ISSUE TITLE
React pose setting a left position when there is already a right position

### ISSUE THREAD

**Issue by Calvein** [Popmotion/popmotion#306]
I'm trying to have some kind of Drawer with popmotion and I have a small issue regarding the exit state of an element inside a `<PoseGroup>`.
I made an example of pretty much what I currently have: https://codepen.io/Calvein/pen/aGdzgb, it's all good except that we're getting a scrollbar when the element is being exited since there is a left position being set when the element already has a right position.
I tried to set the left position in the exit pose and it didn't do anything:
```js
exit: {
  x: '100%',
  left: 'auto',
  transition: (props) => popmotion.tween({
    ...props,
    left: 'auto',
    duration: 2000,
  }),
},
```

Is there a way to remove it ?

**Comment by Calvein** [comment]
For anybody interested in the answer, I needed to add `!important` to my sidebar `position: fixed` because pose was adding a `position: absolute`

**Comment by InventingWithMonster** [comment]
Thanks for updating with a solution and sorry to leave this one hanging
