### ISSUE TITLE
react-pose prevents googlebot from rendering react app

### ISSUE THREAD

**Issue by hiredgun** [Popmotion/popmotion#312]
While I was testing my ract-app in [Fetch As Googl](https://www.google.com/webmasters/tools/googlebot-fetch) tool I discovered that googlebot is not able to render my page at all. After some research, I learn that googlebot is using chrome 41 for rendering websites and if it encounters not supported syntax without polyfill it won't render the page if it's a SPA without prerenderd content. I discovered that in my case the issue was caused by the react-pose lib.  After removing it googlebot renders my app properly. 

The problem with googlebot is that it doesn't show any rendering errors. After trying to add some polyfills and still failing to overcome the issue I started skimming react-poses code and discovered that it uses Proxies. According to Babel's docs, due to the limitations of ES5, Proxies cannot be transpiled or polyfilled so I guess that this is the reason why googlebot can't render my app properly.

**Comment by InventingWithMonster** [comment]
Ah thanks for pointing this out. What a fucking pain. I'm not sure there's a way around this other than replacing the Proxy with an explicit list of elements which would be a shame. I'll look into it.

**Comment by InventingWithMonster** [comment]
@hiredgun Fixed in `react-pose@1.6.4`
