### ISSUE TITLE
react-pose not working in IE 11

### ISSUE THREAD

**Issue by gleborgne** [Popmotion/popmotion#314]
Due to the use of Proxy API, react-pose does not work in IE

Looks like this line (at least) is using ES6 Proxy API :
https://github.com/Popmotion/popmotion/blob/f0888fb8b592a738841bb16d257210b21ce1db4f/packages/react-pose/src/posed.tsx#L59

I had to remove this lib from my app because of this :'(

**Comment by InventingWithMonster** [comment]
Sorry for the wasted time - I’m gonna add this more clearly in the docs.

**Comment by zebulonj** [comment]
Any chance that this could be changed? Is Proxy fundamental to the library? I just discovered Popmotion (and react-pose), love it,... and will likely not be able to use it because it’s not browser compatible.

**Comment by InventingWithMonster** [comment]
@zebulonj It's fundamental in that it allows us to offer in-built support for all HTML element types without bloating up the filesize.

As a compromise I've just released `1.6.2` which has support for div, li, button, span and a tags for people who absolutely must support IE11. It's worth checking your usage stats btw, at work we're getting 0.32% which is a hard no-support.

**Comment by VinSpee** [comment]
FYI IE11 accounts for about 4.5% of our users (TED.com). I think this compromise is plenty generous. Thanks!

**Comment by InventingWithMonster** [comment]
Oh wow. Thanks for the info. Also FYI I also found out that googlebot runs on Chrome 41 which means any client-rendered site breaks if they use any feature not supported by it. Which includes Proxy.

As a result I’ve removed Proxy from 1.6.2 in favour of the same list of elements used by styled-components. It’s added a bit of weight but I can take another pass at that at some point. You should be able to use any element now.

**Comment by Jayphen** [comment]
Re-opening this as it looks like IE11 support may have been broken again.

Specifically, I am getting `Object doesn't support property or method 'find'` when create a posed element that animates between `height: 0` and `height: 'auto'`

**Comment by Andarist** [comment]
You can use a simple polyfill 
```js
function find(predicate, arr) {
	for (let index = 0; index < arr.length; index++) {
		const element = arr[index]
		if (predicate(element)) {
			return element
		}
	}
}

if (typeof Array.prototype.find !== 'function') {
	// eslint-disable-next-line no-extend-native
	Array.prototype.find = function findPolyfill(predicate) {
		return find(predicate, this)
	}
}
```
which ofc is not 100% spec compliant, but should be "good enough". Not sure what's @InventingWithMonster policy on this matter, so not sure if it should be fixed here or at your end.

**Comment by InventingWithMonster** [comment]
This is covered in the [FAQs](https://popmotion.io/pose/api/faqs/)

But I'll dupe in the installation guide

**Comment by Jayphen** [comment]
Ah, I missed that. String.prototype.endsWith was more difficult to track down, since it would just crash Browserstack completely before I could see what the error was.
