### ISSUE TITLE
Animation isn't displayed when you switch between lists

### ISSUE THREAD

**Issue by JonatanGarciaClavo** [Popmotion/popmotion#315]
Hi! i was trying this react-pose lib to be able to do face in/out when user want to switch between two different type of list, let say user has a list of data but that list could be visualised in two ways, one as list and other as card view. To make it even simple i made a codesandox example with this idea behind https://codesandbox.io/s/mypkv19kx9 
As you could see if new items are added or introduced into items array then animation is displayed, meanwhile if items list doesn't change in number of elements when you switch between list 1 and list 2 no animation is done, any ideas why it is this happening?
At the beginning i though it was because i used same key to all items but even changing those still happening.
Maybe is me that i am missing something, if that case, please let me know what i am doing wrong.
Regards

**Comment by InventingWithMonster** [comment]
Hey man thanks for the code example. I’m currently on holiday but I’ll check it out when I’m back on weds

**Comment by InventingWithMonster** [comment]
I haven't got it working but I know that the first issue is your `PoseGroup` needs to be the direct parent of anything mounting/unmounting in order to trigger animations on it.

![image](https://user-images.githubusercontent.com/7850794/39615712-96073552-4f6f-11e8-9c5b-2e38cffe6d46.png)

**Comment by dannsam** [comment]
I know it's been awhile, but I've been looking at the issues I can potentially help with. @JonatanGarciaClavo  is https://codesandbox.io/s/31799qj645 doing what you were trying to achieve ?

**Comment by InventingWithMonster** [comment]
@dannsam Great example, thanks
