### ISSUE TITLE
React Native custom transitions not working

### ISSUE THREAD

**Issue by Rehubbard** [Popmotion/popmotion#316]
I am using Pose for animations in my React Native app. I cannot seem to get a custom transition working. I am following the simple opacity example in the docs (https://popmotion.io/pose/learn/native-custom-transitions/) exactly and it's not working. It appears that the function I give to the transition property never even gets called.

Here's some of my code:

```
const slowTween = ({ value, toValue }) => Animated.timing(value, {
      toValue: toValue,
      duration: 3000,
      useNativeDriver: true
    })

    const config = {
      visible: {
        transition: slowTween,
        opacity: 1
      },
      hidden: { opacity: 0 }
    }

    const SearchInput = posed.View(config)
```

**Comment by InventingWithMonster** [comment]
Hey man. Does the transition work if you *dont* define a custom transition?

**Comment by Rehubbard** [comment]
Thanks for the response 👍 

No, the default opacity transition doesn't seem to work either. When I remove the custom transition, the element just appears instantly.

**Comment by dalbinaco** [comment]
I get the same problem with react-pose. I'm using Gatsby with `gatsby-plugin-react-next` to use React 16+.

**Comment by InventingWithMonster** [comment]
@dalbinaco Can you confirm you're passing `useNativeDriver` to the animation? ie

```
const slowTween = ({ value, toValue, useNativeDriver }) => Animated.timing(value, {
      toValue,
      duration: 3000,
      useNativeDriver    })
```

Also do you have any `passive` values?

**Comment by InventingWithMonster** [comment]
Released

**Comment by dalbinaco** [comment]
@InventingWithMonster I was not using `useNativeDriver` neither any `passive` values. I just defined 2 poses and that's it.
