### ISSUE TITLE
Reorder Pose children

### ISSUE THREAD

**Issue by InventingWithMonster** [Popmotion/popmotion#319]
As demonstrated: https://alex.holachek.com/react-animation-comparison/?selectedKind=Animation%20Examples&selectedStory=Popmotion%20Pose&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

When `PoseGroup` children are reordered, they should reorder themselves in the parent poser.

Once Popmotion Pose is migrated to `pose-core`, we should add a `setChildOrder` method that can rearrange the children and have `PoseGroup` call that.

**Comment by Andarist** [comment]
Could you explain a little bit more about the issue? I might work on this, but the description is vague at the moment (for me - not knowing the internals).
