### ISSUE TITLE
Timeline for Pose

### ISSUE THREAD

**Issue by tclain** [Popmotion/popmotion#322]
Is it possible to use a timeline based animation, e.g a pose that is a sequence of others poses ?
For instance being able to integrate https://popmotion.io/api/timeline/.
That would be really awesome.

BTW, thanks for your work, the lib is really stunning.

**Comment by InventingWithMonster** [comment]
Thanks man! At the moment timeline is basically useless with Pose imo. But recently I added the label prop, and I reckon there might be something useful in naming posers with labels and then using timelines track prop to reference them like “label.prop” but that won’t be for a couple
Months yet

**Comment by tclain** [comment]
ok. I got it.
In this case, is there a recommanded way to use the timeline api from popmotion with react component ? For complex animations, it could be useful to be able to chain transitions.

Thanks for your answers

**Comment by skvithalani** [comment]
@InventingWithMonster 
We are having the same requirement of chaining transitions with react and pose. Is there a recommended way to use timeline api to fulfil this requirement?
