### ISSUE TITLE
Transition fails unless I specify transition on subsequent animations

### ISSUE THREAD

**Issue by jorjordandan** [Popmotion/popmotion#323]
**Describe the bug**
Following the react-native pose tutorial - at the section:

```
const config = {
  visible: {
    opacity: 1,
    y: 0,
    transition: ({ value, toValue, key }) => {
      switch(key) {
        case 'opacity':
          return Animated.timing(value, { toValue })
        case 'y':
          return Animated.spring(value, { toValue })
      }
    }
  },
  hidden: { opacity: 0, y: -50 }
}
```
attempting as shown in the tutorial, throws the following error: 

`Attempting to run JS driven animation on animated node that has been moved to "native" earlier by starting an animation with `useNativeDriver: true`]`

adding the transition function to the "hidden" object prevents the error and everything works as it should.

**Expected behavior**
Either the tutorial to identify this needed step, or the error to not throw :)

**Comment by InventingWithMonster** [comment]
The transition function receives useNativeDriver which you need to pass through to the animation. That should fix this error. I’ll update the docs - thanks for pointing it out!

**Comment by jorjordandan** [comment]
No worries! I'm still actually getting the same error even if I pass in useNativeDriver, though.

**Comment by InventingWithMonster** [comment]
C

**Comment by InventingWithMonster** [comment]
I've got something to release possibly tomorrow that fixes an issue to do with this, have you attached any `passive` values?

**Comment by jorjordandan** [comment]
Just to clarify - the visible animation always works, it's the hidden one that fails. I'm sorry for not being more clear earlier. I don't know the implementation details here, but as far as I can tell once you set useNativeDriver to true, you can't use javascript to animate that node.

**Comment by jorjordandan** [comment]
A repro if it helps:

https://github.com/jorjordandan/pose-animation-repro

**Comment by InventingWithMonster** [comment]
I noticed in the repo you're not passing `useNativeDriver` to the animations themselves. Should be:

```
const tweenBoth = ({ value, toValue, useNativeDriver, key }) => {
  switch(key) {
    case 'opacity':
      return Animated.timing(value, { toValue, useNativeDriver })
    case 'y':
      return Animated.spring(value, { toValue, useNativeDriver })
  }
}
```

Does this fix it? If not, I've replicated your error by leaving `useNativeDriver` out, and the release tomorrow will fix.

**Comment by InventingWithMonster** [comment]
Thanks man! I'm gonna try and make it easier for people to jump in soon with better messaging/instructions. As with everything its finding them time!
