### ISSUE TITLE
Does not find `pose` property with styled-components in TypeScript

### ISSUE THREAD

**Issue by muukii** [Popmotion/popmotion#326]
**Describe the bug**
The case of using TypeScript.
A Component does not find `pose` property with styled-components.

**To Reproduce**

```typescript
const AnimateContainer = posed.div({
  visible: {
    translateY: '0px',
    transition: (props: any) => tween({ ...props, duration: 300 }),
  },
  hidden: {
    translateY: '64px',
    transition: (props: any) => tween({ ...props, duration: 300 }),
  },
})

const BottomStickyContainer = styled(AnimateContainer)`
  position: fixed;
  left: 0;
  right: 0;
  bottom: 0;
`
```

```typescript
<BottomStickyContainer
   pose={this.state.isHiddenEntryBar ? 'hidden' : 'visible'}
>
   <div>...</div>
 </BottomStickyContainer>
```

**Expected behavior**
It can be found the `pose` property.

**Screenshots**
<img width="618" alt="screen shot 2018-05-09 at 01 26 55" src="https://user-images.githubusercontent.com/1888355/39770136-2aca34e8-5329-11e8-98cc-963749855ae7.png">
<img width="644" alt="screen shot 2018-05-09 at 01 35 08" src="https://user-images.githubusercontent.com/1888355/39770161-3d586774-5329-11e8-993b-1859f9978494.png">

**Comment by serranoarevalo** [comment]
@muukii  the same is happening to me, any fix for this?

**Comment by serranoarevalo** [comment]
Holly 💩I just made it work, I'm sure is not correct but it works.

````js

import { PoseElementProps } from "react-pose/lib/components/PoseElement.types";

const PosedHeader = posed.div({
  closed: {
    height: 0,
    opacity: 0
  },
  open: {
    height: "78%",
    opacity: 1
  }
});

const StyledHeader = styled<{ pose: PoseElementProps }, any>(PosedHeader)`
  background: linear-gradient(rgba(0, 153, 196, 0.5), rgba(0, 153, 196, 0.4)),
    url(${bg});
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 78%;
`;
````

And later on

````jsx
<StyledHeader pose={isOpen? "open" : "closed"}>
        <Logo />
</StyledHeader>
````

**Comment by jasondibenedetto** [comment]
Any update on this? I have been having some trouble getting `react-pose`, `styled-components` and `typescript` to play nice with each other.
