### ISSUE TITLE
distribute UMDs

### ISSUE THREAD

**Issue by VinSpee** [Popmotion/popmotion#329]
**Is your feature request related to a problem? Please describe.**
I'd like to use posed/react-pose in more environments. In order to do that, i need to consume it as a UMD.

**Describe the solution you'd like**
add a UMD to typescript's output (https://www.typescriptlang.org/docs/handbook/modules.html#code-generation-for-modules)

looks like minimal maintenance and consequence, but would increase distributability.

**Comment by InventingWithMonster** [comment]
I was literally just looking into this yesterday! It’s the next thing on my list so hopefully sometime by the end of the weekend

**Comment by InventingWithMonster** [comment]
@VinSpee I'm just having a play with Rollup on the `framesync` package. What I don't understand is how people consume UMD modules. I'm looking at Redux and Styled Components, both of which distribute UMDs, neither of which reference these in their package.jsons. Do projects that require UMDs do something special to resolve these deps?

**Comment by VinSpee** [comment]
UMDs are typically referenced in the `browser` field. 

https://github.com/defunctzombie/package-browser-field-spec

An example using `bili`:
https://github.com/VinSpee/react-gcal-events-list/blob/master/package.json#L10

I looked at `react-redux`, they don’t do anything aside from including the entire `dist` directory in the `files` array, which is enough to allow consumers to reference them specifically.

**Comment by InventingWithMonster** [comment]
Cool man thanks. As I understand it, setting `browser` will override `main`? So I've just added `dist` to files like you said.

Could you give this PR the once over? If it looks cool I'll start rolling this out to our other packages and let you know when I've published Pose https://github.com/Popmotion/framesync/pull/3/files

**Comment by InventingWithMonster** [comment]
Hey man

Sorry for the delay, had various things get in the way. Just published `popmotion-pose@2.0.1` and `react-pose@2.0.0`, both of which come with UMD bundles. Let me know how they work out!

**Comment by VinSpee** [comment]
Awesome! I’ll have a chance to give it a try next week.
