### ISSUE TITLE
Playground broken?

### ISSUE THREAD

**Issue by mattvague** [Popmotion/popmotion#335]
**Describe the bug**

Got a bunch of errors trying to run the storybook:

```
Can't resolve '../../packages/react-pose/lib'
Can't resolve '../../packages/popmotion-pose/lib'
Can't resolve '../../packages/popmotion/lib'
...
```

This seems to be because `lib` should actually be `src` (if I'm not mistaken). I only had a few mins to play around but just replacing lib with src didn't seem to fix it.

**To Reproduce**
1. Clone repo
2. Run `npm run playground` 
3. See errors

**Expected behavior**
Storybook should run

**Screenshots**

<img width="912" alt="screen shot 2018-05-18 at 10 18 35 am" src="https://user-images.githubusercontent.com/64985/40239736-e881af36-5a84-11e8-9221-dc418cc7842c.png">

**Desktop (please complete the following information):**
 - Mac OSX

**Comment by InventingWithMonster** [comment]
Ah that isn't really for public consumption hence its scrappy state! To get it working you need to do `npm install` in `/`, `/packages/react-pose`, `/packages/popmotion-pose`, `/packages/popmotion` and `npm run build` in each of those packages too.

**Comment by mattvague** [comment]
Ah! Gotcha. If I were to submit a PR with a task to do this how would you feel?

**Comment by InventingWithMonster** [comment]
Sorry not sure exactly what you mean. Anyone who wants to use the
playground currently has to do this locally - are you suggesting opening a
PR with a single script that automates the process?

**Comment by mattvague** [comment]
@InventingWithMonster Ah sorry, yeah I meant a script that does whatever needs to be done to get the storybook building.

**Comment by InventingWithMonster** [comment]
Oh then yeah that'd be awesome, thanks!
