### ISSUE TITLE
Pose: Move popmotion to peerDependencies

### ISSUE THREAD

**Issue by sonaye** [Popmotion/popmotion#337]
I noticed that `popmotion-pose` is listed under `dependencies` and not `peerDependencies`, well my linter actually complained about it. Is there any reasoning behind that?

Would be happy to submit a PR, thanks for the great work.

**Comment by InventingWithMonster** [comment]
Are you importing the transition compositors from Popmotion-pose? I might
come up with a separate solution for that

**Comment by sonaye** [comment]
I'm not, functional-wise all is good.

Right now running `npm install popmotion-pose` installs `popmotion` as well in the background. I'm proposing moving it to `peerDependencies` to reflect that better and to avoid dev tools thinking that `popmotion` is missing, because it was not explicitly installed. The new way to install would be `npm install popmotion popmotion-pose`.

**Comment by InventingWithMonster** [comment]
Ah sorry so you’re importing animations from popmotion? In which case yeah
you’re right this would be the way to do it and PR would be really helpful
thanks
