### ISSUE TITLE
Pose: TypeScript error with `PoseGroup` and single child

### ISSUE THREAD

**Issue by InventingWithMonster** [Popmotion/popmotion#341]
Ensure `PoseGroup` expects a single child as well as an array

**Comment by klaasman** [comment]
are you able to create a codesandbox with this error?

**Comment by DevanB** [comment]
@klaasman I believe I can. I didn’t know CodeSandbox supported TypeScript!

**Comment by klaasman** [comment]
well, me neither actually, but look at this: https://codesandbox.io/s/react-ts :-)

**Comment by DevanB** [comment]
Okay! Created a basic example that shows my error: https://codesandbox.io/s/qz9m6y68w

Thanks for any help you can provide!
