### ISSUE TITLE
react native pose Draggable "Hello, world" isn't dragging

### ISSUE THREAD

**Issue by spruce-bruce** [Popmotion/popmotion#350]
**Describe the bug**
I'm checking out the library to use in an app I'm building, and I'm trying a simple draggable example. I think I'm probably getting something basic wrong, but I can get non-draggable animations to work just fine using the posed component below.

**To Reproduce**
```
const config = {
  draggable:true
};

class Inner extends Component {
  render() {
    return (
      <View style={{backgroundColor: 'red', height: 100, width: 100}}>
        <Text>Some Test</Text>
      </View>
    );
  }
}

const PosedInner = posed(Inner)(config);
class Outer extends Component {
  state = { isVisible: false }

  render() {
    return (
      <View style={{width: 200, height: 300, backgroundColor: 'green'}}>
        <PosedInner />
      </View>
    );
  }
}

export default Outer;
```

**Expected behavior**
I'm expecting my `Inner` component to be draggable

**Desktop (please complete the following information):**
 - OS: os x 10.13.4

**Smartphone (please complete the following information):**
 - Device: iPhone6 simulator
 - OS: 11.3

**Comment by spruce-bruce** [comment]
Well I'm giving it another shot, and I can make the "hello world" work when I use `posed.View` instead of my custom component from above. I'm going to leave this open because I'm still curious about why my example code didn't work.

**Comment by InventingWithMonster** [comment]
Hey man I’ve had a look through the source code and if you console log out this.props there should be some extra props that you need to pass through to your first View child. I’ll have to update the docs

**Comment by spruce-bruce** [comment]
Ah - ok - thanks for looking into it!
