### ISSUE TITLE
FLIP does not transition from position 'relative' to 'fixed'

### ISSUE THREAD

**Issue by janbaykara** [Popmotion/popmotion#353]
**Describe the bug**
Pose doesn't seem to like transitioning the `position` attribute. It remains `relative` even when a new pose is set with a `fixed` position.

As a side-effect, it also doesn't FLIP between 100px @ relative and 100% @ fixed.

**To Reproduce**
https://codesandbox.io/s/8zj05687z2

Click the second button, 'Pose'.

**Expected behavior**
I want it to switch instantly, so that FLIP can recalculate the element's position and do it's magic.

It should go fullscreen (as (3)Manual Pose does in the above codesandbox). Instead it remains inline.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 66.0.3359.181

**Comment by Andarist** [comment]
I think this is already partially resolved by [https://github.com/Popmotion/popmotion/commit/d0713fad41a42c12b05286a23784024ab2658f1c](this commit). But because your example uses resolver functions for position this case is still bugged - I've prepared a PR with the fix [here](https://github.com/Popmotion/popmotion/pull/470).

**Comment by Andarist** [comment]
I've updated it to the latest pose and that's how I've discovered this other bug preventing it from working as expected.

**Comment by InventingWithMonster** [comment]
@janbaykara Here's a version with updated dependencies and both manual Pose and React Pose have been rewritten to how I'd do it https://codesandbox.io/s/1r9z1jw7j3

**Comment by Andarist** [comment]
@janbaykara the other fix just got merged & released, so you should be able use resolver functions for position
