### ISSUE TITLE
Examples on website don't work

### ISSUE THREAD

**Issue by CGamesPlay** [Popmotion/popmotion#354]
**Describe the bug**
From [get started](https://popmotion.io/pose/learn/popmotion-get-started/), the [React Pose Playground](https://codepen.io/popmotion/pen/mxmrPZ?editors=0010) doesn't animate, only displays a square.

From [the posed HOC](https://popmotion.io/pose/api/posed/), the [first example](https://codepen.io/jesstelford/pen/MVQepE) doesn't show anything except a square, and has a console error: `TypeError: Cannot read property 'createContext' of undefined`.

**Desktop (please complete the following information):**
 - OS: macOS 10.12.6 (16G1314)
 - Browser Chrome Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by superkarolis** [comment]
Hi, the example seems to be incomplete. I got the code working in this pen - https://codepen.io/karolis/pen/KewoVr?editors=0010 . I could contribute a PR but not sure if it would be problematic that new pen is made from my personal account rather than a Popmotion account like in the docs.

**Comment by CGamesPlay** [comment]
Your assessment for the first one seems right (and your pen works for me).

The TypeError was on the other one. I was able to rearrange the dependencies to put `react-pose.js` after React and that appears to have fixed it.

**Comment by InventingWithMonster** [comment]
Yeah that's the bug (load order). I don't have control over that specific example and need to replace it in the docs!
