### ISSUE TITLE
[Pose] Missing html part

### ISSUE THREAD

**Issue by aolko** [Popmotion/popmotion#355]
Pose docs are missing html part, it only has react dom as of right now
![image](https://user-images.githubusercontent.com/581458/40770453-5e31e1e0-64c3-11e8-91ad-e6c53661b008.png)
![image](https://user-images.githubusercontent.com/581458/40770482-73d55edc-64c3-11e8-8530-6d4f2c4b5939.png)

**Comment by InventingWithMonster** [comment]
Not gonna happen without a way to dedupe documentation
