### ISSUE TITLE
React Pose: Can't start a transition with {x: 0}

### ISSUE THREAD

**Issue by bjornlll** [Popmotion/popmotion#358]
**Describe the bug**
When the initial render happens in a pose with `{x: 0}` as it's definition, the pose won't transition on the `x` property. If you add in additional properties, e.g. `opacity`, that property works well. It still won't transition on the `x`, though.[

My guess: When determining which transitions to do it doesn't see the `x` since it has been defined using a `0`, which is a falsey value. E.g. `if (pose.x) { ... }`.

**To Reproduce**
```javascript
const Sidebar = poser.aside({
  closed: { x: '350px' },
  open: { x: 0 },
  initialPose: 'closed',
});
```

Put the code above into a component. Make sure the component does its first render in the `closed` state. Transition between open an closed (e.g. using `setInterval`) - this works. Do a second experiment with the first render in the `open state`, then attempt transitioning. This doesn't work.

**Expected behavior**
Being able to start from both state `open` and `closed` in the example above. 

**Link to CodePen or similar**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version Latest stable

**Additional context**

**Comment by InventingWithMonster** [comment]
What happens if you write 350 instead of ‘350px’? I suspect this is the current lack of support of value types

**Comment by bjornlll** [comment]
Today, when I try, I can't recreate it. This simple experiment below always works no matter how we reconfigure it. Perhaps I had my component in a place where no-unit CSS values did not work?

```javascript
import React from "react";
import { render } from "react-dom";
import poser from "react-pose";

const Box = poser.div({
  closed: { x: "100px" },
  open: { x: 0 },
  initialPose: "open"
});

const styles = { width: "100px", height: "100px", background: "yellow" };

class App extends React.Component {
  timer = null;

  state = { seconds: 0 };
  // state = { seconds: 1 };

  componentDidMount() {
    this.timer = setInterval(
      () => this.setState(({ seconds }) => ({ seconds: seconds + 1 })),
      1000
    );
  }

  componentWillUnmount() {
    this.timer = clearInterval(this.timer);
  }

  render() {
    return (
      <div>
        <Box style={styles} pose={this.state.seconds % 2 ? "closed" : "open"} />
        {this.state.seconds}
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));
```

[![Edit 4woqv6jq54](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4woqv6jq54)

**Comment by bjornlll** [comment]
Finally managed to recreate it.

## This example functions as expected
The box animates from `open` to `closed` on mount.
```
import React from "react";
import { render } from "react-dom";
import poser from "react-pose";

const Box = poser.div({
  closed: { x: "100px" },
  open: { x: "0px" }
});

const styles = { width: "100px", height: "100px", background: "tomato" };

class App extends React.Component {
  render() {
    return (
      <div>
        <Box style={styles} initialPose="open" pose="closed" />
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));
```

## This example does _not_ work as expected
Nothing happens. The difference is the `"0px"`, in the example above, and `"0"`, in this example. Integers work, 0's included. 
```
import React from "react";
import { render } from "react-dom";
import poser from "react-pose";

const Box = poser.div({
  closed: { x: "100px" },
  open: { x: "0" }
});

const styles = { width: "100px", height: "100px", background: "tomato" };

class App extends React.Component {
  render() {
    return (
      <div>
        <Box style={styles} initialPose="open" pose="closed" />
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));
```
[![Edit React Pose: On mount animation](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ovo11kq32y)

**Comment by Andarist** [comment]
This is fixed in the latest `react-pose`, so you might want to close this issue.
