### ISSUE TITLE
FLIP custom transition

### ISSUE THREAD

**Issue by raelmiu** [Popmotion/popmotion#359]
I'm animating new items added to a list. I'm trying to give them a background that pops and then fades. For some reason I can't specify transition time though. Instead the whole animation lags to the point of fail.

My animation:
```
const Item = posed.li({
  preEnter: {
    backgroundColor: '#1789e5'
  },
  enter: {
    backgroundColor: '#ffffff',
    transition: { duration: 600 }
  }
});
```

I'm running this in Chrome on a MacBook Pro.

**Comment by InventingWithMonster** [comment]
When you say it "lags to the point of fail" do you have a live example I can take a look at?
