### ISSUE TITLE
React Pose: "enter"-support for posed.[div|circle|...]()

### ISSUE THREAD

**Issue by bjornlll** [Popmotion/popmotion#361]
**Is your feature request related to a problem? Please describe.**
Triggering animations when a single component is mounted (i.e. letting constant UI items slide onto the screen instead of immediately appearing).

**Describe the solution you'd like**
Allowing for defining `enter` poses for a posed-wrapped component.

**Describe alternatives you've considered**
Using component `state` to trigger a single transition in React's lifecycle hooks on render.

**Additional context**
If this is already easily made possible: Is there any example anywhere to look at?

Thanks!

**Comment by bjornlll** [comment]
Thanks man! That worked perfectly

👇 Here, for anyone else that is trying to animate elements as they mount.
```javascript
import React from "react";
import { render } from "react-dom";
import poser from "react-pose";

const Box = poser.div({
  closed: { x: "100px" },
  open: { x: "0px" }
});

const styles = { width: "100px", height: "100px", background: "tomato" };

class App extends React.Component {
  render() {
    return (
      <div>
        <Box style={styles} initialPose="open" pose="closed" />
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));
```
[![Edit React Pose: On mount animation](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ovo11kq32y)

**Comment by bjornlll** [comment]
Interestingly, I managed to recreate the bug in https://github.com/Popmotion/popmotion/issues/358 whilst testing this out. Will update that thread. Thanks for a great product!

**Comment by grundmanise** [comment]
@InventingWithMonster, strangely enough, this approach does not work when setting `initialPose` in config itself. Is it a bug then?

**Comment by InventingWithMonster** [comment]
@grundmanise No this is a difference in the React and vanilla APIs.

I'm going to split the two out in the docs more to make the difference clearer as I see how this is very confusing.

What React Pose is actually doing if you have `initialPose` explicitly set as a prop is passing that through to the underlying poser, and then on mount immediately calling `poser.set(pose)`. Which in vanilla is something you have the ability to do manually.
