### ISSUE TITLE
React Pose: Performance improvement in PoseGroup

### ISSUE THREAD

**Issue by InventingWithMonster** [Popmotion/popmotion#363]
Demo: https://codepen.io/anon/pen/mKEzVp?editors=0010

Currently, when `PoseGroup` triggers leave animations, it removes the animating element from the DOM once that animation is finished.

The problem is that when lots of other animations are still animating, this React reconciliation stutters.

This ticket proposes that we wait until all known animations finish before removing children DOM nodes, which we will do in one go.

A serious concern is what happens if a second state change occurs while the current DOM elements are still being animated? It might become difficult to know which to remove.

There's a weird side effect where after this stuttering (yellow), activity seems to stop before picking up again:

![image](https://user-images.githubusercontent.com/7850794/41044725-cf0b3a26-699e-11e8-9a9b-f2b69092a321.png)

Visually this looks like a pause in the animation. This performance improvement might fix this alone, but if it doesn't we'll need to investigate this also

**Comment by lighe** [comment]
Any updates on this? It's causing issues when implementing filtering on larger lists. Would love to be able to use it!

**Comment by InventingWithMonster** [comment]
Not yet. I will probably be around a month before I get to this issue - my last day at work is next Tuesday and I'll have a few months to concentrate on Pose. But it might be a couple weeks until I get to this issue.

**Comment by mjlai3** [comment]
Having this stuttering issue too with just 5 child components, can't wait for the fix!

**Comment by InventingWithMonster** [comment]
Published in `react-pose@3.3.4`
