### ISSUE TITLE
Add continuous integration using eg. Travis CI

### ISSUE THREAD

**Issue by voxpelli** [Popmotion/popmotion#365]
As a developer, when I submit a PR like #364 I want to get some early feedback so that I can know whether I've embarrassed myself or not.

Early feedback is especially important for developers with little experience and/or developers new to open source, as being told that their code is wrong because it didn't comply with linting X or test setup Y can be pretty disheartening.

The solution would be to set up a CI job that at least lints the coding style, but which maybe also lints/checks/tests other things – by eg. running the unit tests or even validate that [all dependencies has been included](https://www.npmjs.com/package/dependency-check) and that ones node version range [is supported by all ones dependencies](https://www.npmjs.com/package/installed-check). (Sorry for pushing my own modules here, I do it because I find them useful)

**Comment by InventingWithMonster** [comment]
Added CircleCI
