### ISSUE TITLE
Popmotion uses a lot of memory/cpu usage

### ISSUE THREAD

**Issue by Levelleor** [Popmotion/popmotion#366]
I created a little project, there is simply a class that defines an element and then "throws" it through the screen. 

So basically something like this: 

```
class Ball {
  constructor() {
    this.element = document.createElement("div");
    this.throwme.bind(this)();
  } 
  ...
}
```

Then there is this method: 

```
let blockX = physics({
  velocity: 0,
  acceleration: -100,
  restSpeed: false
}).start((v) => {
  ballX.update(v);
  if (this.element.getBoundingClientRect().left >= WIDTH) {document.querySelector(".game>div").removeChild(this.element); $(this.element).off("mousedown touchstart", unbind); resolve('escaped');}
});

let blockY = physics({
  velocity: 0,
  acceleration: 5050,
  friction: 0.1,
  restSpeed: false
}).start((v) => {
  ballY.update(v);
  if (this.element.getBoundingClientRect().top >= HEIGHT) {document.querySelector(".game>div").removeChild(this.element); $(this.element).off("mousedown touchstart", unbind); resolve('escaped');}
});
```

So I basically delete everything connected to object(listeners, dom elements) and class(instances) so garbage collector could remove that sooner. After Promise resolves there is `delete instance;` happens and the whole class instance should be forgotten. It looks like I managed to clear up a lot of memory I could within my code so it survives longer but Popmotion seems to create own instances that remain active even after class instance gets removed. See image: 
![image](https://user-images.githubusercontent.com/11915185/41115020-2defa404-6a54-11e8-935e-d1399a1dcb0d.png)
Pretty much all the memory and CPU usage is taken by Popmotion: 
![image](https://user-images.githubusercontent.com/11915185/41116156-81047108-6a57-11e8-88a3-836c1de7c387.png)

Is there any way to make this work? I'm afraid I will need to create my own script instead to be able to control the object allocation myself...

**Comment by zaaack** [comment]
Try cache `document.querySelector(".game>div")`,`$(this.element)` via a variable, these operations are too expensive for each animation frame.

**Comment by zaaack** [comment]
> So I basically delete everything connected to object(listeners, dom elements) and class(instances) so garbage collector could remove that sooner

This is a bad practice for game developing because frequent GC would cause frame drop. You should allocate the memory that you might use at the beginning and hold it as long as possible via reusing them.

**Comment by Levelleor** [comment]
Well, the thing is I don't need much memory for that project. There is from 1 to 3 objects that are flying on the screen simultaneously and being removed after leaving the screen. So I guess that shouldn't be a problem for gc to remove them every single time. But even tho I clear all the mentions there is still something left after every loop, which is a problem. What possibly could stack that much in such a small game? I have no idea, and that doesn't really matter anymore, that project survives around 1000 iterations without lag so basically, no one will ever notice it anyway. But I don't feel like using this library in future because of these leaks, or my weak understanding of it.

**Comment by zaaack** [comment]
@Levelleor Not just GC, dom operations are also very expensive. Remove dom or insert dom will cause the browser to reflow & repaint, that's why only css3 properties like transform/opacity are suggested to make animations, because they won't cause reflow. If the performance still matters, you should forget about dom and use canvas/webgl.

**Comment by Levelleor** [comment]
I see. My task looked pretty simple so I just went straight the most obvious/easy way. Anyway, I guess that was my introduction in this type of stuff, next time I have a basic understanding of wha
