### ISSUE TITLE
Issues using react-native-pose with react-native-web

### ISSUE THREAD

**Issue by chrisdrackett** [Popmotion/popmotion#367]
**Describe the bug**

**To Reproduce**
- Install react-native-web
- Install react-native-pose
- Include `react-native-pose` in a file in the project
- Run project

(I'm using create-react-app)

**Expected behavior**
I'm able to use react-native-pose with react-native-web.

**Link to CodePen or similar**

https://github.com/MultiscaleHN/react-native-web-pose-test

**Desktop (please complete the following information):**
- MacOS
- Safari 11.1.1

**Additional context**

Seems to be related to how this module is compiled. Via web searches I've found similar issues:

https://github.com/react-native-web-community/react-native-web-linear-gradient/issues/1#issuecomment-354660128

**Comment by chrisdrackett** [comment]
FYI I was able to get this using in CRA using rewire, not sure if its possible to make this work without rewire, but if anyone else is trying to do this, a demo solution that works on web and native is available here: https://github.com/MultiscaleHN/react-native-web-pose-test/tree/rewire

**Comment by InventingWithMonster** [comment]
Thanks for linking to that. I'm going to close this for now as we don't actively support React Native Web but I might take another look in the near future. I know that someone at Oculus got it working with their internal React VR framework fairly painlessly so I sort of feel it should just work!

**Comment by nirpeer** [comment]
Hi @InventingWithMonster, are you planning to support react-native-web in the future?
We really like this package but our functional components aren't working with it. (works on our react-native app).

We get `Uncaught Invariant Violation: `createAnimatedComponent` does not support stateless functional components; use a class component instead.`

**Comment by OKNoah** [comment]
> Hi @InventingWithMonster, are you planning to support react-native-web in the future?
> We really like this package but our functional components aren't working with it. (works on our react-native app).
> 
> We get: `Uncaught Invariant Violation: 'createAnimatedComponent' does not support stateless functional components; use a class component instead.`

I believe the just a short-coming of RN or RNW right now. `createAnimatedComponent`, I think, is an internal RN thing, no part of Pop*.
