### ISSUE TITLE
React Pose: HOC parameter order is inverted - won't compose.

### ISSUE THREAD

**Issue by Izhaki** [Popmotion/popmotion#371]
This is likely to cause a stir, but...

At the moment, using the HOC syntax for Pose :

    const PosedComponent = posed(MyComponent)(poseProps)

# What's more common?

This is somewhat the opposite from all the other libraries I've came across. Here, for example, is [SizeMe](https://github.com/ctrlplusb/react-sizeme) in use:

```javascript
const Sized = sizeMe({ monitorHeight: true });

const Chart = props => {
    ....
}

export default Sized(Chart);
```

Point is, that:

    f(x)(y)

suggests that `y` is more likely to change than `x`. So you do:

    const g = f(x)

for the more 'stable' stuff. Then:

    const z = g(y) 

for the less 'stable' stuff.

With functional programming you also often see this form:

    const f = x => y => { ... }
    R.map(f(x), list);

So the form:

    const PosedComponent = posed(MyComponent)(poseProps)

Suggests that you may wish to apply different `poseProps` to the same component. Is this a valid use case?

My instinct tells me that the use case of applying the same poseProps to different components will be more common. So the API should change to:

    const PosedComponent = posed(poseProps)(MyComponent)

(WhooHoo, breaking change!)

# Compose

Perhaps a better argument is that in the current form, `posed` cannot be composed as HOCs typically do ([source](https://github.com/mui-org/material-ui/blob/110b6cd40bf8fb9a17898f702259a177f44be2e6/docs/src/pages/layout/hidden/BreakpointDown.js)):

```javascript
export default compose(
  withStyles(styles),
  withWidth(),
)(BreakpointDown);
```

You need the component to be the last parameter of a curried function so you can 'pipe' it in `compose` or `pipe` (see [R.compose](https://ramdajs.com/docs/#compose) and [R.pipe](https://ramdajs.com/docs/#pipe) respectively)

**Comment by InventingWithMonster** [comment]
Hi there

The primary design goal for the Pose API is simplicity.

As a fan of FP and composition, I agree that what you propose is "nicer" in that respect. But, I think more people will understand at a glance `posed.div(config)` than `posed(config)('div')`.

There could be an explanation that "this makes it easier to compose" but anything that comes with caveats or explanations is to be avoided in Pose.

It would be trivial to write your own version of `posed` (that could be republished for other fans of composability! `com-posed` - thank me later...) that just wraps ours:

```javascript
import posed from 'react-pose';

export default config => Component => posed(Component)(config)
```
