### ISSUE TITLE
8.2.4 have breaking change for using subset like docs said

### ISSUE THREAD

**Issue by morlay** [Popmotion/popmotion#372]
There is a lib dir to wrap subset
![image](https://user-images.githubusercontent.com/1667873/41198082-d6700cae-6ca2-11e8-86ed-a23560691d3c.png)
and we can't using a small subset of the library like docs said 
![image](https://user-images.githubusercontent.com/1667873/41198074-9ac45318-6ca2-11e8-8b96-ab87dd6bab4d.png)

**Comment by morlay** [comment]
Still broken in 8.2.5

**Comment by InventingWithMonster** [comment]
Yep, sorry I fucked up, see: https://github.com/Popmotion/popmotion/issues/385
