### ISSUE TITLE
react-pose: Deterministically measure posed element before animations

### ISSUE THREAD

**Issue by strax** [Popmotion/popmotion#373]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a non-FLIP height animation that relies on the posed contents' bounding box.
The element has two poses: collapsed and expanded. When the initial pose is collapsed, the contents' dimensions need to be measured before the initial pose is applied to be able to use the recorded height when transitioning from the collapsed pose into the expanded one. Right now I have a workaround where I call `dimensions.measure()` when the initial animation target value is determined:
```
posed.div({
  collapsed: {
    height: ({ dimensions }: ContentAnimationProps) => {
      console.log(dimensions.measure())
      return 0
    }
})
```

Clearly this is a side effect that does not make the execution order obvious especially when the animation hierarchy is nested. The behavior is also fragile in the sense that calling `height` multiple times results in new measurements.

**Describe the solution you'd like**
To keep pose configurations deterministic, consider adding a `measure: boolean` property to the pose config that measures the element after it has mounted but before it has any initial poses applied to it. For consistency, the measurement should also be taken after the element's child poses have completed.

**Describe alternatives you've considered**
As an alternative, it could be possible to add a callback to the pose config that executes at the same time as the previous approach.

**Comment by InventingWithMonster** [comment]
Undocumented but you can use the `preTransition` config option for this

**Comment by strax** [comment]
@InventingWithMonster Thanks! It seems like `preTransition` does not run on mount, is that intentional?

**Comment by InventingWithMonster** [comment]
Yeah because the `transition` isn't actually run. Maybe there's scope for a
different lifecycle method?

**Comment by strax** [comment]
@InventingWithMonster Yeah, combined with `preTransition` we could move forward with a lifecycle that executes right after the posed component is mounted but before the initial pose is applied. This would need to execute after the child poses have completed, though, or otherwise the measurements will not reflect the posed contents' dimensions.
