### ISSUE TITLE
define what props have auto animations

### ISSUE THREAD

**Issue by chrisdrackett** [Popmotion/popmotion#383]
maybe I'm missing it, but other than the following:

> translate and rotate props use a slighty-bouncy spring.
scale props use a tight spring.
All other props use timing.

I can't seem to find in the docs what props can be auto animated. I'm working on working it out, but it might be nice to list these in the docs vs abstract categories.

**Comment by InventingWithMonster** [comment]
Every prop can be automatically animated. I'll add a section to the Supported Values page that goes through the settings

**Comment by chrisdrackett** [comment]
awesome! probably also worth calling out what works in native vs. web as your statement isn't currently true in both cases :)

**Comment by InventingWithMonster** [comment]
Sorry to be clearer every prop that **can** be animated can be automatically animated. On Native things like colors cant be animated yet so theres no automatic animation either.

**Comment by chrisdrackett** [comment]
ah, this is actually good to know :) (I know pose better than react native still, and never tried to animate anything in native using anything other than pose) ;)

**Comment by InventingWithMonster** [comment]
Added for Pose DOM https://popmotion.io/pose/api/supported-values/
