### ISSUE TITLE
import error when i update from 8.2.3 to 8.2.5 

### ISSUE THREAD

**Issue by wmzy** [Popmotion/popmotion#385]
**Describe the bug**
When I update popmotion from 8.2.3 to 8.2.5,I get an error:
```bash
This dependency was not found in node_modules:

* popmotion/animations/tween
```
Then code from the doc:
```js
import tween from 'popmotion/animations/tween';
```
You changed the package dir:
```bash
node_modules/popmotion
├── CHANGELOG.md
├── dist
├── lib
│   ├── action
│   ├── animations
│   │   ├── decay
│   │   ├── every-frame
│   │   ├── keyframes
│   │   ├── physics
│   │   ├── spring
│   │   ├── timeline
│   │   └── tween
......
├── package.json
├── package-lock.json
├── README.md
├── rollup.config.js
├── src
├── tmp
└── tsconfig.json
```
This is a break change.
BTW, the `tmp` dir should not be publish to npm.

**Comment by InventingWithMonster** [comment]
Yep, really sorry about this, I fucked this one. I moved the build process to Rollbar which bundles everything into a single file which broke the directory imports.

It's technically a breaking change but we're several versions in and we've only had a couple bug reports about it so I think most people are unaffected.

Importing like this:

```javascript
import { tween } from 'popmotion';
```

Will still code split in the way

```javascript
import tween from 'popmotion/animations/tween';
```

Was designed to do
