### ISSUE TITLE
Which browsers are supported?

### ISSUE THREAD

**Issue by voxpelli** [Popmotion/popmotion#392]
I'm not seeing a list of browser targets that Popmotion aim to support? That makes it kind of hard to know what failures to report as bugs and what failures are by design, as that browser is out of scope of what is supported.

Some inspiration for such a list: https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices#browsers-to-test-in

It also helps to know what the expected target is when evaluating the project, as one can then easily know whether it's compliant with ones own browser requirements or not. When there's no expected target that creates some uncertainty.

(Older issue: #231)

**Comment by InventingWithMonster** [comment]
https://popmotion.io/pose/api/faqs/
https://popmotion.io/api/faq/

**Comment by mr-wildcard** [comment]
I recently came across an error on IE 11. I found out that the use of `WeakSet` here is making it crashing : https://github.com/Popmotion/popmotion/blob/master/packages/framesync/src/create-render-step.ts#L15

**Comment by Andarist** [comment]
You have to polyfill `WeakSet` for IE11 support. Similarly how you have to polyfill Map & Set to make React@16 work in it - https://reactjs.org/docs/javascript-environment-requirements.html

**Comment by mr-wildcard** [comment]
Ok thank you @Andarist.
I think it worth adding `WeakSet` to required polyfills in https://popmotion.io/pose/api/faqs/

**Comment by Aratramba** [comment]
Array.find is also needed as a polyfill for IE11

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill

![screenshot 2018-11-28 at 13 51 32](https://user-images.githubusercontent.com/580312/49153169-44447500-f315-11e8-929e-b2e71131196d.png)

**Comment by hthief** [comment]
Can I recommend adding perhaps [core-js](https://github.com/zloirock/core-js) as an alternative to the weakset polyfill?

The [one on the faqs](https://github.com/dy/weakset/blob/master/index.js) doesn't work well with webpack and code splitting

**Comment by Aratramba** [comment]
had to polyfill object.assign as well now for IE11:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill
