### ISSUE TITLE
'draggable' should not be triggered with right mouse click

### ISSUE THREAD

**Issue by up209d** [Popmotion/popmotion#393]
I think it is a bit buggy when `draggable` feature works with the right mouse click. Right click on `draggable` object and keep the mouse pressing, move the mouse to another place then release the mouse pressing. It makes the object immediately following the mouse without any mouse pressing then. Until another mouse click is triggered, it stops. This situation can be easily encountered in all examples of `popmotion` instructions

**Comment by karibertils** [comment]
Is there any workaround to stop this behaviour ?

I am trying to make the drag only happen with left mouse click.

**Comment by up209d** [comment]
@karibertils If you go here https://popmotion.io/pure/, and look at `Functional composition`, you can do draggable like that way and then put the condition for only left `mousedown`
```
listen(ball, 'mousedown touchstart').start((event) => {
    if (event && event.which === 1) {
          schedule(everyFrame(), pointer(ballXY.get()))
            .pipe(smoothXY)
            .start(ballXY) 
    } 
});
```
