### ISSUE TITLE
Typings for DomPopmotionConfig don't seem to be correct

### ISSUE THREAD

**Issue by thomhos** [Popmotion/popmotion#396]
In a few examples I see that you can supply the following config to a `posed.div`

```
{
  draggable: 'x',
  dragBounds: { left: 0 },
  ...
}
```

The typings don't actually allow this. There draggable is defined as a boolean only. Also the dragBounds demand every possible property. Not sure if this will break other things, but I suspect this is a bug?

**Comment by InventingWithMonster** [comment]
Yeah it is, thanks for pointing out
