### ISSUE TITLE
React Posed : Running Test issue with jest & jsdom

### ISSUE THREAD

**Issue by Vandell63** [Popmotion/popmotion#402]
Hey, i try to make test with react-pose.
i used : 
- create-react-app-ts
- jest
- enzyme

Issue with jsdom: 
- With a `posed.g` : `cannot find function getBBox` bounding box of svg. Maybe jsdom don't have support for svg yet ?.

Issue with jest:
- Have an example with jest mock ? i try this : 
```
jest.mock("react-pose", () => ({
    posed: jest.fn()
}))
```
- Last time i try : 
```
jest.mock("react-pose", () => {
    const module: any = jest.genMockFromModule('react-pose');
    const g = mockComponent('g');
    const div = mockComponent('div');
    module.default.g = g
    module.default.div = div;
    return module;
})
```
where `mockComponent` is a function : 
```
import * as React from "react";

export default function mockComponent(name: string): Function {
    return (props: any) => React.createElement(name, props, props.children);
}
```
but cannot figure out to mock `pose.div` or `pose.g`  do you have any example.
I really want to stay on this awesome animation lib but i need to test component now. Im really stuck.
any help appreciated or any example of your test
Thx .

**Comment by rssfrncs** [comment]
React-pose is such a great animation library, but I think that it definitely needs to work out of the box with the most popular React testing framework.

I'm also getting the same error trying to mount a pose SVG Path element.

**Comment by InventingWithMonster** [comment]
We might add an example showing Vandell’s solution but we’re never going to
write code because a popular testing library is deficient. getBBox is a
standard method of SVG elements so it’s reasonable to assume its presence.
