### ISSUE TITLE
Stop mousedown tracking when mouse leave the document (or is out of window)

### ISSUE THREAD

**Issue by maximelebreton** [Popmotion/popmotion#403]
Hello and thanks for your amazing work!

There is a very annoying thing about popmotion drag stuff.

On all examples,   
[1] if you **start dragging** (`mousedown`),  
[2] **then leave** the `document` (or the `window`) **while** you drag,  
[3] **then release the drag** (`mouseup`),  
[4] and **go back** to the document,  
the `mousedown` **listener still tracking** (whereas `mouseup` should have been triggered?)...

Same thing if you keep mousedown while you minimize the window (alt+tab).

Here is a video based on this example: https://codepen.io/popmotion/pen/KZzWdz

![popmotion-2](https://user-images.githubusercontent.com/1072425/42959620-bb0f7944-8b89-11e8-9ee7-80b2e9c6005d.gif)

How can I fix that, and maybe this fix should be applied by default?

Thanks!

**Comment by InventingWithMonster** [comment]
Just fixed this in Pose with the following logic:

```javascript
listen(document.documentElement, 'mouseenter').start((e) => {
  if (e.buttons === 1) {
   // stop dragging here
 }
})
```
