### ISSUE TITLE
low res render when nesting posed.View's in react-native

### ISSUE THREAD

**Issue by chrisdrackett** [Popmotion/popmotion#404]
Snack Here: https://snack.expo.io/@multiscale/pose-bug
(best to view on an actual device as the issue isn't clear on the in-page simulator)

when nesting two `posed.View`'s that animate translate (`x` and/or `y`) on react native the whole view will be rendered in a lower resolution. This happens both during and between animations.

**Comment by therealravitej** [comment]
Facing the same issue.

**Comment by chrisdrackett** [comment]
I tried to update my example to `0.8.1` but ran into an error when trying to use two pose elements together:

https://snack.expo.io/@multiscale/pose-bug-2

**Comment by ChrisBews** [comment]
I'm facing the same issue here. I'm surprised there haven't been more complaints about this, as it pretty much means we can't use this library. If I had to guess, I'd say that it's rasterizing the components at their stated pixel dimensions, when it should actually be factoring the screen's pixel density. Further nesting just compounds the issue (the render quality of each component just gets worse the further you nest).

Would be good if this one was moved up the priority list - if React Native is considered an important target for the library.

**Comment by ChrisBews** [comment]
Further to this - I've found the problem code. It's this line: https://github.com/Popmotion/popmotion/blob/a8ca84eea52c7055657cca15dd77b6480a309ac7/packages/react-native-pose/src/inc/utils.ts#L77

Is there any reason we're forcing perspective here? Without perspective set, the blurring goes away and everything looks great again. I'm sure there was a good reason as to why it was added, but it would be great if we could choose to override this value, or just prevent it getting added. Thanks!

**Comment by InventingWithMonster** [comment]
Yeah I believe it was an Android issue, but due to my lack of comments it's
hard to remember what. That was a while ago though - if you open a PR with
this line removed I'll publish a version without it and deal with the
problems that do or don't arise as they come.

**Comment by ChrisBews** [comment]
I've created that PR here - https://github.com/Popmotion/popmotion/pull/802

Thanks for being so responsive - your work on this library is invaluable, especially when working with React Native!
