### ISSUE TITLE
Place for examples

### ISSUE THREAD

**Issue by Andarist** [Popmotion/popmotion#407]
I have wanted to add an example of using pose with css-in-js library (emotion), but there is no place to do that at the moment. IMHO would be super cool to have such place as some kind of "showcase" for how to use the library in more complex situations that those presented in the docs. I found such lists in other libraries highly useful & inspiring - i.e. take a look on this list https://github.com/final-form/react-final-form#examples .

Also I would propose making such examples on codesandbox.io - it has super feature of keeping the sandbox up to date with the repo which means that anyone could make a PR adding/improving those runnable in the browser examples and their source could live directly in this repo.

**Comment by InventingWithMonster** [comment]
Yeah I think this is important. I'll be leaving work in a couple weeks to spend more time on Popmotion, I'll add some sections for the various libraries and update this issue

**Comment by InventingWithMonster** [comment]
https://popmotion.io/pose/examples
