### ISSUE TITLE
Popmotion: Timeline animation for object and array values not working as expected

### ISSUE THREAD

**Issue by johndigital** [Popmotion/popmotion#408]
## Description
I may be misunderstanding the [documentation for this feature](https://popmotion.io/api/timeline/#timeline-usage-value-types-arrays), but when creating a timeline animation using a custom track name and a value of either an array or an object the value does not animate. The callback fires and the values appear to be in the correct format, but they do not change.

## How to reproduce
1. Simply go to [this codepen](https://codepen.io/johndigital/pen/JBpeKe?editors=0010) and check the values logged in the console. The timeline code is taken directly from the [timeline documentation](https://popmotion.io/api/timeline/#timeline-usage-value-types-arrays), under "Arrays" in the "Value Types" section.

## Expected behaviour
In the provided codepen, the logged value looks like this:
```
{
  ball: [0, "0vh"]
}
```
This value seems to be formatted correctly, but the value does not change. I would expect the first value to animate from 100 to 0 and the second to animate from "10vh" to "0vh"

## Link to CodePen example (or similar)
https://codepen.io/johndigital/pen/JBpeKe?editors=0010

## Device information
 - Device: MacBook
 - OS: OSX 10.13.6
 - Browser: chrome
 - Version: 67.0

**Comment by imjasonmiller** [comment]
Accessing the `ball` track seems to return the actual values here:

```
const { timeline } = window.popmotion;

timeline([
    {
        track: 'ball',
        from: [100, '10vh'],
        to: [0, '0vh']
    }
]).start(v => {
    console.log(v.ball)
})
```

**Comment by johndigital** [comment]
You're 100% right @imjasonmiller, thanks! Weird that it was the wrong values when the whole output is logged. Closing this issue.
