### ISSUE TITLE
React Native Pose: Color poses do not work

### ISSUE THREAD

**Issue by danielbartkowski** [Popmotion/popmotion#409]
## Describe the bug
Both color and backgroundColor do not appear to function in react-native pose.

## How to reproduce
1. Add color properties to poses
2. Set the pose to any of the poses

## Expected behaviour
Color should change to match that of the selected pose.

## Link to Examples
Expected (standard pose):
https://codesandbox.io/s/0owr9n3p7n

Actual:
https://snack.expo.io/@multiscale/react-native-pose-color

## Device information
In which environment are you reproducing the bug?
 - iPhone8
 - iOS

## Additional context
Testing with opacity (as an example of other properties) in place appears to work just fine.
There's some strange behavior with the output of the props. When sending in:

```javascript
poseProps={{
  foo: { color: '#ff00ff' },
  bar: { color: '#000000' },
}}
pose="bar"
```

the output is:
```javascript
{
  "color": "NaN#"
}
```

Named colors such as:
```javascript
poseProps={{
  foo: { color: 'black' },
  bar: { color: 'black' },
}}
pose="bar"
```
result in
```javascript
Cannot read property '0' of null

This error is located at:
    in PoseComponent (at posed.js:21)
```

**Comment by InventingWithMonster** [comment]
Colors are only currently supported as passive values

https://popmotion.io/pose/api/native-supported-values/

I'm currently looking into ways of changing this.
