### ISSUE TITLE
Passing a value to pose has no effect

### ISSUE THREAD

**Issue by VulcanRav** [Popmotion/popmotion#415]
Helllo, I am trying to learn react-pose but I'm a bit frustrated but my lack of understanding of this library.

It doesn't help that all the examples in the docs are developed in codepen, which I find hard(er) to reproduce in a normal environment that leverages module imports. It's also not very helpful, imho, that there's basically just one syntax in the docs which uses styled components and creates elements through the same posed.element method. Github searching hasn't found me many (working) examples of using react-pose with the hoc approach.

Anyway, I was trying to develop a small demo that leveraged the use of posed(MyComponent) but it's getting a bit difficult to do so.

```
import React from "react";
import ReactDOM from "react-dom";
import posed from 'react-pose';
import "./styles.css";

const MyComponent = ({ hostRef, isVisible }) => <div pose={isVisible ? 'visible' : 'hidden'} ref={hostRef}>
  <h1>Hey I am from a Posed Compent</h1>
</div>

const config = {
  'visible' : { opacity: 1},
  'hidden': { opacity: 0}
}

const PosedComponent = posed(MyComponent)(config);

const rootElement = document.getElementById("root");
ReactDOM.render(<PosedComponent isVisible={false} />, rootElement);
```

I am really trying from two days to make this work, but no matter what I pass to the pose property (I even tried hardcoding it to a value in config such as pose={'hidden'} it just doesn't work.

When I check the elements in my html I can clearly see the element has opacity: 1 set, but changing the pose property just won't change the styling.

Here's a demo:

https://codesandbox.io/s/jpxx3rklz5

**Comment by InventingWithMonster** [comment]
You need to pass the pose to the posed component (in this case
PosedComponent), not the div
