### ISSUE TITLE
react-pose: in IE11 child-components seem to ignore parent-pose keys

### ISSUE THREAD

**Issue by klaasman** [Popmotion/popmotion#418]
## Description
In Internet Explorer 11 there seems to be an issue with react-pose: child-components seem to ignore the current pose-key set in a parent.

I've setup a demo repo to reproduce the issue: https://github.com/klaasman/react-pose-ie11-bug

## How to reproduce
1. `git clone https://github.com/klaasman/react-pose-ie11-bug`
2. `cd react-pose-ie11-bug`
3. `yarn install`
4. `yarn start`
5. open [`http://localhost:8000`](http://localhost:8000) in IE11

## Expected behaviour
In IE 11 child components should inherit the pose defined by a parent component.  
See the [screen captures](https://github.com/klaasman/react-pose-ie11-bug#screen-captures) for a visual result.

## Link to example
https://github.com/klaasman/react-pose-ie11-bug

## Device information
In which environment are you reproducing the bug?
 - Internet Explorer 11

**Comment by InventingWithMonster** [comment]
Turns out this is a problem with IE11 and `Array.from`. You can add a [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) and I'll take a look at adding somewhere I can document this

**Comment by klaasman** [comment]
I'm not sure if that's the problem, there's already a polyfill (from polyfill.io) in my demo repo whih is also polyfilling the `Array.from` method.

I'll try to find the actual issue somewhere in the future.

**Comment by InventingWithMonster** [comment]
That’s interesting. The reason why I think this is it, is cuz children.size
is 1 and Array.from(children).length is 0, so it doesn’t iterate over them.
Maybe the polyfill doesn’t fix this. Maybe there needs to be a Set polyfill
to make it iterable

**Comment by klaasman** [comment]
You're right, there appears to be a bug in polyfill.io regarding `Set` and `Array.from`.

https://github.com/Financial-Times/polyfill-service/issues/1390

**Comment by klaasman** [comment]
It looks like it is - and probably will be - a long running issue.
A workaround on popmotion's side would be:
```
Array.from(children.keys())
// or
Array.from(children.values())
```

But I can imagine you're not willing to implement something like this, since it will never end.

**Comment by InventingWithMonster** [comment]
I don’t see anything wrong with that approach, I’ll take a look at simple
solutions tomorrow.
