### ISSUE TITLE
Pose reverting to wrong pose

### ISSUE THREAD

**Issue by Andarist** [Popmotion/popmotion#436]
## How to reproduce
https://popmotion.io/pose/learn/ui-events/#ui-events-and-interactions-drag-poses

Drag box on 1st example in that section - the one with this:
```js
const Box = posed.div({
  draggable: true,
  init: { scale: 1 },
  drag: { scale: 1.2 },
  dragEnd: { scale: 0.5 }
});

const Label = posed.span({
  init: { color: '#000' },
  drag: { color: '#f00' }
});
```

After 1st drag the label's color reverts OK to #000 but after second drag is stays with #f00

## Expected behaviour

Predictable behaviour

## Device information
irrelevant

**Comment by InventingWithMonster** [comment]
Could you try again now? I think CodeSandbox hadn't updated pose-core

**Comment by Andarist** [comment]
Can't reproduce anymore, thanks :)
