### ISSUE TITLE
Add TS to project's devDependencies

### ISSUE THREAD

**Issue by Andarist** [Popmotion/popmotion#438]
The project should explicitly state what its dependencies are - I've run into problems because of missing TS devDep ("random" TS version got used - found in `node_modules` by accident).

I've tried to add it quickly, but encountered such problem while installing:
```js
error An unexpected error occurred: "could not find a copy of typescript to link in /popmotion/node_modules/react-pose-text/node_modules/popmotion-pose/node_modules".
```

So this needs further investigation.

**Comment by InventingWithMonster** [comment]
I've tried to unify TS to one version for the whole project. https://github.com/Popmotion/popmotion/commit/b979f161385357726692e06b26271d58ccb923da

React Pose is compiling fine for me now, you?

**Comment by Andarist** [comment]
Can't rly check it because it depends on popmotion-pose which doesnt compile now with
```
[!] (rpt2 plugin) Error: /popmotion/packages/popmotion-pose/src/factories/pose.ts(218,5): semantic error TS2345 Argument of type '{ bindOnChange: (values: Map<string, Value>, onChange: OnChangeCallbacks) => (key: string) => voi...' is not assignable to parameter of type 'PoseFactoryConfig<Value, Action, ColdSubscription, P>'.
  Object literal may only specify known properties, and 'convertTransitionDefinition' does not exist in type 'PoseFactoryConfig<Value, Action, ColdSubscription, P>'
```

**Comment by InventingWithMonster** [comment]
Could you try building `pose-core` again first? Because I've done a clean install of the project and everythings definietly on ts 2.9.2 now. I wonder if it's referring to an outdated definition in that project

**Comment by Andarist** [comment]
So the only package not building right now for me is `react-360-pose`. Mostly because of the source not being rly authored with types and thus resulting in lots of `implicitly has an 'any' type`

**Comment by InventingWithMonster** [comment]
Yeah it’s a bit of a prototypical package - is there a way to omit or flag
a package?
