### ISSUE TITLE
Set values within Timeline tracks

### ISSUE THREAD

**Issue by imjasonmiller** [Popmotion/popmotion#440]
Hi, 

I have been using [`Timeline`](https://popmotion.io/api/timeline/) with THREE.js—great so far, thank you!—and wondered if it was possible to set values that do not need to be animated over time in a more idiomatic way?

GreenSock offers a zero-duration [`set()`](https://greensock.com/docs/TimelineMax/set) tween, which helps when e.g. setting properties before animating the next track.

I had a quick look at [timeline.ts](https://github.com/Popmotion/popmotion/blob/ea8c6d8136b875b86f35588ff8a40985ebdc93cc/packages/popmotion/src/animations/timeline/index.ts), but could not find anything at the time.

Currently I have done something akin to this, as `duration: 0`  breaks the animation:

    const tracks = [
        { track: "group0Visible", from: 0, to: 1, duration: 10 },
        { track: "group1", from: { z: -Math.PI }, to: { z: 0 } },
    ]
   
Values are then set in the following way:

    setValues(v) {
        // Mesh visibility
        this.group0.visible = v.group0Visible === 1 ? true : false
    }

Is there a better way to do this using Popmotion?

**Comment by InventingWithMonster** [comment]
No I actually do it the same way as you, declaratively setting it based on the status of the output. Stops you having to add that slightly more brittle imperative step
