### ISSUE TITLE
Help with animating between 2 posed components

### ISSUE THREAD

**Issue by b0gd4n** [Popmotion/popmotion#441]
I am trying to figure out the best way to animate 2 different elements that render conditionally on a prop, eg:

```
const AnimContainer1 = posed.div({
  exit: {opacity: 0},
  enter: {opacity: 1}
})
const AnimContainer2 = posed.div({
  exit: {opacity: 0},
  enter: {opacity: 1}
})
{this.props.condition ? (
  <AnimContainer1 pose={this.state.renderc1 ? 'enter' : 'exit'}>{container1contetent}</AnimContainer1>
) : (
  <AnimContainer2 pose={this.state.renderc2 ? 'enter' : 'exit'}>{container1contetent}</AnimContainer2>
)}
```
I tried having 2 different states for each element and pass it to the posed component. I am trying to change the state through a combination of react methods (componentDidMount, componentWillUnmount, componentWillReceiveProps) but it all feels very clumsy and `enter` animation is not working.

Also, I would like to animate the `content` of each component, so fade in/out when `container1content` changes.

**Comment by InventingWithMonster** [comment]
Content can be wrapped in its own posed component with the same poses
defined.

If you wrap the two posed components in PoseGroup, they’ll animate in and
out https://popmotion.io/pose/api/posegroup/

**Comment by b0gd4n** [comment]
I tried with `Math.random()` or giving the first one `key={1}` and the second one `key={2}` so they are certainly different - the same result - they both remain rendered after the condition is flipped.

**Comment by InventingWithMonster** [comment]
Math random certainly won’t work but 1 and 2 would. I’d need to play around
with a codesandbox or
Similar to help further as I’ve not seen this not work before

**Comment by InventingWithMonster** [comment]
Sorry was away yesterday and didn't read the original code correctly. `PoseGroup` handles the poses for you:

```javascript
<PoseGroup>
{this.props.condition ? (
  <AnimContainer1 key={1}>{container1contetent}</AnimContainer1>
) : (
  <AnimContainer2 key={2}>{container1contetent}</AnimContainer2>
)}
</PoseGroup>
```

**Comment by b0gd4n** [comment]
thank you - that works!
