### ISSUE TITLE
react-pose: Added additional attributes when a pose is leaving

### ISSUE THREAD

**Issue by jsm1003** [Popmotion/popmotion#448]
## Add the package name to bug title
react-pose: Added additional attributes when a pose is leaving

## Describe the bug
when a pose is leaving which will be adding additional properties, added position, left and top,

## How to reproduce
checkout this [demo](https://codesandbox.io/s/6wk23j2loz), 

## Expected behaviour
expect no additional CSS attributes when a pose is leaving, as same as it is entering

## Device information
In which environment are you reproducing the bug?
 - Device: [PC]
 - OS: [win10]
 - Browser [chrome: 68]
 - Version [react-pose: 2.3.0]

## Additional context
forgive my poor English😂

**Comment by InventingWithMonster** [comment]
Hi thanks for this and the included example. We add the additional style properties to "pop" the element out of the DOM flow so we can correctly animate its surrounding elements.

We try to do it intelligently so it doesn't affect the exit transition as defined by the user. It looks like it isn't doing the right thing in this example though so I'll take a look

**Comment by jsm1003** [comment]
@InventingWithMonster 
I think there is no need to add additional properties ,if add,  I have to add position: relative property in parent element.

**Comment by InventingWithMonster** [comment]
Not in the instance of having one child but if you’re swapping children or
have multiple children you actually do

**Comment by InventingWithMonster** [comment]
Can you replace `<PoseGroup>` with `<PoseGroup flipMove={false}>` please?

**Comment by jsm1003** [comment]
@InventingWithMonster thanks a lot, it solved my problem👍
