### ISSUE TITLE
Animate filter?

### ISSUE THREAD

**Issue by b0gd4n** [Popmotion/popmotion#449]
Trying have a blur effect animation like so:

```
enter: { opacity: 1, filter: 'blur(0px)', delay: 300 },
exit: { opacity: 0, filter: 'blur(20px)' }
```

but once the animation enters, the blur(20px) sticks:

```
    filter: blur(20px);
    transform-origin: 0% 0% 0px;
    opacity: 1;
```

**Comment by InventingWithMonster** [comment]
Hmm looks like a bug I thought was fixed is still outstanding. Can you instead try animating

`grayscale(0%) blur(0px)` to `grayscale(0%) blur(20px)`

**Comment by InventingWithMonster** [comment]
This will be a temporary fix until I can fix the underlying bug

**Comment by InventingWithMonster** [comment]
Awesome! Just reopening this so I take a look at it
