### ISSUE TITLE
react-pose: pose config as a function

### ISSUE THREAD

**Issue by tadeuszwojcik** [Popmotion/popmotion#451]
I'm working on a project that allows theming of UI components, would love to add pose animations support for it , but currently `poseConfig`  object needs to be provided when creating `pose` elements  so it's bit static and can't be changed dynamically via theme in my use case. Would you consider a change to `react-pose` https://github.com/Popmotion/popmotion/blob/master/packages/react-pose/src/posed.tsx  that instead of passing `poseConfig` to `createElement`  would pass `config` that is defined as:
```js
const config = typeof poseConfig === 'function' ? poseConfig(props) : poseConfig;
```

This way I could provide `theme` object in props and extract from them matching poseConfig object and return in from the function. That would allow me to expose `poseConfig` to end users so they could extend/change animations at will as those would be defined in theme object. Does it make sense? It would be quite similar to `styled` components factory that also allows passing function instead of css object/template string.
Thanks!

**Comment by InventingWithMonster** [comment]
It's interesting, I was actually just thinking if this would be useful yesterday. Good to see an actual use-case for it.

In the linked issue you say you've got it working locally. But if the goal is to update the posed component as a user changes/adds animations, does the poser get updated in your example?

Posers (the actual faux-state machine at the heart of all flavours of Pose) are immutable once created so without reinstaniating the component I don't see how this is working already? I'd be pleasantly surprised if it was. I'm just instinctively hestiant to make a change where we reinstantiate posed components based on config changes as they're nested objects so its expensive to tell if they've "really" changed.

**Comment by tadeuszwojcik** [comment]
My goal is to have configurable animations via theme object which is constructed once. Live updating theme is nice for demos and for sure has wow factor, but in real scenarios not that useful.
I can confirm that when trying to update pose config 'live' then element animations do not change, but it's not a big deal as mentioned.

**Comment by jgoux** [comment]
> Posers (the actual faux-state machine at the heart of all flavours of Pose) are immutable once created so without reinstaniating the component I don't see how this is working already? I'd be pleasantly surprised if it was. I'm just instinctively hestiant to make a change where we reinstantiate posed components based on config changes as they're nested objects so its expensive to tell if they've "really" changed.

I think I have a valid use case for updating the  config.

I want to make page transitions aware of the next destination. As I don't know the destination until the user click a link, I can't determine the `exit` animation when I initialize the posed component.

See https://github.com/Popmotion/popmotion/issues/517#issuecomment-428096011 for more infos.

**Comment by Andarist** [comment]
@jgoux can't you pass your destination as props when it's known and calculate your transition based on your props in your "static" pose config?

smth like
```js
posed.div({
  exit: {
    x: ({ destination }) => destination
  }
})
```

**Comment by jgoux** [comment]
@Andarist I think I could but it's not flexible enough IMO.

What if I have already a default exit and I want to overwrite it with differente keys?

Would this syntax cause the pose elements to be reinstanciated ?

```jsx
const Animation = posed.div({
  from: ({ from }) => from,
  enter: ({ enter }) => enter,
  leave: ({ leave }) => leave
})
```

I understand that we can't add other poses, but what if we could at least change the whole object at once?

**Comment by Andarist** [comment]
Posed elements are always preserved when transitioning from pose A to B, that's the whole point. So at least you don't have to be concerned with this.

Not sure if resolving functions on each level of the config is a good choice, seems to complicate the API. I don't have a strong opinion about this though and I'm not an author of pose, so maybe Matt will state his opinion about this later.

**Comment by InventingWithMonster** [comment]
I see the value of having dynamic poses. It’d be nice to return totally
different values depending on props. But currently there is a deep barrier
to instantiating new values. For instance what happens if a passive value
is defined on a value that might not exist yet? As Mateusz points out, how
do we message that API crinkle? It’s not impossible to solve but it will
require time investment.

**Comment by JesseChrestler** [comment]
@tadeuszwojcik  maybe for the interim you could create your components at run time. Then you could check and only recreate the posed component if the pose changes. I'm doing something similar to you and was able to achieve this. I use a registry so that it's not creating a pose for every instance, but just for every type. Not sure if this helps you but you can work around this issue.
