### ISSUE TITLE
react-pose-text: Changing `pose` dynamically has no effect

### ISSUE THREAD

**Issue by fabe** [Popmotion/popmotion#453]
When changing the `pose` prop of `SplitText` dynamically via the component state or props (as described in [the documentation](https://popmotion.io/pose/api/react-pose-text/#react-pose-text-usage-splittext)) the `posed.div`s do not re-render and animate, because the `parseText` method is only executed when the `children` change (https://github.com/Popmotion/popmotion/blob/master/packages/react-pose-text/src/SplitText.tsx#L47)

## How to reproduce
Change the `pose` prop of `SplitText` dynamically with a ternary operator.

## Expected behaviour
The component re-renders and the pose change is animated.

## Link to CodePen example (or similar)
https://codesandbox.io/s/1072y4yzn7

**Comment by InventingWithMonster** [comment]
Thanks for this and providing a CodeSandbox

Closed in `react-pose-text@3.1.0`
