### ISSUE TITLE
[SVG][polyline][react-pose] - pathLength having no effect

### ISSUE THREAD

**Issue by pr1ntr** [Popmotion/popmotion#454]
I am making a polyline like so:

```
const PolyLine = posed.polyline({
  empty: { pathLength: 0 },
  fill: { pathLength: 100 },
})
```

and then implementing:

```
<PolyLine
    points={points.join(' ')}
    stroke="#ffffff"
    fill="none"
    pose={transitionState === TRANSITION_STATES.ENTERED ? 'fill' : 'empty'}
 />
```

when the `transitionState` changes then nothing. I really can't figure out what I'm doing wrong.

**Comment by InventingWithMonster** [comment]
It only works on path elements. Does polyline support stroke-dasharray etc?

**Comment by klaasman** [comment]
From the MDN docs about the [stroke-dasharray](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray):

> As a presentation attribute, it can be applied to any element but it has effect only on the following eleven elements: `<altGlyph>`, `<circle>`, `<ellipse>`, `<path>`, `<polygon>`, `<polyline>`, `<rect>`, `<text>`, `<textPath>`, `<tref>`, and `<tspan>`

So there's more than only the `path` :-)

**Comment by InventingWithMonster** [comment]
Cool thanks for that. Let me take a look

**Comment by InventingWithMonster** [comment]
Ah yeah the reason for this is `pathLength` works as a percentage which requires the `getTotalLength()` method which isn't widely supported on elements other than `path`.

For other elements you'll need to animate the `stroke-` properties themselves: https://css-tricks.com/svg-line-animation-works/

I'll update the docs to reflect this.

**Comment by InventingWithMonster** [comment]
Closed with https://popmotion.io/pose/api/supported-values/

**Comment by klaasman** [comment]
Ah I see. I've made a codesandbox that shows that both Chrome and Firefox already have wider support for `getTotalLength()` - https://codesandbox.io/s/n02mz8464l

Let's hope that other browsers/devices follow soon :-)

**Comment by pr1ntr** [comment]
Why rely on a native getTotalLength() when the path length calculation isn't that complicated to polyfill? polyline definitely supports stroke-dasharray etc. I switched to a path and it works but polyline point syntax is easier to manager IMO so when I am writing SVG's by hand its the _path_ (😄) of least resistance.
