### ISSUE TITLE
Lag when mount animation in Safari

### ISSUE THREAD

**Issue by inomdzhon** [Popmotion/popmotion#459]
## Add the package name to bug title
react-pose: Safari lag

## Describe the bug
Animation `mount` in Safari have lags.

## How to reproduce
1. Go to https://mzx1jz521p.codesandbox.io/about
2. Click on 'Home'
3. Click on 'About'
4. See lag

## Expected behaviour
Don't lag. Work same how in Chrome, Firefox, etc

## Link to CodePen example (or similar)
- https://lx6k64453l.codesandbox.io
- https://mzx1jz521p.codesandbox.io/about

## Device information
In which environment are you reproducing the bug?
 - Device: Apple Macbook
 - OS: Mac OS
 - Browser Safari
 - Version 11.1.2

## Additional context
I think reason is `PoseGroup`

**Comment by InventingWithMonster** [comment]
I'm testing this now and I'm wondering, do you mean lag as in low framerate, or do you mean the little flash of content?

**Comment by InventingWithMonster** [comment]
This is a bug in Safari https://bugs.webkit.org/show_bug.cgi?id=177484

I'll have to see if there's any way of mitigating it.

**Comment by InventingWithMonster** [comment]
Fixed in `popmotion-pose@3.2.3`
