### ISSUE TITLE
dynamic prop with random poseKey not updating underlying dom element attribute

### ISSUE THREAD

**Issue by jasonkuhrt** [Popmotion/popmotion#461]
Here is a demo showing the problem: https://codesandbox.io/s/186wz3zkq7.

I expect `style.top` to be getting updated continually. It appears to only take the value returned upon first invocation of the dynamic prop, however.

Note that the dynamic prop function is invoking as expected (see console.log output). The issue is in something after that value is returned.

~Probably I'm doing something wrong but maybe I'm hitting a bug, not sure. So far nothing that I've read in the docs makes clear to me that I've used the library wrong.~ Confirmed its a bug.

**Comment by klaasman** [comment]
It seems to be broken since v3.1.0

**Comment by jasonkuhrt** [comment]
Ah ok, its currently blocking my work on a branch of `react-popover`. I would be more than open to helping find a fix for this. I might try to crack open the codebase tonight. Any tips?

**Comment by klaasman** [comment]
Nope, I do not (yet) have any tips, still too unfamiliar with the codebase :-)

I'm sure @InventingWithMonster has an idea what's causing this. In the meantime you can simply depend on v3.0.2 if you're not using any features from v3.1.0+.

**Comment by jasonkuhrt** [comment]
Here's a version that confirms it works with `v3.0.x`: https://codesandbox.io/s/186wz3zkq7

**Comment by klaasman** [comment]
that one is still in 3.2.1 :-) here's an example with 3.0.2: https://codesandbox.io/s/6w4p7wq38w

**Comment by InventingWithMonster** [comment]
Fixed in `popmotion-pose@3.2.4`

**Comment by jasonkuhrt** [comment]
@klaasman thanks! I didn't "save" my changes 😊 

@InventingWithMonster Amazing man! I guess we'll close this issue once a release for `react-pose` is made?

**Comment by InventingWithMonster** [comment]
You can probably clear your lock files and reinstall reactpose and it
should come with the latest version of Popmotion-pose (as it’s a minor
release)
