### ISSUE TITLE
React-pose props

### ISSUE THREAD

**Issue by JulianMined** [Popmotion/popmotion#463]
I'm trying to pass some props to my "posed" element.
The background-color is animating, but not the x.
What's wrong with my code?

```
const BigBox = posed.div({
  init: {
    x: 0,
    backgroundColor: 'rgb(255,255,0)',
  },
  big: {
    x: ({bar}) => bar,
    backgroundColor: ({foo}) => foo,
    }
  }
)
<BigBox pose={this.state.bigBoxPose} foo={'rgb(0,0,255)'} bar={100}>
```

Thanks, Julian

**Comment by JulianMined** [comment]
Hi Matt - my popmotion-pose version is 3.2.3

**Comment by InventingWithMonster** [comment]
If you clear out your node modules, yarn lock/package lock and reinstall
React-pose it should come with 3.2.4 which I *suspect* fixed this

**Comment by klaasman** [comment]
@JulianMined can you confirm it's fixed by reinstalling dependencies as @InventingWithMonster suggests?
