### ISSUE TITLE
Flow types

### ISSUE THREAD

**Issue by sunnyvempati** [Popmotion/popmotion#478]
**Is your feature request related to a problem? Please describe.**
Looks like it's written in typescript.  I tried grabbing the types I care about then generating flow types for them, but there's still some black holes.  It would be nice for the authors to generate this for us and add to `flow-typed`.  (or generate types and add to `DefinitelyTyped`)

**Describe the solution you'd like**
Create flow (or typescript) types in a centralized location to know all the types that exist.

**Describe alternatives you've considered**
Tried creating my own but with its own set of problems.

**Comment by Andarist** [comment]
IMHO this puts too much burden on the maintainer and those types should be created by the community in `flow-typed` repo. Are there any auto-converters that could help you with that?

**Comment by sunnyvempati** [comment]
@Andarist there are auto converters but there is no declaration file for the react-pose ts work so there's a lot of stitching types together on the ts side before it can be converted to flow.

**Comment by Andarist** [comment]
Not sure what do u mean - `react-pose` has a typing file:
```sh
cat node_modules/react-pose/lib/index.d.ts
```
