### ISSUE TITLE
resolveProp called with different set of props

### ISSUE THREAD

**Issue by Andarist** [Popmotion/popmotion#480]
While investigating #466 and the latest fix for it I've noticed that:

`resolveProp` is called with `transitionProps` [here](https://github.com/Popmotion/popmotion/blob/17ddfcde8e3bed5c3b6ca724a00339d7dcaae92f/packages/pose-core/src/factories/setter.ts#L264), but it's called with `poserState.props` [here](https://github.com/Popmotion/popmotion/blob/17ddfcde8e3bed5c3b6ca724a00339d7dcaae92f/packages/popmotion-pose/src/dom/unit-conversion.ts#L60).

While this is probably really minor issue, it indicates to me that current algo is flawed - the resolving is spread across many call sites and is handled inconsistently

**Comment by InventingWithMonster** [comment]
For individual value transitions we add extra props such as to and
velocity. This is covered in the docs. Definitely agree resolution should
be consolidated but I think this one will always have to have the extra
props
