### ISSUE TITLE
Wait for the enter component to finish its animation before unmounting the exit component

### ISSUE THREAD

**Issue by titouancreach** [Popmotion/popmotion#485]
Hello,
I've been stuck for our for this simple feature, I try to keep the exit component alive until the entre compenent has finished transitioning.
I didn't find anything like this in the API or documentation (maybe I misread) 

Here is an example: https://codesandbox.io/s/72o94j423x
We see a white page, I would love that the color page stay in the dom during the transition

Thanks for your help

**Comment by InventingWithMonster** [comment]
You don't have any `exit` pose defined so it thinks its exited immediately.
Give it a transition that lasts the required duration of time, even if its
animating opacity to 1 for x ms

**Comment by titouancreach** [comment]
Thanks for answering!
Is that the correct syntax: https://codesandbox.io/s/k5731ln295

I can make it to work by using delay instead of duration: https://codesandbox.io/s/74vj0j559q

But the behavior seems weird to me:
  - When I click multiple time (fast) on the button, so before the transitions finished, I can still see a white screen. I also noticed that the animations are stacked. If I click 10 times, I can see the 10 animations to pop. There is a way to cancel the previous animation ?
I mean, that the last animation triggered cancel the previous one ?

**Comment by InventingWithMonster** [comment]
It should be transition: {duration: 1000}

I don't think multiple animations are firing, I think there's some kind of
z-index stuff going on but could be wrong

**Comment by titouancreach** [comment]
I'll investigate,
thanks!

**Comment by Andarist** [comment]
@InventingWithMonster if we quickly add & remove consecutive elements their all firing both enter & exit animations, but I would say this is expected behaviour - https://codesandbox.io/s/6ykrqpm6r3
