### ISSUE TITLE
Pose-core: flip & applyAtStart clash

### ISSUE THREAD

**Issue by Andarist** [Popmotion/popmotion#491]
## Describe the bug
It's impossible to make an entering flip animation for posed elements hidden with `applyAtEnd`, because of those lines:

https://github.com/Popmotion/popmotion/blob/5df3b13e8e7a32e8d502a9f1dff1454e01469a21/packages/pose-core/src/factories/setter.ts#L210-L231

`transformPose` call first calculates the flip by calling `explicitlyFlipPose` and only later `applyAtStart` gets applied. The intuition would tell me that this should work and that `applyAtStart` should play nicely with flip here, OTOH `applyAtEnd` & `applyAtStart` ideally would behave the same and assuming my intuition is correct here for `applyAtStart` then fixing this would create an opposite problem of not being able to hide the element with flip.

So maybe it's just matter of documenting this behaviour?

## How to reproduce
```js
const Box = posed.div({
	visible: {
		width: '20vw',
		height: '40vh',
		flip: true,
		applyAtStart: {
			display: 'block',
		},
	},
	hidden: {
		width: '1px',
		height: '1px',
		flip: true,
		applyAtEnd: {
			display: 'none',
		},
	},
})
```

**Comment by souporserious** [comment]
Experiencing a similar problem without using `flip`. It can be seen in the animated title [here](https://codesandbox.io/s/rj2llpqom) when clicking a photo. The transform doesn't seem to get applied when toggling `display: block` from `display: none`.

Relevant code:

```js
const PhotoTitle = posed.h2({
  thumbnail: {
    applyAtEnd: { display: 'none', zIndex: 1 },
    opacity: 0,
    x: '50%',
    y: '100%',
  },
  fullscreen: {
    applyAtStart: { display: 'block', zIndex: 10 },
    opacity: 1,
    x: '50%',
    y: 0,
  },
})
```

**Comment by InventingWithMonster** [comment]
I'm going to have a bug burn down tomorrow so I'll take a look at this then.
