### ISSUE TITLE
Why height animation doesn't work?

### ISSUE THREAD

**Issue by iamrddlr** [Popmotion/popmotion#493]
I am using Popmotion with Vue

```js
import { tween, styler, easing, timeline } from 'popmotion'

enter (el, done) {
      console.log('enter')
      const block = styler(el)
      tween({
        from: { height: 0, opacity: 0 },
        to: { height: 'auto', opacity: 1 },
        ease: easing.easeInOut,
        duration: 500
      }).start({
        update: (v) => {
          block.set(v)
        },
        complete: done
      })
    },
    leave (el, done) {
      console.log('enter')
      const block = styler(el)
      tween({
        from: { height: 'auto', opacity: 1 },
        to: { height: 0, opacity: 0 },
        ease: easing.easeInOut,
        duration: 500
      }).start({
        update: (v) => {
          block.set(v)
        },
        complete: done
      })
    }
```

Opacity works fine, but height doesnt animate. What I am doing wrong? It's just basic accordion.

**Comment by InventingWithMonster** [comment]
Popmotion Pure doesn't support animating to/from `'auto'`, only Pose does. Pure animates between two values of the same kind.

**Comment by iamrddlr** [comment]
@InventingWithMonster well, it doesn't animate to `100%` either. So it's impossible to use Popmotion for accordion? I need Pose for that? It's pretty confusing since there's so much libraries.

**Comment by iamrddlr** [comment]
So, if I will use `Pose` I don't need `Popmotion` at all? Can you please clear this up @InventingWithMonster since I don't want to learn both API (they looks very different). I am new with `Popmotion` but it looks just awesome.

**Comment by InventingWithMonster** [comment]
If you're using the latest version of Popmotion it will animate '0%' to
'100%'. It has to be '0%' not 0

Pose can't do everything Popmotion can but the things it can do are far
easier. For instance, here's a demo of an accordion in Pose for React. It'd
be trivial to make the same with Pose for Vue
https://codesandbox.io/s/pwk5yq8pzx

**Comment by iamrddlr** [comment]
@InventingWithMonster it is not trivial at all. You approach has completely different nature then Vue transitions. Here I tryed - https://codesandbox.io/s/y0l5jnjxx

I have no idea how to use your approach. Ypy create `Box` element in all Vue examples. They are just empty divs. But in real world I have other elements in my transitions. How to completely remove them? For example, heres your Vue example, but if I nest content in `Box` everything breaks https://codesandbox.io/s/y291l1495j

I have no idea how to use `Pose` beside empty divs from examples.

**Comment by InventingWithMonster** [comment]
Please bear in mind as you ask for my help that it isn't my responsibility or obligation to help you with this.

I've provided you an example that works and you've given it just 5 minutes of time (if that) before throwing it back at me. With a small amount of effort you can port the example without any knowledge of Pose or React.

1. Why do you feel obligated to use `v-show`? Do I use anything similar in the example I provided to you (no). So your first step is to remove that.

2. Your content is now visible when an accordion is closed. Why is that? Hint: this is a CSS problem.

There is some work to do on Pose examples and documentation but this is open source software and I don't necessarily have the time to provide examples that replicate complex UIs.

**Comment by iamrddlr** [comment]
With such attitude do you expect me to research this lib more and use it in production, so I could pay you (open source, right)? And by the way, it wasn't `5 minutes`, I saw your tweet with accordion example before you give me that link.

**Comment by InventingWithMonster** [comment]
It's probable this wasn't your intention, but so you're aware, you've come off as demanding and rude in this thread, which is why you're detecting "attitude". Also you don't need a commercial license for Pose.

**Comment by iamrddlr** [comment]
I just read my first 4 comments, and I don't see nothing `rude` or `demanding`. Can you be more specific? Or you mean I was rude when I post a link saying it wasn't trivial (which is absolutely not)? Or saying that examples are not illustrative? Is this what frustrates you? Ok, then imagine how I was frustrating spend couple of hours digging in weird API, just to saw how you close issue immidiately without any help.

`Also you don't need a commercial license for Pose.` cool, will have this is mind if I decide to run Pose on commercial project (which I probably don't)/ Have an awesome day.

**Comment by InventingWithMonster** [comment]
> Ok, then imagine how I was frustrating spend couple of hours digging in weird API

And this is the attitude with which you entered the discussion.

**Comment by Andarist** [comment]
I can only confirm that you (@iamrddlr) sound **really** demanding in this thread, and this is often why OSS maintainers burnout. Popmotion might not be ideal (hint: nothing is), but its OSS and you can use it for free (and maybe even fix a problem or two in its codebase), so don't be a douche. Matt done some pretty amazing work so you don't have to deal with it and even if u have some problems with the API don't ever report it (to any OSS software) in a way you did.

**Comment by iamrddlr** [comment]
So, after all, it *was* the CSS property. Damn, I am feeling very stupid (well, I guess I am). Sorry @InventingWithMonster hope I didn't affect your mood.
