### ISSUE TITLE
React pose: Transition props forwarding bug

### ISSUE THREAD

**Issue by Andarist** [Popmotion/popmotion#494]
## Describe the bug

Props resolvers get stale props.

Stale values are passed here - https://github.com/Popmotion/popmotion/blob/009e777b90100c08e9dae16564babae14682eb2f/packages/react-pose/src/components/Transition/children.ts#L88-L89

This happens because we mutate the children, so when the child enters it receives `propsForChild` as its own props and later when the same child exits its now own props (received previously from `propsForChild`) override current `propsForChild` thus resulting in stale values received. 

## How to reproduce
Write a simple exit/enter animation with resolved value. Enter the item, remove it - observe the resolver calls.

## Expected behaviour
Current values being passed to resolvers.

**Comment by Andarist** [comment]
I was working on something just before going to bed and i was pretty sure about conclusion i drew when i ve wrtten the issue. Laying now in bed Im not entirely sure if the explanation given by me why this happens is true, for sure there is a bug though. Gonna check this again first thing in the morning

**Comment by InventingWithMonster** [comment]
Ah no I totally get what you're saying. Unless a component is entering, we want to filter any props that were set via `propsForChild` from `child.props`

**Comment by Andarist** [comment]
I would rather suggest caching previous `child.props` or something instead of filtering out, that would have IMHO more natural flow. What we want to do is to add `propsForChild` without affecting memoized `children`

**Comment by InventingWithMonster** [comment]
I think the thing about filtering is that it's already happening so it wouldn't be adding any extra logic or memory. I've put a PR up, have a look and see what you think & if you see any potential issues
