### ISSUE TITLE
Change a posed component's draggable property after it has mounted

### ISSUE THREAD

**Issue by joe-schorn** [Popmotion/popmotion#495]
First of all thank you for this library!

**Is your feature request related to a problem? Please describe.**
I would like to change a posed component’s draggable property based on it’s props. For example, I’m using react pose to build a carousel. But on mobile, draggable posed components prevent scroll. I’d like to add logic to conditionally turn the draggable property on and off if I see movement in the direction that should be draggable. 

**Describe the solution you'd like**
It would be nice if the draggable property accepted a function like other pose props. Something like this: 
```
const DraggableContainer = div.pose({
  draggable: ({draggable}) => draggable
});
```
Which would be used something like this:
```
<DraggableContainer draggable={this.state.draggable} />	
```

**Comment by InventingWithMonster** [comment]
Hey Joe

Yeah I totally see the argument for this. It's something I'll take a look at, but the implementation is a bit more complicated than the API would suggest.

It's also not that declarative if you have to go in and add all the event listeners and force rerenders to enable/disable dragging etc. Do you think something like this would work for you:

```javascript
const DraggableContainer = div.pose({
  draggable: ({ angle, distance }) => distance > 5 && angleIsHorizontal(angle)
});
```

**Comment by Andarist** [comment]
You can make it work now with something like this - https://codesandbox.io/s/5x8ojv758x **IF** @InventingWithMonster releases a new version of popmotion-pose, which has support for `dragBounds` function resolver

**Comment by joe-schorn** [comment]
Thanks @Andarist and @InventingWithMonster for the quick replies. 

@InventingWithMonster. Yes I think that would work. (I'm assuming that's not currently supported). I agree the approach I suggested isn't that declarative. I was trying to work around the problem of the page scroll getting locked up on mobile when dragging is on the 'x' axis but user is scrolling on the 'y'. 

@Andarist the issue I'm facing is I want to disable dragging in certain use cases. If i'm following correctly, what you are suggesting is to dynamically alter the drag bounds. But in that case if i limit the drag bounds the user won't be able to drag, but they also won't be able to scroll the draggable element either.

**Comment by Andarist** [comment]
> @Andarist the issue I'm facing is I want to disable dragging in certain use cases. If i'm following correctly, what you are suggesting is to dynamically alter the drag bounds. But in that case if i limit the drag bounds the user won't be able to drag, but they also won't be able to scroll the draggable element either.

Why scrolling would be disabled?

**Comment by InventingWithMonster** [comment]
We prevent scrolling when something’s dragging. For seething like this you
want to prevent scrolling only when there’s a horizontal drag

**Comment by joe-schorn** [comment]
I should have clarified, it's not the element that needs to be scrollable on the y axis, it's the page. It's primarily a mobile issue. If an element is draggable on the x axis it prevents page scrolling on the y axis.

**Comment by Andarist** [comment]
Gotcha, this is indeed a problem - so would be good to provide some API to account for this case.

**Comment by pavship** [comment]
+1

**Comment by gorhgorh** [comment]
also for this specific use case, only Y need to work maybe it could be setup by default when you restrict drag on a specific direction (i want to drag on X scroll work on Y and vice versa)

**Comment by kocsissandor85** [comment]
+1

**Comment by karibertils** [comment]
+1

**Comment by maximelebreton** [comment]
+1

**Comment by bartlomiejzuber** [comment]
+1

**Comment by Andarist** [comment]
I believe this is possible now with https://www.framer.com/motion/ which is Pose's successor.
