### ISSUE TITLE
Pose-group for Vue?

### ISSUE THREAD

**Issue by therddlr** [Popmotion/popmotion#497]
Hello. I don't see something like `transition-group` in `vue-`pose` documentation. Is it available?

**Comment by InventingWithMonster** [comment]
There’s a pose-transition component but it only currently works for
animating single elements. I’ll probably only be able to revisit this if
Pose for Vue gets some traction or run into more financial funding

**Comment by therddlr** [comment]
After spending whole 24 hours playing around with Popmotion and Vue-Pose I must say, it's f#$@%$g unbelievable. You can count on me in both: good PR and finances, after I bring Pose to my boilerplate in the next few weeks. How do you think is it suitable for production (since as I understand Vue and React both was released only a month ago)? Well, I will test it anyway.

Really, this is unbelievable work you guys are doing. Nothing looks like other animation libs, pure craft.

**Comment by Andarist** [comment]
`react-pose` is actually way older, only the vue support was added recently.

**Comment by ffxsam** [comment]
Another vote for `PoseGroup` for Vue!
