### ISSUE TITLE
Vue-Pose: onPoseComplete on exit?

### ISSUE THREAD

**Issue by thariddler** [Popmotion/popmotion#498]
I need to trigger function on Pose exit complete. Trying this, but it's triggered both: on enter and on exit. 

```js
Shade: posed.div({
      enter: {
        opacity: 1,
        scale: 1,
        beforeChildren: true,
        transition: { duration: 200, ease: 'linear' }
      },
      exit: {
        opacity: 0,
        scale: 0.5,
        afterChildren: true,
        transition: { duration: 200, ease: 'linear' },
        onPoseComplete: () => {
          console.log('complete')
        }
      }
    })
```

**Comment by InventingWithMonster** [comment]
Hmm it’s weird it’s triggered at all to be honest, as onPoseComplete isn’t
a valid prop on the actual pose. It should be passed to the component
itself in the Vue template.

So you’d add it conditionally when you’re removing a component. I haven’t
actually tried this in Vue so I don’t know if it’ll update the components
props if you’re removing an element, I had to release a specific feature
for this in React but Vue works differently with leaving components

**Comment by therddlr** [comment]
On component itself? Like this?

```js
Shade: posed.div({
      enter: {
        opacity: 1,
        scale: 1,
        beforeChildren: true,
        transition: { duration: 200, ease: 'linear' }
      },
      exit: {
        opacity: 0,
        scale: 0.5,
        afterChildren: true,
        transition: { duration: 200, ease: 'linear' }
      },
      onPoseComplete: () => {
        console.log('complete')
      }
    })
```
This way I have an error 

```
Error in mounted hook: "Error: HEY, LISTEN! Pose 'onPoseComplete' is of invalid type. All poses should be objects."
```

Not sure how to use it elsewhere?

**Comment by InventingWithMonster** [comment]
Sorry like

<Shade :onPoseComplete=“yourMethod”

**Comment by therddlr** [comment]
I made a reproduction https://codesandbox.io/s/mymv6ljxkj

**Comment by therddlr** [comment]
Any tips why it's not working? Is it my code or it's a bug?

**Comment by InventingWithMonster** [comment]
I'll need to take a look tomorrow morning. Might be a bug?

**Comment by InventingWithMonster** [comment]
Ah yeah it's this line:

https://github.com/Popmotion/popmotion/blob/master/packages/vue-pose/src/components/pose-transition.ts#L23

We're currently calling the poser.set directly from `pose-transition`, bypassing the logic in `posed` that would usually attach `onPoseComplete` to the returned `Promise`.

In React we accomplish this by setting the new pose via `cloneElement`. I don't know enough about Vue to know if there's something similar. I'll have to dig in further next week

**Comment by InventingWithMonster** [comment]
This approach is a hard limit as a side effect of using Vue's native `transition` component. I don't think it's fixable without porting a version of our own `Transition` from React.

This'd be pretty cool as it'll enable multiple children and FLIP-reordering but I won't get the opportunity for a couple weeks yet.

**Comment by WolfspiritM** [comment]
Is that also the reason why I can't get "applyAtStart" and "applyAtEnd" working?
Maybe you should remove that features from the docs if it's not supported right now?

This sadly makes the usage of this library very limited for vue if there is no way to tell when an animation is done.

**Comment by snowyu** [comment]
Maybe the simplest way is add the `onPoseComplete` event to `PoseTransition`.

**Comment by snowyu** [comment]
I've found the `onPoseComplete` is a prop instead of the event on the `Posed.[element]`. 
And it is not work yet.

https://github.com/Popmotion/popmotion/blob/bbf4e33c9cd61dee0e52a121e395b3f4cadcc74f/packages/vue-pose/src/components/posed.ts#L13-L33

**Comment by snowyu** [comment]
I've got the reason and already fixed it. 

Compliance with the vue specification

* Change `onPoseComplete` prop to the `@poseComplete` vue event.

*Note*: 

* put the `poseComplete` event on `pose-transition` now.
