### ISSUE TITLE
React-pose Error: Pose 'hoverable' is of invalid type. All poses should be objects.

### ISSUE THREAD

**Issue by nevernotsean** [Popmotion/popmotion#499]
react-pose: 3.3.0

When using the example in a project, 'hoverable: true' results in a type error

using the example: from https://codesandbox.io/s/4j4p49vmkx

My Code:
`
const PosedColorBlock = posed.div({
	hoverable: true,
	init: {
		scale: 1,
		boxShadow: '0px 0px 0px rgba(0,0,0,0)'
	},
	hover: {
		scale: 1.2,
		boxShadow: '0px 5px 10px rgba(0,0,0,0.2)'
	}
});
`

**Comment by InventingWithMonster** [comment]
Hey man, I'll need to see a reproducible version of this error because
using your code in that sandbox seems to work fine with 3.3.0

**Comment by nevernotsean** [comment]
I can't seem to re-create in an isolated instance. I'll keep checking my code and reopen if I find anything.
