### ISSUE TITLE
React Native <Transition />: cannot read property 'key' of null

### ISSUE THREAD

**Issue by kevinwolfcr** [Popmotion/popmotion#504]
## Ensure you're using the latest version
```
{
  "dependencies": {
    "@emotion/native": "9.2.9",
    "react-native-pose": "0.8.0"
  }
}
```

## Add the package name to bug title
`react-native-pose`

## Describe the bug
When I try to create a [switching visibility](https://popmotion.io/pose/api/native-transition/#{{0}}-usage-switching-visibility) pose, it throws an error: `Cannot read property 'key' of null`.

## How to reproduce
1. Follow the [switching visibility](https://popmotion.io/pose/api/native-transition/#{{0}}-usage-switching-visibility) guide on the docs.

## Expected behaviour
To not throw error 😅

## Link to CodePen example (or similar)
https://snack.expo.io/@kevinwolf/popmotion-issue

## Device information
Expo Snack and local react native app.

**Comment by InventingWithMonster** [comment]
If you want to get going for now this might just be a bug in
posed(Component) syntax rather than posed.View so you could try posed.View
until I can take a look at this

**Comment by Andarist** [comment]
Isnt this just caused by not filtering out falsy children in RN here:
https://github.com/Popmotion/popmotion/blob/009e777b90100c08e9dae16564babae14682eb2f/packages/react-pose-core/src/components/Transition/children.ts#L34

Like you do for DOM here:
https://github.com/Popmotion/popmotion/blob/009e777b90100c08e9dae16564babae14682eb2f/packages/react-pose/src/components/Transition/index.tsx#L22

**Comment by InventingWithMonster** [comment]
Should be fixed in the latest `react-pose-core` - you'll need to refresh you dependencies.

**Comment by kevinwolfcr** [comment]
@InventingWithMonster created PR #510 upgrading the version on `react-native-pose`. Otherwise it won't work as it is not listed on `peerDependencies`.

**Comment by InventingWithMonster** [comment]
Thanks man

**Comment by InventingWithMonster** [comment]
`react-native-pose@0.4.1`

**Comment by darkowic** [comment]
I am having the same issue with newest `react-pose` package (3.3.6) for web. Rolling back to 3.3.0 solves the problem

**Comment by Andarist** [comment]
@darkowic could u prepare a simple codesandbox reproducing the error? would help fixing this sooner

**Comment by Andarist** [comment]
Do you maybe pass i.e. undefined as key?
