### ISSUE TITLE
Link in documentation leads to dead page

### ISSUE THREAD

**Issue by christiankaindl** [Popmotion/popmotion#505]
On the API docs page for [Pointer](https://popmotion.io/api/pointer/), there is a link titled `deltaOffset` that leads to a dead url: https://popmotion.io/api/delta-pointer

Does DeltaPointer still exist? Or was it removed from Popmotion?

Here's the snippet on the Pointer page:
> To apply the change in pointer movement to, for instance, a slider, you can use the `deltaOffset` action.

**Comment by InventingWithMonster** [comment]
Thanks for the heads-up! I'll remove this reference. The rest of the paragraph is accurate - to perform relative motion you pass the initial point to `pointer`
