### ISSUE TITLE
Exit event not firing

### ISSUE THREAD

**Issue by nkov** [Popmotion/popmotion#507]
Version 3.3.3

## Description
Exit animations for child components are not being fired. Instead, it jumps directly to the exit state.

![](https://i.gyazo.com/5d6539caddaf308c2045349316bc927e.gif)

## Link to CodePen example (or similar)
https://codesandbox.io/s/r7ovv5vo7p

## Device information
Chrome 68 on OSX

## Additional context
In my project, the exit animation for the children shows once (the first time), after that, it jumps directly to the end. However, in the codepen it doesn't happen even the first time. I am new to this library and following [this example](https://popmotion.io/pose/learn/route-transitions-react-router/) so it's entirely possible I'm doing something wrong. Setting `duration` or `delay` doesn't seem to help.

**Comment by InventingWithMonster** [comment]
You're creating all the posed components every time a the component renders. This is both expensive and prevents the component from remembering its previous position.

Could you try moving any code like this:

```javascript
const Component = posed.whatever()
```

Outside `render` or functional components and let me know how you get on?

**Comment by nkov** [comment]
Great! That makes sense and works almost perfectly. The reason I say almost is because still when using `<Redirect />` it seems to jump. I made a small example [in this fiddle](https://codesandbox.io/s/v81qn16n6l). Are there are any best practices for this approach?

On a related note, is there a way to prevent the enter or exit animations firing in certain cases? My current idea is to replace the animated object with a different or non-animated one.
