### ISSUE TITLE
[react-pose] Manually register children of PoseGroup

### ISSUE THREAD

**Issue by jgoux** [Popmotion/popmotion#517]
Hello,

I'm trying to make react-pose to work with react-tunnels, but I'm hitting a wall right now.
I use [react-tunnels](https://github.com/javivelasco/react-tunnels) to inject components in specific part of my Layout, and I'd like to animate some of these parts by wrapping them inside `<PoseGroup/>` (so I can declare different animations per screen).

Right now I do this in my Layout : 
```jsx
<Layout>
<PoseGroup>
  <TunnelPlaceholder id="Layout.Main" />
</PoseGroup>
</Layout>
```

And somewhere else down the tree when I define a new screen, I inject a posed element : 
```jsx
const Animated = posed.div({ enter: { opacity: 1 }, exit: { opacity: 0 } })
```
```jsx
<Tunnel id="Layout.Main">
  <Animated key="one-page">I am animated</Animated>
</Tunnel>
```

I think the issue is that the posed element isn't a direct child of <PoseGroup>, so it isn't registered / detected by it.
Is there any solution to this, like registering children manually? Or maybe `<PoseGroup>`  isn't the solution here?

I didn't want to go with a posed container like the react-router tutorial because I want to define per screen animations, not the same global transition.

EDIT : I've made a codesandbox example of what I'd like to achieve : https://codesandbox.io/s/m4nyjpmp99

**Comment by jgoux** [comment]
Sorry for the double post.

In fact thanks to this : https://github.com/javivelasco/react-tunnels/pull/9#issue-189184034 I was able to define `PoseGroup` as the `TunnelPlaceholder`!

It now works! 🎊 

I updated the example : https://codesandbox.io/s/m4nyjpmp99

**Comment by InventingWithMonster** [comment]
Thats very cool and thanks for updating the demo for people to reference

**Comment by jgoux** [comment]
@InventingWithMonster Actually I think I'll need a way to register children explicitly.

I have this component : 
```jsx
export const mkAnimatedTransitionAwareTunnel = (
  id,
  defaultPoseProps = { from: {}, enter: {}, leave: {} }
) =>
  withRouter(props => (
    <Tunnel id={id}>
      <AnimatedTransitionAware
        defaultPoseProps={defaultPoseProps}
        key={`${id}@${props.location.key}`}
        {...props}
      />
    </Tunnel>
  ))
```

`AnimatedTransitionAware` is an intermediate layer between my `posed.div` and the `Tunnel`. React-pose doesn't complain as I define an explicit key on it, but the `posed.div` component within isn't removed on unmount.

```jsx
class _AnimatedTransitionAware extends React.Component {
  componentDidUpdate() {
    if (this.props.nextLocation) {
      this.props.release()
    }
  }
  render() {
    const {
      // mkAnimatedTransitionAwareTunnel props
      defaultPoseProps,
      // withRouter props
      match,
      location,
      history,
      // withRouteTransition props
      previousLocation,
      nextLocation,
      release,
      // Tunnel props
      from,
      enter,
      leave,
      children,
      // Remaining props are from react-pose injection
      ...props
    } = this.props
    let poseProps = merge(defaultPoseProps, { from, enter, leave })
    if (pathEq('state.transition', 'POP')(location)) {
      poseProps = { ...poseProps, from: poseProps.leave }
    }
    if (pathEq('state.transition', 'POP')(nextLocation)) {
      poseProps = { ...poseProps, leave: poseProps.from }
    }
    const Animation = posed.div(poseProps)
    return <Animation {...props}>{children}</Animation>
  }
}

const AnimatedTransitionAware = withRouteTransition(_AnimatedTransitionAware)
```

How could I register the final posed `<Animation/>` as a child of the parent `<PoseGroup/>`?

**Comment by jgoux** [comment]
Thanks to @Andarist advice, I made it work by defining my animation like this
```jsx
const lateral = {
  from: {
    x: ({ reverseEntry }) => (reverseEntry ? -100 : 100),
    opacity: 0,
    transition: {
      duration: 500
    }
  },
  enter: {
    x: 0,
    opacity: 1,
    transition: {
      duration: 500
    }
  },
  leave: {
    x: ({ reverseExit }) => (reverseExit ? 100 : -100),
    opacity: 0,
    transition: {
      duration: 500
    }
  }
}

class _AnimatedTransitionAware extends React.Component {
  componentDidUpdate() {
    if (this.props.nextLocation) {
      this.props.release()
    }
  }
  render() {
    const {
      // mkAnimatedTransitionAwareTunnel props
      id,
      defaultPoseProps,
      // withRouter props
      match,
      location,
      // withRouteTransition props
      nextLocation,
      // Tunnel props
      from,
      enter,
      leave,
      children
    } = this.props
    let poseProps = merge(defaultPoseProps, { from, enter, leave })
    // if (!previousLocation) {
    //   poseProps = { ...poseProps, from: {} }
    // }

    // initial render : entry calculation
    if (nextLocation === null && pathEq('state.transition', 'POP')(location)) {
      poseProps = { ...poseProps, reverseEntry: true }
    }
    // second render : exit calculation
    else if (pathEq('state.transition', 'POP')(nextLocation)) {
      poseProps = { ...poseProps, reverseExit: true }
    }
    return (
      <Tunnel id={id}>
        <Animation key={`${id}@${match.url}`} {...poseProps}>
          {children}
        </Animation>
      </Tunnel>
    )
  }
}
```

And a picture to illustrate where I'm getting at : 
![transition](https://user-images.githubusercontent.com/1443499/46670992-e7112a80-cbd3-11e8-8880-8d373a44ef73.gif)

Thanks again for the help and this awesome library! 🌟 🎊
