### ISSUE TITLE
Dependency ajv

### ISSUE THREAD

**Issue by port513** [Popmotion/popmotion#520]
When installing react-pose with npm install react-pose I get an error that tells me that dependency for ajv is missing. Why isn't the package including this if it needs this?

I tested on at least 3 different node.js setups and they all give me the same error

Easy fix to just install ajv manually but... it should really request this when installing right?

**Comment by InventingWithMonster** [comment]
I don’t even know what ajv is. It could be a dependency of a dependency and
they’re missing the include. I’ll take a look

**Comment by InventingWithMonster** [comment]
Could you copy-paste the full error please?
