### ISSUE TITLE
/lib not be compiled in publishing @ 8.4 

### ISSUE THREAD

**Issue by morlay** [Popmotion/popmotion#523]
![image](https://user-images.githubusercontent.com/1667873/46002129-c6c77300-c0df-11e8-804f-e9c22b09e566.png)
![image](https://user-images.githubusercontent.com/1667873/46002170-e8285f00-c0df-11e8-9f0e-6bcbe5a98c6a.png)

**Comment by Andarist** [comment]
Not sure what do u mean, the first screen shows the file from `lib` directory and it's very much compiled.

**Comment by InventingWithMonster** [comment]
I think the difference is its using the old framesync syntax. In `lib` all
the code is actually contained in `index.js`. Everything else is cruft that
shouldn't have been published, I've cleared my `lib` directory so in the
next release this will be gone.

**Comment by morlay** [comment]
@Andarist
Sorry. It is mean lib folder contains older version, and the api of `framesync` is incompatible.

@InventingWithMonster 
It is fine to remove lib folder. but should expose full types.
I need the type `TweenProps`, which is not exposed by `popmotion`, so I have to use `popmotion/lib/animations/tween/types` for it (and I can't use `popmotion/src/animations/tween/types` instead, with different tsconfig in my project, and it will show errors for using `popmotion/src/animations/tween/types`).

**Comment by InventingWithMonster** [comment]
Ah I see, thanks for letting me know. I’ll ensure option types are exported
via the main package
