### ISSUE TITLE
react-pose: Typescript | Cannot find name 'ReactElement'.

### ISSUE THREAD

**Issue by poniraq** [Popmotion/popmotion#526]
## Describe the bug
Newest 3.3.5 version of react-pose fails to compile. Build fails with this error:
```
.../node_modules/react-pose/lib/components/Transition/types.d.ts
(20,24): Cannot find name 'ReactElement'.
```

## How to reproduce
1. Setup react project with typescript
2. Add react-pose@3.3.5 package
3. Create any posed element & try to render it
4. Build fails

## Expected behaviour
Successful build.

## Additional context
There is a typo in `components/Transition/types.ts` file:

```typescript
export declare type State = {
    displayedChildren: Array<React.ReactElement<any>>;
    finishedLeaving: {
        [key: string]: boolean;
    };
    hasInitialized: boolean;
    indexedChildren: {
        [key: string]: ReactElement<any>; // <-- should be React.ReactElement<any>
    };
    scheduleChildRemoval: (key: string) => void;
};

```

**Comment by poniraq** [comment]
fix PR: https://github.com/Popmotion/popmotion/pull/527

**Comment by InventingWithMonster** [comment]
`3.3.6`
