### ISSUE TITLE
react-pose: Using NavLink in conjunction with posed causes activeClassName to break

### ISSUE THREAD

**Issue by aamirkhan-91** [Popmotion/popmotion#539]
## Description of Bug
While playing around with `pose` and `PoseGroup` I ran into what seems like a bug: When using `react-pose` in conjunction with `react-router-dom`'s [`<NavLink>`](https://reacttraining.com/react-router/web/api/NavLink), the [`activeClassName`](https://reacttraining.com/react-router/web/api/NavLink/activeclassname-string) prop, that attaches a specified class name to the `NavLink` that corresponds to the currently active route doesn't seem to work. It seems like the class is attached on the first render but isn't changed in subsequent renders, despite the route being changed. This results in the wrong `NavLink` being attached with the `active` class.

## Link to CodeSandbox example 
https://codesandbox.io/s/kkp3q73k9v

In the CodeSandbox example linked above I have created two `Sidebar` components, one with `posed` and one without. Both are laid out side by side in the layout. The `Sidebar` on the left animates in using`<PoseGroup>` and highlights the `NavLink` corresponding to the `/` path. Changing the route by clicking on the `NavLink`s in either of the Sidebars you will note that the highlighted NavLink changes on the right Sidebar (non pose), and not on the left.

## Expected behaviour
NavLink should be updated with the correct class corresponding to the currently active route.

## Device information
 - OS: Mac OS
 - Browser: Chrome

**Comment by Andarist** [comment]
This is caused by the fact that posed elements are extending `PureComponent`. I'm not a react-router user but from what I see only the toplevel `Router` listens to history changes in 4.3.1, it sets state - but it doesnt get propagated through PureComponent boundary. This should be a common react-router problem so I believe the workaround is known - you will have to find it yourself though (or maybe you already know it).

From what I see there is available v4.4.0-beta.1 version which should fix it by using React's new context API.

**Comment by aamirkhan-91** [comment]
@Andarist  [I did find a workaround](https://codesandbox.io/s/rmwwrovpym), but tbh I am not sure why it works: [From the documentation for `PureComponent`]
> Furthermore, React.PureComponent’s shouldComponentUpdate() skips prop updates for the whole component subtree. Make sure all the children components are also “pure”.

I am not sure why passing the actual `<NavLink>` as a child works. Shouldn't prop checking for this also be skipped if the Posed `div` is a PureComponent?

**Comment by Andarist** [comment]
NavLink is an impure child so it invalidated PureComponent's shouldComponentUpdate altogether. And thus the history change can "propagate" to its PosedLinks' children.

In your current example `withRouter` is not needed, it works without it.

**Comment by aamirkhan-91** [comment]
Thanks @Andarist, that makes sense.
