### ISSUE TITLE
react-pose: onPoseComplete on a deeper nested posed component within a PoseGroup is not working

### ISSUE THREAD

**Issue by JoostKiens** [Popmotion/popmotion#544]
## Describe the bug
The `onPoseComplete`-callback is not triggered with the following conditions:

- There's a `PoseGroup` container
- A direct child is a posed component
- This child renders another posed component with a `onPoseComplete`-callback. This callback is never called.

```js
<PoseGroup animateOnMount>
  <Foo onPoseComplete={logSuccess} key="2">
    I'm a direct child and my onPoseComplete is triggered
  </Foo>

  <FooContainer key="1">
    <Foo onPoseComplete={logFailure}>
      I'm nested, and this one doesn't work
    </Foo>
  </FooContainer>
</PoseGroup>
```

## How to reproduce
go to https://codesandbox.io/s/km3k7qp68o and run it. There should be two log messages, however there's only one message.

## Device information
Latest Chrome

**Comment by Andarist** [comment]
The issue is actually different - `onPoseComplete` doesn't fire for any nested elements. Repro -https://codesandbox.io/s/xzxk44jrww .

react-pose knows how to chain pose propagation through context, so you can orchestrate animation of multiple elements and it fires `onPoseComplete` only on the ancestor which changes the actual pose.

I believe your expectation is correct though, this should fire for nested elements. WDYT @InventingWithMonster ?

Could you also describe your use case?

**Comment by JoostKiens** [comment]
Hi @Andarist thanks for your reply!

My situation is the following:

I have two components, an SVG and a div, which I want to animate sequentially on mount, on unmount they should animate in reverse. See a simplified use case below.

```jsx
const Line = posed.path({
  exit : { d: 'M0 0 L 0 0' },
  enter: { d: 'M0 0 L 100 100' }
})

const Text = posed.div({
  enter: { opacity: 1 },
  exit: { opacity: 0 }
})

const Container = posed.div()

class Main extends React.Component {
  state = { isOpen: false }

  render() {
    return (
      <div 
        style={{ width: 500, height: 500, border: '1px solid hotpink' }}
        onClick={_ => this.setState({ isOpen: !this.state.isOpen })}
      >
        <PoseGroup>
          {this.state.isOpen && (
            <Container key='container'>
              <svg width={500} height={400}>
                <Line stroke='black' />
              </svg>
              <Text>Foo</Text>
            </Container>
          )}
        </PoseGroup>
      </div>
    )
  }
}
```
 
What would be the best way to accomplish this?

**Comment by InventingWithMonster** [comment]
In this instance you could try using the staggerChildren and
staggerDirection config options for enter and exit poses in Container,
which would give you control over the execution over the Line and Text poses

For example

posed.div({
enter: { staggerChildren: 200 },
exit: { staggerChildtrn: 200, staggerDirection: -1 }
})

Adjusting times as needed

**Comment by JoostKiens** [comment]
Right, obviously actually. Thanks!
