### ISSUE TITLE
Support for <main>

### ISSUE THREAD

**Issue by penumbra1** [Popmotion/popmotion#546]
**Is your feature request related to a problem? Please describe.**
I was following this [tutorial](https://popmotion.io/pose/learn/route-transitions-reach-router/) in Gatsby and used the \<main\> element as route wrapper: `posed.main(...)`. This produced an error: `Uncaught TypeError: react_pose__WEBPACK_IMPORTED_MODULE_2__.default.main is not a function`. I saw [here](https://github.com/Popmotion/popmotion/blob/master/packages/react-pose/src/utils/supported-elements.ts) that main is not supported.

I tried creating a custom component that renders \<main\> and making it posed. It kinda worked, but then it didn't: I couldn't get the components to exit without breaking the layout (I guess position: absolute wasn't applied on route change).

I thought I was being stupid and spent a day trying to fix the layout and transitions, but then I changed the route container to div, and everything worked great. I guess it would be helpful to list or link to the supported elements in the docs as it would save all the \<main\> lovers a few hours. Right now the [docs ](https://popmotion.io/pose/api/posed/#posed-props-%E2%80%A6props) claim all HTML elements are supported, and I believed them:)

**Describe the solution you'd like**
It'd be nice if \<main\> was supported. I had no trouble using other semantic elements like article and section, and they allow to write lean and accessible HTML.

**Describe alternatives you've considered**
Of course, it's easy to wrap \<main\> around a posed div or anything else, but in my case of route transitions, it would be an extra wrapper with no meaning just to contain the page. The spec [says ](https://html.spec.whatwg.org/multipage/grouping-content.html#the-div-element) semantic elements are preferable.

P.S. Thanks a lot for Pose, it's awesome!

**Comment by klaasman** [comment]
Feel free to create a pull-request! In the meantime you could use this as a workaround;

```jsx
const Main = posed(({ hostRef, innerRef, ...props }) => <main ref={hostRef} {...props} />)({
  // your pose config
});
```

**Comment by Andarist** [comment]
Worth using the same list as styled-components & emotion - https://github.com/emotion-js/emotion/blob/ccc992c3a630ab7a301f96e342adf51a50629a5c/packages/styled/src/tags.js . Would be good to make a package out of it - but is out of scope of this particular issue. I'll try to create such package later when I have time.

IMHO as optimization it would be good to revive my idea of popmotion's babel plugin, cc @InventingWithMonster . As mentioned back then - I'm willing to take care of its development, maintenance and any issues related to it.

**Comment by Andarist** [comment]
Also, you should be able to do just that:
```js
const Main = posed('main')({
  // ... pose config
})
```

**Comment by alandraper** [comment]
Hrm. Typescript doesn't like that. 
```
const Main = posed('main')({
// ... pose config
})
```
> Argument of type '"main"' is not assignable to parameter of type 'ComponentType<unknown>'.

Any ideas?

**Comment by alandraper** [comment]
Just want to say I was pissed off when I read this, then I bit the bullet and migrated from Pose to Motion, and it worked great... even fixed some of the bugs I had. Thanks for your hard work.
