### ISSUE TITLE
[react-pose] Posed element config is hoisted

### ISSUE THREAD

**Issue by jgoux** [Popmotion/popmotion#550]
Hello,

I wanted to take advantage of the fact that we can initialize a posed element using the props : 

```jsx
const Animation = posed.div(({ from, enter, leave }) => ({
  from,
  enter,
  leave
}))
```

But now everytime I use my `Animation` element (multiple `Animation` per screen), they all have the same animations, even if I pass different props to them.

Here is a log (key + props) of what I pass to each of my `Animation` : 
![image](https://user-images.githubusercontent.com/1443499/46682055-dfaa4b00-cbec-11e8-91ed-107d19291ed3.png)

You can see that Layout.FAB have a different animation than the two others, but when I transition everything is animated the same way (it seems to pick the props from the first rendered `Animation`).

I'd expect `Animation` to work like a class, and being instantiated only when I call `<Animation/>`.

**EDIT** : Seems like the `config` is hoisted : https://github.com/Popmotion/popmotion/blob/master/packages/react-pose/src/posed.tsx#L31

Is it necessary? Can we avoid the hoisting when using a function?

**Comment by Andarist** [comment]
Sorry for this - it seems to be my fault as I have introduced this config hoisting. I believe it's still possible (& desirable) to cache this, it just has to be done in different way - per instance.

**Comment by Andarist** [comment]
Just a quick draft of proper caching:
```js
const instanceCache = new WeakMap();

const createComponentFactory = (key: string | React.ComponentType) => {
  const componentFactory: ComponentFactory<any> = (poseConfig = {}) => {
    const instanceRender = (inputProps) => {
      if (!instanceCache.has(instanceRender)) {
        const { withParent = true, ...props } = inputProps;
        const config = (typeof poseConfig === 'function' ? poseConfig(props) : poseConfig);

        const noParentRender = ({ withParent = true, ...props }) => (
          <PoseElement poseConfig={config} elementType={key} {...props} />
        )

        const withParentRender = ({ withParent = true, ...props }) => (
          <PoseParentContext.Consumer>
            {(parentCtx: PoseContextProps) => (
              <PoseElement
                poseConfig={config}
                elementType={key}
                {...props}
                {...parentCtx}
              />
            )}
          </PoseParentContext.Consumer>
        );
        
        instanceCache.set(
          !withParent || props.parentValues
            ? noParentRender
            : withParentRender
        )
      }

      return instanceCache.get(instanceRender)(inputProps)
    };

    return instanceRender;
  };

  componentCache.set(key, componentFactory);

  return componentFactory;
};
```

PS. I have not tested this code at all yet.

**Comment by Andarist** [comment]
Hah, no - there is no reason 😅 was responding back to you late and was too focused on fixing the current code (with function component) than realizing this is easier. 

I would still be for caching render because I don't think switching between `withParent=true` & `withParent=false` is supported and might lead to some weird cases. Or is it supposed to work? And just unmount old node & mount new one?

**Comment by InventingWithMonster** [comment]
Yeah that isn’t supported, I should make a note in the docs

**Comment by Andarist** [comment]
We can also either cache the render function to make such update impossible, but maybe that's an overkill, or add a development warning that this is not supported.
