### ISSUE TITLE
react-pose: shouldn’t always return to init after hover

### ISSUE THREAD

**Issue by emilbruckner** [Popmotion/popmotion#552]
## Describe the bug
When a component leaves the hover state / pose, it returns to the state it was in before it was hovered, instead of returning to `props.pose`. Thus, if the pose is changed while hovering (for example by clicking), it goes to the wrong pose when hovering ends.

If I understand this correctly:
> This also means that when both drag and hover states are removed, the value reverts to whichever pose it was in previously. In this case, that’s the new special 'init' pose (which does what it says on the tin). – [Introducing Pose 3.0](https://popmotion.io/blog/20180820-introducing-pose-3/)

this behaviour might actually be expected?

## Link to CodePen example (or similar)
https://codesandbox.io/s/rmp9mkjyw4
(It’s the Medium-style image zoom example + a hover pose & `hoverable: true`)

## How to reproduce
How to reproduce unexpected behaviour in example:
1) Click image
2) stop hovering it (leave the image). 
3) Instead of returning to the `zoom` pose, it goes to `init`. I’d expect, or at least want it to go *back* into `zoom` state.

## Expected behaviour
I’d expect the pose to return to `zoom` state when its props says so and it’s not being hovered.

## Solutions
Maybe I just don’t get how react-pose works. Maybe there is a solution to this problem.

### What I tried
I tried bypassing this problem by dynamically setting the hoverEnd like so:

```js
hoverEnd: {
    position: ({isOpen, ...rest}) => isOpen ? 'static' : 'absolute'
}
```
but hoverEnd seems not to be calculated dynamically, as `rest.value.raw.props.value` doesn’t update. Maybe that’s a bug? 

## Device information
In which environment are you reproducing the bug?
 - OS: macOS 10.13.2
 - Browser chrome
 - Version 69

Thanks in advance!

**Comment by InventingWithMonster** [comment]
Position can’t be animated so you could try setting it via appyAtStart or
applyOnEnd

Otherwise I think this is a bug. If the pose is changed while the component
has a hover state, it should count as the “previous” pose. I’ll have to
look into why this might not be the case.

**Comment by emilbruckner** [comment]
@InventingWithMonster Thanks, but it still seems buggy.
Just for the record, it’s applyAtStart & applyAtEnd.

I made another example which is a little closer to what I’m doing:
https://codesandbox.io/s/o7jwyr3mx6
Same thing again:
1) hover `click me` → goes to hover state
2) click `click me` → goes to clicked state
3) leave `click me` → goes to init, but would expect clicked state

Another bug I noticed in the example (if you confirm this, I can open another issue?):
If you hover `click me` and leave it before the animation finishes, it scalesY to > 4 for a moment
