### ISSUE TITLE
React-Pose: PoseGroup Animations running on render/update instead of mount

### ISSUE THREAD

**Issue by mradambeck** [Popmotion/popmotion#553]
While using the PoseGroup in React 16.4.2, I'm finding that my animations are running every time the component updates and re-renders, instead of upon mount. I'm simply using the `enter` and `exit` attributes on my `posed` components, and they are replaying the animation every time the component updates instead of when it mounts.

**Comment by InventingWithMonster** [comment]
Can you show us a code example? I suspect the posed component is being
reinitialised

**Comment by mradambeck** [comment]
Yeah, figured it out, I was calling the animations in the render function, my bad, closing this out.
