### ISSUE TITLE
[react-pose] Poses config update API

### ISSUE THREAD

**Issue by jgoux** [Popmotion/popmotion#554]
Hello,

I want to open an explicit issue about this https://github.com/Popmotion/popmotion/issues/451#issuecomment-428165273

My specific use case is web app page transitions. I'd like to be able to redefine the poses I initialized on a component later in time.

Right now I can do it using this : 
```jsx
const lateral = {
  from: {
    x: ({ reverseEntry }) => (reverseEntry ? -100 : 100),
    opacity: 0,
    transition: {
      duration: 500
    }
  },
  enter: {
    x: 0,
    opacity: 1,
    transition: {
      duration: 500
    }
  },
  leave: {
    x: ({ reverseExit }) => (reverseExit ? 100 : -100),
    opacity: 0,
    transition: {
      duration: 500
    }
  }
}
```

But it's not very practical and I can't define a whole new animation, for example I'd like to change the `leave` pose here to something much different, which doesn't involve the same animation attributes at all.

Would it be possible to take inspiration from React's `setState` here?

As I see it, posed configs are very similar to an initial state.

What if we could redefine each of the poses using the component's props?

### Example

All the poses are accessible through Animation's props at `from`, `enter`, and `leave`
Or maybe a `poses={{ from, enter, leave }}` prop, I don't know what's best for typing
```jsx
const initialPoses = { from: {}, enter: {}, leave: {} }
const Animation = posed.div(initialPoses)
```
Later, once Animation is instanciated, I want to redefine the `leave` pose
I can pass either an object which will replace the whole config for "leave"
```jsx
<Animation leave={{ y: 100, opacity: 0 }} {...props} />
```
Or I could also pass a function to access the current pose config
```jsx
<Animation leave={pose => ({ ...pose, x: props.reverse ? pose.x * -1 : pose.x })} {...props} />
```

**Comment by jgoux** [comment]
Any thoughts on this @Andarist @InventingWithMonster ?

**Comment by InventingWithMonster** [comment]
I do like it but I think it'd need thinking through. It'd certainly require a significant amount of refactoring and rethinking of several core assumptions that we make in the library.

I think 

```javascript
posed.div({
  leave: props => ({})
})
```

is the closest we'll get to this kind of API (ie no dynamically adding/removing poses after creation, but being able to return different poses of that name based on props)

**Comment by jgoux** [comment]
> I think
> 
> ```js
> posed.div({
>   leave: props => ({})
> })
> ```
> 
> is the closest we'll get to this kind of API (ie no dynamically adding/removing poses after creation, but being able to return different poses of that name based on props)

This is all I want, I don't see any use cases for adding/removing poses dynamically. If poses are like a state machine I assume it wouldn't work so well. 😄
