### ISSUE TITLE
react-pose: flip scales incorrectly

### ISSUE THREAD

**Issue by emilbruckner** [Popmotion/popmotion#555]
As in [this example](https://codesandbox.io/s/ov5ql9jqmz), an animation with `flip: true` might scale too much when the state changed before the animation is finished.

**Reproduce in example:** 
1) hover box
2) leave before animation finishes

I already pointed this out in #552, where, as in this example, scaleY takes on a too high value if the box is left (hovering is stopped) before the animation finishes.

**Edit:** I also just noticed that the box won’t go back to its init state, which might be related.

**Comment by Andarist** [comment]
I think this is caused somehow by mixing flip & non-flip transition, I'll continue debugging this later but for now I've discovered another bug when trying to use flip for both poses (https://github.com/Popmotion/popmotion/issues/562)

**Comment by Andarist** [comment]
This is a log of what gets applied to the DOM
```
poser set hover
;height:120.98686419555682px
;height:130.5544444399836px
;height:139.5047901155842px
;height:147.8379012222336px
;height:155.5537777599964px
;height:162.6524197288727px
;height:169.13382712890555px
;height:180.24493822221677px
;height:184.8746419155426px
;height:188.8871110400077px
poser unset hover
;height:100px
;transform-origin:0% 0% 0;transform:scaleY(1.88875) translateZ(0)
poser set hoverEnd
;height:195.060345582218px;transform:scaleY(1.6600440837082795) translateZ(0)
;height:198.7646418488907px;transform:scaleY(1.3045551956706625) translateZ(0)
;height:199.99999984px;transform:scaleY(1.0626847262474437) translateZ(0)
;height:200px;transform:scaleY(0.960365097580236) translateZ(0)
;transform:scaleY(0.945570789186234) translateZ(0)
;transform:scaleY(0.9644049879910856) translateZ(0)
;transform:scaleY(0.9856002448526077) translateZ(0)
;transform:scaleY(0.9931828430627141) translateZ(0)
;transform:scaleY(0.9984024675137654) translateZ(0)
;transform:scaleY(1.0030773274677414) translateZ(0)
;transform:;transform: none
```

We can see that `height` is still getting animated (it's not interrupted by the corresponding flip property - `scaleY`) when we transition from `hover` to `init`.

Those things are hard to debug but I feel confident now to come to conclusion that this is caused by not calling stop on height's animating value when we start to animate scaleY in the reverse direction.

Is mixing flip/non-flip supported @InventingWithMonster ?
