### ISSUE TITLE
react-pose-text change renderChars to render span

### ISSUE THREAD

**Issue by soiluong** [Popmotion/popmotion#556]
In react-pose-text `renderChars()` class method renders a `<div style="inline-block">` for each character. Can I change this to `<span>` because it is natively `inline` and it is good for html semantics?

**Comment by InventingWithMonster** [comment]
Hey man 

I can't remember why I settled on `div`. There is a reason, some browser quirk that couldn't be fixed with CSS alone. 

The element needs to be explicitly set to `inline-block` as `inline` elements can't be transformed. I was surprised too.
