### ISSUE TITLE
`stop` callback

### ISSUE THREAD

**Issue by aprilmintacpineda** [Popmotion/popmotion#558]
**Is your feature request related to a problem? Please describe.**

I want to detect when a particular animation has been stopped via `myAnimation.stop()`. Because when we loop `Infinity` I'm assuming that we would have to stop that animation ourselves for the script to stop executing. I also want to run some codes after an animation has been stopped.

**Describe the solution you'd like**

Something like `complete`, but instead it's called when the `stop` is called.

Example:

```js
const myAnimation = tween({
  from: 0,
  to: 100,
  duration: 30000,
  loop: Infinity
}).start({
  update: v => {
    announcementStyler.set({
      x: `${-v}%`
    });
  },
  stop: () => {
    // animation stopped
  }
})
```
-------> User action -----> `myAnimation.stop()`.

**Comment by Andarist** [comment]
if you call the stop method u can just call a function (callback) right after you call the stop method

**Comment by InventingWithMonster** [comment]
Yeah 👆 this. I’ve tried to keep the callbacks as functions that fire
passively. So there’s no onStart either, for instance

**Comment by sprlwrksAprilmintacpineda** [comment]
So what's the difference between stop and complete?

**Comment by aprilmintacpineda** [comment]
Oh well, I guess I'm just going to pass reference around.
