### ISSUE TITLE
Popmotion: Runs slow on mobile devices

### ISSUE THREAD

**Issue by aprilmintacpineda** [Popmotion/popmotion#559]
## Ensure you're using the latest version
CodeSandbox examples might not always be using the latest version of Pose.

## Add the package name to bug title
For instance, if this is a bug in Popmotion, write "Popmotion: Name of bug"

## How to reproduce

Run on mobile device.

## Expected behaviour

Should still run smoothly.

## Link to CodePen example (or similar)

None.

## Device information
In which environment are you reproducing the bug?
 - Device: Oppo X9009, 4GB ram, Octa core, Android 5.1
 - OS: ColorOS v3
 - Browser: Native wrapper, Chrome@latest, Firefox@latest

- Popmotion@8.4.1

**Comment by InventingWithMonster** [comment]
Can I take a look at the code you're using to animate?

**Comment by nkov** [comment]
We had an issue like this and it was due to redux logging being enabled in production.

**Comment by aprilmintacpineda** [comment]
Never mind. I ended up converting all animations using CSS and they all ran smoothly.
