### ISSUE TITLE
[question] flip implementation

### ISSUE THREAD

**Issue by Andarist** [Popmotion/popmotion#561]
1. This line caught my eye:
https://github.com/Popmotion/popmotion/blob/879e6f0300933947fd6de8ef24403697460a2934/packages/popmotion-pose/src/dom/flip.ts#L88

You call `elementStyler.set(propsToSet).render();` where `.set` leads to this line:
https://github.com/Popmotion/popmotion/blob/879e6f0300933947fd6de8ef24403697460a2934/packages/stylefire/src/styler/index.ts#L25

Which schedules `render` callback but the `.render` is also called immediately after `.set` gets called. 

So it seems to me that `render` is called twice here. Is this intentional? Or am I missing something?

2. also when flipping should `height` be animated using `scaleY`?

**Comment by InventingWithMonster** [comment]
Yeah it’s intentional. The render function is exposed to allow developers
to force a render early. In this instance we’re forcing a render to allow
measuring of the element in its updated state - the two measurements are
then used to calculate the inverted transform

**Comment by Andarist** [comment]
I get why we need to call render and the thing about 2 measurements, but Im wondering why do we call render here 2 times, I understand why we have this sync render call right after set, but in this case the scheduled async render (in setValue) seems to be unnecessary.

Also what about:
> also when flipping should height be animated using scaleY?

And as you are responding to my questions I'd like to ask one more 😉 I'm debugging a community filed issue now (#555) and I'm not fully done yet, but maybe you could point me to the place in the code where "magic" `init` pose should be set when "reversing" the UI events - from what I understand the animation should be automatically reversed to the init pose if explicit end pose is not defined.

**Comment by InventingWithMonster** [comment]
If the renders been flushed manually and nothing has changed in the meantime it won’t actually render a second time.

The email cut out the second question - height should be animated with scaleY. Isn’t it? There are issues with FLIPing to 0 though (in the invert being Infinity) so there probably needs some work around that. 

There’s actually a pose stack, which is managed in pose-core. So it doesn’t actually revert to init explicitly, it’s just that init is the default initial pose. It actually just pops hover pose off the stack and reverts to the previous one. I believe the relevant code is in factories/setter

**Comment by Andarist** [comment]
> The email cut out the second question

I've edited the post right after posting it, so that's probably why it wasn't in the email.

> The email cut out the second question - height should be animated with scaleY. Isn’t it?

It is and gives a weird effect on contained text, not sure how to fight it yet.

> There’s actually a pose stack, which is managed in pose-core. So it doesn’t actually revert to init explicitly, it’s just that init is the default initial pose and so is likely to be the previous one. It actually just pops hover pose off the stack and reverts to the previous one. I believe the relevant code is in factories/setter

Thanks, gonna look into it as it seems that something is broken there.

**Comment by InventingWithMonster** [comment]
Ah. So the thing with inverse scale transforms, I suspect there’ll need to
be a new component that wraps content to compensate for the scale
transforms in some way. It’ll never be perfect because changing the width
and height will affect the internal layout regardless but it will help in a
lot of cases

**Comment by Andarist** [comment]
Just going back to the double render call for the last question.
> If the renders been flushed manually and nothing has changed in the meantime it won’t actually render a second time.

It might not render a second time, but seems like an excessive call - if we know that it won't rerender because we render with the same values beforehand then that scheduled call seems to be unnecessary. Personally I try to avoid calling things if I can determine that they dont have to be called instead of relaying on the fact that called things just wont do anything if called unnecessarily.

**Comment by Andarist** [comment]
Fair enough. Thanks for answering my questions!
