### ISSUE TITLE
Pose: resizable option

### ISSUE THREAD

**Issue by souporserious** [Popmotion/popmotion#566]
**Is your feature request related to a problem? Please describe.**
Creating resizeable UI can be tedious and requires a third party library. It seems like Pose is set up to handle this nicely already.

**Describe the solution you'd like**
I had the idea after seeing [this library](https://reactjsexample.com/resizable-and-movable-component-for-react/) since we can pass `draggable` already, this UI could easily be achieved with a `resizeable` option. I think this could also work with [snapPoints](https://github.com/Popmotion/popmotion/issues/489) and allow mimicking [react-grid-layout](https://strml.github.io/react-grid-layout/examples/0-showcase.html).

I'd love to hear your thoughts on this. Maybe it's weird and doesn't fit because Popmotion is geared towards animation 🤷‍♂️. Seems like Popmotion could start getting on the same API level as [InteractJS](http://interactjs.io/), but be lightweight and declarative.

**Comment by InventingWithMonster** [comment]
Yeah I really like this. Though as its such a niche use case I wonder if there's a generic way of tackling this in a plugin-esque fashion.

Thinking out loud:

```javascript
const Resizable = posed.div({
  resizable: ['right']
});
```

```javascript
pose.addProperty('resizable', {
  validate: r => Array.isArray(r) || typeof r === 'boolean',

  onCreate: ({ element, setPose, values } /* maybe props or poser context */) => {
    const startResizing = () => {
      
    }

    element.addEventListener(startResizing)

    // Return stuff for cleanup or maybe the initial pose map etc
    return startResizing
  },

  // 
  onDestroy: (startResizing) => element.removeEventListener(startResizing)
});
```

**Comment by souporserious** [comment]
Did some [messing around](https://codesandbox.io/s/jnwy8r8z65) last night to replicate IneractJS. Seems like it might be beneficial to rename `dragBounds` to something like `bounds` that other properties (plugins?) can interact with. In the case of this issue, something `resizeable` could hook into and determine if bounds are defined or not.
