### ISSUE TITLE
enable dynamic props for passive values

### ISSUE THREAD

**Issue by MrLoh** [Popmotion/popmotion#567]
**Is your feature request related to a problem? Please describe.**
I need to animate a color value in react native pose based on a theme prop (in this case using the styled-components theme provider) unfortunaltely, [unlike normal props](https://popmotion.io/pose/learn/dynamic-props/) the passive value doesn't seem to support dynamic assignment. 

**Describe the solution you'd like**
Just like all other props, passive values should also be assignable to a function that resolves with the props as value. 

```js
posed.Text({
  default: {
    marginRight: 0,
  },
  selected: {
      marginRight: 1,
  },
  passive: {
    color: (p) => [
      'marginRight',
      {
        inputRange: [0, 1],
        outputRange: [p.theme.colors.main, p.theme.colors.brand],
      },
    ],
  },
});
```

**Describe alternatives you've considered**
A current workaround is to define the posed prop in the constructor of a wrapper class component and rerender update it, whenever the theme variable changes.

**Comment by Andarist** [comment]
Could u give a code example of what are u trying to achieve? Passive values are derived from other changing style properties, so Im not entirely sure how do u want to use props for this. Do you want your passive function to receive both "source" property and props?

**Comment by Andarist** [comment]
I think that @MrLoh is interested in updating the passive values because he mentions this:
> A current workaround is to define the posed prop in the constructor of a wrapper class component and rerender update it, whenever the theme variable changes.

I don't think that's fixable with config as function as it works only with initialProps

**Comment by MrLoh** [comment]
I didn't know that was possible, I think that should do the trick for me for now, I don't really need life updating. But it shouldn't be too hard to build life updating with the same trick, I used to create it now: 

```js
class PassiveDynamicProp extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = { Component: this.createComponent() };
  }

  componentDidUpdate = (prevProps) =>
    this.props.theme !== prevProps.theme && this.setState({ Component: this.createComponent() });

  createComponent = () =>
    posed.Text({
      default: {
        marginRight: 0,
      },
      selected: {
        marginRight: 1,
      },
      passive: {
        color: [
          'marginRight',
          {
            inputRange: [0, 1],
            outputRange: [this.props.theme.colors.main, this.props.theme.colors.brand],
          },
        ],
      },
    });

  render = () => <this.state.Component {...this.props} />;
}
```

Maybe I could prepare a PR, if you think this approach should work for react-native-pose as well. But I'm not familiar with this codebase, so maybe this isn't feasible.

**Comment by MrLoh** [comment]
I guess the main issue here is, that for this to be performant it needs to have a check inside the componentDidUpdate.

**Comment by MrLoh** [comment]
@Andarist @InventingWithMonster Actually the posed config as a function does not seem to work in `react-native-pose`. I also added a code example to the issue description of what I would like to be able to do.

**Comment by InventingWithMonster** [comment]
Ah sorry yeah that hasn’t been implemented, I missed that. I’ll try and
implement soon

**Comment by MrLoh** [comment]
Here's my current workaround to enable a config function with an updating theme props, if anyone runs into this issue for now.

```js
import * as React from 'react';
import { withTheme } from 'styled-components/native';
import posed from 'react-native-pose';

const posedWithTheme = (componentName) => (config) => {
	class PosedComp extends React.PureComponent {
		constructor(props) {
			super(props);
			this.state = { Component: this.createComponent() };
		}

		componentDidUpdate = (prevProps) =>
			this.props.theme !== prevProps.theme && this.setState({ Component: this.createComponent() });

		createComponent = () => posed[componentName](config(this.props));

		render = () => <this.state.Component {...this.props} />;
	}
	return withTheme(PosedComp);
};

['Text', 'View', 'TouchableOpacity'].forEach((componentName) => {
	Object.defineProperty(posedWithTheme, componentName, {
		get: () => posedWithTheme(componentName),
	});
});
```

**Comment by ElliottJRo** [comment]
hey @MattPerry8 have you had a chance to work on this by any chance?

Im not sure if my use case should be done via pose.passive ->

I want to animate an element based on mouse scroll event and element absolute position (on screen)
If I use @MrLoh 's work around, I would be creating a new element on scroll which is probably not a good idea.

example:
As you scroll down the page, animate the element's x value to slide across the screen

**Comment by micha149** [comment]
I want to use a prop to calculate the result for a passive value. But I can't get it working. The only workaround I can imagine is to pass a container like a popmotion value as a prop an modify its value in an effect, but this is not very cool.

I can imaging different solutions but don't know anything about the internal architecture, so they may be not realizable:
1. the passive handler function will receive current props on each call
2. `passive` can be a function which is called with `props` each time the component will receive props
3. `passive.<styleProperty>` can be a function which is called with `props` each time the component will receive props

Here is what I would like to see working:
```javascript
const TitleText = posed.div({
    passive: ({ maxOffset }) => ({
        left: ['x', x => Math.max(0, Math.min(-x, maxOffset)), true]
    })
});

const SliderGroup = ({ children, title }) => {
    const containerRef = useRef();
    const titleRef = useRef();
    const { width: containerWidth } = useElementSize(containerRef);
    const { width: titleWidth } = useElementSize(titleRef);

    return (
        <div ref={containerRef} style={containerStyle}>
            <div ref={titleRef} style={titleStyle}>
                <TitleText style={titleTextStyle} maxOffset={containerWidth - titleWidth}>{title}</TitleText>
            </div>
            <div style={wrapperStyle}>
                {children}
            </div>
        </div>
    )
};
```
