### ISSUE TITLE
React Pose: Animations don't start if the next pose is an array of equal length

### ISSUE THREAD

**Issue by timmyjs** [Popmotion/popmotion#574]
## Describe the bug
Posed animations don't execute if I use string[] with the same length on both sides of a ternary operator in a pose prop.

```js
<Content pose={
	open ? ["open", "highlight"] : ["closed", "highlight"]
}>
```

## How to reproduce
1. Go to CodePen example
2. Click on Accordian header elements
3. See error - Animation isn't working
4. Remove 'highlighted' animation from one of the arrays within the pose prop.
5. Animation works now

## Expected behaviour
Animation works if you have arrays with same length.

## Link to CodePen example (or similar)
https://codesandbox.io/s/9qm0703pzr

## Device information
 - Device: MacBook Pro
 - OS: macOS Mojave 10.14
 - Browser: Google Chrome
 - Version: 69

**Comment by InventingWithMonster** [comment]
Have you tried swapping the poses around so the last one is open/closed? Would still be a bug but might help you for now

**Comment by timmyjs** [comment]
I found a workaround by adding an additional (empty) fake animation to one of the arrays.

Anyway, thanks for your quick answer and providing the fix.
