### ISSUE TITLE
[react native] text within nested posed component with animated position renders in low quality

### ISSUE THREAD

**Issue by kevinwolfcr** [Popmotion/popmotion#590]
## Version
`react-native-pose`: `^0.9.0`

## Describe the bug
Text is rendering in low quality when it is within a posed view with animated position and that view is within another posed view which also animates position.

## How to reproduce
1. Create a posed component with animated position and put a text inside it.
2. Wrap that component and animate the position of the wrapper component.
3. The text will now be in low quality.

## Expected behaviour
Text rendered in normal quality.

## Link to CodePen example (or similar)
https://snack.expo.io/@kevinwolf/nested-pop-issue

## Device information
In which environment are you reproducing the bug?
 - Device: Any iPhone
 - OS: iOS
 - Browser N/A
 - Version `^0.9.0`

### Component without wrapper component
![simulator screen shot - iphone 6 - 2018-10-25 at 21 12 52](https://user-images.githubusercontent.com/3157426/47542488-e5fe1f80-d89a-11e8-9340-f3d96bd3205c.png)

### Component wrapped
![simulator screen shot - iphone 6 - 2018-10-25 at 21 13 32](https://user-images.githubusercontent.com/3157426/47542494-eac2d380-d89a-11e8-8e70-b64cbe5fad9b.png)

**Comment by kevinwolfcr** [comment]
Any update on this?

**Comment by kevinwolfcr** [comment]
Didn't get a response, had to switch back to `LayoutAnimation` :/

**Comment by juliusbangert** [comment]
I came across the same problem I asked for [help on stackoverflow](https://stackoverflow.com/questions/56264783/weird-antialias-artefacting-with-react-native-on-nested-posed-components)

Did you ever find a solution?
