### ISSUE TITLE
Writing inline styles with `element.style.cssText` violates some CSP policies

### ISSUE THREAD

**Issue by Andarist** [Popmotion/popmotion#592]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#Violation_cases

The only way to cover using popmotion with those CSP rules is to switch to using either `node.style[property] = value` or `node.style.setProperty(property, value)`

**Comment by InventingWithMonster** [comment]
Do you know if browsers batch renders for instance if someone was to
animate both width and height with this approach would it relayout twice?
It’s been a while since I looked at this

**Comment by Andarist** [comment]
I think it has been fixed by https://github.com/Popmotion/popmotion/pull/659
