### ISSUE TITLE
[vue-pose] Install for nuxt.js

### ISSUE THREAD

**Issue by exdeniz** [Popmotion/popmotion#602]
How to correct install vue-pose with Nuxt.js via plugins?

**Comment by InventingWithMonster** [comment]
I'm not sure to be honest! A quick glance at the Nuxt.js docs isn't making things much clearer either.

I'm going to close this ticket though as there shouldn't be anything special we have to do on the Pose side to enable this. You might find advice on a Nuxt.js community who are more familiar with that framework.
