### ISSUE TITLE
[react-pose]: Build fails on attempt to import springForce

### ISSUE THREAD

**Issue by TheMegaTB** [Popmotion/popmotion#606]
## Describe the bug
On build it attempts to import `springForce` from `@popmotion/popcorn` which results in the following error:
```
Failed to compile.

./node_modules/popmotion/dist/popmotion.es.js
Attempted import error: 'springForce' is not exported from '@popmotion/popcorn'.
```

## How to reproduce
1. Create a new project using the latest `create-react-app`
2. Execute `yarn add react-pose`
3. Modify `src/App.js` to contain `import posed from 'react-pose';`
4. Build the project using `yarn start`
5. Get the error

## Expected behaviour
It is expected to build and import without errors.

## Device information
In which environment are you reproducing the bug?
 - During build time with a create-react-app project on Manjaro Linux with NodeJS v11 and react-scripts v2.1.1

## Additional context
Project created with the latest create-react-app. Then executed `yarn add react-pose react-router-dom`:
```
success Saved 21 new dependencies.
info Direct dependencies
├─ react-dom@16.6.0
├─ react-pose@3.3.8
├─ react-router-dom@4.3.1
└─ react@16.6.0
info All dependencies
├─ @emotion/is-prop-valid@0.6.8
├─ @emotion/memoize@0.6.6
├─ @popmotion/popcorn@0.1.0
├─ @types/invariant@2.2.29
├─ @types/node@10.12.1
├─ framesync@4.0.1
├─ hoist-non-react-statics@2.5.5
├─ path-to-regexp@1.7.0
├─ popmotion-pose@3.3.2
├─ popmotion@8.4.2
├─ pose-core@2.0.0
├─ react-dom@16.6.0
├─ react-is@16.6.0
├─ react-pose@3.3.8
├─ react-router-dom@4.3.1
├─ react-router@4.3.1
├─ react@16.6.0
├─ resolve-pathname@2.2.0
├─ style-value-types@3.0.7
├─ stylefire@2.1.0
└─ value-equal@0.4.0
```

**Comment by jonathanselwall** [comment]
Experiencing the same problem, I've tried to install older versions of react-pose as well but that doesn't work either.

**Comment by InventingWithMonster** [comment]
@TheMegaTB Can you clear node_modules and install `react-pose@3.4.0` - I had someone say it didn't work for them but I've just installed this on a clean CodeSandbox and it worked.

**Comment by kevva** [comment]
It still doesn't work. `popmotion` tries to import `springForce` from `popcorn`, but it's not exported.

```
react-pose@3.4.0
  └─┬ popmotion-pose@3.4.0
    └─┬ popmotion@8.5.0
      └── @popmotion/popcorn@0.1.0
```

**Comment by jonathanselwall** [comment]
> @TheMegaTB Can you clear node_modules and install `react-pose@3.4.0` - I had someone say it didn't work for them but I've just installed this on a clean CodeSandbox and it worked.
> 
> Edit: That changelog is out of date, the change it mentions was never released.

I tried it on a CodeSandbox earlier and that worked for me as well, although it doesn't seem to work locally.

**Comment by InventingWithMonster** [comment]
I find it suspicious that it works on a clean install but not on your local envs. Almost as if there's some caching issue. I've also verified that all the compiled files in popcorn are correctly exporting `springForce`. I've republished as `0.1.1` just in case.

If one of you could go into `node_modules/@popmotion/popcorn` and check the contents of `dist/popcorn.es.js` for `springForce` that'd be of interest.

**Comment by kevva** [comment]
@InventingWithMonster, see above. I've checked the contents for `0.1.0` and it doesn't include the export. `0.1.1` works so I guess this can be closed.

**Comment by InventingWithMonster** [comment]
👍 Glad to hear it, didn't realised you'd eyeballed the file. It's not possible to publish without building the files so not sure what happened here.

**Comment by TheMegaTB** [comment]
I can confirm that this indeed did fix the issue. Thanks for the quick fix :+1:

**Comment by Andarist** [comment]
I can confirm that 0.1.1 had to be published - ive mentioned this in my PR
which switched the repo to popcorn. That export was not exported in 0.1.0
