### ISSUE TITLE
[popcorn] Wrong imports in distance.d.ts

### ISSUE THREAD

**Issue by slavasitnikov** [Popmotion/popmotion#607]
## How to reproduce
1. Install `@popmotion/popcorn@0.1.1`
2. Open `node_modules/@popmotion/popcorn/lib/utils/distance.d.ts`. [Link to dist](https://unpkg.com/@popmotion/popcorn@0.1.1/lib/utils/distance.d.ts)
3. See import paths like `import("popcorn/src/types").Point2D`
4. Get errors from ts compiler: `TS2307: Cannot find module 'popcorn/src/types'.`

## Expected behaviour

Imports must use correct paths for e.g. `"../types"`

**Comment by Andarist** [comment]
Do you realize that you can also fix it by preparing an appropriate PR? I know - it's shocking.

**Comment by slavasitnikov** [comment]
@Andarist Yeah, I would make a PR if I knew how to fix this. I have no idea how 
https://github.com/Popmotion/popmotion/blob/master/packages/popcorn/src/utils/distance.ts became  https://unpkg.com/@popmotion/popcorn@0.1.1/lib/utils/distance.d.ts

**Comment by InventingWithMonster** [comment]
I basically don't know why this is happening. Typescript generated these files - it should be able to parse them. Help on this is appreciated.

**Comment by InventingWithMonster** [comment]
Published in `@popmotion/popcorn@0.1.2`
