### ISSUE TITLE
[help] draggable only on X and Y axis

### ISSUE THREAD

**Issue by StefKors** [Popmotion/popmotion#609]
Setting the prop `draggable: true` allows free dragging over the whole area. Is there a way for the dragged element to stay both on a strict X and Y axis? 

Something like `draggable: 'x' && 'y',` is what I'm looking for.

**Comment by InventingWithMonster** [comment]
So if you start dragging it on the x axis, it says on it, and if you start on the y axis it stays on that instead?

**Comment by StefKors** [comment]
Yes exactly!

**Comment by InventingWithMonster** [comment]
Not currently. There's a loose proposal to have `draggable` be a function that would run on drag without effect until it returns `'x'`, `'y'` or `false`. Which would be useful in your use case. But I don't know when I'll find the time to implement that.

**Comment by StefKors** [comment]
right, makes sense. Would using `onValueChange` and passing the either `draggable: 'x'` or `draggable: 'y'` to the prop be possible?
