### ISSUE TITLE
React-pose: typings error when using react-pose@3.4.0 in typescript project

### ISSUE THREAD

**Issue by mnajdova** [Popmotion/popmotion#610]
Adding react-pose v3.4.0 in typescript react project throws the following error:
```
node_modules/react-pose/lib/components/PoseElement/types.d.ts
(28,39): Cannot find name 'props'.
```

## How to reproduce
1. Create react app using typescript scripts. Example:
```
yarn create react-app popmotion-playground --scripts-version=react-scripts-ts
```
2. Add react-pose
```
yarn add react-pose
```
3. Use posed in your app. Example:
```
import * as React from 'react'
import {default as posed} from 'react-pose'
const Hidden = posed.div({
  visible: {
    opacity: 1,
  },
  hidden: {
    opacity: 0,
  },
})

class App extends React.Component {
  public render() {
    return (
      <div>
          <Hidden pose={'visible'} style={{width: '100px', height: '100px', backgroundColor: 'red'}} />
      </div>
    );
  }
}
```
```
node_modules/react-pose/lib/components/PoseElement/types.d.ts
(28,39): Cannot find name 'props'.
```

## Expected behaviour
No typings errors

## Device information
 - OS: Windows 10
 - Browser: chrome
- react-pose version: 3.4.0
- typescript version: 3.1.6
- react version: 16.6.0

**Comment by InventingWithMonster** [comment]
I've updated the types in this commit https://github.com/Popmotion/popmotion/commit/69c21b2040331947084ef93ab3fdb427db1fe548

I don't know why Typescript allowed this to compile. Just now it was flagged in my code editor but seemed to compile via Rollup just fine.

The fix will be released with `4.0.0`

**Comment by mnajdova** [comment]
Great, thanks for the info!

**Comment by dimitar-nikovski** [comment]
Would it be possible to open a tag so that we can pull this fix earlier?
