### ISSUE TITLE
[react-pose] PoseGroup children animated from original position when a child leaves the DOM 

### ISSUE THREAD

**Issue by bwallberg** [Popmotion/popmotion#614]
## Describe the bug
As of 3.3.8 when a child is removed from a `<PoseGroup>` the remaining children are animated from their original position. ( 4.0.1 tested as well )

## How to reproduce
1. Go to https://codesandbox.io/s/1y967z8zjj
2. Click on a any item in the menu, this will remove the first child in the list
3. Do this a few times
4. Observe
5. Go to package.json and change to 3.3.7
6. Repeat step 3 & 4, observe the nicer animation.

## Expected behaviour
When children are removed from a <PoseGroup> tree the remaining children should animate from their current position to their new position

## Device information
 - Device: Desktop
 - OS: macOS
 - Browser: Firefox, Chrome
 - Version: Latest

**Comment by Andarist** [comment]
From what I see the children are animated in both cases (3.3.7 & 4.0.1) - the previous version has a nicer animation though. Could you confirm what I'm seeing?

**Comment by bwallberg** [comment]
It's a lot more visible with a tween animation, I've updated the above codesandbox.

**Comment by bushblade** [comment]
I found this an issue too and resorted to using height transitions on a list where items are added and removed.

**Comment by Andarist** [comment]
According to my quick test this should get fixed by #629
