### ISSUE TITLE
Stylefire: allow numeric values for props like padding, margin, etc.

### ISSUE THREAD

**Issue by souporserious** [Popmotion/popmotion#615]
**Describe the solution you'd like**
Similar to how React works, I'd like to use numeric values instead of strings for props like `padding`, `margin`, `borderRadius`, etc. when using `styler`.

If this sounds like an ok addition, please let me know and I will create a PR 😊.

**Comment by InventingWithMonster** [comment]
Huh I was surprised to find it doesn’t already work like that! 
https://github.com/Popmotion/popmotion/blob/master/packages/stylefire/src/css/value-types.ts

By all means!

**Comment by InventingWithMonster** [comment]
Huh I was surprised to find it doesn’t already work like that!
https://github.com/Popmotion/popmotion/blob/master/packages/stylefire/src/css/value-types.ts

**Comment by souporserious** [comment]
Sweet! Took a quick look and it isn't entirely obvious where I should put this change 🤔. Would you want maybe an array for each pixel value that can accept a number as well? Or maybe do a check somewhere around [here](https://github.com/Popmotion/popmotion/blob/master/packages/stylefire/src/css/render.ts#L116)?

**Comment by InventingWithMonster** [comment]
You can add the value types to the file I linked above. So for instance 

```
padding: px,
paddingTop: px
```

etc
