### ISSUE TITLE
[React-Pose] A x-draggable element intercepts scroll event on touch devices

### ISSUE THREAD

**Issue by dbismut** [Popmotion/popmotion#618]
## Description
A `draggable` element on the `x` axis in react-pose intercepts vertical scroll events on touch devices.

## How to reproduce
1. On a mobile phone, go over [Codesandbox](https://codesandbox.io/s/p2jryz2roq)
2. Try starting a vertical scroll on the body from the red draggable square
3. The body doesn't scroll

## Expected behaviour

Maybe this is the intended behavior, but I was curious if there was a way that draggable elements would forward scroll trigger events to the DOM. I understand this is not as easy as it sounds but I'm in the situation where this would be useful.

## Codesandbox link
https://codesandbox.io/s/p2jryz2roq

## Device information
In which environment are you reproducing the bug?
 - iPhone X
 - iOS 12
 - Safari

**Comment by dbismut** [comment]
Thanks for your answer!

Is there a dirty turnaround that you would suggest? Atm I'm including the content I want to scroll _within_ the draggable element (which incidentally takes the full viewport anyway) and make the element also draggable on the `y` axis, with a `decay` function that sort of emulates the scroll inertia, but you may have a better idea at of your hat?

**Comment by meebix** [comment]
@dbismut - did you ever find a good dirty solution for this? I am currently running into the same issue.

**Comment by maximelebreton** [comment]
Hey @InventingWithMonster, and thanks for your amazing work!
I have the same issue with `Vue Pose`, and remember that on my band website [luuuge.fr](https://luuuge.fr) who uses on a old version of the pure popmotion (`8.1.9`), I handled this case with a:
```js
pointer({
  x: albumY.get(),
  preventDefault: false  // <-- this little thing
})
```
(you can drag the album on the `x` axis, and the scroll works on touch devices)

But I can't find this param in `Vue Pose`, so maybe it's not based on [popmotion Pure's pointer](https://popmotion.io/api/pointer/)?

Any idea for a dirty workaround in the meantime?

**Comment by bpurtz** [comment]
Any progress on this branch? I found in the source code where this happens. It is in /input/pointer/mouse.ts on line 21 when you call .preventDefault. I realize you need to do this in order to prevent scrolling on the y axis, but I feel like a compromise could be reached such as a prop in config that would allow me to disable the preventDefault(). Any update on this issue would be greatly appreciated! We are using a hack right now for vertical scrolling and I am not super stoked on it to say the least. @meebix
