### ISSUE TITLE
Compose Values/Reactions

### ISSUE THREAD

**Issue by jacobp100** [Popmotion/popmotion#619]
**Is your feature request related to a problem? Please describe.**
I have multiple `value`s and I want to output them to a function that is updated whenever one or more of the values updates.

I have two values that control how parameters used for canvas drawing, so I want to redraw any time a value changes, with the latest values

**Describe the solution you'd like**
Similar to `compose` or `merge`, but specifically for `value`s.

**Describe alternatives you've considered**
I wrote my own [here](https://github.com/jacobp100/hooks-test/blob/master/src/animation/mergeValues.js)

**Comment by InventingWithMonster** [comment]
We're going to move away from this model to something simpler.
