### ISSUE TITLE
Cordova Integration

### ISSUE THREAD

**Issue by dbandhu** [Popmotion/popmotion#622]
Hi,
Not an issue, just a question (sorry didn't know where else to get ahold of developers).. 
Integrating React Router with Cordova requires using HashRouter if utilizing 'push()', wondering if the implementation of RoutesContainer uses BrowserRouter or HashRouter?
Thanks!

**Comment by designbyadrian** [comment]
`RoutesContainer` is just an arbitrary name given to a posed component. You can name it however you want, because it's got nothing to do with your router.

All router plugins use clever ways of hiding and showing containers. Pose just animates the different states.

**Comment by dbandhu** [comment]
Ah right...sorry for the newb question.. Thanks!
