### ISSUE TITLE
React-Pose Animations don't happen if nested in dynamic returns

### ISSUE THREAD

**Issue by HoogsterInc** [Popmotion/popmotion#623]
## Describe the bug
If you make a posed element and that element needs to be rendered dynamically through state changes then no animation happens. In my case, I have a card with a switch statement that renders different data and interaction to the user. I want a hover animation (I want a more complicated animation but this is what I started with) for when a user hovers over a picture of another user. "posed.img" is still showing the image and there are no errors - however, nothing happens when you hover over the image. If you pull the exact copy out of the dynamically rendered card it works perfectly. 

## How to reproduce
Create a component with state to switch between different content
Have it switch between three different states that show a different colored box
Try to have the box scale up on hover.

## Device information
In which environment are you reproducing the bug?
 - Device: Macbook
 - Browser Chrome
 - Version 4.0.1

**Comment by Andarist** [comment]
Could u prepare a codesandbox showcasing the problem?

**Comment by HoogsterInc** [comment]
I made a quick one that doesn't follow exactly what's going on with my project (I've got some time restraints for a deadline). Everything in that quick version seemed to work great. I'll close this and when I have more time to make sure it isn't something I've done and if there is still an issue I'll reopen it. Thanks for your great work!

**Comment by HoogsterInc** [comment]
If another use seems to have this problem have them check their bootstrap classes. I don't know exactly what was happening but my "card-img-overlay" bootstrap class was causing some serious issues with what was able to register mouse events.
