### ISSUE TITLE
react-pose version 4 bug with FLIP/PoseGroup not present in version 3

### ISSUE THREAD

**Issue by bushblade** [Popmotion/popmotion#624]
There is a bug in version 4 of react-pose that prevents the FLIP animation running until after a second user input.

To show this I have forked one of the Pose examples on codeSandbox

[working version 3 here](https://codesandbox.io/s/40rr3w4n29)

[bugged version 4 here](https://codesandbox.io/s/6mm19rr3)

version 3 works from the first click but version 4 only works after the second click.

**Comment by Andarist** [comment]
Thanks for the report! I'll take a look at it, but it may take few days.

**Comment by Andarist** [comment]
It seems that migrating to `getSnapshotBeforeUpdate` - https://github.com/Popmotion/popmotion/pull/579 has caused this. Not yet sure why - need to investigate further.
