### ISSUE TITLE
Passive opacity for both X and y axis?

### ISSUE THREAD

**Issue by StefKors** [Popmotion/popmotion#625]
So I understand how it's possible to use passive values on either the X and Y axis.
is it also possible to use it on both the X and Y axis?
something like this?

```Javascript
posed.div({
  draggable: true,
  passive: {
    opacity: ['x', interpolate(
      [-200, -100, 100, 200],
      [0, 1, 1, 0]
    )],
    opacity: ['y', interpolate(
      [-200, -100, 100, 200],
      [0, 1, 1, 0]
    )]
  }
})
```

**Comment by klaasman** [comment]
What is your expected opacity when for example `x = -200` and `y = -100` (simultaneously)?

**Comment by Andarist** [comment]
This syntax would not work obviously, but this is somewhat interesting use case - from what I see it's not possible to combine 2 values into 1 passive one, but seems like this should be supported.

Probably the only place that would have to get tweaked is here - https://github.com/Popmotion/popmotion/blob/52579805a29735531a774727481872b8db777e3e/packages/pose-core/src/factories/values.ts#L153 . However I'm not sure how to combine properly 2 latest values in popmotion's reactive system.

**Comment by StefKors** [comment]
This seems like a great way of using passive values!
