### ISSUE TITLE
[react-pose] Example with React Context consumer 

### ISSUE THREAD

**Issue by mark-schaal** [Popmotion/popmotion#627]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be useful to see how to pose an existing Component using forwardRef() when rendering output from React Context's consumer.

**Describe alternatives you've considered**
I have explored using custom components using the posed(MyComponent)(config) example, as well as controlling animation rendering with the enter/exit configuration options, but I would find it very useful to see a working example for how this would be setup when using a consumer from React Context.

**Additional context**
The concept I am working from is that a React application is using the Context API to define a custom, global notification tray component. In the Context Provider, there is a conditional rendering of a Notification component, which uses Context's Consumer functionality to control rendering the child element.

The idea I started with was that I could use a PoseGroup in the Provider component to control animation behavior on enter/exit, which means that the export from the Notification component (Consumer) would need to use forwardRef() in order to allow the component to be used as a custom component.

As I worked with this, it became very convoluted. The issue that I am running into is understanding how forwardRef() would work in this scenario, given that the Consumer is wrapping the rendered output inside of Notification.

**/Components/shared/Context/Notifications.jsx**
```
import React, { Component } from 'react';
import { Col, Row } from 'react-bootstrap';
import posed, { PoseGroup  } from 'react-pose';

// Import local Components.
import { Notification } from '/Components/shared/Alerts/Notification';

// Define new Context.
const NotificationsContext = React.createContext();

// Define new Context Provider.
class NotificationsProvider extends Component {
  constructor(props) {
    super(props);

    this.state = {
      isVisible: false,
      notification: {
        type: 'info',
        title: '',
        messages: [],
        hint: '',
      },
    }
  }

  openNotifications = (notification) => {
    this.setState({
      isVisible: true,
      notification,
    });
  };

  closeNotifications = () => {
    this.setState({
      notification: {
        type: 'info',
        title: '',
        messages: [],
        hint: '',
      },
      isVisible: false,
    });
  };

  render() { 

    const { children } = this.props;
    
    return (
      <NotificationsContext.Provider
        value={{
          openNotifications: this.openNotifications,
          closeNotifications: this.closeNotifications,
          visibility: this.state.isVisible,
          notification: this.state.notification,
        }}
      >

      <Row className="notifications_tray">
        <Col md={12}>
          <PoseGroup>
            { this.state.isVisible && [
              <Notification key="notification_tray" />
            ]}
          </PoseGroup>
        </Col>
      </Row>

        {children}
      </NotificationsContext.Provider>
    );
  }
}

// Define new Context Consumer.
const NotificationsConsumer = NotificationsContext.Consumer;

// Export Context Consumer and Provider.
export {
  NotificationsConsumer,
  NotificationsProvider,
};
```

**/Components/shared/Alerts/Notification**
```
import React from 'react';
import { Alert } from 'react-bootstrap';

// Import local Components.
import { NotificationsConsumer } from 'Components/shared/Context/Notifications';

const Notification = () => (
  <NotificationsConsumer>
    { ({ notification }) => (
      <Alert bsStyle={notification.type}>
        <h4>{notification.title}</h4>
        {
          notification.messages.map((message, i) => {
            if (typeof message == 'string') {
              return <p key={i}>{message}</p>; 
            }
  
            return <div key={i}>{message}</div>;
          })
        }
      </Alert>
    )}
  </NotificationsConsumer>
);
 
export default Notification;
```

Any guidance would be appreciated, and thanks for all of the hard work on this module. Very useful.

**Comment by Andarist** [comment]
I assume u want to pose ur `Alert`
```js
import React from 'react';
import posed from 'react-pose';
import { Alert } from 'react-bootstrap';

// Import local Components.
import { NotificationsConsumer } from 'Components/shared/Context/Notifications';

const PosedAlert = posed(React.forwardRef((props, ref) => <Alert {...props} innerRef={ref} />))

const Notification = () => (
  <NotificationsConsumer>
    { ({ notification }) => (
      <PosedAlert bsStyle={notification.type}>
        <h4>{notification.title}</h4>
        {
          notification.messages.map((message, i) => {
            if (typeof message == 'string') {
              return <p key={i}>{message}</p>; 
            }
  
            return <div key={i}>{message}</div>;
          })
        }
      </PosedAlert>
    )}
  </NotificationsConsumer>
);
 
export default Notification;
```

**Comment by mark-schaal** [comment]
Thanks @Andarist , this solved my problem! I think I had a fundamentally incorrect understanding of where to call React.forwardRef(), and your example helps clarify that. I'll close this out, thanks again!

**Comment by mark-schaal** [comment]
For anyone else who comes across this issue, as it turns out, the Alert element in react-bootstrap does not interact with the DOM directly (it uses the transition prop), and as such attempting to forward refs to <Alert /> will always break.
