### ISSUE TITLE
Popmotion Pure: Interpolate not clamping if output exceeds it's max outputRange despite the docs

### ISSUE THREAD

**Issue by cybervaldez** [Popmotion/popmotion#630]
## Describe the bug
As stated in https://popmotion.io/api/transformers/#transformers-preset-transformers-interpolate
> Provided values outside the given ranges will be clamped to the output range limits.

## How to reproduce
const invert = interpolate([0, 100], [100, 0]);
invert(155) // -55

## Expected behaviour
invert(155) // 0

## Device information
In which environment are you reproducing the bug?

**Comment by InventingWithMonster** [comment]
I'm looking into this today but in the meantime you can compose with the `clamp` function to restore this functionality

**Comment by InventingWithMonster** [comment]
Published in `@popmotion/popcorn@0.3.0`
