### ISSUE TITLE
[react] Inner ref is deprecated

### ISSUE THREAD

**Issue by daydream05** [Popmotion/popmotion#631]
Warning on the console log saying the inner ref is deprecated.

Here is the code reproduced

https://codesandbox.io/s/88mpqqnw88

**Comment by Andarist** [comment]
I've prepared a PR fixing this in react-waypoint - https://github.com/brigade/react-waypoint/pull/278

**Comment by Andarist** [comment]
My PR to react-waypoint got merged in. Please update to the newest version - it should fix your issue. You can also close this one :)

**Comment by daydream05** [comment]
Thanks!
