### ISSUE TITLE
Animate Multiple Elements at same time in React

### ISSUE THREAD

**Issue by amcdnl** [Popmotion/popmotion#637]
## Request
I need the ability to animate multiple SVG elements together in react. For example, I have a 3 elements: Area, Line and Point Indicator. I would want them all 3 to move together. 

## Current
The way you currently declare animations is on a per-element-basis which makes it difficult to sync all those elements together.

## Proposal
Today I'm using react-move which allows me to define the transition props at the parent and then pass them downwards so all the children elements move together.

```
<NodeGroup
        data={data}
        keyAccessor={this.getKeyAccessor}
        start={this.getStart}
        enter={this.getEnterUpdate}
        update={this.getEnterUpdate}
      >
        {transitionData => (
          <React.Fragment>
            {this.renderArea(transitionData)}
            {this.renderMarkLine()}
            {this.renderSymbols(transitionData)}
          </React.Fragment>
        )}
      </NodeGroup>
```

Given this uses React's props, its not a very good solution since it will have to participate in the lifecycle and not be as performant. 

I was thinking maybe using React's context and children just inherently receiving them might work.

**Comment by InventingWithMonster** [comment]
Does it not work just to set the same pose on them all at the same time?

**Comment by amcdnl** [comment]
Sadly not - https://www.screencast.com/t/LOqHVqL0ogV

**Comment by Andarist** [comment]
You should be able to create a hierarchy such as:
```js
<Parent>
  <A/>
  <B/>
  <C/>
</Parent>
```

make them all posed elements, but set `pose` prop only on the Parent. That pose should flow through the tree through context (A, B & C dont have to be direct children of Parent) and set that pose on all children - so their animations should sync with itself.

**Comment by amcdnl** [comment]
@Andarist - Thanks for the idea. Would you mind giving me a snippet of code I could go off of?

**Comment by Andarist** [comment]
https://codesandbox.io/s/w6m757yj6l

Look how `Item` doesn't receive a pose prop, but it can still "react" to the pose set on `Sidebar`. You are not restricted to using only a single type of the component as Item, so you should be able to use A, B, C and more.

Also `Sidebar` doesn't even have any animation on its own - it can just receive pose prop so it gets at the same time~ to all children which expects it.

**Comment by amcdnl** [comment]
Hmnm interesting. I think that helps but not sure how I could apply that technique to an array of elements. I'll play w/ it though.

**Comment by amcdnl** [comment]
I'll build an example in codesandbox to show you want I'm trying to do.

**Comment by amcdnl** [comment]
OK - it seems I had something else going on that was tearing down my posed components. I was able to figure it out. Thanks for your help!
