### ISSUE TITLE
Stylefire + Pose Docs

### ISSUE THREAD

**Issue by amcdnl** [Popmotion/popmotion#638]
## Request
There currently isn't any docs on how to use stylefire and react-pose together.

I'm trying to figure out how to do a simple line animation where react-pose sets the path's d attribute and stylefire animates the stroke.

**Comment by InventingWithMonster** [comment]
You shouldn’t need to use stylefire directly, because Pose uses it it had
access to all the same values.
https://popmotion.io/pose/api/supported-values/

**Comment by amcdnl** [comment]
Gotcha - Makes sense.
