### ISSUE TITLE
Pose pathLength not working when combined with animated d attrs

### ISSUE THREAD

**Issue by amcdnl** [Popmotion/popmotion#641]
## Issue
When combining the use of the `pathLength` along with the `d` attribute in a single animation, the transition will never animate. I assume it's because it can't find the length of the item its trying to animate?

Example:

```
{
   enter: {
      d: () => getLinePath(getCoords()),
      pathLength: 100
    },
    exit: {
       d: () => getLinePath(getCoords()),
       pathLength: 0
    }
}
```

If that is true, then I think a adding a footnote to the docs and maybe throw an exception if used together? Do you have advice on how to achieve this? I'm happy to make a PR.

Reference: https://popmotion.io/pose/api/supported-values/

**Comment by InventingWithMonster** [comment]
Huh. Yeah that’s a great point. That’d be really difficult to fix without
really getting into the weeds, I think an exception is a more sane road to
walk

The problem is it’d mean writing special code to remeasure the line in this
specific eventuality which I think could be messy.

**Comment by amcdnl** [comment]
I found this researching the issue but it looks very 'optimistic' - https://github.com/rveciana/svg-path-properties

I ended up just rendering the line and hiding it and measuring from that.
