### ISSUE TITLE
[react-pose] applyAtStart/applyAtEnd problem

### ISSUE THREAD

**Issue by AlexeyBee** [Popmotion/popmotion#644]
I want my accordion to be `display: none` when it is closed. but the animation breaks when I open the accordion. What am I doing wrong?

I want my animation to be smooth

here is my configuration:
```
const Content = posed.div({
  closed: {
    height: 0,
    display: "none",
    applyAtStart: { display: "block" },
    applyAtEnd: { display: "none" }
  },
  open: {
    height: "auto",
    display: "block",
    applyAtStart: { display: "block" },
    applyAtEnd: { display: "block" }
  }
});
```

CodeSandbox example: https://codesandbox.io/s/20575z7ljy
package: "react-pose": "4.0.2"

**Comment by InventingWithMonster** [comment]
This looks like it works:

```
const Content = posed.div({
  closed: {
    height: 0,
    applyAtEnd: { display: "none" }
  },
  open: {
    height: "auto",
    applyAtStart: { display: "block" },
  }
});
```

**Comment by AlexeyBee** [comment]
> This looks like it works:
> 
> ```
> const Content = posed.div({
>   closed: {
>     height: 0,
>     applyAtEnd: { display: "none" }
>   },
>   open: {
>     height: "auto",
>     applyAtStart: { display: "block" },
>   }
> });
> ```

if you click even more, it will break
