### ISSUE TITLE
iOS 8 import popmotion console log: "ReferenceError: Can't find variable: WeakSet"

### ISSUE THREAD

**Issue by Haojen** [Popmotion/popmotion#648]
I'm useing popmotion 8.5.3

When i on iOS 8 device `import popmotion from 'popmotion'`,  the console tips `ReferenceError: Can't find variable: WeakSet`

**Comment by Andarist** [comment]
You have to polyfill it

**Comment by InventingWithMonster** [comment]
Added this to the docs https://github.com/Popmotion/popmotion/commit/df22bf26e6acb8e34da1ba687ab1544921b27259

**Comment by Haojen** [comment]
> You have to polyfill it

is true, use polyfill  this problem can be fixed, but ... but ..., popmotion `chain` not workiing and no anything error thow
