### ISSUE TITLE
FrameSync: Unable to implement cancelSync

### ISSUE THREAD

**Issue by dschu-lab** [Popmotion/popmotion#651]
## Describe the bug
I'm trying to figure out how to implement `cancelSync`. I created [a fresh codesandbox](https://codesandbox.io/s/9y2mpo1ryy) and copied the example code, but the render function isn't even running.

## How to reproduce
Check out this [codesandbox](https://codesandbox.io/s/9y2mpo1ryy)

## Expected behaviour
Count to 10 then cancel the counter

## Link to CodePen example (or similar)
[codesandbox](https://codesandbox.io/s/9y2mpo1ryy)

## Device information
In which environment are you reproducing the bug?
Tested in Chrome 70

**Comment by InventingWithMonster** [comment]
It’s cancelSync.render(), sorry the docs are wrong

**Comment by dschu-lab** [comment]
@InventingWithMonster Figured it out too, thanks! I'm submitting a PR right now, if you want :)
