### ISSUE TITLE
[react-pose] StaggerChildren on PoseGroup

### ISSUE THREAD

**Issue by amcdnl** [Popmotion/popmotion#654]
## Issue
I can't seem to get `staggerChildren` to work in combination with a `PoseGroup`. It would also be really nice if `PoseGroup` supported passing `staggerChildren` as a prop natively too.

For example:

```
const transition = {
  y: {
    type: 'spring',
    velocity: 10,
    damping: 100
  }
};

const CardsContainer = posed.div({
  enter: {
    staggerChildren: 100
  }
});

const CardContainer = posed.div({
  enter: {
    opacity: 1,
    y: 0,
    transition,
    // delay: ({ index }) => index * 50
  },
  exit: {
    opacity: 0,
    y: '-25px',
    transition
  }
});
```

then in my JSX I have -

```
            <CardsContainer pose="enter">
              <PoseGroup animateOnEnter={true}>
                {insights && insights.map(t => (
                  <CardContainer key={insight.id} index={index} poseKey={insight}>....</CardContainer>
               )}
              </PoseGroup>
            </CardsContainer>
```

**Comment by Andarist** [comment]
Could u prepare a simple codesandbox showcasing the problem?

**Comment by InventingWithMonster** [comment]
Yeah it’s a bit of a black hole in the API. The only real way to stagger
across children of a PoseGroup is by using index to write a custom delay
prop

**Comment by amcdnl** [comment]
@InventingWithMonster - Gotcha - Thats what I'm dong now and thats 'ok' but its not great.

The main driver for that is lets say I have a bar chart, I want to stagger the bars in but using a delay w/ spring will only allow me to 'kind of' stagger them since Y might enter before X is done.

Any suggestions on the right way to handle this?

**Comment by InventingWithMonster** [comment]
Sorry not sure what you mean by " since Y might enter before X is done."

As staggerChildren only really emulates a custom delay strategy anyway

**Comment by cereallarceny** [comment]
Any update on this @InventingWithMonster?

Is this part of any future development timeline?
