### ISSUE TITLE
BUG: subscribing to a value is firing update on other subscriptions

### ISSUE THREAD

**Issue by cybervaldez** [Popmotion/popmotion#656]
This is the same example from the docs:
const foo = value(0);
foo.subscribe(() => console.log('first reaction'));
foo.subscribe(() => console.log('second reaction'));
foo.subscribe(() => console.log('third reaction'));

Code:
https://codepen.io/anon/pen/OadBZP?editors=0011

Expected result:
first reaction
second reaction
third reaction

Returned result:
"first reaction"
"first reaction"
"second reaction"
"first reaction"
"second reaction"
"third reaction"

## Device information
In which environment are you reproducing the bug?

**Comment by InventingWithMonster** [comment]
Yeah what's happening here is every time we add a subscriber we re-fire all subscriptions. When really we just want to fire the one that's being added. I'll make a fix now

**Comment by InventingWithMonster** [comment]
Fixed in `popmotion@8.5.4`
