### ISSUE TITLE
Support css position attribute

### ISSUE THREAD

**Issue by meepeek** [Popmotion/popmotion#664]
**Is your feature request related to a problem? Please describe.**
I would like to do something like this
```
posed.div({
a: {
  width: 100, height: 100, position: 'relative'
},
b: {
  position: 'fixed', top: 0, left: 0
}
})
```
but it seems position css attribute is not supported by pose

**Describe the solution you'd like**
add support to the attribute

**Describe alternatives you've considered**

**Additional context**
This would be useful in morph dom object to fullscreen e.g. popup. Currently, I need to add the position style manually.

**Comment by InventingWithMonster** [comment]
You can set this non-animated value with the `applyAtStart` prop:

```
a: {
  width: 100,
  applyAtStart: { position: 'relative' }
}
```

**Comment by klaasman** [comment]
Isn't the [FLIP technique](https://popmotion.io/pose/learn/flip/) created for such things?

**Comment by meepeek** [comment]
I try what you guys recommend, the style applied but the animation was not correct though. I would like to make an effect where user tap a list item and it expand itself to fullscreen card. Please follow the pen: https://codepen.io/anon/pen/ebmKaL

**Comment by klaasman** [comment]
Have a look at the following example: https://popmotion.io/pose/examples/react-medium-style-image-zoom/

**Comment by meepeek** [comment]
Thanks for the example. I have found the cause. Problem solved.
