### ISSUE TITLE
Popmotion Pure with react-native

### ISSUE THREAD

**Issue by Marcotrombino** [Popmotion/popmotion#667]
I’m getting confused about libraries 😅.
I need to use some Popmotion Pure features like playback controls (pause, resume, etc) on react-native, can I use it or I can only use React Native Pose (which hasn’t these features)?
In the “Learn” section I’ve seen tutorials about using Popmotion Pure with styler for DOM, but nothing about react-native!

**Comment by InventingWithMonster** [comment]
Yeah Pure is JavaScript-only so you probably won’t great performance on
React Native. You can still use it and those features but for performance
Pose for React Native uses React Animated which has Java and Objective C
implementations under the hood. The downside being it’s more limited in
what you can achieve - you’d probably have better luck using React
Reanimated for these advanced use cases

**Comment by Marcotrombino** [comment]
Thanks! I want give a try because my use case is a little “tricky” and I just need those features on the web. 
To be more clear: my react-native app is useless itself for this purpose, because it has to be converted with react-native-web (so I could accept the javascript driver there).

The problem is that I have no idea about how to get the react-native element:

```js
const ball = document.querySelector('#c .ball');
const ballStyler = styler(ball);

tween({
  from: { x: 0, scale: 1 },
  to: { x: 300, scale: 2 },
  ease: easing.easeInOut,
  flip: Infinity,
  duration: 1000
}).start(v => ballStyler.set(v));

```

In this case ```ballStyler``` is obtained through ```styler``` which works on DOM, but how can I get the react-native element? 

ps: Another solution could be using the same approach above and, just because I’m targeting react-native-web, using something like:

```js
const ballStyler = styler(this.ref) // react-native-web will use a real DOM node
```

**Comment by InventingWithMonster** [comment]
There's no such thing as a React Native element, that's the fundamental problem here. It's different on React Native Web as it runs on the DOM ultimately, but on apps it's quite different.

All you have are things they've implemented in React, that you get provided an interface to via React components. So you could animate a component's state:

```
.start(v => this.setState(v))
``` 

Or you could import `Animated` from React Native:

```
class MyComponent extends React.Component {
  x: new Animated.value(0)
  y: new Animated.value(0)

  startAnimation() {
    tween(props).start(({ x, y, }) => {
      this.x.set(x)
     this.y.set(y)
     })
  }

render() {
   return <Animated.View style={{ transform: [{ translateX: this.x }]}} />
}
}
```

(Rough example)

**Comment by InventingWithMonster** [comment]
Closing for now, though interested as to how you got on
