### ISSUE TITLE
PoseGroup, collapsing list items could customised?

### ISSUE THREAD

**Issue by crowemr** [Popmotion/popmotion#668]
Could I customise collapsing for items in React Pose?

**code**:

```
const Item = posed.div({
  enter: {
    opacity: 1,
    x: 0,

    transition: {
      x: {
        type: 'spring',
        velocity: 10,
        damping: 100,
      },
    },
    delayChildren: 20,
  },
  exit: {
    opacity: 0,
    x: '100%',
    transition: {
      x: {
        type: 'spring',
        velocity: 10,
        damping: 100,
      },
    },
  },
});
```

```
<PoseGroup>
       {
              this.props.list.map(type => (<Item key={type}>Hello Item</Item>))
       }
</PoseGroup>
```
When my Items exit DOM other Items from the list collapsing to top with default "bouncing" animation, so I want to remove this animation for typically easing animation.

Sorry for gif! But I did it for more clearer understanding.

gif of the issue
![screeny video 13 dec 2018 at 14 05 32](https://user-images.githubusercontent.com/26653363/49934886-9faf5f00-fee0-11e8-8c0e-7eb4e5bd11de.gif)

Is there any way to fix collapsing animation with PoseGroup?

**Comment by Andarist** [comment]
**I think** although not 100% sure, that you can customize `flip` pose which does this.

**Comment by InventingWithMonster** [comment]
Yeah exactly its a bit of a hack but if you provide a `flip` pose you can add `transform` just like any other pose and that will control this animation

**Comment by crowemr** [comment]
Thanks for responding. I tried several times and still can't change anything. Could you tell me how I can change transition prop for **flip**. 
My code below:
`
...    
flip: {
      transition: 'transform 300ms ease',
    }
...
`

**Comment by crowemr** [comment]
> Yeah exactly its a bit of a hack but if you provide a `flip` pose you can add `transform` just like any other pose and that will control this animation

could you show how to add custom transition [here](https://codepen.io/popmotion/pen/eMexyR)?

**Comment by Andarist** [comment]
https://codesandbox.io/s/zxjmqy7ln4

**Comment by crowemr** [comment]
> https://codesandbox.io/s/zxjmqy7ln4

omg, problem was that I tried configure **flip** inside **enter/exit**...
solve is:
```
const Item = posed.div({
  flip: {
    transition: {
      type: 'tween',
      ease: 'linear',
    },
  },
  enter: {
    ...
  },
  exit: {
    ...
  },
});
```

@Andarist thank you very much!

**Comment by SeedyROM** [comment]
@crowemr This is exactly what I needed, I feel like this is missing from the documentation. It seems PoseGroup automatically sets up Flip to have a spring effect, which is cool for a demo but annoying to actually use in the real world. Maybe set the default to not spring? I have no idea. :man_shrugging:

**Comment by osheinonen** [comment]
You can also disable the flip by setting `flipMove={false}` to the `PoseGroup`.
https://popmotion.io/pose/api/posegroup/#posegroup-props-flipmove
