### ISSUE TITLE
react-pose overrides unrelated CSS properties creating glitches

### ISSUE THREAD

**Issue by desmap** [Popmotion/popmotion#672]
## Ensure you're using the latest version
4.0.4

## Describe the bug
This bug overrides unrelated CSS properties during an animation creating glitches (like unwanted scrollbars)

## How to reproduce
1. Go to https://codesandbox.io/s/2v783085j0
2. Change the browser window size, make it smaller
3. You see unwanted scroll bars coming and going

Open Chrome Inspector and check the CSS props of the animated slide, you see that react-pose sets own props which differ from the original one, e.g. width and height get fixed px values. Before they were vh and vw (this creates the scrollbars)

Also top and left were overwritten (at least the same values this times). I don't know if other props might also be overwritten.

## Expected behaviour

No overriding of unrelated CSS props during an animation
This works flawlessly with react-spring which employs the same implementation: 
https://codesandbox.io/embed/morr206pv8

## Link to CodePen example (or similar)

see above

## Device information
In which environment are you reproducing the bug?
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by desmap** [comment]
@Andarist , thanks for the quick response and good to know. I was screening my code for two days, first suspecting React's useEffect for this glitch (since it is called with the empty array option), then Emotion and so on. Understanding what was really happening paired with testing, taking in and out other libs/components was a bit nerve-wracking. Also looking in the Inspector right from the beginning wouldn't have helped. I need to slow down all the animations to see what is happening.

I just checked the doc on popmotion.io and found only a FLIP option which seems to be somehow related but not the flipMove option. I think it would be great to mention it and/or stress that such an option exist. Another thought would be to turn it off as default and a small warning that if turned, glitches might happen. Then, you would have a hint where to search first. However, I guess that turning it off as default might break code...

**Comment by Andarist** [comment]
From what I know this won't be a default in the future, but it has to be changed in major version. I agree it should be emphasized more in the docs for the time being, would you be maybe able to help with that?

**Comment by desmap** [comment]
> would you be maybe able to help with that?

sure, not today but maybe next week...

**Comment by InventingWithMonster** [comment]
I do think that having it off by default will be the probably solution going forward

**Comment by desmap** [comment]
@Anadarist, I forked the repo and tried to get the package `site` working: After npm installed all packages and I installed nmh, I tried `npm run build` in the site folder but got an error, I pasted below error and debug log. Tried also yarn. Before this, I also npm-installed/-built the main folder (I think it was not required but just to be sure). Pls find below all error messages/logs.

For the sake of simplicity: We should already add following one-liner right at the beginning of the 'Enter/Exit transitions' page:

**_CAUTION: By default, FLIP animations are turned on for performance reasons. They might cause glitches which could be hard to debug. Turn them off with `{ flipMove: false }` and before you turn them on for production do in-depth tests. Find more information on the FLIP technique [here.](https://aerotwist.com/blog/flip-your-animations/). We might change the default setting to false with the next major version._** 

We could do of course more but this little sentence would already be a quick and easy fix. Would you mind adding this sentence as a first step, just to get started?

NPM errors:
```
Site content created
> Using external babel configuration
> Location: "/home/d/popmotion/packages/site/.babelrc"
> Using "webpack" config function defined in next.config.js.
> Failed to build on /tmp/feced96d-0c6a-4c91-bf1b-b7a153bec11a
{ Error: commons.js from UglifyJs
Invalid assignment [commons.js:101207,68]
    at /home/d/popmotion/packages/site/node_modules/next/dist/server/build/index.js:183:21
    at emitRecords.err (/home/d/popmotion/packages/site/node_modules/next/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/home/d/popmotion/packages/site/node_modules/next/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/home/d/popmotion/packages/site/node_modules/next/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/home/d/popmotion/packages/site/node_modules/next/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/home/d/popmotion/packages/site/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/d/popmotion/packages/site/node_modules/next/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/d/popmotion/packages/site/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/d/popmotion/packages/site/node_modules/next/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/home/d/popmotion/packages/site/node_modules/next/node_modules/webpack/lib/Compiler.js:354:15)
  errors:
   [ 'commons.js from UglifyJs\nInvalid assignment [commons.js:101207,68]' ],
  warnings: [] }
```

```
  1 0 info it worked if it ends with ok
  2 1 verbose cli [ '/home/d/.nvm/versions/node/v10.13.0/bin/node',
  3 1 verbose cli   '/home/d/.nvm/versions/node/v10.13.0/bin/npm',
  4 1 verbose cli   'run',
  5 1 verbose cli   'build' ]
  6 2 info using npm@6.4.1
  7 3 info using node@v10.13.0
  8 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
  9 5 info lifecycle popmotion-website@7.0.0~prebuild: popmotion-website@7.0.0
 10 6 info lifecycle popmotion-website@7.0.0~build: popmotion-website@7.0.0
 11 7 verbose lifecycle popmotion-website@7.0.0~build: unsafe-perm in lifecycle true
 12 8 verbose lifecycle popmotion-website@7.0.0~build: PATH: /home/d/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/d/popmotion/packages/site/node    _modules/.bin:/home/d/bin:/home/d/.local/bin:/home/d/.nvm/versions/node/v10.13.0/bin:/home/d/bin:/home/d/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/u    sr/local/games:/snap/bin:/home/d/.fzf/bin
 13 9 verbose lifecycle popmotion-website@7.0.0~build: CWD: /home/d/popmotion/packages/site
 14 10 silly lifecycle popmotion-website@7.0.0~build: Args: [ '-c',
 15 10 silly lifecycle   'npm run build-content && next build && next export -o public' ]
 16 11 silly lifecycle popmotion-website@7.0.0~build: Returned: code: 1  signal: null
 17 12 info lifecycle popmotion-website@7.0.0~build: Failed to exec build script
 18 13 verbose stack Error: popmotion-website@7.0.0 build: `npm run build-content && next build && next export -o public`
 19 13 verbose stack Exit status 1
 20 13 verbose stack     at EventEmitter.<anonymous> (/home/d/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
 21 13 verbose stack     at EventEmitter.emit (events.js:182:13)
 22 13 verbose stack     at ChildProcess.<anonymous> (/home/d/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
 23 13 verbose stack     at ChildProcess.emit (events.js:182:13)
 24 13 verbose stack     at maybeClose (internal/child_process.js:962:16)
 25 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
 26 14 verbose pkgid popmotion-website@7.0.0
 27 15 verbose cwd /home/d/popmotion/packages/site
 28 16 verbose Linux 4.4.0-140-generic
 29 17 verbose argv "/home/d/.nvm/versions/node/v10.13.0/bin/node" "/home/d/.nvm/versions/node/v10.13.0/bin/npm" "run" "build"
 30 18 verbose node v10.13.0
 31 19 verbose npm  v6.4.1
 32 20 error code ELIFECYCLE
 33 21 error errno 1
 34 22 error popmotion-website@7.0.0 build: `npm run build-content && next build && next export -o public`
 35 22 error Exit status 1
 36 23 error Failed at the popmotion-website@7.0.0 build script.
 37 23 error This is probably not a problem with npm. There is likely additional logging output above.
 38 24 verbose exit [ 1, true ]
```

Yarn build error:
`error Command failed with exit code 137.`

**Comment by Andarist** [comment]
> We could do of course more but this little sentence would already be a quick and easy fix. Would you mind adding this sentence as a first step, just to get started?

This is question to @InventingWithMonster but for me it sounds ok - I would only change the tone to be more informative than warning and would try to describe in short what kind of things might glitch with `flipMove={true}`. It's a great start though, could u prepare PR for it? We could discuss it further there.

As to `site` package - I've never ran it, but in general it should only require `yarn` in root directory and later some start script ofc. I might take a look at it later, but you can just edit docs without running the site package if u wont be able to run live demo locally.

**Comment by desmap** [comment]
>  but you can just edit docs without running the site package

This is considered to be bad practice. Even if it's just adding one paragraph. Layouts can break, wrong CSS style can be chosen and so on. Even if code reviewed: People should not request/push 'blind' commits. At the end they are more work for both maintainers and contributors.

I just tried again to setup a local env following the steps from the `CONTRIBUTING.md` and the build process of the site package crashed again with `error Command failed with exit code 1.` (within step 7 of `CONTRIBUTING.md`). I tried this on Ubuntu 16.04 and 18.04 with each node 10.14.2 installed.

Re your thoughts, a toned-down, informative version might be nicer (so just exchange 'CAUTION:...' by 'Be aware,...' and link to this issue to have an example) but it would be wrong and sugarcoating. I would recommend a strongly emphasized warning. This is no small thing and if you miss this little piece of important advice you run into days of trouble. If one is already using a sophisticated  animation lib like react-posed he intends to do pixel-perfect animations without popping-up scrollbars throughout his app and he must not miss this info. 

However, I also think that such a warning might give react-posed a negative connotation and scare people away. The terms 'warning' and 'glitches' right at the beginning of a page or even the entire doc could distract too much from react-posed' key features and its otherwise brilliant and simple API. Hence, I recommend to set `{ flipMotion: false }' as default ASAP.

If ok for all, I am going to close this issue since the actual problem was clarified, thanks for the support.

**Comment by InventingWithMonster** [comment]
Yeah there’s an issue with the site generator script at the moment. It only
works on my laptop and struggling to figure out what the difference is.

As a side note all the docs are written in markdown so it’d be quite
impressive if you could break the docs with it!

**Comment by desmap** [comment]
Hey Matt, thanks that you found some time to test the script.

> docs are written in markdown so it’d be quite impressive if you could break the docs with it!

I know. Everything else than Markdown would be a bit cumbersome. Of course, I wouldn't break any code with changing some Markdown but that's not the point in this particular case: I'd like to know how the end result looks. Are the styles right? Is the position right? Maybe better on the React entry page? Add a brief title? As h1 to h2 and so on. Without seeing it rendered, I could also email your the 'PR'.

C'mon, if it's just about adding one plain paragraph as Markdown as a quick fix and if it was really urgent (which I think it is because this undocumented default setting can drive people nuts), then you won't need a PR by a random dude and a Xmas-long discussion about this--then one might just add it without any PR (a draft is in this thread).

Let's rather change the flipMove default setting asap, fix the site's build script and I'll be super happy to contribute to a new page 'Perfomance Optimization' in the docs which give more details about flipMove and how to turn it on and not the way around. ;)
