### ISSUE TITLE
React-pose - Whole component re-renders when nested routes are triggered

### ISSUE THREAD

**Issue by albinmartinsson91** [Popmotion/popmotion#673]
## Describe the bug
Nested routes trigger the component they're nested inside to re-render. In my example I've set up a top level routes `<Route component={Tabs} path="/tabs" />` and inside the `<Tabs />` component I've added additional routes `<Route path="/tabs/:section" component={TabSection}/>`. When you navigate between different `<TabSection />`-components  the whole `<Tabs />`-component re-renders causing it to animate again.

## How to reproduce
1. Go to the /tabs route
2. Navigate between the different tab sections
3. See how the whole component e.g. `<Tabs />` re-renders each time a `<TabSection />` is routed

## Expected behaviour
I'd expect only the nested routes to fire and render when nested inside a component. Without the react-pose library the `<Tabs />`-component doesn't re-render while the `<TabSection />` renders as expected. 

## Link to Code Sandbox
https://codesandbox.io/s/wop354v6p7

## Device information
In which environment are you reproducing the bug?
 - Device: Macbook Pro
 - OS: MacOS
 - Browser: Chrome

**Comment by Andarist** [comment]
That's because of this line:
```js
<RouteContainer key={this.props.location.pathname}>
```

`<PoseGroup/>` tracks its children by their keys to know if they enter/exit/move. So by giving this a new key you tell PoseGroup to exit old child and enter new one - hence the animation.

**Comment by albinmartinsson91** [comment]
> That's because of this line:
> 
> ```js
> <RouteContainer key={this.props.location.pathname}>
> ```
> 
> `<PoseGroup/>` tracks its children by their keys to know if they enter/exit/move. So by giving this a new key you tell PoseGroup to exit old child and enter new one - hence the animation.

I see. Are there any examples or workarounds recommended by the creators for this kind of use-case as Pose requires a unique key?

**Comment by Andarist** [comment]
I don't know what you are trying to achieve exactly here. I think you just have to adjust your component structure to cover your needs. It's not that unique of Pose to do this - it's how React works, Pose only delays exiting children so it can perform animation, but `key` prop for React means that if it changes it's a new element and the old one should get unmounted.

**Comment by albinmartinsson91** [comment]
As you mention it's just the way react works. Seems like similar libraries have the same issue. For anyone interested I found that the only way to create different animations for top-level and nested routes is to explicitly send only the first part of the url as key.

`key={this.props.location.pathname.split('/')[1]}` works as a temporary solution for me until I find a sustainable solution. 

Thank you @Andarist !
