### ISSUE TITLE
onPoseComplete missing in react-native-posed

### ISSUE THREAD

**Issue by FezVrasta** [Popmotion/popmotion#674]
**Is your feature request related to a problem? Please describe.**
`onPoseComplete` is available for the web version but is missing on react native

**Describe the solution you'd like**
I'd like the same `onPoseComplete` to be available on react-native-posed

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Andarist** [comment]
Hm, just looking quickly through the source (not testing it) it seems there is an implementation for this here - https://github.com/Popmotion/popmotion/blob/master/packages/react-pose-core/src/components/PoseComponent.tsx#L92-L94

**Comment by FezVrasta** [comment]
Ok then it doesn't seem to work :-(

**Comment by Andarist** [comment]
Could u try to debug it? Probably making the fix shouldnt be too hard, but unfortunately I dont have experience with react-native to investigate it quickly

**Comment by Rusta** [comment]
@FezVrasta I'm successfully using `onPoseComplete` in a react-native project. Any chance you can post a repo that replicates the issue you are having as the problem may be specific to your implementation?

**Comment by FezVrasta** [comment]
I don't think I'll have time to look into it anytime soon, let's close this issue then.
