### ISSUE TITLE
disable animation

### ISSUE THREAD

**Issue by lifeiscontent** [Popmotion/popmotion#677]
**Is your feature request related to a problem? Please describe.**
is there a way to to disable animation and fallback to start/end states?

**Describe the solution you'd like**
for accessibility purposes I'd like to disable animations for users who prefer to not have animations enabled. I was thinking maybe there could be a Context which would allow this feature to be toggled on or off via a Provider.

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by InventingWithMonster** [comment]
There is a PR for this https://github.com/Popmotion/popmotion/pull/452
though there’s some bugs that need ironing out. But yeah I would like this
in

**Comment by typical000** [comment]
Hello! There is any more common way to disable animations using react-pose?
I have some kind of integration tests (launched with Puppeteer, inside headless chrome browser), where, as for me - animations are not obbligatory thing, and I want to disable them.

Now I'm doing thing like this:
```
// Some module with animation
const Animation = posed.div(
  defineAnimation({
    enter: {
      opacity: 1,
      scale: 1,
      x: 0,
      transition: {duration: ANIMATION_SPEED},
    },
    exit: {
      opacity: 0.5,
      scale: 0.8,
      x: '100%',
      transition: {duration: ANIMATION_SPEED},
    },
  }),
);

// defineAnimation.js (Just one place where I must write this hack :))
const defineAnimation = (animation) => (process.env.TEST ? {} : animation);
```
So I disable animations completely for test environment, without any need to modify all components that uses animations.

Anything works fine with single animated elements.
But not with *PoseGroup* :( I can't find any soulution how to disable animations between childrens inside group.

For more efficient "visual explanation", look at this sandbox:
https://codesandbox.io/s/312vxmpk3q
(Press "Add notifications" repeatedly and very quickly)

The question is - how to disable animation inside PoseGroup, when new children appears and shifts down already rendered things? Looks like it tooks some default animation around 300ms
