### ISSUE TITLE
React-Pose: Component factory type issue with props

### ISSUE THREAD

**Issue by jas99** [Popmotion/popmotion#678]
Hey @InventingWithMonster 
:1st_place_medal: Have to say awesome work on popmotion !!!

In popmotion/packages/react-pose/src/posed.tsx
```
export declare type ComponentFactory<T> = 
(poseConfig?: DomPopmotionConfig | DomPopmotionConfigFactory<T>) => ComponentType<any>;

```
does'nt it makes sense to return `ComponentType<PoseElementProps & T>` instead of `ComponentType<any>`

Is this somthing to do with not setting styles directly but via config? 

Thx
Jaspreet

**Comment by InventingWithMonster** [comment]
Yeah that's probably a good idea, you could open a PR if you can get it working. I tend to veer towards permissiveness when using a part of TS that I don't fully understand and might break things for consumers
