### ISSUE TITLE
compatibility problem

### ISSUE THREAD

**Issue by Army-U** [Popmotion/popmotion#679]
**Is your feature request related to a problem? Please describe.**

Browser: Android 4.4.4
Problem: popmotion uses CSS attr `transform` realize animation, it does not work in low version Android without prefix `-webkit-`.

**Describe the solution you'd like**

Autoprefix like `-webkit` `-moz-` `-ms-` `-o-` based on whether attr exists or not.

**Describe alternatives you've considered**

Nope.

**Additional context**

[Currently, is hard code here](https://github.com/Popmotion/popmotion/blob/master/packages/stylefire/src/css/build-styles.ts#L103)

**Comment by ssehacker** [comment]
+1

**Comment by LBRDan** [comment]
+1
