### ISSUE TITLE
Text effect

### ISSUE THREAD

**Issue by xavierfoucrier** [Popmotion/popmotion#681]
Hi Popmotion team!

I am trying to use **Popmotion Pure** to create a simple text effect to animate letters of a title from bottom to top: the container `h1` contains the text, each letter of the text are cuts in multiple `span` parts, each part are animated using a `tween` and a random `delay`, like this:

```js
// independantly animates each characters
Array.from(document.querySelectorAll('.char')).forEach(function(char) {
  const character = Popmotion.styler(char);
  character.set('y', '100%');

  Popmotion.chain(
    Popmotion.delay(Math.round(Math.random() * 250)),
    Popmotion.tween({
      from: '100%',
      to: 0,
      duration: 1000,
      ease: easing.cubicBezier(0.42, 0, 0, 1)
    })
  ).start(character.set('y'));
});
```

This code are producing **artefacts**, clearly some letters appears, then sometimes, go back to bottom, then reach the top. Randomly. When setting a constant delay instead of a random, it works fine, but the effect is not the expected one because each letter appears at the same time.

Here is a slow motion demo with duration:5000 and delay:4000 to see the issue:

![artefacts](https://user-images.githubusercontent.com/2471223/50591234-cd0f7d00-0e8e-11e9-8c03-bf1632bf7bad.gif)

May be I am using it the wrong way.
Thanks for your feedback!
:wink:

**Comment by Andarist** [comment]
Thanks for the repro case! I'll try to play with it in following days to see if I manage to find the problem.

**Comment by InventingWithMonster** [comment]
That's weird. It loos like the animations start from scratch intermitently.
Is it possible to put a console.log in the function that creates the
animations and see if its running more than once?

**Comment by xavierfoucrier** [comment]
I can confirm, the function is called once.

May be this will help you a little, but I have logged the output of the "y" character:

```js
(
...
).start({
  update: (v) => {
    character.set('y', v);

    if (char.innerText === 'y') {
      console.log(v);
    }
  },
  complete: () => {
    if (char.innerText === 'y') {
      console.log('complete');
    }
  }
});
```

... and it seems that sometimes, randomly, there are weird values generated by the update method: 2.842193680407945e-8%, 3.763291545055836e-8% or 4.91533569402236e-8% as soon as we get close to 0%.

:confused:

**Comment by xavierfoucrier** [comment]
@Andarist have you take time to reproduce the bug? thx

**Comment by InventingWithMonster** [comment]
@xavierfoucrier could you throw together a codesandbox example for this?

We could run some kind of `toFixed` rounding on the numbers to make sure we don't output values like these. But that doesn't explain IMO why the animations are starting from the beginning.

**Comment by xavierfoucrier** [comment]
@InventingWithMonster I will try to send you a codepen soon :wink:

**Comment by xavierfoucrier** [comment]
Well, it seem's that my code is properly working on CodePen using popmotion.global.min.js. https://codepen.io/xavierfoucrier/pen/BvOLQJ. I need to investigate more... :confused:

**Comment by xavierfoucrier** [comment]
Finally, I found the solution!

I am using `document.querySelectorAll('.char')` to animate the current title, but the page contains multiple titles, like the repro case!

The solution is to only **target chars inside the current title** element with `title.querySelectorAll('.char')` instead of using `document`, that will parse other title chars again, and give a random weird effect.

I close the issue :tada: :wink:
