### ISSUE TITLE
[React-Pose - <Transition>] Insertion index for leaving children doesn't take entering children into consideration

### ISSUE THREAD

**Issue by JabX** [Popmotion/popmotion#685]
Hello,
I'm a new user of `react-pose` and I'm currently rewriting my existing `react-motion` code with it, and it's truly a pleasure.

While using `<Transition>` to animate entering and leaving children in a list, I noticed that nothing was implemented to handle properly both entering and leaving children during the same render, as seen [here](https://github.com/Popmotion/popmotion/blob/master/packages/react-pose/src/components/Transition/children.ts#L150).

The problem arises when a leaving child is located after an entering child, so a quick fix I thought of that seems to work well (at least for my particular issue) was to shift the inserting index of the leaving child by the number of entering children that are located before the original index.

I have a PR with the change that you can see below, and I'd be happy to contribute so that it can be merged.

**Comment by InventingWithMonster** [comment]
Fixed in 4.0.5

**Comment by InventingWithMonster** [comment]
Yeah not sure how that happened, I thought I only posted once(!)
