### ISSUE TITLE
.each is not a function

### ISSUE THREAD

**Issue by tinchox5** [Popmotion/popmotion#69]
Hi, I tried to make some animation using .each() , but I got this error 'TypeError: listcontacts.each is not a function'. Here is my codepen http://codepen.io/tinchox5/pen/BoKvgZ

Thank you

**Comment by InventingWithMonster** [comment]
Release 2.0.4 has fixed this, the docs were out of date too:

```listcontacts.each((actor) => {
    actor.play({
        css: {
            rotateZ: 60,
            translateX: 18,
            translateY: 18
        }
    })
});```

**Comment by InventingWithMonster** [comment]
Amended version to 2.0.5
