### ISSUE TITLE
[React-Native-Pose] StaggerChildren not working properly

### ISSUE THREAD

**Issue by tmmgn** [Popmotion/popmotion#690]
## Description
Childs not appearing one by one as expected, after first item appears there is small delay and then all other childrens appears together
On first gif - behavior with staggerChildren
on second - without stagger

|behavior with staggerChildren|without stagger|
|----------|------|
| ![with](https://user-images.githubusercontent.com/11463030/50975551-f53a5400-14fe-11e9-9fd6-e97269bd1cb5.gif) |  ![without](https://user-images.githubusercontent.com/11463030/50975552-f53a5400-14fe-11e9-91d4-f9b016d7dada.gif) |

```javascript
const Overlay = posed.View({
  hidden: {
    staggerChildren: 0,
  },
  visible: {
    staggerChildren: 50,
  },
});
```

```javascript
const RouteBox = posed.View({
  hidden: { y: 0, scale: 0, opacity: 0 },
  visible: {
    y: ({ y }) => -y,
    scale: 1,
    opacity: 1,
  },
});
```

```javascript
<Overlay pose={this.state.active ? 'visible' : 'hidden'}>
    {this.renderActions()}
</Overlay>
```

and inside renderActions() I return
 ```javascript
return (
        <RouteBox key={`action_${i}`} y={y}>
          <Chip
            onPress={() => this.actionPressed(route)}
          >
            {route.title}
          </Chip>
        </RouteBox>
      );
```

## How to reproduce
1. Just follow this instructions https://popmotion.io/pose/learn/native-animating-children/

## Expected behaviour
Each children will appear one by one

## Device information
In which environment are you reproducing the bug?
 - Device: Google Pixel 2
 - OS: Android

**Comment by maryasdk** [comment]
Same thing happening with me on an iPhone 6, even if I implement the effect with a dynamic delay on children without the parent view staggering effect
