### ISSUE TITLE
react-pose: `onPoseComplete` does not fire on hover changes

### ISSUE THREAD

**Issue by IanVS** [Popmotion/popmotion#692]
## Describe the bug
I expected (and would really like!) for `onPoseComplete` to fire when I've set `hoverable: true` on the config and am animating between different states based on the hover.  Instead, it seems that it only fires when I set an `initialPose`, and then change the `pose` prop.

I can make a reproducible case if that helps, but hopefully this is clear enough.  Let me know if you have any questions and I can try to explain it better.

**Comment by Andarist** [comment]
> I can make a reproducible case if that helps, but hopefully this is clear enough.

Even for clear issues it always help to have reproducible example as it shortens the debug/feedback loop on library's maintainer side.

**Comment by Andarist** [comment]
I've prepared a repro for this - https://codesandbox.io/s/nnv3nq480j and dug a little bit into the code. Seems like this affects every "configurable" interaction (press, hover, drag)m focus).

The part of the code that sets this has no direct access to props, so Im not sure how to fix this properly - but I'll give it a thought.

**Comment by karibertils** [comment]
+1 would like to see this fixed
