### ISSUE TITLE
react-native-pose: simplest example is not working 

### ISSUE THREAD

**Issue by hatemalimam** [Popmotion/popmotion#694]
## Describe the bug
I have followed the [Hello World](https://popmotion.io/pose/learn/native-get-started/) example to animate a `View` between 'hidden' and 'visible' , but the box is as is.

Example:
**box.js**

``` jsx
const Box = posed.View({
  visible: { opacity: 1 },
  hidden: { opacity: 0 }
});

export default ({ isVisible }) => (
  <Box
    style={{ width: 100, height: 100, backgroundColor: "red" }}
    pose={isVisible ? "visible" : "hidden"}
  />
);
```

**App.js**

``` jsx
export default class App extends Component<Props> {
  constructor(props) {
    super(props);

    this.state = {
      isVisible: false
    };
  }

  render() {
    const { isVisible } = this.state;
    return (
      <View style={styles.container}>
        <Box isVisible={isVisible ? "visible" : "hidden"} />
        <TouchableOpacity
          onPress={() => {
            this.setState({
              isVisible: true
            });
          }}
        >
          <Text>Show Box</Text>
        </TouchableOpacity>
      </View>
    );
  }
}
```

## How to reproduce
1. Go to https://github.com/hatemalimam/RNPosedExample
2. clone the repo
3. `yarn && react-native run-ios` 
4. after that click on Show Box

## Expected behaviour
The box should be hidden, on clicking the button it should be visible and animated.

## Link to CodePen example (or similar)
https://github.com/hatemalimam/RNPosedExample

## Device information
In which environment are you reproducing the bug?
 - Device: Version 10.1 (SimulatorApp-877 CoreSimulator-581.2)
 - OS: iOS
 - React-Native Version: 0.57.8
 - react-native-pose Version: 0.9.0

**Comment by davidglivar** [comment]
@hatemalimam looks like a typo, change:

```
<Box isVisible={isVisible ? "visible" : "hidden"} />
```

to

```
<Box isVisible={isVisible} />
```

**Comment by hatemalimam** [comment]
@davidglivar yes indeed 😐
