### ISSUE TITLE
ReactPose does not work on ReactDOM.createPortal

### ISSUE THREAD

**Issue by reduxdj** [Popmotion/popmotion#696]
## Ensure you're using the latest version
CodeSandbox examples might not always be using the latest version of Pose.

## How to reproduce
Create any animation inside a react-pose element, and nest it inside a ReactDOM.createPortal render =  the animations style attributes are not modified, animation does not play.

## Device information
In which environment are you reproducing the bug?
 - Device: All
 - OS: OSX
 - Browser  All
 - Version 4.0.5

**Comment by Andarist** [comment]
Could u provide codesandbox with the issue reproduced?

**Comment by hegelstad** [comment]
I do not experience this problem. However I am experiencing some stuttering when the child component of Transition is exiting.
