### ISSUE TITLE
react-pose: Drag example not consistent in 4.0.5

### ISSUE THREAD

**Issue by melMass** [Popmotion/popmotion#700]
When trying to create a custom slider I tried to use this example as a base:
https://j27p9l3v6y.codesandbox.io/

But updating to 4.0.5 the example, the element goes back to initial pose on drag end...

## How to reproduce
1. Go to https://codesandbox.io/s/j27p9l3v6y?from-embed
2. Update `react-pose` to 4.0.5,
3. See error

## Expected behaviour
The element should stay where `dragend` unless specified.

## Link to updated example
https://codesandbox.io/s/8lq5mw4p08

**Comment by melMass** [comment]
Does anyone know how to make the drag with bounds not go back to the initial position on `4.0.5`?

**Comment by melMass** [comment]
Thanks @Andarist but it seems to be doing the same on 4.0.6 🙁

**Comment by melMass** [comment]
Ok I just understood this is the exact same issue as #704 I was not refering to negative values but the fact that the element goes back to it's initial positon !

**Comment by Florian007** [comment]
#730 > In react-pose@4.0.8 popmotion-pose needs to be manually upgraded to min version popmotion-pose@3.4.7
