### ISSUE TITLE
react-pose: Nothing animates (w/ react 16.8.0-alpha.1)

### ISSUE THREAD

**Issue by brentjett** [Popmotion/popmotion#715]
## Version
Using react/react-dom 16.8.0-alpha.1 (hooks) but to be fair, I rolled back to stable react and had the same outcome.

## The Bug
States work, in that they snap from one state to another, but no animations occur.

## How to reproduce
1. Install React/ReactDOM 16.8.0.alpha.1 (or alpha.0)
2. Install react-pose 4.0.6 (went back to 3.x and same outcome)
3. Try to animate something with posed.div or posed.li (those are what I was trying to use)

## Expected behaviour
Animations.

## Device information
In which environment are you reproducing the bug?
 - Device: 15" MBP (Late 2016 / touchbar)
 - OS: MacOS 10.14.3 (18D42)
 - Browser Chrome
 - Version 71.0.3578.98 (Official Build) (64-bit)

## Additional context
This was on the frontend of a WordPress site. There are other scripts present but no js errors.

**Comment by Andarist** [comment]
Could u prepare a repro case? It's hard to help without seeing the problem.

**Comment by brentjett** [comment]
Hi @Andarist, I have it in a repo here: [Pose Testing Branch](https://github.com/beaverbuilder/assistant/tree/testing-pose-animations)

If you look at [this file](https://github.com/beaverbuilder/assistant/blob/testing-pose-animations/src/front/ui/components/panel-parts/index.js) you'll see I have a `Box` component. Unfortunately just putting this component in the tree causes endless re-renders at the moment. That's an issue I wasn't originally experiencing but am now.

The intention here is a simple animation like making the panel slide on and off the screen. But my experience has been (before the re-render issue) that any animation attempts just snap to their end configuration rather than animate. I've tried the library a number of different ways. 

This is a WordPress plugin. You can build this scripts with `npm run build`. When active you can see the UI on the frontend of any page.

**Comment by Andarist** [comment]
This must be connected to how `PanelFrame` is used and probably what children does it have. Do any of them call setState in componentDidMount or smth?

Either way - you should define your `Box` OUTSIDE of render. It creates a component and if you rerender your PanelFrame React won't be able to tell that it's the very same component than before, similarly to this:
```js
const A = () => {
  const B = () => {}
  return <B/>
}
```

**Comment by brentjett** [comment]
Good catch! That solved the render craziness. Now if you look at it you'll see still no animation. I've even simplified it where the Frame is only returning a div and a button. For the life of me, i can't get it to animate anything.

This project isn't using any Class components, but rather the new hooks provided in react 16.8.0.alpha.1. So no, there's no `componentDidMount` stuff happening here.

**Comment by Andarist** [comment]
> This is a WordPress plugin. You can build this scripts with npm run build. When active you can see the UI on the frontend of any page.

What do you mean? I have no idea how to run this live.

**Comment by brentjett** [comment]
If you're unfamiliar with WordPress I understand. It's a very popular website content management system and this is a plugin for it. I don't currently have a public-facing instance running for you to look at. I appreciate your help. I'll just have to look at other animation options for this project.

**Comment by Andarist** [comment]
In general I would say that there is some mistake in your code, I can't help you validate it without running it myself unfortunately.

I've basically copy-pasted code (& adjusted it slightly) from your project [here](https://7m715zwyyq.codesandbox.io/) and it works.

**Comment by brentjett** [comment]
Thanks, that was helpful actually. I was able to take most of my application out and make the animation happen near the top of the component tree, so i'll look through my components and see where the problem is occurring. I appreciate your help!

**Comment by brentjett** [comment]
Closing this out. Problem was related to my component tree.
