### ISSUE TITLE
react-pose: supporting iOS 8 ?

### ISSUE THREAD

**Issue by littlee** [Popmotion/popmotion#719]
react-pose is great, but when running on iOS 8, it throw an error from the code here.

https://github.com/Popmotion/popmotion/blob/1b181ee1673003cb7239a2696623da3f494217be/packages/popmotion-pose/src/dom/unit-conversion.ts#L26

```
undefined is not an object (evaluating 'transform$$1.match')
```

and I think react-pose can use `webkitTransform` in legacy iOS to fix this.

one of my boss is using an iPhone with iOS 8.4, that's frustrating

**Comment by Andarist** [comment]
> iOS 8.4 was released on June 30, 2015.

And according to https://data.apteligent.com/ios/ this version has 0.1% of market share. This doesn't seem to warranty including code for those legacy purposes

**Comment by littlee** [comment]
Can't agree more, I will upgrade the system of my boss's iPhone without being noticed.

**Comment by littlee** [comment]
<img width="1184" alt="2019-02-09 11 06 19" src="https://user-images.githubusercontent.com/7534668/52515789-2f605800-2c5b-11e9-8bd9-a9507c3a1d07.png">

it turns out there are still hundreds of my end users that are using iOS 8
