### ISSUE TITLE
[Feature Request] Motion path

### ISSUE THREAD

**Issue by notsuretho** [Popmotion/popmotion#720]
In continuation to issue https://github.com/Popmotion/popmotion/issues/198

An API similar to [Anime.js motion path](https://animejs.com/documentation/#motionPath) would be great!

Also [responsive motion path](https://github.com/juliangarnier/anime/issues/234)

**Comment by InventingWithMonster** [comment]
This is coming in CSS https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Motion_Path
