### ISSUE TITLE
[react-pose] Performance Optimization for conditionally skipping animations

### ISSUE THREAD

**Issue by amcdnl** [Popmotion/popmotion#721]
## Issue
I have a chart that uses pose for enter/update/exit animations. The chart also allows users to zoom/pan the data. When a user starts trying to pan/zoom it staggers because its trying to run the animations (which are not needed) when a user is panning.

In this performance shot, you can see how much its doing:

![img](https://content.screencast.com/users/amcdaniel22/folders/Snagit/media/7d09c09b-dd6b-420d-828f-89c7770c1e45/2019-01-30_09-16-56.png)

If you dive deeper down into the stack, the majority of the time is spent starting/stopping the animations:

![img2](https://content.screencast.com/users/amcdaniel22/folders/Snagit/media/75cfbbc5-c8d5-4aca-b05d-0e01c9608c07/2019-01-30_09-18-54.png)

If we had the ability to turn off animations completely in a condition, this could really be optimized. I'm already doing this type of logic to kill the delay but its still running the flows -

```js
export const PosedCircle = posed.circle({
  enter: {
    opacity: 1,
    cx: ({ enterProps }) => enterProps.cx,
    cy: ({ enterProps }) => enterProps.cy,
    delay: ({ animated, index }) => (animated ? index * 10 : 0),
    transition: ({ animated }) => (animated ? transition : { duration: 0 })
  },
  exit: {
    opacity: 0,
    cx: ({ exitProps }) => exitProps.cx,
    cy: ({ exitProps }) => exitProps.cy
  }
});

```

Thoughts?

### Versions
```
"react": "^16.7.0",
"react-dom": "^16.7.0",
"react-pose": "^4.0.6"
```

**Comment by InventingWithMonster** [comment]
So this is actually quite difficult off the top of my head with Pose's current architecture. I have just implemented this feature (as a direct result of this issue) in a WIP library, which a future version of Pose might be built upon. But I won't have the time to personally implement this (open to PRs!)

If anyone fancies taking this on, `render={false}` is the API in the WIP library

**Comment by amcdnl** [comment]
@InventingWithMonster - Few ?s

- Whats the timeline for that? I'm assuming its a re-write so not soon.
- Is that code public?
- Can you point me in the direction of where this change might need to be made?

**Comment by InventingWithMonster** [comment]
No specific timeline - probs a few weeks for 1.0 but we’ll see. and the
code isn’t public yet

Thinking about it I’m not actually sure this is possible after all. Reason
being posers are immutable which doesn’t work well with reacts model. You’d
have to route a prop from React-pose -> Popmotion-pose -> pose-core,
exporting a new method in pose-core that allows something to flip a
shouldRender boolean

**Comment by amcdnl** [comment]
@InventingWithMonster - Any suggestions on how to accomplish this then?

**Comment by InventingWithMonster** [comment]
You could transition to the end state of the animation by having a dupe
pose and setting transition: false?

**Comment by amcdnl** [comment]
@InventingWithMonster - Can you show an example of what that would look like?

My current code is like this:

```
export const PosedCircle = posed.circle({
  enter: {
    opacity: 1,
    cx: ({ enterProps }) => enterProps.cx,
    cy: ({ enterProps }) => enterProps.cy,
    delay: ({ animated, index }) => (animated ? index * 10 : 0),
    transition: ({ animated }) => (animated ? transition : { duration: 0 })
  },
  exit: {
    opacity: 0,
    cx: ({ exitProps }) => exitProps.cx,
    cy: ({ exitProps }) => exitProps.cy
  }
});
```

In this example, I pass `animated` false when a user is panning to set the transition duration to `0`.

**Comment by amcdnl** [comment]
@InventingWithMonster - ^^ Any suggestions?

**Comment by Andarist** [comment]
You literally have to return `false` from transition factory to generate "instant" transition.

```js
export const PosedCircle = posed.circle({
  enter: {
    opacity: 1,
    cx: ({ enterProps }) => enterProps.cx,
    cy: ({ enterProps }) => enterProps.cy,
    delay: ({ animated, index }) => (animated ? index * 10 : 0),
    transition: ({ animated }) => (animated ? transition : false)
  },
  exit: {
    opacity: 0,
    cx: ({ exitProps }) => exitProps.cx,
    cy: ({ exitProps }) => exitProps.cy
  }
});
```

**Comment by mayteio** [comment]
I have the same problem. When rendering literally anything, the pose clogs up my computer and the frame rate drops to zero. 

*How can I tell `posed` and `PosedGroup` to animate only when their props change?*

@Andarist's solution still has the same laggy problem with Pose clogging the performance shot.

**Comment by amcdnl** [comment]
You can see the issue here when you drag - https://jask-oss.github.io/reaviz/?path=/story/charts-zoom-pan--default-zoom

Code is in this issue - https://github.com/jask-oss/reaviz
