### ISSUE TITLE
[react-pose] Custom window for instanceof checks when running in an iframe

### ISSUE THREAD

**Issue by bradbarrow** [Popmotion/popmotion#723]
**Is your feature request related to a problem? Please describe.**

When rendering a posed element inside an IFrame using something like 
https://github.com/ryanseddon/react-frame-component the instanceof checks in pose fail, because they are instances of `Element` on the IFrame `contentWindow` rather than the browser global window.

**Describe the solution you'd like**
It be nicest if pose could determine the window context automatically, perhaps with `ownerWindow` or something...otherwise a way to specify a window context? I'm not quite sure where...since it feels out of place in pose config

**Comment by Andarist** [comment]
Could u prepare a repro case for this and point to the lines of code which fail in pose?

**Comment by bradbarrow** [comment]
It's not a repo, but illustrates the issue :) 
https://codesandbox.io/s/v3qm561zo5

**Comment by bradbarrow** [comment]
https://github.com/Popmotion/popmotion/blob/master/packages/react-pose/src/components/PoseElement/index.tsx#L169

https://github.com/Popmotion/popmotion/blob/master/packages/react-pose/src/components/PoseElement/index.tsx#L188

**Comment by bradbarrow** [comment]
Any `instanceof SomeGlobalType` will fail when it's in a frame, with the source script running outside the frame :)

More here: https://github.com/seek-oss/playroom/issues/45

**Comment by bradbarrow** [comment]
Hi @Andarist - is there any more info I can provide? Have you got a gut feeling about whether this makes sense as a feature?

**Comment by quentez** [comment]
We're having the same problem when rendering in external windows.
We've made a fork of the lib for now, but would be interested in a longer term fix.

**Comment by quentez** [comment]
@bradbarrow We've ended up building a custom Babel plugin that replaces the `instanceof` implementation by something that's iFrame-aware as a general fix that we can apply to any package with a similar issue (we've seen quite a few).

**Comment by Andarist** [comment]
@quentez could u share the mapping which you have used? would be helpful now and in the future

**Comment by eramdam** [comment]
@Andarist I've uploaded a gist of the babel plugin @quentez is talking about. So far we've been using to apply on `react-pose` and `stylefire` without any apparent issues. 

https://gist.github.com/eramdam/c0ffb9d598509907f47f7c0e75f58dc0

Depending on how soon you're planning to fix this, we can look into publishing it as its own package (we're trying to use it ourselves first before doing that though 😬 )

**Comment by bradbarrow** [comment]
That's an outside the box solution :) Thanks for the stopgap :)
