### ISSUE TITLE
Question: does this work for route transitions in vuejs?

### ISSUE THREAD

**Issue by philippeluickx** [Popmotion/popmotion#726]
**Is your feature request related to a problem? Please describe.**
I am looking for a way to use animations when navigating through a vuejs app. Pose looks like a valid candidate, but I couldn't find any documentation if this is possible?

**Describe the solution you'd like**
Would be nice to know 1. if this is actually possible and 2. how to do it (explained in docs with an example)

**Describe alternatives you've considered**
I looked at React for inspiration and checked the pose-vue docs. Couldn't figure it out by myself.

**Comment by Kbitt** [comment]
I'm curious about this as well. The closest provided example [here](https://popmotion.io/pose/learn/vue-enter-exit-transitions/) provides nice enter and exit animations when `v-if` is toggled (and you can change it to `v-show` too). However, introduce `vue-router` and it seems the enter animation works but not the exit; upon transition to a new `router-view` the current view instantly disappears and the new views enter transitions begins. I have an example [here](https://codesandbox.io/s/vue-pose-posetransition-modal-example-wcl05)

**Comment by StephenStrickland** [comment]
Would also like to know
