### ISSUE TITLE
PoseGroup frame performance on numerous flip animations

### ISSUE THREAD

**Issue by hthief** [Popmotion/popmotion#727]
### Issue
Hi all, was hoping you could me

I've run into a performance issue which I'm trying to figure out the cause of. It's more noticeable in some browsers than others, but overall the animation result isn't as smooth as it could be.

The animation flow is supposed to work the following way: you remove an item, that items fades out, and then the grid items adjust themselves accordingly to their new position. The issue comes up when handling a large grid, say 100 or more items.

With a grid of around 100+ items, when you remove an item, everything cascades down and the animation suffers.
[Example on codesandbox, it's very barebones, sorry 😬 ](https://codesandbox.io/s/w746mp259k)

Barring any performance changes outside of react-pose, like say windowing, what could be happening? Is the flip config, in conjunction with delay, messing up? I also noticed while debugging that `measureWithoutTransform` gets called for each item that is moved; is there a way to give a fixed measure of the item so that it uses that value instead of always measuring?

### Versions
"react": "^16.3.2"
"react-pose": "^4.0.4"

**Comment by carlosagsmendes** [comment]
Hey @hthief I'm just getting started with React-Pose.

But I noticed that if I change your config from

```
const Item = posed.div({
  flip: {
    transition: props => tween({ ...props, duration: 400 }),
    delay: 150
  },
  exit: {
    opacity: 0,
    transition: {
      opacity: {
        duration: 150
      }
    }
  }
});
```

To:

```
const Item = posed.div({
});
```

the animation gets quite smooth. 

Maybe you can try to build your config in small steps to find out the bottleneck.

**Comment by hthief** [comment]
Yeah, probably the exit animation is doing too much, and maybe the tween is a bit resource heavy, but then it gets to the issue that those configs are how they're intended to look :/
