### ISSUE TITLE
React-Pose:  Draggable example no longer works

### ISSUE THREAD

**Issue by TonyLB** [Popmotion/popmotion#729]
Per the documentation, the dragEnd should allow you to specify a location to transition to after the drag is released.  Instead, it chooses the location of the release of the drag.

1. Pull from: https://github.com/TonyLB/react-pose-bug
2. npm start

Expect the div in the middle of the page to always try to return to center when released.  It does not.

**Comment by Andarist** [comment]
Thanks for the repro, it has allowed me to quickly find the problem - https://github.com/Popmotion/popmotion/pull/730

**Comment by InventingWithMonster** [comment]
Published as `react-pose@4.0.7`
