### ISSUE TITLE
react-pose: pose not applied for some strange reasons

### ISSUE THREAD

**Issue by izziaraffaele** [Popmotion/popmotion#731]
## Describe the bug
I have defined an input component (with styled-components) with `init`, `hover`, `focus` and `error` poses. Each pose animates the `color` and `border` css props to give users visual feedbacks while interacting with the input component.

At a first look everything works fine but if the input component reaches the `focus` or the `error` pose, the `hover` pose will never be applied anymore, even if the `pose` prop is changed correctly.

Unfortunately, I wasn't able to understand the reasons behind this strange behavior. 

## How to reproduce
1. Go to this [codesandbox example](https://codesandbox.io/s/4qqj715x69)
2. Try to hover the input field (border color should change)
3. Try to focus the input field (border color should change again)
4. Type something in the input field and click outside the input (border should return to the init state)
5. Try to hover again the field (border are not applied)
6. See error (check console to see the last pose)

## Expected behaviour
Whenever the `pose` prop changes I want animations to be applied

**Comment by Andarist** [comment]
You don't have to manage focus & hover yourself - let pose do it: https://codesandbox.io/s/8119kvp719 .

**Comment by izziaraffaele** [comment]
@Andarist I already tried that solution but I wasn't able to find a way to force the `error` pose in case there are errors (I don't want the `hover`/ `focus` pose to be applied in that case) so I tried to manage the state myself. That's actually how I encountered the problem.

**Comment by Andarist** [comment]
I've hacked this around - https://codesandbox.io/s/yp8zmn75zv . Aint too pretty though, API in the future will (most likely) allow disabling those interactions in a nicer way, but for now it's the best way in which I could make it work.

**Comment by izziaraffaele** [comment]
@Andarist thanks for the awesome hacky solution!!! at least I can move forward with my work using pose instead of traditional css. Disabling the interaction supported by default from pose will definitely solve the issue without hacks in the future.

Though, I'm not sure if you should close this issue as it wasn't related with my specific task. It's an issue with pose itself which, for some reasons unknown to me, doesn't play the animation even if the pose prop changes

**Comment by Andarist** [comment]
> Though, I'm not sure if you should close this issue as it wasn't related with my specific task. It's an issue with pose itself which, for some reasons unknown to me, doesn't play the animation even if the pose prop changes

That's true - I'm going to investigate it too.
