### ISSUE TITLE
PoseGroup and lazy component with Suspense

### ISSUE THREAD

**Issue by Tirlipinpin** [Popmotion/popmotion#732]
Hey guys,

I'm using the PoseGroup container on a react-router in which one my route components are lazy loaded with Suspense.

The problem occurs when I load these routes for the first time, the animation looses its mind because everything on the page is not rendered !

Is their a way to get around this issue ? With a waiting time for example ?

**Comment by Andarist** [comment]
You have to workaround this in your app, it's impossible to deal with it in here.

**Comment by Tirlipinpin** [comment]
@Andarist Thanks for you answer, I'll find a way to make it work somehow 😉

**Comment by krontill** [comment]
Hello @Tirlipinpin . How are you? Do you find a way to solve the problem?
I have the same problem...

**Comment by Tirlipinpin** [comment]
Hello @krontill I'm fine thanks for asking ! Unfortunately I haven't found a solution at the moment, I just don't do it...

**Comment by krontill** [comment]
I added a pose="enter" everywhere, 

`<PoseGroup animateOnMount>
                    <RouteContainer key={...}>
                      <Suspense fallback={<Loader />}>
                        <FadeIn pose="enter">
                          <Switch location={location}>
                            {routes.map(({ ... }) => (
                              <Route ... /> // all posed in the components <FadeIn pose="enter">
                            ))}
                          </Switch>
                        </FadeIn>
                      </Suspense>
                    </RouteContainer>
                  </PoseGroup>`

where FadeIn = export const FadeIn = posed.div(
