### ISSUE TITLE
How to transition number from 0 to x with react-pose

### ISSUE THREAD

**Issue by bflemi3** [Popmotion/popmotion#733]
How can I use react-pose to transition from 0 to a number (passed in as prop) upon page load? Something similar to this [react-animated-number demo](http://ameyms.com/react-animated-number/).

I know I can use `tween` to do this without React, but I'm having trouble getting this to work with react-pose. 

With tween
```javascript
const counter = document.querySelector('#a .counter');
const updateCounter = (v) => counter.innerHTML = v;

tween({ to: 1000, duration: 2000 })
  .pipe(Math.round)
  .start(updateCounter);
```
With my attempt, I'm failing to understand how to reflect `value` as it changes in the DOM.
```
const AnimatedNumber = posed.div({
    exit: { opacity: 0 },
    enter: {
        opacity: 1,
        transition: {
            duration: 2000
        }
    }
})

export default ({ value }) => (
    <AnimatedNumber initialPose='exit' pose='enter' to={value}>{value}</AnimatedNumber>
)

**Comment by Andarist** [comment]
Popmotion tries to short circuit react rendering by applying changes directly to the DOM - it's more performat this way. You can listen to value changes though, I've prepared a demo with how you can do it in 2 way - using React rerendering & direct DOM manipulation: https://codesandbox.io/s/5voqpr50mk

**Comment by bflemi3** [comment]
This is really educational and super helpful. Thank you so much :1st_place_medal:
