### ISSUE TITLE
react-post: dragEnd does not return element to original position, instead returning to where the mouse was released

### ISSUE THREAD

**Issue by drj17** [Popmotion/popmotion#734]
## Describe the bug
The example on the package website has the posed element returning to center, if you update to latest version, it only returns to the latest mouse position.

## Expected behaviour
I expected the square to return to center, but it does not
## Link to CodePen example (or similar)
https://codesandbox.io/s/4q2zl1qmy4

## Device information
In which environment are you reproducing the bug?
All devices have this issue.

**Comment by Andarist** [comment]
The fix for this was merged in already but not yet published - https://github.com/Popmotion/popmotion/pull/730#issuecomment-462892633

**Comment by designbyadrian** [comment]
`dragEnd` still doesn't work using react-pose 4.0.8 and popmotion-pose 3.4.8

**Comment by designbyadrian** [comment]
Doesn't matter. This is the pen borrowed from your [get-started page](https://popmotion.io/pose/learn/popmotion-get-started/) 

https://codesandbox.io/s/pose-sandbox-7477z

But the example page uses react-pose 3.0.1, so I scratched my head for a while wondering why it worked in your example. I changed it to 4.0.8 and the example no longer works.
