### ISSUE TITLE
Question: Flat list Items

### ISSUE THREAD

**Issue by sm2017** [Popmotion/popmotion#737]
How can I set animation for flatlist items? like https://popmotion.io/pose/learn/native-animating-children/

I want to apply animations like when you press Home at https://mzx1jz521p.codesandbox.io/

**Comment by gino8080** [comment]
same question

**Comment by brooksbecton** [comment]
I made a snack here: https://snack.expo.io/@broabect/react-native-pose-flat-list-bug

But I'm seeing an issue where items outside of the view are not being animated in.
