### ISSUE TITLE
[react-pose] Combination of flip and dynamic prop

### ISSUE THREAD

**Issue by bartlangelaan** [Popmotion/popmotion#739]
When there is a posed component that has `flip: true` set, and a dynamic prop, the dynamic prop isn't being re-calculated when the `poseKey` changes.

## Reproduce
I have made an CodeSandbox that shows the bug:

[![Edit React Pose - Dynamic prop with flip](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zl1z06o733)

There are two almost identical pose components, one _with_ `flip: true` and one _without_.

The one without flip animation nicely changes position every second, while the one with flip animation enabled doesn't move after its initial render. Both should move the same.

## Device information
Tested with:
- Browsers: Safari 12.0.2 and Chrome 71
- React-pose: 4.0.7

**Comment by Andarist** [comment]
I'm investigating this issue - but actually you don't need flip at all for animating `y`

**Comment by bartlangelaan** [comment]
@Andarist thanks for investigating!

I know that I don't need to flip for animating `y`. My actual use case is flipping between `top`, `left` and `right` properties with at the same time a dynamic `y` prop. But this was the most easy reproduction example I was able to make. :smile:

**Comment by Andarist** [comment]
So to be sure - you want your element to be in layout at certain position but you want to translate it visually to the other spot? This is something I've noticed isn't working while investigating this so far, I have some leads on how to fix this but I don't have much time lately, gonna work on fixing this though (hopefully I won't fail 😉 ).

**Comment by bartlangelaan** [comment]
This is close to my actual use case:

[![Edit React Pose #739 - Dynamic prop with flip with multiple poses](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0owlvj7j3v)

It has a pose with a static position, and a 'moving' pose that has a dynamic prop. The moving pose should move down a bit every second, but right now it is jumping between the 'transformed' and 'untransformed' y-axis.

> I don't have much time lately, gonna work on fixing this though

No hurry, just wanted to give you all the information I have. I'm not waiting for this fix, but I was thinking you wanted to know about this bug. And, it's open source, so you never have to excuse yourself for taking the time to fix stuff 😃

**Comment by Andarist** [comment]
So this new demo is showcasing another problem 😅 damn, won't be that easy to fix - need to think this through thoroughly
