### ISSUE TITLE
Make dragBounds respected even with transitions

### ISSUE THREAD

**Issue by alxsavard** [Popmotion/popmotion#742]
First things first, thanks for that library! Very well done and simple to use. 

I use react-pose a lot for handling dragging with inertia. So far so good, but one thing bothers me quite a lot. When you make something draggable and add dragBounds, the bounds are respected as long as the element is not in transition when passing the bound. 

Example: 
As long as I keep the mouse pressed, the element will never go out of bounds. Things is as soon as I add a dragEnd transition and I give the element a swing, it goes out of bounds. 
https://codesandbox.io/s/6z63ww9m9n
![kapture 2019-02-25 at 14 46 54](https://user-images.githubusercontent.com/11441711/53364190-44e8a980-390c-11e9-979e-02aa27951e68.gif)

It'd be really cool to have the bounds be respected even with transitions. If there's some use case I haven't think of that needs the bounds to be open during transitions, maybe we can add a props to do it?

I currently work around this by handling the animation myself and looking manually at where the element will end up and then correcting the end position if I need to. But this would literally 10's of lines in my code and simplify my life quite a lot!

If the feature sounds interesting to you I'm open to make a PR when I have the time.

Thanks!

**Comment by Andarist** [comment]
Seems like a problem. What is your expected result here? Should the element never go across drag bound? Or should it return to the drag bound if we make it go through it with inertia? Or something else?

**Comment by alxsavard** [comment]
In an 🌈ideal world 🦄 I'd say we should have control on what happens when the object hits a boundary, but for now if it could just stop and never go across it would be fine. (And probably way simpler to implement)

**Comment by Andarist** [comment]
WDYT @InventingWithMonster ?

**Comment by yogevlahyani** [comment]
+1

**Comment by designbyadrian** [comment]
@yogevlahyani instead of typing +1, use the thumbs up icon on the post.

**Comment by designbyadrian** [comment]
I'm experiencing this on react-pose 4.0.8

```
draggable: 'y',
dragBounds: { top: -100, bottom: 100 },
dragEnd: { transition: spring },
```

While dragging, the element stops at -100px and 100px, according to the dragBounds.

If I click, drag, then release, the element does _not_ return to position 0.

If I "flick" the element, it goes goes out of bounds with a bounce animation, and stops out of bounds as well.
