### ISSUE TITLE
Bounce Easing

### ISSUE THREAD

**Issue by magnusriga** [Popmotion/popmotion#743]
**Is your feature request related to a problem? Please describe.**
The request is for a bounce type of easing, as described on https://easings.net/ (e.g. easeOutBounce). GreenSock is an example of another library with this functionality. As I use Popmotion for all my animation work, it would be great to have these easings in Popmotion too.

**Describe the solution you'd like**
Either built-in bounce easings, or allowing us to make new easings with Penner functions.

**Describe alternatives you've considered**
I have tried to manually implement Penner functions, but it is messy and not ideal when applying several different animations in parallel. See my CodePen example: https://codepen.io/magnusriga/pen/jJPJzB?editors=0111

**Comment by Andarist** [comment]
I've prepared a PR for those - https://github.com/Popmotion/popmotion/pull/744
