### ISSUE TITLE
react-pose: on hoverable fill property is `NaN`

### ISSUE THREAD

**Issue by lifeiscontent** [Popmotion/popmotion#745]
## Ensure you're using the latest version
CodeSandbox examples might not always be using the latest version of Pose.

https://codesandbox.io/s/0qnp6j8n4v

## Add the package name to bug title
For instance, if this is a bug in Popmotion, write "Popmotion: Name of bug"

## Describe the bug

fill and stroke concat a `NaN` to its string value on hover.

**Comment by Andarist** [comment]
That's current limitation for color **names** - you can rgb or hsl because they are a numeric format and pose knows how to transition from one value to another https://codesandbox.io/s/525kz2j28x

**Comment by lifeiscontent** [comment]
@Andarist ah, ok, that makes sense.
