### ISSUE TITLE
react-pose 4.0.1 -> 4.0.2 upgrade makes tween bounce

### ISSUE THREAD

**Issue by szist** [Popmotion/popmotion#750]
1. With 4.0.1 and older there is no bounce when doing a simple tween animation (yoyo off, flip on).
2. Upgrading from 4.0.1 to 4.0.2 or newer versions causes the same animation to bounce and behave as if there was a spring or bounce animation involved.

The component is:
```
 <PoseGroup preEnterPose="preEnter">
        <SlideInOut key={uniq_key}>{children}</SlideInOut>
</PoseGroup>
...
const BASE_TRANSITION = { duration: 200, type: "tween" };
const SlideInOut = posed.div({
  enter: {
    x: 0,
    zIndex: 1,
    transition: BASE_TRANSITION
  },
  preEnter: {
    x: ({ direction }: Props) => (direction === "right" ? "100%" : "-100%"),
    zIndex: 3,
    transition: BASE_TRANSITION
  },
  exit: {
    x: ({ direction }: Props) => (direction === "right" ? "50%" : "-50%"),
    zIndex: 1,
    transition: BASE_TRANSITION
  }
})
```
Where the SlideInOut components are swapped out when switching between components.

When doing the same thing on a different project the exact same components work as expected. The changelogs do not suggest any breaking changes with dependencies. Re-installing all packages/clearing cache did not help.

**Comment by Andarist** [comment]
Could you prepare a runnable repro, i.e. on codesandbox? It would be of great help.

**Comment by gangwarily** [comment]
Take a look at this: https://codesandbox.io/s/v8q3ry1395?fontsize=14 (home.js in particular)

The use of the useContext() hook seem to be the cause of my issue. When I use other methods of managing render state (useState, props, etc), the additional bounce animation when switching between the two `return` calls are not present.

Let me know if you prefer a separate issue being opened.
