### ISSUE TITLE
react-native-pose [0.9.0]: enterAfterExit not working with opacity

### ISSUE THREAD

**Issue by lrholmes** [Popmotion/popmotion#754]
I'm experiencing an issue when animating `opacity` on a child to `Transition`, with the `enterAfterExit` prop enabled. When I use `y`, the animation works as expected, but when I add `opacity`, the first animation will occur, and then the new element will never transition in.

## How to reproduce
Snack reproducing: https://snack.expo.io/@lawrenceholmes/intrigued-soda
* Run the app
* Press toggle button
* Observe first element exiting, and next item not entering

## Expected behaviour
* First element exits, then next item enters

## Device information
In which environment are you reproducing the bug?
 - Device: iPhone 7 Plus
 - OS: iOS 12

**Comment by jbwhitcombe** [comment]
I can verify, this is a problem I'm experiencing too. In the meantime I'm using ScaleY.

**Comment by aroc** [comment]
+1, encountering this bug as well on 0.9.1. It seems present on 0.8.1 as well.

**Comment by masiamj** [comment]
Any news on this? Thanks for your great work!
