### ISSUE TITLE
[react-native-pose] animating width or height gives error

### ISSUE THREAD

**Issue by CyberMew** [Popmotion/popmotion#755]
The dreaded red box appears with the message:
Attempting to run JS driven animation on animated node that has been moved to "native" earlier by starting an animation with `useNativeDriver: true`

I am just starting out and I have this issue with this config:
```
const AViewConfig = {
  visible: {
    opacity: 1,
    width: 200,
  },
  hidden: { 
    opacity: 0.5,
    width: 100,
   },
};
const AView = posed.View(AViewConfig);
```
If I remove `width` OR `opacity`, all is ok, but I need them both to work in tandem. Any idea why?

**Comment by gbmsimoes** [comment]
Did you find a way to get this to work?

**Comment by CyberMew** [comment]
No I did not. I went back to React Native animations and it worked fine there. If you found a solution or workaround, please let me know!
