### ISSUE TITLE
why is react-pose almost as big as react-dom?

### ISSUE THREAD

**Issue by lifeiscontent** [Popmotion/popmotion#756]
Just curious why this is such a huge library. I'd like to use it but I might consider finding something a bit smaller due to the size of it.

**Comment by InventingWithMonster** [comment]
Hey man. It largely boils down to functionality, performance and convenience. Things like keyframes, spring, tween and physics animations, sane SVG transforms, template-less CSS transforms, unit type conversion all takes space.

**Comment by lifeiscontent** [comment]
@InventingWithMonster yeah, I guess that makes sense. any ideas on having the ability to selectively add features? I'd love to potentially strategize on this with you if you are interested!
