### ISSUE TITLE
React Pose Script Embed throwing errors (Dependency issue?)

### ISSUE THREAD

**Issue by mattcee233** [Popmotion/popmotion#758]
Hi, not sure if this is me just being an idiot but I'm unable to get Pose to work with React, I'm getting various errors when using the "<script src="https://unpkg.com/react-pose/dist/react-pose.js"></script>" method of installation.

Currently I'm including

    <script src="https://unpkg.com/react-pose/dist/react-pose.js"></script>
    <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>

and am either getting a "react-pose.js:1 - Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined" or "react-pose.js:1 - Uncaught TypeError: Vr(...) is not a function" error depending upon if react-pose is before or after react/react-dom includes respectively...

Please help :(

**Comment by mujtaba-ahmad** [comment]
Facing the same issue

**Comment by amirHossein-Ebrahimi** [comment]
having same problem tested in stack-blitz with site sample (`Magic animations`) and below versioning 
```json
  "dependencies": {
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "react-pose": "4.0.8"
  }
```
`Error in .../react-pose@4.0.8/dist/react-pose.js (1:54910)`
`Error: Vr(...) is not a function`

**Comment by SevereOverfl0w** [comment]
There is a slightly different error in 4.0.6 also. 4.0.0 seems to work, so does 4.0.4.

4.0.5 is where the alternative error starts (e is not defined).
