### ISSUE TITLE
"Get started" exemples not working in Firefox 41

### ISSUE THREAD

**Issue by lionel-bijaoui** [Popmotion/popmotion#76]
Everything seem fine in Chrome, but Firefox 41 don't work. Nothing happen.
I just discovered Popmotion, but this is kind of a deal breaker.
Please, can you fix this ?

**Comment by InventingWithMonster** [comment]
Browser update broke our (incorrect) way of testing supported `style` properties. This has been fixed in 3.1.2 - I'll update all our CodePens asap.

Many thanks for pointing this out @lionel-bijaoui !

**Comment by lionel-bijaoui** [comment]
You are welcome, thank you for fixing this.
