### ISSUE TITLE
Interia `dragEnd` after first drag - React Pose and Popmotion

### ISSUE THREAD

**Issue by bringking** [Popmotion/popmotion#761]
## Ensure you're using the latest version
Tested on 4.0.8 and 2.0.0
## Add the package name to bug title
React-pose, popmotion interia
## Describe the bug
A Posed Div is created and it marked as "draggable" on the y axis. A dragEnd transition is setup and using popmotion Interia. 

Using posed 4.0.8 results in the first drag using interia when released. The second drag no longer uses interia. 

## How to reproduce
1. Go to https://codepen.io/anon/pen/XGoOKq?editors=0010
2. Drag the white "drawer" and release for interia. Do it again, notice it fails
3. Click on settings. Then JavaScript. Change the unpkg URL to use react-pose@2.0.0. Save and close
4. Notice the drag and release behavior works every time
## Expected behaviour

When dragging and releasing the "drawer" it will use interia motion every time.
## Link to CodePen example (or similar)
 Go to https://codepen.io/anon/pen/XGoOKq?editors=0010

## Device information
In which environment are you reproducing the bug?
 - Device: [e.g. iPhone6] Macbook
 - OS: [e.g. iOS] OSX 10.14.3
 - Browser [e.g. chrome, safari] Firefox, Chrome 
 - Version [e.g. 22] Chrome 73, Firefox 66

## Additional context
N/A

**Comment by Andarist** [comment]
Thanks for the report - I've prepared a fix https://github.com/Popmotion/popmotion/pull/762
