### ISSUE TITLE
react-pose 4.0.4 -> 4.0.5 PoseGroup y value is reset to 0

### ISSUE THREAD

**Issue by EmilTholin** [Popmotion/popmotion#765]
## Describe the bug
`PoseGroup` disregards the value of `y` in the `enter` pose when the transition is complete and resets it back to `0`.

## Expected behaviour
It should stay on the `y` value of the `enter` pose like it did in version `4.0.4`

[CodeSandbox example showing the bug in `4.0.5`](https://codesandbox.io/s/y29040jzyj)  
[CodeSandbox example showing the correct behaviour in `4.0.4`](https://codesandbox.io/s/9yxnvw1npo)

## Device information
 - Device: MacBook Pro 2018
 - OS: macOS High Sierra 10.13.6
 - Browser: Chrome 73.0.3683.86

**Comment by Andarist** [comment]
It's quite a complex bug - unfortunately current flip algorithm has multiple edge cases. As you have demonstrated your issue on a demo (thanks for that!) it's hard to tell what your actual use case is- based on it maybe I would be able to offer some workaround until the issue gets fully resolved.

**Comment by EmilTholin** [comment]
Thank you for your insight @Andarist!

That's very kind of you, but you definitely don't have to make a temporary workaround for me. I noticed various types of entering/exiting components FLIPing on the Y axis behaving strangely when upgrading to `4.0.8`, I'm not sure my example is very pedagogical. There's no problem for me to use `4.0.4` in the meantime.

**Comment by purplesquirrels** [comment]
I'm also experiencing this issue. I was using 4.0.8, but rolling back to 4.0.4 the issue goes away.

I have a <MenuRenderer> component that renders fly-out menus in a PoseGroup based on a prop. When a menu was animated in, it would animate to the the correct X,Y location, then animate back to 0,0 for no apparent reason.
