### ISSUE TITLE
When user drags out of window, it should automatically let go

### ISSUE THREAD

**Issue by colindevs** [Popmotion/popmotion#77]
### Problem:
*If the user's mouse goes out of the window it should just let go, stop user input, etc...*
### Example:
![screen shot 2015-10-03 at 12 04 45 am](https://cloud.githubusercontent.com/assets/12850952/10261378/948bf988-6962-11e5-838d-6c010c0dc3b6.png)
### Code: 
I actually haven't take a look at the source code yet, so don't know how this could be done, I just noticed it while playing around at <a href="www.popmotion.io">popmotion</a>.
Once I take a look, I might find a solution!

**Comment by InventingWithMonster** [comment]
I think this is more an issue with the site than the framework, I feel like this is outside the scope of Popmotion (devs should decide when input events stop and start). Thanks for raising the issue though I'll think about it.

**Comment by colindevs** [comment]
Ok, thx for clarifying!

**Comment by Shuunen** [comment]
Can this be a solution ?

http://codepen.io/Shuunen/pen/XmRwpN
