### ISSUE TITLE
[react-pose] poseGroup transition delay causes weird lags

### ISSUE THREAD

**Issue by Fxlr8** [Popmotion/popmotion#770]
## Describe the bug
When pose's transition delay is not zero animation looks jerky.

## How to reproduce
1. Go to https://codesandbox.io/s/k31198y5mo
2. The timer will count down, you will see words "Ready", "Set", "Go!" instead of the last three numbers
3. Words animation is jerky
4. If you set animationDelay=0 on line 9 words animation becomes smooth again

## Expected behaviour
The animation is delayed for the desired amount of time and plays smoothly

## Device information
In which environment are you reproducing the bug?
 - Device: MBP 2016
 - OS: MacOS Mojave
 - Browser: Firefox
 - Version: 66

**Comment by hegelstad** [comment]
Happens on my machine too, don't know why.

**Comment by brettsnaidero** [comment]
I'm experiencing the same issue, getting some jank when I introduce `delay`:

![jank](https://user-images.githubusercontent.com/10969164/60234644-58bb1100-98e8-11e9-8424-66ee2b2bf97d.gif)

**Comment by brettsnaidero** [comment]
The issue only seems to be present when `flipMove` is turned on for the `<PoseGroup />`

**Comment by infokani** [comment]
Me too same problem.
