### ISSUE TITLE
React Pose: `overflow: hidden` not respected on exit animation

### ISSUE THREAD

**Issue by dimascyriaco** [Popmotion/popmotion#777]
The exit animation is not respecting the parent element's `overflow: hidden` property.

The enter animation works fine. The posed element appear only inside the parent element.

But on the exit animation the element goes over the boundaries of the parent element.

## How to reproduce
1. Add a posed element (inside a `PoseGrout`) inside an element with `overflow: hidden`.
2. Add this poses to the posed element:
```
  enter: {
    x: 0
  },
  exit: {
    x: -100
  }
```
3. Animate the element.

## Expected behaviour
The posed element should not go over the boundaries of the parent element.

## Link to CodePen example
https://codesandbox.io/embed/l3nxllz9x7

## Device information
Chrome 77
Solus 4

**Comment by acnebs** [comment]
You need to set `position: relative;` on `.box`, as the coordinate animations in Pose set absolute position on the child.

**Comment by dimascyriaco** [comment]
Yep. That resolved the problem.

That makes sense now that i'm thinking about it. But maybe it could be more clear in the documentation?

Anyway, thank you.
