### ISSUE TITLE
[React-Pose] Transition props not evaluated

### ISSUE THREAD

**Issue by Ghirigoro** [Popmotion/popmotion#779]
Setting transition properties via function doesn't work. In the example below I would expect both functions in the `extended` pose to be called but the one in the transition is not:
```ts
const Line = posed.div({
    retracted: {
        width: "0rem"
    },
    extended: {
        width: (props: Props) => {
            console.log("THIS IS CALLED");
            return `${props.width}rem`;
        },
        transition: {
            duration: (props: Props) => {
                console.log("THIS IS NOT CALLED");
                return props.duration;
            }
        }
    }
});
```

This is running on:
**OS:** OSX 10.14.14
**Browser:** Vivaldi 2.4.1488.40 (Stable channel) (64-bit) the version 
**React:** 16.8.4 
**React-Pose:** 4.0.8
**Typescript:** 3.3.3333

**Comment by msheakoski** [comment]
"rem" is not a supported value type. Use a number (which represents px) or one of the supported units in https://github.com/Popmotion/popmotion/tree/master/packages/style-value-types

**Comment by Ghirigoro** [comment]
Sorry, I must be missing something but that doesn't make sense to me. The function that uses `rem` ***does*** work but the one that uses a simple number ***does not*** work. Also regardless of the unit the arrow function should still be evaluated.

**Comment by msheakoski** [comment]
@Ghirigoro my apologies, I misread your example. I believe you need to specify width as a top-level property inside of transition if you want to do a special calculation for it. [See in the docs here](https://popmotion.io/pose/api/react-config/#config-options-poses-transition) where it shows "x" and "default":
```javascript
extended: {
    width: (props: Props) => {
        console.log("THIS IS CALLED");
        return `${props.width}rem`;
    },
    transition: {
        width: {
            duration: (props: Props) => {
                console.log("THIS SHOULD BE CALLED NOW");
                return props.duration;
            }
        }
    }
}
```

**Comment by Ghirigoro** [comment]
@msheakoski Thanks for updating your response and sorry for not responding sooner (was traveling). I tried your suggestion but the props in transition still does not get called:
```ts
const GrowingLine = posed.div({
    retracted: {
        width: "0rem"
    },
    extended: {
        width: (props: Props) => {
            console.log("I get called");
            return `${props.width}rem`;
        },
        transition: {
            width: {
                duration: (props: Props) => {
                    console.log("I do not");
                    return props.duration;
                }
            }
        }
    }
});
```

**Comment by msheakoski** [comment]
Hmm I thought that would do the trick :( If you can make a simple example on https://codesandbox.io it would be easier to figure out what is going on.

**Comment by Ghirigoro** [comment]
Here's a link to the sandbox: https://codesandbox.io/embed/7464vn118j
Thanks for taking a look.

**Comment by msheakoski** [comment]
I found something that works after seeing https://popmotion.io/pose/api/react-config/#config-options-poses-transition. Check the part where it says "A function that returns a transition definition or a Popmotion animation".

The entire transition property needs to be a function that returns the transition config. You should now see it respect the duration set via the prop (I added a couple other properties to demonstrate the transition config).

[![Edit zn5x1kqm1x](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zn5x1kqm1x?fontsize=14)

**Comment by Ghirigoro** [comment]
Thanks for digging into this! Much appreciated
