### ISSUE TITLE
[react-pose 4.0.8]  memoize_cjs is not a function (umd  build)

### ISSUE THREAD

**Issue by sgilligan** [Popmotion/popmotion#781]
When using UMD builds of popmotion@7.6.8 and react-post@4.0.8, the error 'memoize_cjs is not a function' is thrown and the package will not work.

Steps to reproduce:
1. Go to https://dmap.io/testcase/react-pose.1/
2. Observe the error thrown in the js console

Expected behaviour is for this error not to be thrown.
Test MacOS, chrome/firefox

**Comment by mujtaba-ahmad** [comment]
Found any solution for that ?

**Comment by sgilligan** [comment]
@mujtaba-ahmad, no I haven't. Until fixed, the latest version of the UMD build I can use is popmotion@8.6.4 and react-pose@4.0.4.

**Comment by amirHossein-Ebrahimi** [comment]
same problem.
Are these issue tracked by react-pose team ? 
the nearest merged branch was for `Fix/improve type matching (#790)` 25 days ago. Is there any responsibility for thier team to answer these issues?
