### ISSUE TITLE
popmotion and framesync

### ISSUE THREAD

**Issue by msdobrescu** [Popmotion/popmotion#788]
Hello, I am not using typescript, node and other fancy stuff. Just javascript.
I try to understand another library that uses Popmotion and Framesync.
So, I have downloaded Popmotion Pure and I try to work with Framesync too.
Is Framesync included in Popmotion? If so, how to access it?
If not, how to use Framesync. If I include it separatedly, from https://unpkg.com/framesync@4.0.2/dist/, it throws an error:

`ReferenceError: process is not defined[Learn More] framesync.js:19:3
    <anonymous> framesync.js:19
    <anonymous> framesync.js:4
    <anonymous> framesync.js:1`

What is the proper way to do this? Is this a bug?

**Comment by InventingWithMonster** [comment]
Closed for inactivity
