### ISSUE TITLE
[Question] How do I get animation to occur for when just the prop changes but no change in pose?

### ISSUE THREAD

**Issue by bilal-fazlani** [Popmotion/popmotion#789]
Thank you for this amazing library.
I have a requirement and I am not sure if it possible with this library though.

Say there is a SVG line and a TextBox. Users can enter a number in text and as they change the value of textbox I want the svg line to move with an animation. I want to highlight that there are no fixed number of poses here because user can enter any value.

```js
const Line = posed.line({
    default: {
        x1: (props) => props.x1,
        y1: (props) => props.y1,

        x2: (props) => props.x2,
        y2: (props) => props.y2,
    },
})
```

```js
    <svg>
        <Line stroke={"black"}
              strokeWidth="4"
              pose={'default'}
              x1={this.state.x1} y1={this.state.y1} x2={this.state.x2} y2={this.state.y2}
        />
    </svg>
```

I tried to achieve this with just one state called "default" and used [Dynamic pose props ](https://popmotion.io/pose/learn/dynamic-props/) to change coordinates of line. However since there is no change in pose, line coordinates do change but without any animation.

How do I get animation to occur for when just the prop changes but no change in pose?

**Comment by msheakoski** [comment]
Have a look at the poseKey prop https://popmotion.io/pose/api/posed/#posed-props-posekey. You can do something like this:
```jsx
const MyComponent = () => {
    const [poseKey, setPoseKey] = useState(Date.now());
    return (
        <Line pose="default" poseKey={poseKey}/>
        <input type="text" onInput={() => setPoseKey(Date.now())}/>
    )
}
```
Every time a character is typed in the input, the poseKey gets set to a new value and it triggers the animation to run.

**Comment by bilal-fazlani** [comment]
That worked! Thank you so much!
