### ISSUE TITLE
Popmotion@8.6.9 getActionCreator is not a function

### ISSUE THREAD

**Issue by ar7casper** [Popmotion/popmotion#794]
On version 8.6.9 - getActionCreator results in a typeError. 

It's missing `var actionCreator = createAction;` (in dist/popmotion.es.js).

Reverting to 8.6.8 fixed the issue.

**Comment by kbrock84** [comment]
> Try setting “500” to 500 - I’ll add better handling around this


😳 Well that's embarrassing. Seems like it's working now.

**Comment by adamthewan** [comment]
We are also getting this crash on our dev localhost every few minutes. It seems to be ok on production though

**Comment by InventingWithMonster** [comment]
Looking into a fix now

**Comment by InventingWithMonster** [comment]
This *should* be fixed on `8.6.10` - please install and let me know if it fixes your use-cases.

**Comment by Sudbina** [comment]
I'm getting this error on react-pose 4.0.8 only when an animation starts, it doesn't stop anything from working (that I know of) but was wondering if this is the same issue as above, just on the react-pose lib instead?

**Comment by rlems** [comment]
Updating to `8.6.10` solved this issue for me.

**Comment by bilal-fazlani** [comment]
Working now! thanks!

**Comment by rovansteen** [comment]
Still having this issue with `react-pose@4.0.8` which requires `popmotion@8.6.9` any chance that it can be updated to bump the popmotion dependency?

**Comment by yeehaa123** [comment]
@rovansteen same here. Is there a way to bump popmotion independently from react-pose?
