### ISSUE TITLE
[react-pose] Clone on Drag

### ISSUE THREAD

**Issue by amcdnl** [Popmotion/popmotion#796]
## Request
I would like the ability to clone an element when a user drag and drops it and then on drop, remove the cloned element.

### Use Case
A user has a list of items they can drag and drop them into a canvas. When a user starts dragging, rather than move the item they are dragging create a clone so that a user could drag it again.

Example use case: https://codesandbox.io/s/q356vp2v94?fontsize=14

**Comment by designbyadrian** [comment]
This is an animation library. You can listen to the `dragEnd` event, but otherwise I'd suggest https://github.com/react-dnd/react-dnd

**Comment by amcdnl** [comment]
I agree but given the drag functionality, its almost like why have drag?

I ended up implementing this on my own: https://github.com/jask-oss/reaviz/blob/master/src/common/Gestures/Move.tsx because its used in a SVGs.

**Comment by InventingWithMonster** [comment]
Yep Pose does support gestures also, explicitly. I think the feature's a
great idea but we'll probably be implementing it in a different library.
