### ISSUE TITLE
Simulation being called in "onComplete" for another simulation isn't having an affect

### ISSUE THREAD

**Issue by cmalven** [Popmotion/popmotion#80]
I'm attempting to fire a simulation inside of the `onComplete` callback inside of another simulation, but even though I can tell that the second simulation starts (through a `console.log` inside of the `onStart` callback) the simulation isn't having any affect, and I'm having a hard time figuring out why.

Test case: http://codepen.io/cmalven/pen/vNxawg?editors=001

**Comment by InventingWithMonster** [comment]
Good find, this is weird. I'll take a look today, thanks.

**Comment by InventingWithMonster** [comment]
@cmalven Hey man I just pushed a fix for this 3.1.3

Thanks for bringing it to my attention.

Also you might be interested in the `stopSpeed` property - it stops an Simulate action automatically if its absolute speed drops below that number, ie

    rotateZ: {
        velocity: 300 * currentVelocity,
        friction: 0.1,
        stopSpeed: 100
    }
