### ISSUE TITLE
[react-pose] Strange behaviour with nested posed components

### ISSUE THREAD

**Issue by dimascyriaco** [Popmotion/popmotion#800]
## Describe the bug
Nested components seams to affect each other pose. Don't know if this is the intended behaviour.

![nested-posed-components](https://user-images.githubusercontent.com/65256/57573801-5407cf80-7404-11e9-8db6-3ff49880f964.gif)

## How to reproduce
1. Click the 'activate' button of the 'Big Box' component.
2. See how Box 1 and Box 2 changes color even though their states (and poses) are 'inactive'.

## Expected behaviour
I would expect that the inner boxes to maintain their poses.

## Link to CodePen example (or similar)
https://codesandbox.io/s/vylrwyn14l?fontsize=14

## Device information
In which environment are you reproducing the bug?
 - Device: Desktop
 - OS: Linux
 - Browser Firefox/Chrome
 - Version 4.0.8

**Comment by danilotorrisi** [comment]
I encountered a similar bug, if a posed component B is inside a posed component A like:
<img width="180" alt="Example Screenshot" src="https://user-images.githubusercontent.com/608595/57837518-44e99e80-77c3-11e9-8871-97625b4979e6.png">
If both component are hoverable with two different transitions, when I hover inside the parent component A also the child component B gets the hover transition. Don't know if this may be related or not.

**Comment by shiftonetothree** [comment]
parent and it's child should use different  `pose` name, such as `activateParent`, `activateChild` may solve this

**Comment by broyde** [comment]
I've created one more example:
https://codesandbox.io/s/react-pose-animating-between-value-types-height-ms0mj

As a workaround, I'm planning to use unique animation names for each component instance.
