### ISSUE TITLE
Popmotion: SVG line drawing playground on CodePen is not working

### ISSUE THREAD

**Issue by 0x416c69** [Popmotion/popmotion#803]
Well, I know you know how it used to work, it supposes to rotate, it's just solid now.
https://codepen.io/popmotion/pen/yPxNao

## Device information
In which environment are you reproducing the bug?
 - Device: Normal Computer?
 - OS: Latest Windows 10
 - Browser Latest Chrome
 - Version Latest

**Comment by 0x416c69** [comment]
Seriously, I want the fixed code!

**Comment by DamianEl** [comment]
There is some kind of bug with latest version, change it to 8.4 and all works fine.

https://codepen.io/DamianEl/pen/vwQGPO

**Comment by 0x416c69** [comment]
Just to update, 8.6.1 is not ok.

Although somehow demo in website is ok: https://popmotion.io/pure/

**Comment by InventingWithMonster** [comment]
Updated
