### ISSUE TITLE
Ability to unmount when animation is complete without <PoseGroup/>?

### ISSUE THREAD

**Issue by johot** [Popmotion/popmotion#807]
I have currently created some animations for showing / hiding some input fields. I basically have an `<ExpandAnimation />` component that I wrap my inputs in and on that `ExpandAnimation` component I have a `show` prop that gets converted into a pose for an underlying `posed.div`.

Now I want to make sure the wrapped input gets removed from the DOM when the animation is completed. The only way to do this I found was to use a `<PoseGroup/>`.

Is there any sense in adding an `unMountOnExit` prop for a `posed.div` for simpler scenarios where you do not want to add a full `<PoseGroup />` (or is there no sense in that)? 

Thank you for a great library!

**Comment by Andarist** [comment]
Unfortunately there is no sense in that. It's because of how React works - it always tries to sync DOM with returned elements. PoseGroup works because it tracks the children you give it and rerenders with them or without them at certain stages of the animation, but a single element can't do that.

If you really want to make it you can make a component which would render your content conditionally but you'd have to handle exit/enter states "manually", smth along those lines:
```js
const Posed = posed.div({
  // define those transitions
  enter: {},
  exit: {}
});
function ExpandAnimation({ show }) {
  const [isShown, setIsShown] = React.useState(show);

  if (show && !isShown) {
    setIsShown(true);
  }

  return isShown ? (
    <Posed
      pose={show ? "enter" : "exit"}
      onPoseComplete={pose => {
        if (pose === "exit") {
          setIsShown(false);
        }
      }}
    />
  ) : null;
}
```

**Comment by johot** [comment]
@Andarist Thank you for your feedback!

Your implementation actually looks really close to what I have, nice! But I found that if I unmount the `posed.div` the animation behaves a bit strange. The animation will for example "pop" back in after unmounting / then mounting back. Probably because the `posed.div` contains some internal state that gets reset?

Also I moved over to using a ref instead of `useState` because calling `useState` during render caused a lot of strange things to happen (+ extra rendering) and as far as I know you should try avoid calling `setState` during render?

However I got a perfectly working solution by conditionally rendering it's children (and using an "exited" ref) instead:

```ts

export function ExpandAnimation(props: ExpandAnimationProps) {
  const exited = useRef(!props.show);
  const forceUpdate = useForceUpdate();

  if (props.show) {
    exited.current = false;
  }

  return (
    <PosedDiv
      onPoseComplete={(pose: CurrentPose) => {
        if (pose === "exit") {
          exited.current = true;
          forceUpdate();
        }
      }}
      pose={props.show ? "enter" : "exit"}
      style={{ overflow: "hidden" }}
      {...props}
    >
      {exited.current ? null : props.children}
    </PosedDiv>
  );
}

export function useForceUpdate() {
  const [, setTick] = useState(0);
  const update = () => {
    setTick(tick => tick + 1);
  };
  return update;
}

```

**Comment by Andarist** [comment]
> Your implementation actually looks really close to what I have, nice! But I found that if I unmount the posed.div the animation behaves a bit strange. The animation will for example "pop" back in after unmounting / then mounting back. Probably because the posed.div contains some internal state that gets reset?

Hm, this shouldn't be the case - posed.div can't hold state, because its instance is controlled by React. If a component unmounts it loses its all state and when it remounts it's being instantiated fresh.

If you want to share your implementation with me on codesandbox I could take a look at it.

**Comment by johot** [comment]
Yes I will see if I can get to it tomorrow. But anyways something happens when a posed.div gets unmounted, as you say it starts fresh. Will that not affect the animation in any way you say? And I guess some kind of state must be kept somewhere since we are talking about an animation over time?

What I think happens is that if a posed.div renders the first time it will not animate unless setting `initialPose`. So basically if I unmount the `posed.div` on exit and then create a new `posed.div` when the animation should start again, the animation will "pop in" since it's a new component instance. So basically it is working as intended, but in my case it causes problems.

Does this sound reasonably?

**Comment by Andarist** [comment]
Yes, sounds reasonable. And as you have noticed - initialPose is the way to fix it.
