### ISSUE TITLE
Popmotion: physics.setSpringTarget() doesn't handle partial completions

### ISSUE THREAD

**Issue by danielpaull** [Popmotion/popmotion#808]
When animating a composite value (such as animating X and Y) using the physics animation, some components may not animate to the new target value when the target is updated via setSpringTarget().

It appears that if the animation for a given component completes (ie, it's velocity drops to zero) before the composite animation completes, then the completed component does not start animating again when the new target is set.

## How to reproduce
Create an animation that requires no interpolation for one component, like from { x: 0, y : 0 } to { x: 100, y: 0 } - notice that "y" requires no interpolation.  Then, while the animation is running, call setSpringTarget() with a target that requires interpolation of that component, like setSpringTarget( { x: 200, y: 100 } ).  When the animation completes, the final value will be { x: 200, y: 0 } in the example given.

I expect that the problem is that the animation of "y" completed before the call to setSpringTarget() and it does not get restarted as a result of calling setSpringTarget().

## Expected behaviour
All components should animate correctly and the final value should be the spring target.

## Link to CodePen example (or similar)
https://codepen.io/monarodan/pen/xNaOWg

The Pen animates three boxes and all should end up in the same location because a call to setSpringTarget() is made for each running animation that makes them all target the same final point.  But, the blue box does not.

## Device information
Chrome on Windows, but expected to affect all devices and platforms.

**Comment by stokesman** [comment]
I've ran into this as well. It can be avoided by adding `restSpeed:false` to the physics props (which isn't in the docs, I noticed it in a codepen demo). Of course, doing so means the action will not complete and one would have to write their own logic for that if needed.
