### ISSUE TITLE
codepen typo

### ISSUE THREAD

**Issue by panzerstadt** [Popmotion/popmotion#809]
hey i was just following along on the FLIP tutorial and the tutorial didn't work. found out it was a typo, was wondering if you could update that for future users!

this one: https://codepen.io/popmotion/pen/BrmGmR

<img width="719" alt="Screen Shot 2019-06-03 at 19 07 16" src="https://user-images.githubusercontent.com/18601248/58794514-56d89780-8633-11e9-82d5-01fae204eb8f.png">

**Comment by InventingWithMonster** [comment]
This is fixed now
