### ISSUE TITLE
Feature request: React Pose, animating overflow hidden / visible

### ISSUE THREAD

**Issue by johot** [Popmotion/popmotion#812]
Thank you for a great library!

I am currently trying to create an expander animation. What I want is for `overflow` to be set to  `hidden` until the animation is completed (the expander is expanded). In that case I want to revert back to `overflow: 'visible'`.

I can't seem to find a way to do so. The overflow value is never changed during animation. Is string values currently not supported?

This is my current pose config: 
```ts
{
        exit: {
          height: 0,
          overflow: "hidden",
          transition: {
            duration: props.duration ? props.duration : 200,
            ease: "easeInOut"
          }
        },
        enter: {
          height: "auto",
          overflow: "visible",
          transition: {
            duration: props.duration ? props.duration : 200,
            ease: "easeInOut"
          }
        }
      }
```

I've also tried using stuff like keyframes but to no effect. I also thought about setting overflow manually using `onPoseCompleted`, could probably work but it would be easier if there also was an `onAnimationStarted`. I can't find such a prop?

Can this be done or is this a new feature that needs to be built?

Thank you very much!

**Comment by InventingWithMonster** [comment]
You can use applyAtStart/applyAtEnd for this
https://popmotion.io/pose/api/config/#config-options-pose-config-applyatstart/applyatend

**Comment by johot** [comment]
Wow thank you @InventingWithMonster I totally missed it most likely because I only read the getting started docs and missed the API docs, will try at once. I will close this now and thank you for your time and library!
