### ISSUE TITLE
everything is being called twice

### ISSUE THREAD

**Issue by holyxiaoxin** [Popmotion/popmotion#82]
When an actor or tween or simulate is being called, it happens twice. A onComplete: function(){ console.log('completed');} would replicate this.

**Comment by InventingWithMonster** [comment]
@holyxiaoxin Could you provide a full example, ie a CodePen? Because I haven't encountered this and want to know your full setup so I can investigate further.

**Comment by holyxiaoxin** [comment]
I'm sorry. this was my own configuration error.
