### ISSUE TITLE
All the examples on "Constrain Motion" page is not working

### ISSUE THREAD

**Issue by laychinhan** [Popmotion/popmotion#831]
Hi, so i'm new to popmotion, still learning it, i don't know if this is the appropriate place to ask, but since i try to google it and find no solution for it.
When i'm at the ["constrain motion"](https://popmotion.io/learn/constrain-motion/), i notice that all of the examples is not working.

Can anyone help to point out where the error is or maybe create a working one on codepen.

Thank you!

**Comment by InventingWithMonster** [comment]
Thanks for the PR, these examples are fixed now
