### ISSUE TITLE
Document deprecation in favour of Framer Motion

### ISSUE THREAD

**Issue by mulholio** [Popmotion/popmotion#834]
https://popmotion.io/pose/ mentions nothing about the package being deprecated in favour of Framer Motion.

Consequentially, I have just implemented Pose, only to find out that I will need to refactor to Framer Motion.

Please add at least a note on this.

**Comment by montogeek** [comment]
@mulholio Being deprecated? Where was this stated?

**Comment by mulholio** [comment]
https://github.com/Popmotion/popmotion/tree/master/packages/react-pose

**Comment by montogeek** [comment]
I see, thanks, was about to start using it.

**Comment by InventingWithMonster** [comment]
Yeah sorry about this - I've published the version of React Pose with the latest Readme but the delay to the site is the `site` package was broken by a version of Node so I've limited time to update the site. I'll set a reminder to take a look tonight.

**Comment by proof666** [comment]
What about react native support?
