### ISSUE TITLE
Typo/wrong information in Stylefire SVG documentation 

### ISSUE THREAD

**Issue by alexpi** [Popmotion/popmotion#851]
I was trying to use the pathLength property Stylefire provides, with no luck. Stylefire's documentation reads: 
```These are all set as a progress of the total path length, from 0 to 100, which is automatically measured by Stylefire.```
This seems to be wrong, it should be '0 to 1'.

**Comment by InventingWithMonster** [comment]
Thanks this should have been changed on the site recently
