### ISSUE TITLE
style-values-type: color objects with bad format are wrong detected like valid colors

### ISSUE THREAD

**Issue by nathanredblur** [Popmotion/popmotion#855]
style-values-type is detecting like valid color object that is not like `color.test({ red: '' })`
I create a pull request that fix this issue and many others.

https://github.com/Popmotion/popmotion/pull/854

**Comment by InventingWithMonster** [comment]
Closing as these checks are more practical (determine between hex and rgb), type systems will do a more robust check for invalid values.
