### ISSUE TITLE
Support rem unit

### ISSUE THREAD

**Issue by purplecandle** [Popmotion/popmotion#862]
I can barely use this library because I use relative units in my project. It's pretty simple, when it comes to animating  a single value (transformY in rem), but what about complex ones like a clip-path? For example, I have a value 'polygon(8rem 0%, 100% 0%, 100% 100%, 0rem 100%)'; I can't animate it at all.

I tried { complex } from style-value-types package, but it can't work on that value.

**Comment by stokesman** [comment]
> but what about complex ones like a clip-path?

Here's an [example](https://clip-path-motion.glitch.me/) of clip-path animation with either `tween` or `spring`. Those handle complex value types and units don't matter. The strings passed as `from` and `to` can be anything with numbers in them. Both just need to contain the same quantity of numerical portions.

**Comment by purplecandle** [comment]
Thanks for providing an example. Closing this issue.
