### ISSUE TITLE
package name change to @popmotion/core

### ISSUE THREAD

**Issue by souporserious** [Popmotion/popmotion#863]
Curious how you feel about renaming the `popmotion` package to `@popmotion/core`? It could then be referred to as Popmotion Core instead of Popmotion Pure in the docs for a little bit better clarification.

**Comment by InventingWithMonster** [comment]
I think I'm probably going to be ditching the `@popmotion/x` packages. They're not nice to import, they're a pain to maintain and it starts to get confusing remembering where things should be imported from.

It's more likely I'll move everything back into Popmotion in 9: https://github.com/Popmotion/popmotion/pull/859

**Comment by souporserious** [comment]
Ah, didn't see that! Sounds good 🎉
