### ISSUE TITLE
Add support for WebXR frame updates

### ISSUE THREAD

**Issue by daevid66** [Popmotion/popmotion#864]
Problem:
When switching to webxr/vr mode requestAnimationFrame events are no longer triggered in Chrome (since the original web view is considered a hidden tab when you go in to vr-mode). This breaks any VR app using popmotion for tweens/frame updates. 

Solutions:
We could either:
1. Automatically use vrDisplayInstance.requestAnimationFrame() instead of window.requestAnimationFrame() when applicable
2. Add the option to manually switch update mechanism.
3. Add the possibilty to manually trigger the frameUpdate mechanism that is used by tweens etc (I have not found support for this).

**Comment by daevid66** [comment]
Here is documentation on vrDisplayInstance.requestAnimationFrame():
https://developer.mozilla.org/en-US/docs/Web/API/VRDisplay/requestAnimationFrame

Discussion on chrome support for raf in vr presentation mode:
https://bugs.chromium.org/p/chromium/issues/detail?id=704341
(was first fixed but later reverted back to not triggering raf)

**Comment by InventingWithMonster** [comment]
Thanks for this issue, the latest Popmotion 9 stuff will have support for custom drivers so it'll be possible to do this. I'll take a look at the docs you provided and see if we can bake something in

**Comment by InventingWithMonster** [comment]
Closing this with Popmotion 9 RC1 https://github.com/Popmotion/popmotion/blob/9/README.md#driver
