### ISSUE TITLE
pose-core: version 2.1.1 includes typescript as dependency which bloats production installs

### ISSUE THREAD

**Issue by seanstern** [Popmotion/popmotion#867]
## Bug Description
pose-core@2.1.1 has the following dependency list
```
  "dependencies": {
    "@types/invariant": "^2.2.29",
    "@types/node": "^10.0.5",
    "hey-listen": "^1.0.5",
    "rollup-plugin-typescript2": "^0.25.2",
    "tslib": "^1.10.0",
    "typescript": "^3.7.2"
  },
```
Note that `typescript` is included as a dependency.

This is a problem for any project that
1. uses `pose-core` as a `dependency`
2. prunes out `"devDependencies"` in production environments (leaving only `"dependncies"`) to reduce overall project size in production environments

Essentially, these projects pull in an additional 50Mb of unnecessary data because `pose-core` is pulling in `typescript` as a dependency.

I believe `pose-core` should specify `typescript` as a `devDependency` only.

## How to reproduce
1. Create a package.json with the following prop
`{
  "dependencies": "pose-core": "@2.1.1"
}`
2. Run `yarn install --production`
3. Go to `node_modules/typescrpt` to see that `typescript` has been installed

## Expected behaviour
`typescript` should not be installed

## Additional context
`typescript` was added as a `dependency` to `packages/pose-core/package.json` in [this commit](https://github.com/Popmotion/popmotion/commit/cf76a9a782788b731f67018bc41ad3a4dcafa7d2)

It was not removed until [this commit](https://github.com/Popmotion/popmotion/commit/3b5adba1d453ae85557911b11c1272d8aacdf63b)

However, the latter commit has not been published to [npm](https://www.npmjs.com/package/pose-core/v/2.1.1) or [yarn](https://classic.yarnpkg.com/en/package/pose-core) because both still list `typescript` as a `dependency`

**Comment by stefanoruth** [comment]
This seems to be fixed, but not yet published, please publish a new version
