### ISSUE TITLE
Fake

### ISSUE THREAD

**Issue by Shuunen** [Popmotion/popmotion#87]
This library seems too awesome, can you fix that ?

**Comment by InventingWithMonster** [comment]
@Shuunen Thanks! That's actually now in the roadmap, 1 in 10 releases will randomly contain a site-crashing bug. I'll make sure the community knows who suggested it :)

**Comment by Shuunen** [comment]
Great ! I will try to use your lib while there is no bugs yet. 

I made a solitaire game in HTML/CSS/JS, actually I use CSS transform to move cards but it does not seems really fluid and natural. I will test your animation & physics. For the user inputs I use Hammer.js, maybe I could drop it and use the Input tracking of your lib too.
