### ISSUE TITLE
Future of Pose for Vue

### ISSUE THREAD

**Issue by ortonomy** [Popmotion/popmotion#888]
**Is your feature request related to a problem? Please describe.**
I just want to know about the plans for the for the future, especially Pose for Vue. Is there a roadmap published anywhere?

**Describe the solution you'd like**
I'm a Vue/React.js developer and since Pose for React was deprecated in favour of Framer Motion (which is an insanely great lib by the way), it's left me nervous about the future for Pose Vue. Vue Pose has always seemed the ugly step-child of the react versions anyway, but I'd like to know if Pose Vue is going to be expanded or even branched off into its own flavour a la Framer.

**Describe alternatives you've considered**
I've considered this lib https://github.com/liuhann/vue-anime which is the only one that comes close to having the declarative form of Pose, but it'd be great if I can keep my knowledge of Pose/Framer across my two worlds of Vue/React

**Comment by InventingWithMonster** [comment]
Hi there

On the docs you can see that Pose for Vue has already been deprecated https://popmotion.io/pose/learn/vue-dynamic-props/

Vue Anime is probably a safer long term bet, or it'd be possible for someone to fork a projected off from Vue Pose.

**Comment by ortonomy** [comment]
I swear this is a new notice! It was there a few weeks ago! Colour me better informed. It's a real pity, because the Vue Pose idea is soooooooooo much better than the current Vue Transition / Animation API.

**Comment by ortonomy** [comment]
Also, if it's ALL been deprecated, why still the active issues @InventingWithMonster ?

**Comment by InventingWithMonster** [comment]
I haven't updated the site in months so it's been up for a while 😅 Sorry if it wasn't clear enough though!

I need to go through the active issues but it's only the Pose libraries that have been deprecated.
