### ISSUE TITLE
[BUG] Popmotion 9: spring animations not working with object values

### ISSUE THREAD

**Issue by souporserious** [Popmotion/popmotion#889]
## Describe the bug
`NaN` is returned in the `onUpdate` function when using object values and `animate({ type: 'spring' })`.

## How to reproduce
Visit this [Codesandbox](https://codesandbox.io/s/simple-flip-mouse-follow-yvwqi?file=/src/App.js:2239-2254) and click around, when commenting out `type: 'spring'` it works as expected.

## Expected behaviour
Spring animations work with object values:
`animate({ type: 'spring', from: { x: 0, y: 0 }, to: { x: 10, y: 20 } })`

---

I couldn't tell by the docs, but maybe this isn't supported and I should be using seperate `animate` calls to each value?

**Comment by InventingWithMonster** [comment]
Yeah objects aren't explicitly supported. The reason for this is Framer Motion and Pose both only ever used single-value syntax. 

I assume what's happening is the keyframes animation actually supports objects and arrays because it works on top of `interpolate`.

**Comment by souporserious** [comment]
Ah, ok cool that makes sense! Thank you for the explanation! 🙏

**Comment by levrik** [comment]
@mattgperry I'm heavily relying on using objects in spring animations in our app so this blocks me from upgrading to Popmotion 9. It would be awesome to get this feature back.
But in general it seems to me from above's response that Popmotion solely exists to fulfill Framer Motion's needs so I'm wondering why it is still available as external library at all.

**Comment by mattgperry** [comment]
Because it exports lots of functions and features that make sense in a low-level utility library but not a high-level declarative animation library. 8 hasn’t disappeared, do you need to upgrade?

**Comment by levrik** [comment]
@mattgperry The TypeScript declarations in Popmotion 8 are quite broken and I was really happy to see that this has been solved in 9. Also the API seems a lot nicer so I would have loved to upgrade.
I might search for another similar library probably then. I was using Popmotion to drive animations on some canvas based component in our application.

**Comment by mattgperry** [comment]
Ah I see, interesting, I didn't know that about the types.

I just knocked this up, it should take objects for `from` and `to` (and you could do similar for other options):

```javascript
import sync from "framesync"

function animateAll({from, to, onUpdate, onComplete ...options}) {
  const latest = {}
  const animations = {}
  const isComplete = {}
  
  function update() {
    onUpdate(latest)
  }
  
  function checkAllComplete() {
    for (const key in isComplete) {
      if (!isComplete[key]) return
    }
    onComplete()
  }
  
  for (const key in from) {
    animations[key] = animate({
      from: from[key],
      to: to[key],
      ...options,
      onComplete: () => {
        isComplete[key] = true
        checkAllComplete()
      },
      onUpdate: (v) => {
        latest[key] = v
        sync.update(update, false, true)
      }
    })
  }
  
  return {
    stop: () => {
      for (const key in animations) {
        animations[key].stop()
      }
    }
  }
}
```
