### ISSUE TITLE
Can't get 'watch' to work

### ISSUE THREAD

**Issue by mkraessig** [Popmotion/popmotion#89]
Hi there,

I really like what you've been doing with Popmotion!
So far it's been a breeze to work with, just one thing: I can't get the watch-property to work.

What are some potential reasons? As far as I can see I am doing everything as specified.

```javascript
var handle = new ui.Actor({
	element: '.' + styles.testObject,
	values: {
		iris: {
			watch: 'x'
		}
	},
	onUpdate: function (output){
		console.log(output.iris)
	}
})
		
var horizontal = new ui.Track({
	values: {
		x: {}
	}
})
```

The `x` value is output correctly, but the `iris` just stays 0, no matter what I do.
In case that might be relevant, I am using React.

Perhaps you have an idea?

Thanks a bunch,
— Maxi

**Comment by InventingWithMonster** [comment]
Hey @mkraessig Can I check which version you're using? Also I see the two definitions should correct there but could you also confirm you're passing the mouse event to the `start` function like this (or with your framework/non-framework of choice):

    $('body').on('mousedown', yourElement, function (event) {
        handle.start(horizontal, event);
    })

**Comment by InventingWithMonster** [comment]
@mkraessig Like this: http://codepen.io/popmotion/pen/YyVrEJ?editors=011

**Comment by mkraessig** [comment]
Hi @InventingWithMonster,

I just installed it using `npm`, so the version is `3.2.0`.
Yup, I am passing the event argument just like that.

Wow, this is getting mysterious. The codepen is working perfectly fine. I am pretty much out of ideas.

Thanks for the super-quick response!
— Maxi

**Comment by InventingWithMonster** [comment]
Is there any way for me to see the full code you're working with?

**Comment by mkraessig** [comment]
Sure, no problem. As I said, I am using React and it seems more and more likely that the problem is related to that - even though I don't see how.

Thanks, @InventingWithMonster!

```javascript
import React, { Component } from 'react/addons'
import ui from 'popmotion'

import styles from './wheel.styl'

var handle
var glideStop
var catchIt
var catchItRight
var horizontal

export default class Wheel extends Component {
	constructor(props) {
		super(props)
		React.initializeTouchEvents(true)
		
	}
	componentDidMount(){
		
		handle = new ui.Actor({
			element: '.' + styles.testObject,
			values: {
				iris: {
					watch: 'x'
				}
			},
			onUpdate: function (output){
				console.log(output.iris)
			}
		})
		
		horizontal = new ui.Track({
			values: {
				x: {}
			}
		})
		
		glideStop = new ui.Simulate({
			values: {
				x: {
					friction: 0.08,
					bounce: .5
				}
			},
			onUpdate: function(output){
				if (parseInt(output.x, 10) < 0){
					handle.start(catchIt)
				}
				if (parseInt(output.x, 10) > 800){
					handle.start(catchItRight)
				}
			}
		})
		
		catchIt = new ui.Simulate({
			simulate: 'spring',
			spring: 400,
			friction: .3,
			bounce: 0,
			values: {
				x: {
					to: 0
				}
			}
		})
		
		catchItRight = new ui.Simulate({
			simulate: 'spring',
			spring: 400,
			friction: .3,
			bounce: 0,
			values: {
				x: {
					to: 800
				}
			}
		})
	}
	handlePan = (e) => {
		event.preventDefault()
		event.stopPropagation()
		handle.start(horizontal, e)
	}
	handlePanEnd = (e) =>{
		event.preventDefault()
		event.stopPropagation()
		handle.stop().start(glideStop)
	}
	render() {
		return(
			<div className={ styles.container }>
				<div className={ styles.wrapper } onMouseDown={ this.handlePan } onTouchStart={ this.handlePan } onMouseUp={ this.handlePanEnd } onTouchEnd={ this.handlePanEnd }>
					<div>
						<div className={ styles.testObject }></div>
					</div>
				</div>
			</div>
		);
	}
}
```

**Comment by InventingWithMonster** [comment]
No worries mate I've been wanting an excuse to check it out with react.
I'll look into it tonight.

**Comment by InventingWithMonster** [comment]
@mkraessig Hey man. Oddest bug. I can get it working in Chrome but not Firefox. Are you developing it in Firefox and looked at my Codepen in Chrome?

I'll take a look at fixing this later tonight or tomorrow morning. I have an idea what might be the problem (all objects have a `watch` property in Firefox). For now I'd recommend using Chrome until I can push a fix.

Also by the way, I really like what you're doing here, the catching is a good interaction and you've made me want to look into tighter integration with React (which wasn't the problem!)

Let me know if you need anything else.

**Comment by InventingWithMonster** [comment]
Could you give 3.2.1 a go please?

**Comment by mkraessig** [comment]
Seems to fine work now! Thanks so much!

**Comment by bobwal** [comment]
Yep. Scrubber example is working now.
