### ISSUE TITLE
Typing error after updating to v8.7.4 from v8.7.3

### ISSUE THREAD

**Issue by Ky6uk** [Popmotion/popmotion#891]
TypeScript is producing an error after the last update

```
 39:17 This expression is not callable.
   Type 'typeof import("node_modules/popmotion/lib/animations/keyframes")' has no call signatures.
     37 |       x: 0,
     38 |
   > 39 |       transition: keyframes({
        |                 ^
     40 |         values: [0, 15, 0],
     41 |         duration: 200
     42 |       })
```

**Comment by Ky6uk** [comment]
It looks the last update has introduced new `keyframes.d.ts` on the root of the animations directory. And at the same time the directory `keyframes` also exist.

**Comment by Ky6uk** [comment]
It looks the last update has introduced new `keyframes.d.ts` on the root of the `lib/animations` directory. And at the same time, the directory `keyframes` also exist, @InventingWithMonster.

**Comment by InventingWithMonster** [comment]
Thanks for the report! Can you check `8.7.5` for me?

**Comment by Ky6uk** [comment]
Yep. It works fine in `v8.7.5`.
