### ISSUE TITLE
Add LICENCSE file to the pop motion repo. 

### ISSUE THREAD

**Issue by lemiesz** [Popmotion/popmotion#893]
**Is your feature request related to a problem? Please describe.**
My orgnizations indexing service checks for supported licenses before letting me install a NPM package. 
Since popmotion does not have one it does not get properly indexed 

**Describe the solution you'd like**
Add a license file to this repo  https://github.com/Popmotion/popmotion

**Comment by yellow1912** [comment]
Yeah, what is the license of this project?

**Comment by kamiyubidan** [comment]
The license is currently here:
https://github.com/Popmotion/popmotion/blob/master/packages/popmotion/LICENSE.md

**Comment by lemiesz** [comment]
Got it thanks, I think our scanner was not properly finding the license. That seems to be resolved now
