### ISSUE TITLE
Stagger not exported by popmotion.es.js

### ISSUE THREAD

**Issue by coolemur** [Popmotion/popmotion#895]
Hi. Just installed latest version from npm. Trying to import stagger from popmotion:

```
import { stagger } from 'popmotion';
```

Result:

Error: 'stagger' is not exported by node_modules/popmotion/dist/popmotion.es.js

**Comment by mattgperry** [comment]
Thanks for the heads up, I accidentally published Popmotion 9 to `latest`. Just publishing `8.7.6` now to `latest`.
