### ISSUE TITLE
Popmotion watch / scrubber example.

### ISSUE THREAD

**Issue by bobwal** [Popmotion/popmotion#90]
Using popmotion.global.min.js locally with the scrubber example.
The output.timestamp fails (always zero).
Using codepen popmotion.global.min output.timestamp works.

**Comment by InventingWithMonster** [comment]
@bobwal Can I double check which browser you're using? For both.

**Comment by bobwal** [comment]
Yep,  Chrome 45.0.2454.101, no Firefox

**Comment by InventingWithMonster** [comment]
Thanks for that info. Could you try the latest popmotion.global.min.js please?
