### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by lucasfeijo** [Popmotion/popmotion#904]
The readme just shows usages of the `animate` function, but doesn't explain where to put it. With very little effort, that could be clarified in the beginning of the readme.

**Comment by mattgperry** [comment]
What do you mean by "where to put it"? It's just a function that will animate some values. What you do with those values is up to you.

**Comment by lucasfeijo** [comment]
To me it's still not clear what the applications are. Is it for react web? Is it for react native? Do I use it with Reanimated or regular RN Animated? How do I actually use this lib? No idea from the readme.

**Comment by mattgperry** [comment]
If it’s not clear from the docs that are already there then the library is probably too low-level for your use-case, which is okay! It really is just a function that animates a value over time, as well as some helper functions which are all documented. It’d be weird if lodash had examples for use with React - think of this like a lodash for animation. 

If you’re a React dev, which it sounds like you are, you’re 100% better off sticking to something like Framer Motion or React Spring.

**Comment by lucasfeijo** [comment]
@mattgperry I think I understand a bit better now, thanks!
