### ISSUE TITLE
popmotion@8.value and popmotion@8.physics on popmotion@9

### ISSUE THREAD

**Issue by barbarbar338** [Popmotion/popmotion#905]
`popmotion@8.value`
`popmotion@8.physics`

I was using these two methods in a project I made with popmotion@8, but I couldn't see it in popmotion@9. I wonder what's the equivalent of these in popmotion@9?

thanks :)

**Comment by decademoon** [comment]
I would also like to know this. I used `value` to transition between different animations smoothly (by applying an initial velocity to the new animation equal to the current velocity of the `value`). This this no longer supported? Do I have to use iterators or something like that now?

**Comment by stokesman** [comment]
Those are features that do not have equivalents in v9
>Do I have to use iterators or something like that now?

Or maybe keep using v8.

**Comment by barbarbar338** [comment]
then continue to use popmotion@8 :D
Thanks

**Comment by decademoon** [comment]
It seems framer motion has its own [MotionValue](https://github.com/framer/motion/blob/34228e848352f6dc4166aab22ac2986fde3e93f1/src/value/index.ts#L28), I'll have to do something like that.
