### ISSUE TITLE
Could I set up a global driver?

### ISSUE THREAD

**Issue by fy0** [Popmotion/popmotion#911]
**Is your feature request related to a problem? Please describe.**
I'm using popmotion for game engines with javascript interpreter. `requestAnimationFrame` is just a web api.
I need to write `{ driver: xxx }` for every call.

**Describe the solution you'd like**
```javascript
GameEngin.timer.loop((dt) => {
    popmotion.update(dt);
});
````

**Describe alternatives you've considered**
```javascript
popmotion.setDefaultOption({
    driver: updateFunction
})
```

**Additional context**
.

**Comment by mattgperry** [comment]
You can compose a function that does this:

```
export function animate(options) {
  return popmotion.animate({
    …options,
    driver: yourDriver
  })
}
```
