### ISSUE TITLE
Question: Is there any documentation on how to do a drag with inertia?

### ISSUE THREAD

**Issue by patchthecode** [Popmotion/popmotion#913]
I was looking at how to do this here -> https://popmotion.io/pose/learn/dragging/
But then i just realized that Pose and vue-pose is depracated.

Does this library have a way to the same types of drag as in the link above? and if yes, is there a documentation link?

**Comment by stokesman** [comment]
https://www.framer.com/api/motion/examples/#drag
It's not this library but does use this library and is the successor to Pose.

**Comment by patchthecode** [comment]
thanks.

**Comment by patchthecode** [comment]
Hmm.. it looks like that library is specifically for react (not VueJS).
Is there a way or any function that this library uses that will be able to do something like this?

**Comment by stokesman** [comment]
Here's [an example](https://codesandbox.io/s/vue-use-gesture-usedrag-hook-m2fn2?file=/src/App.vue) of such in Vue. It uses Popmotion for the inertia animation and [vue-use-gesture](https://github.com/koca/vue-use-gesture) for drag position and velocity calculation.

**Comment by patchthecode** [comment]
thank you
