### ISSUE TITLE
watch x

### ISSUE THREAD

**Issue by Shuunen** [Popmotion/popmotion#92]
The get started say :
```
var foo = new ui.Track({
    values: {
        x: {}
        // equivalent to
        // x: { watch: 'x' }
    }
});
```
but 
```
var foo = new ui.Track({
    values: {
        x: { watch: 'x' }
    }
});
```
doesn't work :)

**Comment by InventingWithMonster** [comment]
Thanks for pointing this out! I'll let you know when I have a fix. Generally you'll never need to set `watch` for a value that is watching an `Input` value of the same name, but this still should work.
