### ISSUE TITLE
Popmotion: React import { animate } from "popmotion"; fails

### ISSUE THREAD

**Issue by InfamousStarFox** [Popmotion/popmotion#923]
Using Popmotion version 10.0.2

The basic quick start:
```
import { animate } from "popmotion"

animate({
  from: 0,
  to: 100,
  onUpdate: latest => console.log(latest)
})
```

Causes my React site to fail to compile with the error:
```
./node_modules/popmotion/dist/es/animations/index.mjs
Can't import the named export '__rest' from non EcmaScript module (only default export is available)
```

What is the correct import for this to work?

**Comment by mattgperry** [comment]
It’s likely you’re using create-react-app which isn’t compatible with ES modules yet (see: https://github.com/framer/motion/issues/1307)

if you use the latest version of popmotion@9.x it should work as expected

**Comment by InfamousStarFox** [comment]
Yep, it looks like the problem is because create-react-app doesn't support the `.mjs` extension

Downgrading to 9.x fixed it.
