### ISSUE TITLE
Feature Request: Actor Collision Detection

### ISSUE THREAD

**Issue by mmmeff** [Popmotion/popmotion#96]
Hey all, love the library thus far - it's been a blast integrating it with my current project. Just one thing though - it would be magnificent if actors could behave naturally when colliding with one another. Are there any plans to add collision detection to the physics API?

**Comment by Shuunen** [comment]
Yeah I was wondering this also :) Hope yes

**Comment by InventingWithMonster** [comment]
Hey guys - glad you're enjoying it!

There are plans for collision detection, yeah. Annoyingly I have limited time on this and there's multiple other features I'm working on at the moment, so it might be a couple months before I get round to this.

**Comment by Shuunen** [comment]
Is it possible to display a roadmap on the readme ? with the features you are working on , the planned features ?

**Comment by InventingWithMonster** [comment]
Sure, I actually had a ROADMAP.md file and recently removed it. I'll add a new one.

**Comment by InventingWithMonster** [comment]
Okay, I've uploaded a roadmap file. This should give you some better visibility.

**Comment by InventingWithMonster** [comment]
@mmmeff @Shuunen @MichaelFBA Just launched an early version of a collision detection plugin: https://github.com/Popmotion/collision-detector It doesn't currently provide conflict resolution but it does provide the data and events necessary to achieve this.

**Comment by MerovingianByte** [comment]
So what happened with the collision detection plugin? The page is dead.
