### ISSUE TITLE
new Actor

### ISSUE THREAD

**Issue by Shuunen** [Popmotion/popmotion#97]
Just found that this work :

`new ui.Actor('.class-example');`

and :

`new ui.Actor(document.getElementsByClassName('class-example')[0]);`

does not work :) is it normal ? because according to http://popmotion.io/api/actor it should work with both DOM selectors & DOM elements

**Comment by InventingWithMonster** [comment]
Yeah that is as currently designed - it's inconsistent because obviously `ui.select` works with either. I'll look into supporting elements too though.
