### ISSUE TITLE
Tween seems to reset

### ISSUE THREAD

**Issue by laicosly** [Popmotion/popmotion#99]
After the first tween, a second tween seems to start from the original position instead of the end result of the first tween.  Is this intentional?  Is there a way to specify from/to values for a tween?

**Comment by laicosly** [comment]
This only occurs if not reusing the original actor reference.

http://codepen.io/anon/pen/YyxYLq

**Comment by InventingWithMonster** [comment]
Hi @laicosly - yeah this is intended behaviour. Actors are performance-first, so if you don't manually set initial conditions on Actor creation it won't read from the DOM (potentially expensive). So you should generally use the same Actor for the same element. As you say, your pen works fine when line 9 is commented out.

If you were animating `height` and `width` here with different Actors it'd work fine, but `x` and `y` are output as part of the same `transform` property so they really need to come from the same Actor.

There is a way of specifying to/from values, however. Setting a value like this:
```
x: {
    current: 100,
    to: 50
}
```
Will force `current` to a different value.

Finally, you can cache and retrieve cached Actors simply by using `ui.select('#ball')` - you'll have to change the included version of Popmotion to 3.3.2 but after that you can change both `new Actor()` calls with this and you'll see it finds the same Actor.
